### ISSUE TITLE
Master branch fails against 2.1.4

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#1006]
It works fine with 2.1.5 but when using 2.1.4, we get dozens of equality comparisons failing. I switched it back to 2.1.5, we can investigate this more if 2.1.4 is something we want to support.

**Comment by cheerfulstoic** [comment]
Shouldn't travis represent the fact that we're failing with Neo4j 2.1.4?

**Comment by subvertallchris** [comment]
We haven't supported or tested against 2.1.4 in nine months or more, I
don't know why we would start now.

**Comment by subvertallchris** [comment]
Post-script: talked with Brian, agreed we'd test against the latest patch release of each version.
