### ISSUE TITLE
`find_or_create` (uses merge) should not change anything on match

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#1017]
This:

```ruby
      def find_or_create(find_attributes, set_attributes = {})
        on_create_attributes = set_attributes.merge(on_create_props(find_attributes))
        on_match_attributes =  set_attributes.merge(on_match_props)
        neo4j_session.query.merge(n: {self.mapped_label_names => find_attributes})
          .on_create_set(n: on_create_attributes).on_match_set(n: on_match_attributes)
          .pluck(:n).first
      end
```

Should be this:

```ruby
      def find_or_create(find_attributes, set_attributes = {})
        on_create_attributes = set_attributes.merge(on_create_props(find_attributes))
        neo4j_session.query.merge(n: {self.mapped_label_names => find_attributes})
          .on_create_set(n: on_create_attributes)
          .pluck(:n).first
      end
```

**Comment by venkatd** [comment]
This sounds useful. I have some confusion about how merge works...

Suppose I have an Account node with
```
source_name: google
source_id: 1234
email: bob@hotmail.com
```

Then I later want to do a find_or_create like so:
```
Account.find_or_create({source_name: 'google', source_id: '1234'}, {email: 'coolbob@gmail.com'})
```

What would be the behavior of find-or_create?

**Comment by subvertallchris** [comment]
In a single Cypher query, it will `find` using the first hash and if no match is found, it will create using that and the contents of the second hash.

**Comment by leviwilson** [comment]
@venkatd _currently_ it will update all of your properties specified I think. So your `bob@hotmail.com` will get blown away with `coolbob@gmail.com`. Which is what I'm seeing anyway.

I _think_ the behavior should be this:

## `CREATE`
Takes both your "find" properties and your "set" properties and `Hash.merge` them to compose what your node should have.

## Already Exists
Nothing.

That seem legit to you in how that method should behave?

**Comment by cheerfulstoic** [comment]
Oh, interesting... I came here to fix this issue but I think because #1030 says "fixes #1017" that when I closed the PR it closed the original issue.  Neat...

**Comment by cheerfulstoic** [comment]
Released in 5.2.14, BTW

**Comment by venkatd** [comment]
@leviwilson I thing that behavior makes sense with `find_or_create`. I do find myself frequently wanting a `find_or_update` so I think it would be helpful to have the a `find_or_update` method. I'll add it when I'm back from vacation.

**Comment by cheerfulstoic** [comment]
I have another issue about this elsewhere, but I feel like `find_or_create` should be a two query method: find and then (optionally) create.  It should work just like ActiveRecord.  I think we should have other methods which do the other stuff which is special and awesome in Neo4j
