### ISSUE TITLE
Weird behaviour on ActiveRel instantiation

### ISSUE THREAD

**Issue by mrstif** [neo4jrb/neo4j#1024]
There is a seemingly weird behaviour when initialising an `ActiveRel` object:

    module Graph
      class Follows
        include Neo4j::ActiveRel

        creates_unique

        from_class Graph::User
        to_class   Graph::User

        property :status
    end

    f = Graph::Follows.new
    [DEBUG]  CYPHER 3ms MATCH n WHERE (ID(n) IN {ID_n}) RETURN n | {:ID_n=>[]}
    (Object doesn't support #inspect)
    => 

Is that cypher query supposed to execute? And that message to show?

I'm using:
- ruby (2.2.2)
- rails (4.2.4)
- **neo4j (5.2.13)**
- **neo4j-core (5.1.11)**

**Comment by subvertallchris** [comment]
That is definitely an odd bug that slipped in, I just confirmed it. Give me a few minutes to see where the conflict is.

**Comment by subvertallchris** [comment]
`ActiveRel#inspect` is trying to load `from_node` and `to_node`, which obviously don't exist early on. The PR referencing this issue modifies it to only return as much info about the nodes as it has at any given time. It will also prevent extra queries to load nodes for the purpose of `inspect`.

**Comment by subvertallchris** [comment]
You can lock your gemfile at the commit, `gem 'neo4j', github: 'neo4jrb/neo4j', ref: 'dbe9c258412bcd8f957ca2a301f923b295441b2d'` if you want this now; otherwise, it will be part of a release in the next day or two. Alternatively, latest 6.0.0.alpha release does not suffer from this bug.

**Comment by mrstif** [comment]
Cheers @subvertallchris ! Looking forward to version 6

**Comment by cheerfulstoic** [comment]
FYI the release candidate series of 6 is out (latest version currently is `6.0.0.rc.4`).  Only bug fixes for this series and we plan to release the final in the next day or two.

**Comment by mrstif** [comment]
Awesome @cheerfulstoic ! Thanks for the heads up!

**Comment by subvertallchris** [comment]
Closing this, please get in touch if it returns.
