### ISSUE TITLE
Property default value not overridden on new / create

### ISSUE THREAD

**Issue by LouisSayers** [neo4jrb/neo4j#1033]
I'm on 6.0.0.alpha.10, and experiencing that the default value is not being overridden during create for a Model object.

e.g.

```ruby 
class Notification
  include Neo4j::ActiveNode
  property :has_been_read, default: false
end

# Test code
notification = Notification.create(has_been_read: true) # new also has same behaviour
notification.has_been_read #gives false
```

**Comment by subvertallchris** [comment]
Can you try the master branch? I think this was fixed early this morning.

**Comment by LouisSayers** [comment]
Yep, is working on master, thanks :)

**Comment by subvertallchris** [comment]
Cool, sorry about that. I committed it right before running out and didn't
have time to cut a new release. I'll be home in a few minutes and will yank
.10, release .11. There's a new spec for this so it won't happen again.

**Comment by LouisSayers** [comment]
No worries ;) Thanks for the speedy reply!
