### ISSUE TITLE
When running rake tasks, automatically set neo4j.yml for that environment

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#1041]
Now that we support `config/neo4j.yml` files, we can have the rake task automagically add to / update the file whenever somebody runs `neo4j:install` or `neo4j:config`.  I would want people to understand what is going on, though, so perhaps a prompt could exist asking them if they want the change to be made for them.

**Comment by cheerfulstoic** [comment]
I started to work on this, but then I realized that if we're running the yml file through ERB first that we wouldn't always be able to do this.  Even if we weren't, somebody might be using yaml key aliasing and we might not be able to read the yaml file and then generate it again with our changes.

I'd be curious for thoughts from @mrstif as author of #1060

**Comment by mrstif** [comment]
@cheerfulstoic I get what you're trying to do. However, I dunno if it can become quite messy to handle that automagical change given that configuration can be managed in a number of different ways and the several possibilities that, as you said, the yaml file provides.

That said, I think it's a nice to have... but also that the scope is too broad to make it a real advantage.

**Comment by cheerfulstoic** [comment]
Yeah, agreed, thanks!  I wonder if it might be simple enough to output some simple instructions or a link to the ways in which you can configure the connection
