### ISSUE TITLE
Add extra labels to a model class

### ISSUE THREAD

**Issue by venkatd** [neo4jrb/neo4j#1042]
I want to add extra labels for book-keeping purposes. For example, any nodes that import from Google would have a `Google` label. I know I could inherit from a base class but would rather specify the label explicitly.

Should I be overriding `labels_for_create` to do this?
https://github.com/neo4jrb/neo4j/blob/6295181d79715aa348f9e55ec095e6d402c55b16/lib/neo4j/active_node/persistence.rb#L78

Thanks!

**Comment by subvertallchris** [comment]
That is an option. You could also add the label using the `Neo4j-core` API after the node is created but it's an extra query.

```
node = YourModel.create(props)
node._persisted_obj.add_label('Google')
```

https://github.com/neo4jrb/neo4j-core/blob/master/lib/neo4j-server/cypher_node.rb#L104

I am not sure that `_query_or_fail` works nicely in transactions, so let us know if you go that route and have weird results.

**Comment by venkatd** [comment]
I opted to go the route of overriding `labels_for_create` like so:

```ruby
class MyModel
    include Neo4j::ActiveNode

    def extra_labels
      [:Google]
    end

    def labels_for_create
      super + extra_labels
    end
end
```

**Comment by venkatd** [comment]
Also, I wonder if `_persisted_obj` should be renamed to reflect that it's a vanilla `Neo4j::Server::CypherNode`?

**Comment by subvertallchris** [comment]
`_persisted_obj` can be a few different flavors of node or relationship from `Neo4j::Core`, so we'd have to be careful. I don't know why it was never renamed it to something a bit more descriptive, at least `unwrapped_obj` or something.
