### ISSUE TITLE
Trouble finding objects with `with_associations`

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#1048]
Trying this:

```ruby
    @person1 = Person.all.with_associations(:authored_episodes, :mentioned_in).where(name: params[:name1]).to_a.first
```

But the `WHERE` is after the `OPTIONAL MATCH` and thus doesn't work

Tried switching to:

```ruby
    @person1 = Person.where(name: params[:name1]).with_associations(:authored_episodes, :mentioned_in).to_a.first
```

But that doesn't work either.

Tried this:

```ruby
    @person1 = Person.where(name: params[:name1]).query_as(:person).proxy_as(Person, :person).with_associations(:authored_episodes, :mentioned_in).to_a.first
```

Which kind of works, except that since there aren't any matches for `authored_episodes` then the `OPTIONAL MATCH`es don't match anything.  ARGH!

**Comment by cheerfulstoic** [comment]
I think #1054 might alleviate this some

**Comment by ProGM** [comment]
Uhm I'm having a similar issues with eager loading.

I'm trying to load a desk with all it's authors:

```ruby
Desk.all.where(title: 'Desk Title 2').with_associations(:creator).to_a
```

Generated query:
```
MATCH (n:`Desk`) OPTIONAL MATCH n-[:`creator`]->creator WHERE (n.title = {n_title}) AND (creator:Person) RETURN n, [collect(creator)] | {:n_title=>"Desk Title 2"}
```

As a result, the `where` statement is completely ignored.

I have a proposal: what about adding a `with` statement to separate `OPTIONAL MATCH` and the `WHERE`?

So the generated query should be:

```
MATCH (n:`Desk`) WHERE (n.title = {n_title}) WITH (n)  OPTIONAL MATCH n-[:`creator`]->creator WHERE (creator:Person) RETURN n, [collect(creator)] | {:n_title=>"Desk Title 2"}
```

**Comment by cheerfulstoic** [comment]
I think that `7.0.0` fixes this. Let me know if not!
