### ISSUE TITLE
change object from subclass A to subclass B

### ISSUE THREAD

**Issue by Vuuo** [neo4jrb/neo4j#1049]
Hi,

Is there any way to change an object from subclass A to subclass B?
Would like to do something like this:

```ruby
class User
  include Neo4j::ActiveNode
end

class Manager < User
end

class Admin < User
end

Manager.first.become Admin
```

**Comment by subvertallchris** [comment]
To do it permanently, you'd change labels. At the moment, I think that the Neo4j-core APIs that provide this need a little work, so it might be better to use the Cypher DSL.

```ruby
manager = Manager.first
Neo4j::Session.current.query.match_nodes(:m, manager).remove(m: Manager.mapped_label_names).break.set(m: Admin.mapped_label_names)
end
```

To do it within a subclass, you should be able to do it like this:

```ruby
manager = Manager.first
Admin.new.init_on_load(manager._persisted_obj, manager._persisted_obj.props)
```

**Comment by Vuuo** [comment]
Get it. Thanks for the quick reply.
