### ISSUE TITLE
uninitialized constant Neo4j::Algo ?

### ISSUE THREAD

**Issue by halfblood369** [neo4jrb/neo4j#1051]
I can not find Neo4j::Algo, why? Anyone can tell me, thanks!

**Comment by subvertallchris** [comment]
That class is no longer part of the gem. It was in the early versions but
when we rebuilt for the 3.0 release, which focused on Neo4j Server and MRI,
it was not part of the roadmap. Sorry!

**Comment by halfblood369** [comment]
o, thanks! can you tell me some a solution?

**Comment by halfblood369** [comment]
I want get the shortest paths, thanks!

**Comment by cheerfulstoic** [comment]
If you're in jRuby embedded mode you can use the Java APIs:

http://neo4j.com/docs/stable/tutorials-java-embedded-graph-algo.html
http://neo4j.com/docs/stable/tutorial-traversal-java-api.html


In any version of Ruby you can either use `shortestPath` or `allShortestPaths` in Cypher:

http://neo4j.com/docs/stable/query-match.html#query-shortest-path

or use the specific endpoints (which would be outside the context of the Neo4j.rb gems):

http://neo4j.com/docs/stable/rest-api-graph-algos.html

**Comment by cheerfulstoic** [comment]
Closing the issue since I don't think there's anything to do, but we still welcome questions / notes on this issue
