### ISSUE TITLE
Embedded Mode for jRuby (documentation?)

### ISSUE THREAD

**Issue by spinlock99** [neo4jrb/neo4j#1052]
Hi there. After following the docs to run neo4j as an embedded db with jRuby and Rails I get the following error:

    NoMethodError: undefined method `each_with_object' for nil:NilClass
                          properties_map at /Users/spinlock/.rvm/gems/jruby-1.7.22@neo4j/gems/neo4j-core-5.1.11/lib/neo4j-embedded/embedded_session.rb:34

Which is caused by `properties_map` expecting a hash for `config.neo4j.session_options[:properties_map]` (in neo4j-embedded/embedded_session.rb):

      def properties_map
        return @properties_map if @properties_map

        props = @config[:properties_map].each_with_object({}) do |(k, v), m|
          m[k.to_s.to_java] = v.to_s.to_java
        end
        @properties_map = java.util.HashMap.new(props)
      end

A "fix" is to add a line for `config.neo4j.session_options` to `config/application.rb`:

    # Configure where the embedded neo4j database should exist
    # Notice embedded db is only available for JRuby
    config.neo4j.session_type = :embedded_db  # default #server_db
    config.neo4j.session_path = File.expand_path('neo4j-db', Rails.root)
    config.neo4j.session_options = {properties_map: {}}

or, this could be fixed by making sure `@config[:properties_map]`:

      def properties_map
        return @properties_map if @properties_map

        @config[:properties_map] ||= {} 

        props = @config[:properties_map].each_with_object({}) do |(k, v), m|
          m[k.to_s.to_java] = v.to_s.to_java
        end
        @properties_map = java.util.HashMap.new(props)
      end

**Comment by cheerfulstoic** [comment]
Thanks for this and for doing the detective work!

Could you try loading the `5.1.x` branch of `neo4j-core` in your `Gemfile` (like `gem 'neo4j-core', github: 'neo4jrb/neo4j-core', branch: '5.1.x'`) and see if that works for you?   If so I'll cut a gem

**Comment by spinlock99** [comment]
@cheerfulstoic that did the trick. Everything looks good with `neo4j-core` at 5.1.11.

Thanks!

P.S. I've also noticed that I can't run a rails console while I'm running the server:

    $rails c
    Start embedded Neo4j db at /Users/spinlock/neo4j/asset_portal/neo4j-db
    LoadError: load error: /Users/spinlock/neo4j/asset_portal/config/environment -- java.lang.RuntimeException: Error starting org.neo4j.kernel.EmbeddedGraphDatabase, /Users/spinlock/neo4j/asset_portal/neo4j-db

Is that just a limitation of running neo4j as an embedded db or is there a way around it?

**Comment by cheerfulstoic** [comment]
Great, thanks!  `5.1.12` is now released with this fix.

Unfortunately that's a limitation of using Neo4j in embedded mode.  Two processes (of any sort) can't access the same Neo4j database at the same time.  That's one of the advantages of server mode.
