### ISSUE TITLE
Any planned support for ActiveRecord-like #increment! method?

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1067]
Do you plan to add support for `#increment!` to both `ActiveNode` and `ActiveRel`?

It could be useful for keeping visits count.

http://apidock.com/rails/ActiveRecord/Base/increment!

**Comment by cheerfulstoic** [comment]
Interesting, I'm a long time AR user but I hadn't heard of `#increment!` before.  Definitely something we could implement.  I can't tonight but I'll give it a shot tomorrow (a PR is also welcome in the meantime.  We're happy to help on https://gitter.im/neo4jrb/neo4j if you have any issues / questions)

**Comment by ProGM** [comment]
Uhm... I checked how it's implemented in ActiveRecord. It seems it simply does something like:

```
def increment(attribute, by = 1)
    self[attribute] ||= 0
    self[attribute] += by
    self
end

def increment!(attribute, by = 1)
    increment(attribute, by).update_attribute(attribute, self[attribute])
end
```

This is ok, but it's not concurrent (as stated in the docs). Do you think it's better to implement it in the same way or do some custom query like `SET attribute = attribute + 1`?

**Comment by cheerfulstoic** [comment]
I think it would be good to mock the API, but then if we want a concurrent version to create a separate method like `concurrent_increment`.

**Comment by ProGM** [comment]
@cheerfulstoic @subvertallchris Shouldn't this be closed?
However, I discovered the rails way for `concurrent_increment`, probably we should fix this:
http://apidock.com/rails/v4.2.1/ActiveRecord/CounterCache/ClassMethods/update_counters

**Comment by cheerfulstoic** [comment]
Yup, good catch!  Tagging with milestone `6.1.x` in case somebody else comes along looking for this

Happy to have improvements, but I think we can close if it's working
