### ISSUE TITLE
Support `enum` like in ActiveRecord

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#1082]
See:

http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html
http://stackoverflow.com/questions/34420013/how-can-i-implement-enum-in-a-graph-database-like-neo4j

Items:

 - [ ] Validation that the properties is one of the values
 - [ ] Validation that enum values don't conflict with each other
 - [ ] `?` and `!` methods
 - [ ] Automatic scopes
 - [ ] Making sure that enums are supported in `where` and `rel_where` (including `Array` values)
 - [ ] Documentation (with information about prefix, suffix, and index options)

**Comment by ProGM** [comment]
@cheerfulstoic  @subvertallchris 
Hello, I made an enum implementation using `TypeConverters`.

If you like it, I can make a pull request ;)

Usage example:
```ruby
class File
  include   include Neo4j::Timestamps
  include Neo4jEnum
    enum type: [:image, :video, :unknown]
end

f = File.new
f.type # => :image
f.type = :video
f.video? # => true
f.unknown!
f.type # => :unknown
f.save
#  CYPHER 5ms CREATE (n:`File` {props}) RETURN ID(n) | {:props=>{:uuid=>"fbab3d84-70da-417d-9b26-d4daecd1d628", :type=>2}}

# Finders:
File.unknown # => finds all Files where type is :unknown
File.where(type: :unknown) # => the same
File.where(type: [:video, :unknown]) # => NOT WORKING
```

Code:
```ruby
module Neo4jEnum
  extend ActiveSupport::Concern

  class EnumConverter
    def initialize(enum_list)
      @enum_list = enum_list
    end

    def converted?(value)
      value.is_a?(db_type)
    end

    def db_type
      Integer
    end

    def convert_type
      Symbol
    end

    def to_ruby(value)
      @enum_list[value] unless value.nil?
    end

    alias_method :call, :to_ruby

    def to_db(value)
      @enum_list.index(value.to_s.to_sym) || 0
    end
  end

  module ClassMethods
    attr_reader :neo4j_enum_data

    def enum(options = {})
      options.each do |property_name, enum_list|
        @neo4j_enum_data ||= {}
        @neo4j_enum_data[property_name] = enum_list
        property property_name, serializer: EnumConverter.new(enum_list),
                                default: enum_list.first
        define_enum_methods(property_name, enum_list)
      end
    end

    private

    def define_enum_methods(property_name, enum_list)
      define_enum_methods_?(property_name, enum_list)
      define_enum_methods_!(property_name, enum_list)
      define_enum_scopes(property_name, enum_list)
    end

    def define_enum_scopes(property_name, enum_list)
      enum_list.each do |name|
        scope name, -> { where(property_name => name) }
      end
    end

    def define_enum_methods_?(property_name, enum_list)
      enum_list.each do |enum_value|
        define_method("#{enum_value}?") do
          __send__(property_name).to_s.to_sym == enum_value
        end
      end
    end

    def define_enum_methods_!(property_name, enum_list)
      enum_list.each do |enum_value|
        define_method("#{enum_value}!") do
          __send__("#{property_name}=", enum_value)
        end
      end
    end
  end
end
```

**Comment by subvertallchris** [comment]
This is extremely cool! An added benefit of your use of the type converter is that QueryProxy should be able to use it for arguments passed in a `where` or `rel_where`.

**Comment by ProGM** [comment]
Yep, in fact both `where` and `rel_where` are working!

Unfortunately it's not working for lists:

```ruby
File.where(type: [:image, :video]) # => Not working ):
```

**Comment by cheerfulstoic** [comment]
I think I like this, but I feel like it needs some thought.  Does it make sense in all case to have the automatic methods like `video?` and the scope `video` for all enums?  Since `type` is a sort of fundamental thing I can see how it makes sense.  But it might also make sense to do `video_type` or `type_video`.

I'm trying to think of another example, but I just double checked and see that ActiveRecord does this.  I suppose it makes sense since you can only ever be in one state for an `enum`.

We'd probably need to make sure that no two `enum` states for different `enum` properties can be the same.  That is:

```ruby
class Tree
  enum :kind, [:oak, :fir]
  enum :covering, [:fir, :bar]
  # Really making shit up here, maybe that's bad of me, but just trying to get my point across ;)
end
```

Does it make sense to automatically index `enum`s?

The array not working thing could be a larger but with using type converters in `where`-ish clauses.  If so that would be a great catch!

**Comment by ProGM** [comment]
About adding video_type, or something like this, ActiveRecord solves this adding some options:
```ruby
  enum status: [:active, :archived], _suffix: true # => Generates `.active_status!` and `.active_status?`
```
Or also:
```ruby
  enum status: [:active, :archived], _prefix: :comments # => Generates `.comments_active!` and `.comments_active?`
```
I think we can do the same.

About conflicts... Well, ActiveRecord is checking for conflicts, and it's raising an error when there are some.

```ruby
ENUM_CONFLICT_MESSAGE	=	\ "You tried to define an enum named \"%{enum}\" on the model \"%{klass}\", but " \ "this will generate a %{type} method \"%{method}\", which is already defined " \ "by %{source}."
```

Finally:
> Does it make sense to automatically index `enum`s?

Dunno, really. Maybe we can add an option `_index: true`?

**Comment by cheerfulstoic** [comment]
Unfortunately `enum` isn't a column type so it isn't generated in migrations and that's where `ActiveRecord` normally puts it's indexed-by-default things, so we can't really say what they would do.

Since we're creating scopes automatically which will make queries which use this property I would say that indexes should be opt-out.  If we put the ability to have `index: false` in the documentation I think it would be enough.

Why the underscores in the options, I wonder...  Is the third argument used for something else?  Will be back later, but this seems to be the source file:

https://github.com/rails/rails/blob/19e7f65dd1/activerecord/lib/active_record/enum.rb

**Comment by cheerfulstoic** [comment]
Since we're talking about a lot of things I made a checklist in the original issue body with things that we've talked about.

In case it wasn't clear, a PR would be very most welcome (including PRs which only take care of part of the list)!

**Comment by subvertallchris** [comment]
OK to close?

**Comment by ProGM** [comment]
This it's still not working:

```ruby
File.where(type: [:image, :video]) # => Not working ):
```

But maybe it's a new issue, isn't it?

**Comment by cheerfulstoic** [comment]
I decided to take a quick look at the arrays in where clauses.  I have a solution in #1150 which I'd appreciate feedback from both of you on.

If it looks good I say we can release it as part of 7.0.0
