### ISSUE TITLE
Neo4j 3.0 Bolt support?

### ISSUE THREAD

**Issue by chrisgogreen** [neo4jrb/neo4j#1087]
Is the new binary Bolt protocol going to be supported?

**Comment by cheerfulstoic** [comment]
Yes!  That's the plan.  I'm in the process of building a new neo4j-core API for sessions which uses adapters so it will be easy to add Bolt.

I also previously helped build a partial implementation of Bolt in Ruby.  It's a bit out of date but it shouldn't take too much to get it working with the latest version of Neo4j.  Probably that will happen with their first release candidate.

Brian

**Comment by cheerfulstoic** [comment]
I was on my phone before, so much a bit more info.  Here's the code for supporting PackStream and a bit for supporting Bolt:

https://github.com/neo4j-contrib/new-remoting-ruby

As I said it's a bit out of date, but I plan to bring it up to date with the 3.0 RC

I've also just put together some basic intro docs to the new API here (on a branch):

https://github.com/neo4jrb/neo4j-core/tree/new_cypher_api#basic-usage

Feedback definitely welcome!

In case you want to look at the source code, I've made a diagram of the modules/classes:

http://i.imgur.com/g5FdPDn.png

**Comment by ProGM** [comment]
Bolt is officially supported by `neo4j >= 8.0.0.rc.1`
