### ISSUE TITLE
Node instances cannot be marshaled, which means they can't be cached

### ISSUE THREAD

**Issue by jhoffner** [neo4jrb/neo4j#1093]
```ruby
class MyNode
  include Neo4j::ActiveNode
end

Marshal.dump(MyNode.create)
```

raises a `TypeError: no _dump_data is defined for class Proc`

This prevents Rails caching from working correctly.

**Comment by cheerfulstoic** [comment]
Great point, thanks!

Just opened a pull request for `neo4j-core`:

https://github.com/neo4jrb/neo4j-core/pull/246

and `neo4j`:

https://github.com/neo4jrb/neo4j/pull/1094

If you'd like to try these out you can use this in your `Gemfile`:

```ruby
gem 'neo4j-core', github: 'neo4jrb/neo4j-core', branch: 'marshal'
gem 'neo4j', github: 'neo4jrb/neo4j', branch: 'marshal'
```

Thanks!

**Comment by cheerfulstoic** [comment]
@subvertallchris Worth a backport if everything looks OK?

**Comment by subvertallchris** [comment]
Might as well do it as a minor release, maybe? It's about that time anyway.

**Comment by cheerfulstoic** [comment]
6.1.0 released on Friday with this issue fixed.  Give it a try!
