### ISSUE TITLE
uninitialized constant Neo4j::NodeMixin

### ISSUE THREAD

**Issue by f7n** [neo4jrb/neo4j#1101]
In my model, movie.rb, I've tried to define my fulltext lucerne index, but I'm getting this error: `NameError: uninitialized constant Neo4j::NodeMixin`. Here is my movie.rb file:

    class Movie
	    include Neo4j::NodeMixin
	    property :id
	    property :movieID
	    property :name, :index => :fulltext
	    property :year
	    property :imdB
	    property :rtRating
	    property :poster
    end

**Background** - Previously, I created my custom index through the Neo4j console (following this guide: http://jexp.de/blog/2014/03/full-text-indexing-fts-in-neo4j-2-0/). I then imported my data from .CSV files. Now I'm trying to use the Neo4j gem along with Sinatra to interact with my Neo4j graph. I'm testing it with this query query: `Movie.find('name: toy story', :type => :fulltext).`

**Comment by subvertallchris** [comment]
Unfortunately, the code you're using was from the legacy, 2.x series release. 3.0 was a full rewrite and did not include support for full-text indexes. You can find the modern docs at http://neo4jrb.readthedocs.org/en/6.1.x/.

**Comment by f7n** [comment]
I see, thank you. You're actually just the person that could help me. Because of this issue, I've been trying to use Searchkick, and the first gem I tried was neo4j-searchkick. First of all, would this gem even work with Sinatra? Or is it designed for rails? The error I get when using it with Sinatra is: `NameError: undefined local variable or method 'searchkick' for Movie:Class` (see: https://github.com/ankane/searchkick/issues/599). I've included it in my gemfile, should I be requiring it?

Should I create an issue on the neo4j-searchkick repo or is this working as intended, i.e it doesn't support Sinatra.

**Comment by subvertallchris** [comment]
We can talk about it here, our Issues aren't so busy that we really need more sprawl today. ;-)

Make sure you require `searchkick` and `neo4j-searchkick` before calling `searchkick` in the body of the model. It's been a while since I've looked at that code but I imagine that the loading of those gems will patch `ActiveNode` as required to get things going.

**Comment by subvertallchris** [comment]
Hmm, might be wrong there. `searchkick` might have been modified in such a way that it expects ActiveRecord. Try adding `extend Searchkick::Model` before you call `searchkick`. It looks like they're doing that for you with ActiveRecord: https://github.com/ankane/searchkick/blob/7def99b65ddf0737c3221e710fec3a513542ea89/lib/searchkick.rb#L135

**Comment by f7n** [comment]
OK -- so I need to include both searchkick and neo4j-searchkick? I was doing one or the other previously. Now I'm getting this response: `NoMethodError: undefined method 'attr_internal' for Searchkick::ControllerRuntime:Module`. Can you see where I've gone wrong?

This is my model:
	
class Movie
	  extend Searchkick::Model
	  include Neo4j::ActiveNode
	  searchkick
	end

And this is my gemfile:

	source 'https://rubygems.org'
	
	gem 'sinatra'
	gem 'searchkick'
	gem 'neo4j-searchkick'
	gem 'neo4j'
	gem 'haml'
	gem 'shotgun'

Full trace: 

	NoMethodError: undefined method `attr_internal' for Searchkick::ControllerRuntime:Module
	
	/Library/Ruby/Gems/2.0.0/gems/searchkick-1.1.2/lib/searchkick/logging.rb:101:in `<module:ControllerRuntime>'
	/Library/Ruby/Gems/2.0.0/gems/searchkick-1.1.2/lib/searchkick/logging.rb:96:in `<module:Searchkick>'
	/Library/Ruby/Gems/2.0.0/gems/searchkick-1.1.2/lib/searchkick/logging.rb:3:in `<top (required)>'
	/Library/Ruby/Gems/2.0.0/gems/searchkick-1.1.2/lib/searchkick.rb:12:in `require'
	/Library/Ruby/Gems/2.0.0/gems/searchkick-1.1.2/lib/searchkick.rb:12:in `<top (required)>'
	models/movie.rb:1:in `require'
	models/movie.rb:1:in `<top (required)>'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/environment.rb:7:in `load'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/environment.rb:7:in `block in <top (required)>'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/environment.rb:6:in `each'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/environment.rb:6:in `<top (required)>'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/app.rb:1:in `require'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/app.rb:1:in `<top (required)>'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:115:in `require'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:115:in `inner_app'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:103:in `assemble_app'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/favicon.rb:12:in `call'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/static.rb:14:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

**Comment by subvertallchris** [comment]
I'd have to look through the code to know if you _need_ to require both but it certainly won't hurt. It's likely that the `neo4j-searchkick` gem requires the other as a dependency but I don't know offhand. That gem was thrown together very quickly, as evidenced by issues like these and the fact that its gemfile doesn't specify what versions of `searchkick` it works with in the first place.

That new error is because we haven't loaded that file. Try adding this line before requiring the searchkick gems:

```
 require 'active_support/core_ext/module/attr_internal'
```

If that doesn't work, you'll want to lock your version of Searchkick at the version that was out at the time of our patch's release: `gem 'searchkick', `~> 0.8.0` should accomplish that.

**Comment by f7n** [comment]
Thanks, but no luck :(.

Adding ` require 'active_support/core_ext/module/attr_internal'` before requiring the gems results in this error:

`LoadError: cannot load such file -- neo4j-searchkick`

I've rolledback to searchkick 0.8.0, but I'm still getting the `attr_internal` error:

	NoMethodError: undefined method `attr_internal' for Searchkick::ControllerRuntime:Module
	
	/Library/Ruby/Gems/2.0.0/gems/searchkick-0.8.0/lib/searchkick/logging.rb:54:in `<module:ControllerRuntime>'
	/Library/Ruby/Gems/2.0.0/gems/searchkick-0.8.0/lib/searchkick/logging.rb:49:in `<module:Searchkick>'
	/Library/Ruby/Gems/2.0.0/gems/searchkick-0.8.0/lib/searchkick/logging.rb:3:in `<top (required)>'
	/Library/Ruby/Gems/2.0.0/gems/searchkick-0.8.0/lib/searchkick.rb:13:in `require'
	/Library/Ruby/Gems/2.0.0/gems/searchkick-0.8.0/lib/searchkick.rb:13:in `<top (required)>'

**Comment by subvertallchris** [comment]
Try `require neo4j/searchkick` instead of `neo4j-searchkick`. Your requires should look like this:

```
require 'neo4j'
require 'active_support/core_ext/module/attr_internal'
require 'searchkick'
require 'neo4j/searchkick'
```

At that point, you should be able to extend that module in the model:

```
class YourModel
  include Neo4j::ActiveNode
  extend Searchkick::Model
```

Sorry for the guesswork on my part but I last worked with these in Nov 2014, all my suggestions are coming from quick checks of each gem's code. If you're still having trouble, hop into Gitter, https://gitter.im/neo4jrb/neo4j. I can probably help you faster there.

**Comment by cheerfulstoic** [comment]
To reduce complications I would remove `neo4j-searchkick` for right now.  It's just there to add support for `ActiveRel` models.  `searchkick` should work fine with `ActiveNode`, though if it doesn't that's certainly something that we should fix.

**Comment by subvertallchris** [comment]
Are you sure about that? I thought it was necessary for ActiveNode but it's
been a long time since I've used it.

**Comment by cheerfulstoic** [comment]
I've definitely used `searchkick` with just `ActiveNode` without issues.

Also, the `neo4j-searchkick` `README` says:

"to provide support for Neo4j relationship models created using the Neo4j ruby gem ActiveRel module."

**Comment by subvertallchris** [comment]
Ah, well that's good to know.
