### ISSUE TITLE
Why is Neo4j::ActiveNode::Labels::RecordNotFound not inheriting from Neo4j::RecordNotFound?

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1104]
By default, ActiveRecord fails to find object raising an `ActiveRecord::RecordNotFound`. In rails, it's rescued by default with a 404 page.

Instead, `Neo4j::RecordNotFound` generates a more generic "internal server error".

So I tried to catch it with `rescue_with`:

```ruby
rescue_from Neo4j::RecordNotFound do
  render text: 'Not Found', status: 404
end
```

But, it does not catches all `Neo4j::ActiveNode::Labels::RecordNotFound` errors.

I would expect that `Neo4j::RecordNotFound` was the parent of `Neo4j::ActiveNode::Labels::RecordNotFound`, or to be both child of `Neo4j:: Neo4jrbError`.

Do you plan to add a default behavior for all neo4j errors or add some infos about it in the docs?

**Comment by subvertallchris** [comment]
The reorganization of error classes is something that I've been meaning to
do for a little while but it's an issue of time and priorities. If you'd
like to spearhead that or get it started, we'd love your input!

**Comment by subvertallchris** [comment]
Do we want to close this now?

**Comment by ProGM** [comment]
Uhm... Do you think that errors need more refactor?

For me it's ok...

**Comment by subvertallchris** [comment]
I think you made great progress, I'm ok with closing. We can always revisit if it's necessary later.

**Comment by ProGM** [comment]
Great :+1:

**Comment by cheerfulstoic** [comment]
:+1:
