### ISSUE TITLE
Unable to find factory for #<Neo4j::ActiveRel::RelatedNode:0x0000000b8977a8>

### ISSUE THREAD

**Issue by djvs** [neo4jrb/neo4j#1107]
Trace:

    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/shared/query_factory.rb:20:in `create'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence/query_factory.rb:67:in `query_factory'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence/query_factory.rb:60:in `block in iterative_query'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence/query_factory.rb:58:in `each'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence/query_factory.rb:58:in `inject'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence/query_factory.rb:58:in `iterative_query'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence/query_factory.rb:23:in `block in build!'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence/query_factory.rb:41:in `block (2 levels) in node_before_callbacks!'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/shared/callbacks.rb:41:in `conditional_callback'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/related_node.rb:62:in `method_missing'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence/query_factory.rb:40:in `block in node_before_callbacks!'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/shared/callbacks.rb:41:in `conditional_callback'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence/query_factory.rb:39:in `node_before_callbacks!'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence/query_factory.rb:22:in `build!'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence.rb:123:in `_create_rel'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence.rb:49:in `create_model'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/shared/callbacks.rb:53:in `block (2 levels) in create_model'
    /usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
    /usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
    /usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/shared/callbacks.rb:53:in `block in create_model'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-core-6.0.4/lib/neo4j/transaction.rb:105:in `run'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/shared/callbacks.rb:52:in `create_model'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/shared/persistence.rb:83:in `create_or_update'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/shared/callbacks.rb:48:in `block in create_or_update'
    /usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
    /usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
    /usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/shared/callbacks.rb:48:in `create_or_update'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/persistence.rb:32:in `save'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/shared/validations.rb:18:in `save'
    /usr/local/rvm/gems/ruby-2.2.0/gems/neo4j-6.1.0/lib/neo4j/active_rel/callbacks.rb:11:in `save' 

Error is encountered after trying to save a relationship with one of the parameters a RelatedNode (accessed from something like foo.to_node).

**Comment by subvertallchris** [comment]
Gotta help us out here. Context? Steps to reproduce?

**Comment by djvs** [comment]
^ Error is encountered after trying to save a relationship with one of the parameters a RelatedNode (accessed from something like foo.to_node).

**Comment by subvertallchris** [comment]
Ahh, are you trying to create a rel using `rel.from_node` or something?

**Comment by djvs** [comment]
Yes.

**Comment by subvertallchris** [comment]
Haha alright. I can fix later for you or you can try a PR if you have a few
mins to look at code. It should be an easy fix.

**Comment by djvs** [comment]
I can wait, I wouldn't know where to begin.

**Comment by subvertallchris** [comment]
It's pretty easy. ActiveRel uses factories to create cypher statements that
create or match on one or more objects. The logic it's using to determine
the path to take doesn't know what to do with a RelatedNode, which is the
wrapper that holds and proxies calls to ActiveRel instances from_ and
to_node. The solution is to find and fix that, probably changing an `is_a?`
to `respond_to?`.

**Comment by djvs** [comment]
I don't know what to do with a RelatedNode either.  If NodeQueryFactory will correctly handle a Neo4j::ActiveRel::RelatedNode in place of a Neo4j::ActiveNode, then line 15 in lib/neo4j/shared/query_factory.rb could be changed I think to `                when Neo4j::ActiveNode, Neo4j::ActiveRel::RelatedNode`.  But I'm not really set up to test it right now.

**Comment by djvs** [comment]
Or else if there is some method to resolve a Neo4j::ActiveRel::RelatedNode to a  Neo4j::ActiveNode... something I have been wondering for a year or so.

**Comment by subvertallchris** [comment]
`RelatedNode` is just a wrapper for `ActiveNode` instances. https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_rel/related_node.rb
It sends most methods straight to the node but it includes some behavior to assign and load them from the database. It's mostly unchanged from its earliest implementation, so it's possible there could be better ways to handle some of it.

**Comment by djvs** [comment]
I'll send a PR for aforementioned change then.

**Comment by subvertallchris** [comment]
See if you can do it in a way that doesn't rely on class name, it'd be better for it to be based on behavior. I don't want to have to add a new class to that list every time we add a wrapper.

**Comment by djvs** [comment]
Any particular behavior coming to mind?

**Comment by subvertallchris** [comment]
We'd need to find a method that ActiveNode instance respond to that ActiveRel don't. It might also be worthwhile to add methods to `node_wrapper.rb` and `rel_wrapper.rb`, maybe something like `#graph_object_type`, that just responds `:node` or `:rel`. Then any methods that rely on branching behavior can rely on that.

**Comment by subvertallchris** [comment]
There might already be something like that, too.

**Comment by djvs** [comment]
.respond_to?("uuid") gives true for node and false for rel.  How about that?

**Comment by djvs** [comment]
Seems safe enough considering neo4j itself will error out if the node doesn't exist.

**Comment by subvertallchris** [comment]
That's only true if they're using the default `id_property` settings.

**Comment by djvs** [comment]
OK...the .node method?

**Comment by subvertallchris** [comment]
I'm not familiar with that one. Can you link me?

**Comment by djvs** [comment]
I think it's somewhere in the Rails ORM, Active-something.  It's not in the neo4j source tree as far as `grep -r "def node *"` can show me.

**Comment by djvs** [comment]
I just looked up all the methods on an ActiveNode and tested respond_to for both a rel and a node with that, it gave me a true and false.

**Comment by subvertallchris** [comment]
Huh... That's weird. I guess we can start there. Went to send over a PR? Make sure to add tests if you don't mind.

**Comment by subvertallchris** [comment]
Fix is merged, just released 6.1.3.

**Comment by subvertallchris** [comment]
Thanks for working on this with me!

**Comment by djvs** [comment]
No problem - is there a release coming soon?

**Comment by subvertallchris** [comment]
> subvertallchris commented 3 minutes ago
> Fix is merged, just released 6.1.3.

**Comment by djvs** [comment]
Great, thanks
