### ISSUE TITLE
find_or_create_by(!) should run in a transaction

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#1121]
Right?

**Comment by subvertallchris** [comment]
I don't think so? It calls `create`, which has its work done in a transaction.

**Comment by cheerfulstoic** [comment]
Are you thinking of `find_or_create` perhaps and not `find_or_create_by`?  `find_or_create_by` and `find_or_create_by!` both do a `find` and then a `create`:

https://github.com/neo4jrb/neo4j/blob/d40d84774abb1caa84fab8427b542695d1ac1bae/lib/neo4j/active_node/persistence.rb#L146

Also (pet peeve alert), `find_or_create_by` are doing what `ActiveRecord`'s `find_or_create` method does. ;)

**Comment by subvertallchris** [comment]
The `_by` version. `create` just calls `save` which is within a transaction. Unless wrapping it in a transaction would give the `find_by` call access to uncommitted data created within a parent transaction?

**Comment by cheerfulstoic** [comment]
I was just thinking that a method making two database calls should probably be wrapped in a transaction, though I didn't think about it too much.  I suppose since the `find_by` doesn't change anything that it doesn't seem like a big deal.

What about this situation, though:

Let's say two processes/threads call `find_or_create_by` at around the same time and this particular order happens:

A: `find_by` (nothing found)
B: `find_by` (nothing found)
A: `create` (node created)
B: `create` (node created)

It probably wouldn't even need to be two calls to `find_or_create_by`, but that is the most straightforward example, I think.  I think having the two queries run inside a transaction *might* alleviate this.  Although maybe not... If all you've done so far is two reads in two transactions then I don't think it would lock.  If you do a `create` I don't know what it would lock, but even if it did I think that the second `create` could still execute after the first transaction is done because there's nothing conflicting about the two created nodes (unless there's a constraint, perhaps)

**Comment by subvertallchris** [comment]
Right, it won't help in that case for the reasons you described. I don't think it would lock at all unless you were creating a relationship. `Merge` would help here but it has those known drawbacks within the gem.

**Comment by cheerfulstoic** [comment]
Yeah, I definitely want an option where people can do this where it's going to respect validations / hooks.  Ok, going to close for now, thanks ;)
