### ISSUE TITLE
Suggestion: RSpec matchers, possibly separate gem?

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#1124]
Can we think of any matchers specific to this library and Neo4j as a whole that might be worth including in this gem or a separate one? @michaeldelorenzo on Slack asked about `have_many`, like:

```ruby
 it { should have_many(:other_things) }
```
Can we think of others? Would they be helpful?

**Comment by michaeldelorenzo** [comment]
I'm using RSpec and shoulda matchers in my project....

The ones I've already come across being useful are ones similar to those you might use to check associations with ActiveRecord:

- `have_many`
- `have_one`

Of course checking the type of the relationship, how `#class_name` works and probably the direction `:in` or `:out`.

**Comment by subvertallchris** [comment]
It'd be nice to check indexing status on properties.

**Comment by leviwilson** [comment]
We were _just_ talking about this today. How timely :) /cc @cheerfulstoic 

- `track_modifications`
- `define_property`
- `define_constraint`

**Comment by andrewhavens** [comment]
Sounds like this should be `shoulda-matchers-neo4j` or `neo4j-rspec` analogous to: https://github.com/mongoid-rspec/mongoid-rspec

**Comment by cheerfulstoic** [comment]
Indeed!  `track_modifications` is for making sure that a `created_at` and `updated_at` exist.  I think we'd definitely want a `define_index`.

A `neo4j-rspec-matchers` gem would be great and probably an easy project for somebody to pick up :wink:

**Comment by cheerfulstoic** [comment]
For `ActiveRel` I also imagine we might have some matchers.  `come_from_model` and `lead_to_model`

For associations yeah, direction is definitely a thing.  Maybe something that checks that an `ActiveRel` model is attached.  Maybe something that checks that any relationship type is allow.

**Comment by sineed** [comment]
I've created new repo https://github.com/sineed/neo4j-rspec.
I'm new to Neo4j and I find it a good attempt to learn and help community. I've already implemented `have_many` matcher. 
I will continue to add new matchers if nobody minds.

**Comment by cheerfulstoic** [comment]
This is great @sineed , thanks!  I've actually got a half finished PR for this repo with some extra matchers.  Look for that soon

**Comment by cheerfulstoic** [comment]
For anybody else reading this thread, I submitted a PR to add `define_property`, `define_constraint`, `track_creations`, and `track_modifications` matchers
