### ISSUE TITLE
nodes(path) results vary with and without wrapping under transaction

### ISSUE THREAD

**Issue by ezuhaib** [neo4jrb/neo4j#1125]
Given that I have the model:

```ruby
class Person
  include Neo4j::ActiveNode
  property :name
  has_many :out, :children, type: 'PARENT_OF', model_class: :Person

  def self.demo
	@grandfather = Topic.create(name: 'grandfather')
	@father = Topic.create(name: 'father')
	@son = Topic.create(name: 'son')
	@grandfather.children << @father
	@father.children << @son
	Neo4j::Session.query.match("p=({name: 'son'})<-[PARENT_OF*]-({name: 'grandfather'})").return('nodes(p)').to_a[0][0].map(&:name)
  end
end
```

Running `Person.demo` inside console correctly returns: `['son','father','grandfather']`.
However if we wrap the query it in a transaction in any way, the output becomes: `['son','son','son']`

**Why wrap in transaction?**
Of course in the above example, wrapping in a transaction serves no purpose. But I end up in similar situations when I wrap my rspec examples inside transactions to speed up my tests.

**Comment by subvertallchris** [comment]
Queries run within transactions have responses that are structured a bit differently from those outside of the transaction, so we see rare issues where results are not formatted correctly. It will be helpful to clarify whether this occurs when the entire method is run in a transaction or only that last line, the query returning the data.

Is this an actual query that you're running in your app? If so, is this the only query that is presenting a problem like this?

**Comment by subvertallchris** [comment]
Yes, this is an issue with the Neo4j-core gem having issues parsing this response due to different JSON formatting when using the transactional endpoint. I seem to have found a way to fix it and simplify our transaction response parsing but it will be a few more minutes before I'm confident that it works.

**Comment by ezuhaib** [comment]
It happens in both cases: wrapping the entire method inside a transaction, and wrapping only the last line, i.e. the actual query.

And no this is not actual code.This was the simplest possible reproduction of the issue. I tried wrapping a lot of other queries inside transactions, but the others were fine. Problem only occurred while working with paths.

**Comment by subvertallchris** [comment]
Can you include the following in your gemfile:

```
gem 'neo4j-core', github: 'neo4jrb/neo4j', branch: 'simpler-transaction-response-parsing'
```

And see if it fixes the problem?

**Comment by ezuhaib** [comment]
It perfectly fixes it! :+1: 
This fix immediately allowed me to use transaction rollback as database cleanup strategy in my tests, thereby speeding them by a factor of 3! Thanks!

**Comment by subvertallchris** [comment]
Great! I need to confer with the other maintainer on the proper versioning of the release since I changed Neo4j-core's public API slightly. If you don't mind, stick with that branch and we'll leave this issue open until the patch is released and you confirm that you're using it.

**Comment by ezuhaib** [comment]
Sure!

On Sat, Jan 30, 2016 at 12:56 AM, Chris Grigg <notifications@github.com>
wrote:

> Great! I need to confer with the other maintainer on the proper versioning
> of the release since I changed Neo4j-core's public API slightly. If you
> don't mind, stick with that branch and we'll leave this issue open until
> the patch is released and you confirm that you're using it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neo4jrb/neo4j/issues/1125#issuecomment-176941823>.
>



-- 
Zuhaib M.Ali

**Comment by subvertallchris** [comment]
Sorry for the delay! Just released neo4j-core 6.1.2. Can you please update your Gemfile with:

```
gem 'neo4j-core', '~> 6.1.2'
```

And let me know if things are good? If so, I will delete the branch you have been using and close this issue.

**Comment by ezuhaib** [comment]
Great!! Working perfectly!

**Comment by subvertallchris** [comment]
Excellent!
