### ISSUE TITLE
`with_associations` and Kaminari-neo4j not working together

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1126]
I'm having issues when running `with_associations` and `kaminari` together.
I have tried this query: 
```
Article.all.with_associations(:creator).page(1).to_a
```
The `page` method comes from `kaminari-neo4j` gem.

I'm getting this error:

```bash
Neo4j::Session::CypherError: Invalid input 'K': expected 't/T' or 'e/E' (line 1, column 84 (offset: 83))
"MATCH (n:`Article`) OPTIONAL MATCH n-[:`creator`]->creator WHERE (creator:Person) SKIP {skip_0} LIMIT {limit_25} RETURN n, [collect(creator)]"
```

The generated query:

```cypher
MATCH (n:`Article`) OPTIONAL MATCH n-[:`creator`]->creator WHERE (creator:Person) SKIP {skip_0} LIMIT {limit_25} RETURN n, [collect(creator)] | {:skip_0=>0, :limit_25=>25}
```
I'm not sure if it's a `with_association` bug or something related with kaminari
It seems like `with_associations` is pulling the `return` statement in the bottom of the query.

Any ideas?

@cheerfulstoic

**Comment by cheerfulstoic** [comment]
Looks like there's a `break` in the code for `with_associations`.  I know I put it in there for a reason so I need to track that down ;)

Heading out to lunch now, but I'll look again shortly.  Thanks for the report!

**Comment by cheerfulstoic** [comment]
Ok, so this is actually kind of tough... With `with_associations` the `OPTIONAL MATCH`es aren't added to the chain until you do the enumeration (the `to_a` in your case).  I did this to copy ActiveRecord, but I'm thinking maybe it's a bad idea and that we should build the `OPTIONAL MATCH` parts at the time you call `with_associations`.

@subvertallchris do you see a problem with that?  Your feedback is welcome too @ProGM  ;)

**Comment by ProGM** [comment]
I know I already said on the previous issue with `with_associations`, but I think that adding a `with` statement before any call of `optional match` could be a solution.

Example:
```
MATCH (n:`Article`) WITH n SKIP {skip_0} LIMIT {limit_25} OPTIONAL MATCH n-[:`creator`]->creator WHERE (creator:Person)  RETURN n, [collect(creator)] | {:skip_0=>0, :limit_25=>25}

```
But, as you said, I'm not sure if this has some implication on performances....

**Comment by ProGM** [comment]
@cheerfulstoic @subvertallchris 
Any news?

`with_associations` is currently broken for 80% of use cases I tried, since `limit`, `page`, `optional_match` and sometimes `where` are breaking the generated query.

I think that eager load is quite a critical feature if someone wants to use `neo4j` in production.

Maybe to avoid problems, an options is using two queries instead of one.

Example

```cypher
MATCH (n:`Article`) RETURN n.uuid SKIP {skip_0} LIMIT {limit_25} <-- OR any other complex query here

MATCH (n:`Article`) WHERE n.uuid IN {article_ids} OPTIONAL MATCH n-[:`creator`]->creator WHERE (creator:Person)  RETURN n, [collect(creator)] <-- it's easier to control this query
```

What do you think about it?

**Comment by cheerfulstoic** [comment]
I agree that it's an important feature.  And actually, yeah, a second query could make some things a lot simpler.  It could still load multiple associations in the same query which would be better than AR.  It's frustrating because I feel like there's probably a solution but I haven't had a chance to sit down and think about it.  Life has been quite busy lately....

**Comment by ProGM** [comment]
@cheerfulstoic I see.
I'm quite new to neo4j, so I don't think I can really help with this...
When you have time please take a look. If I could help, tell me :)

In the meanwhile, I created an **horrible** patch to make it work temporary.
If someone needs, simply add this in `config/initializers`:

```ruby
module QueryProxyEagerLoadingPatch
  def each(node = true, rel = nil, &block)
    return super if with_associations_spec2.size.zero?

    query_from_association_spec2.pluck(identity, with_associations_return_clause2).map do |record, eager_data|
      eager_data.each_with_index do |eager_records, index|
        record.association_proxy(with_associations_spec2[index]).cache_result(eager_records)
      end

      block.call(record)
    end
  end

  def with_associations_spec2
    @with_associations_spec2 ||= []
  end

  def with_associations_return_clause2
    '[' + with_associations_spec2.map { |n| "collect(#{n})" }.join(',') + ']'
  end

  def with_associations2(*spec)
    invalid_association_names = spec.reject do |association_name|
      model.associations[association_name]
    end

    if invalid_association_names.size > 0
      fail "Invalid associations: #{invalid_association_names.join(', ')}"
    end

    new_link.tap do |new_query_proxy|
      new_spec = new_query_proxy.with_associations_spec2 + spec
      new_query_proxy.with_associations_spec2.replace(new_spec)
    end
  end

  private

  def query_from_association_spec2
    with_associations_spec2.inject(query_as(identity).return(identity)) do |query, association_name|
      association = model.associations[association_name]

      query.optional_match("#{identity}#{association.arrow_cypher}#{association_name}")
        .where(association.target_where_clause)
    end
  end
end

Neo4j::ActiveNode::Query::QueryProxy.include QueryProxyEagerLoadingPatch
```

And call `with_associations2` when you need to query with `limit` or `page`.

**Comment by cheerfulstoic** [comment]
Hey @ProGM could you try a branch for me?

In your `Gemfile` you could try:

    gem 'neo4j', github: 'neo4jrb/neo4j', branch: 'with_associations_fix_70'

I believe that you're using the 7.0 rc which is why I specified that branch.  If you're using 6.1.x you should try the `with_associations_fix_70` branch

This puts in a `WITH`, but it also separates all of the `OPTIONAL MATCH` clauses with `WITH` because if you have multiple associations specified and at least one of them has multiple results you'll get a cartesian product.

**Comment by ProGM** [comment]
> This puts in a WITH, but it also separates all of the OPTIONAL MATCH clauses with WITH because if you have multiple associations specified and at least one of them has multiple results you'll get a cartesian product.

Uhm, I see... I didn't noticed it! If you have time, can you write me an example of this behavior? I'm very interested in it.

However, I tried this branch, it seems to work quite good :+1:

I did just a couple of tests, but it works well with both base queries:
```ruby
Article.all.with_associations(:creator).page(1).to_a
```

But also more complex:

```ruby
Blog.all.articles.branch { topic }.with_associations(:creator).page(1).to_a
```
And it seems to work, too. :)

**Comment by cheerfulstoic** [comment]
Excellent, thanks for checking it!


So here's an example:

```cypher
  MATCH (asset:`GraphGist`:`Asset`)
  WHERE (asset.featured = {asset_featured})
  OPTIONAL MATCH asset-[:`FOR_INDUSTRY`]->industries
  WHERE (industries:Industry)
  OPTIONAL MATCH asset-[:`FOR_USE_CASE`]->use_cases
  WHERE (use_cases:UseCase)
  RETURN
    asset,
    [collect(industries),collect(use_cases)] | {:asset_featured=>true}
```

All of `MATCH` (including `OPTIONAL MATCH`) queries which are next to each other will work together to form a single match pattern.  So if my `GraphGist` has two `Industry` nodes and one `UseCase` node it will match:

gist, use_case, industry1
gist, use_case, industry2

So that when we do `collect(use_case)` we end up with duplicates.

This branch makes it work more like:

```cypher
  MATCH (asset:`GraphGist`:`Asset`)
  WHERE (asset.featured = {asset_featured})
  WITH asset
  OPTIONAL MATCH asset-[:`FOR_INDUSTRY`]->industries
  WHERE (industries:Industry)
  WITH asset, collect(industries) AS industries_collection
  OPTIONAL MATCH asset-[:`FOR_USE_CASE`]->use_cases
  WHERE (use_cases:UseCase)
  WITH asset, industries_collection, collect(use_cases) AS use_cases_collection
  RETURN
    asset,
    [industries_collection, use_cases_collection] | {:asset_featured=>true}
```

Ideally the `industries` and `use_cases` variables might be `industry` and `use_case`, but that would be a larger change and there's an argument to be made to making sure the variable name matches the association name.

**Comment by ProGM** [comment]
Oh, I see. This makes sense!

So, this bug with cartesian product was in `with_associations` also in the previous (buggy) version of it?

Definitely, this fix looks great.

**Comment by cheerfulstoic** [comment]
Great, thanks!  I've pinged a couple of other people who've had issues so I'm going to wait for at least one more confirmation, then I'll throw it into 7.0.0.

I'm a bit tempted to make a patch for 6.1.x, though it's definitely a potential breaking change in the way that queries work when you use `with_associations`.  If we have 7.0.0 out there maybe that can just be the way that we can offer for people to fix it.

Thanks again

**Comment by cheerfulstoic** [comment]
I think that `7.0.0` fixes this. Let me know if not!
