### ISSUE TITLE
Error on neo4j shell

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#1138]
I was working for the shell, in the (insane) attempt to show relationship attributes.
It returned me the following error:

```
neo4j-sh (37)$ cd -r 18
neo4j-sh [:has_dog,18]$ ls
org.neo4j.kernel.impl.core.RelationshipProxy cannot be cast to org.neo4j.graphdb.Node
```

I posted here because of the `cannot be cast to org.neo4j.graphdb.Node`

**Comment by subvertallchris** [comment]
That class still comes from Neo4j's Java API, none of the Ruby gems get involved in the shell at all.

**Comment by pdipietro** [comment]
Chris,
Can you redirect it to the right thread?
TIA
Paolo

**Comment by subvertallchris** [comment]
This issue? No, you'll need to open an issue on the Neo4j repository or ask
them in Slack. I'd ask in Slack, this doesn't look like a bug, it seems to
mean what it says. They can help you do what you're trying to do.

**Comment by pdipietro** [comment]
Well, what I want to see is just looking the attributes of a relationship.
I'll post it on the repository.
