### ISSUE TITLE
----

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1140]
Sorry, I opened this issue by mistake.

**Comment by cheerfulstoic** [comment]
Nessun problema! ;)

**Comment by ProGM** [comment]
Haha, do you know italian? :D

**Comment by cheerfulstoic** [comment]
No, so solo Google Translate;) Se vado avanti così, però, qualcosa è destinato ad andare male

**Comment by ProGM** [comment]
This last sentence, indeed, was not very correct, but I got the point, haha :laughing:
