### ISSUE TITLE
A strange behaviour with the query

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#1142]
I discovered the following wrong behaviour while running the following query:

```
old_rel = owner_name.classify.constantize.as(:o).where(uuid: owner_id).pluck(:o)

D, [2016-02-26T19:29:40.467207 #20272] DEBUG -- :  SubjectProfile 52ms MATCH (o:`SubjectProfile`) WHERE (o.uuid = {o_uuid}) RETURN o | {:o_uuid=>"cab3c913-1209-4a5a-b1d7-3f751a81cb41"}
D, [2016-02-26T19:29:40.493816 #20272] DEBUG -- : Transaction failed: wrong number of arguments (0 for 1)
```

If I copy & past & substitute parms, the query runs fine in the Neo4j browser.

![image](https://cloud.githubusercontent.com/assets/3890316/13380054/c2a54e00-de38-11e5-97d3-e6eadb9396ce.png)

**Comment by cheerfulstoic** [comment]
Odd...

"wrong number of arguments" is a Ruby error.  Can you see a backtrace to see where it's coming from?

**Comment by pdipietro** [comment]
Well, I'm having some strange behaviours like the one above.
I restarted the machine and that error disappeared. BUT:
I added the latest part of the query and the result was not as expected, without raising exceptions.

```
old_rel = owner_name.classify.constantize.as(:o).where(uuid: owner_id).has_image(:i, :r).where(r: {object: "#{object}"}).pluck(:r)
(byebug) old_rel
[]
```

Then, I run the same query on the Neo4j-shell:

```
neo4j-sh (?)$ export i_r_object="photo"
neo4j-sh (?)$ export o_uuid="bc3cb602-323e-4cae-9427-7309417cdb21"
neo4j-sh (?)$ MATCH (o:`SubjectProfile`) WHERE (o.uuid = {o_uuid}) MATCH o-[r:`has_image`]->(i:`Image`) WHERE (i.r.object = {i_r_object}) RETURN r ;
+---+
| r |
+---+
+---+
0 row
51 ms
```

while running the following query succeeded: 
```
neo4j-sh (?)$ MATCH (o:`SubjectProfile`) WHERE (o.uuid = {o_uuid}) MATCH o-[r:`has_image`]->(i:`Image`) WHERE (r.object = {i_r_object}) RETURN r ;
+---------------------------------------------------------------------------+
| r                                                                         |
+---------------------------------------------------------------------------+
| :has_image[0]{object:"photo",created_at:1451695520,updated_at:1451695520} |
+---------------------------------------------------------------------------+
1 row
60 ms
```

the difference is in the `WHERE (i.r.object = {i_r_object})`:

Why the parameter name in the first query includes the initial `i.`?
If I remove the initial i. it succeeded.

2 options: 
1. my fault in the query 
OR 
2. an error in the parm name generator.

**Comment by cheerfulstoic** [comment]
You can't do `.where(r: {object: "#{object}"})` in the context of a association proxy chain.  That's something that you would do in the `Query` API.  You could fix this in a couple of ways:

```ruby
.has_image(:i, :r).where("r.object = '#{object}'")
.has_image(:i).where_rel(object: "#{object}")
```

For the former I'd probably suggest using params:

```ruby
.has_image(:i, :r).where("r.object = ?", object)
```

**Comment by pdipietro** [comment]
Thank you.

I used the first and the last together, end it run fine.

**Comment by cheerfulstoic** [comment]
:+1:
