### ISSUE TITLE
Scopes context doesn't include associations

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1143]
I was trying to define a scope that selects all `Article`s that has a relation with `Version`.

Article and Version are defined like this:

```ruby
class Article
   ...
  has_one :out, :published_version, type: :published_version, model_class: :Version, unique: true
end

class Version
   ...
  has_one :in, :article, type: :published_version, model_class: :Version, unique: true
end
```

I built my query like this:

```ruby
Article.as(:n).published_version(:v).query.proxy_as(Article, :n)
```

And it works quite good.

So I tried to put this query in a scope:

```ruby
scope :published, -> { published_version(:v).query.proxy_as(Article, identity) }
```

But when I call `Article.published`, I receive:

```
NoMethodError: undefined method `published_version' for #<Neo4j::ActiveNode::Scope::ScopeEvalContext:0x007fb66aac2a38>
```

It's a bit annoying that Scopes can't see relations, since in ActiveRecord I could to the same by doing:

```ruby
scope :published, -> { join(:published_version) }
```

Is it a bug? Or I'm doing it wrong?

**Comment by cheerfulstoic** [comment]
Interesting.... does this work?

```ruby
scope :published, -> { all.published_version(:v).query.proxy_as(Article, identity) }
```

If not, this should definitely work:

```ruby
  def self.published
    all.published_version(:v).query.proxy_as(Article, identity)
  end
```

Probably scopes should allow for this, though.  And we should have a better way to reach out through an association to do a conditional (or even just a `MATCH` like you're doing) and then return the original scope context.  Maybe something like:

```ruby
Article.branch { |articles| articles.published_version(:v) } # Returns a scope re-wound to the "articles" point
```

**Comment by ProGM** [comment]
Uhm, I see. This is working:

```ruby
  def self.published
    all.published_version(:v).query.proxy_as(Article, identity)
  end
```
But definitely it's not a scope (so I can't chain).

The other one isn't. :(

`branch` method would be very useful!

Do you mean something like:

```ruby
def branch
  if block_given?
    yield(self).query.proxy_as(self.class, identity)
  else
    fail ArgumentError, "Block required"
  end
end
```

**Comment by cheerfulstoic** [comment]
It's not a scope, but it should work just like a scope.  Give it a try in a chain! ;)  Keep in mind, though, that the `all` is the secret to making it chain-able

And yeah, that's actually pretty much all you'd have to do I think ;)  I'd honestly be happy with the default `LocalJumpError: no block given` error if you wanted to skip the `block_given?` check.  Want to make a PR to get credit?

The only thing that I might quibble about is that I think that there might be a better name for the method out there.  I'm open to suggestions (shout out to @subvertallchris ), but `branch` is the best that I can think of at the moment

**Comment by ProGM** [comment]
Oh, yep, I know I can chain it, but I can't use it IN a chain ;)

I mean:

```ruby
Article.where(something).published
```

Oh, `LocalJumpError`! That was the name!

I'll make a pull request with it ;)

**Comment by cheerfulstoic** [comment]
I'm not sure I understand ;)  I think that you can use it in a chain, but can you give me an example of what works and what doesn't, and for when it doesn't work what's wrong with it?

A PR would be great, thanks!

**Comment by ProGM** [comment]
I have still my problems with `scope`s :laughing: 
if I do:
```
  def self.published
    all.branch { published_version }
  end
```

I can do:

```ruby
Article.published.where(...)
```
But not:
```ruby
Person.articles.published.where(...)
```

I should use a `scope` for this, but if I do:
```ruby
scope :published, -> { all.branch { published_version } }
```
I got:
```bash
undefined method `branch' for #<Neo4j::ActiveNode::Scope::ScopeEvalContext:0x007fd359843a30>
```

This is because the `ScopeEvalContext ` delegates only this methods:
https://github.com/neo4jrb/neo4j/blob/371ad1ce48311f7b32486d3c4862c1f660ed19d5/lib/neo4j/active_node/query/query_proxy.rb#L141

I think we can change this:
https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/scope.rb#L93
To delegate more methods (example: `branch`, or also associations)

**Comment by cheerfulstoic** [comment]
`scope` is something that comes from `ActiveRecord`.  In `ActiveRecord` it is mostly the same as a class method.  This article, though covers some of the differences:

http://blog.plataformatec.com.br/2013/02/active-record-scopes-vs-class-methods/

I think our `scope` method is probably broken in at least a couple of ways.  I think that this could probably be fixed relatively easily by having it define a class method (dealing with the context that the method runs in will need to be figured out).

**Comment by ProGM** [comment]
I think that this could be closed
