### ISSUE TITLE
Verify/fix modification of `DeclaredProperty` when using `index` class method

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#1145]
A comment on https://github.com/sineed/neo4j-rspec/pull/4 reports that `Model.index :property` does not correctly update the `DeclaredProperty` option, so reflection is impossible.

**Comment by sineed** [comment]
I wrote some specs in #1146 now I think that index method is correct.

**Comment by sineed** [comment]
Think that this may be closed

**Comment by subvertallchris** [comment]
:pray:
