### ISSUE TITLE
Strange behavior with transactions and `save`

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1156]
I have a model like this:
```ruby
class Resource
  include Neo4j::ActiveNode
  ...
  property :url, type: String, constraint: :unique
  validates :url, presence: true, uniqueness: true
end
```
I tried this code:

```ruby
old = Resource.new(url: 'http://www.google.it')
old.save # => true

Neo4j::Transaction.run do |tx|
  new_res = Resource.new(url: 'http://www.google.it')
  puts tx.failed?  # => false
  new_res.save # => false
  puts tx.failed? # => true
  # many other things that doesn't fail
end
# HERE EVERYTHING IS SILENTLY ROLLBACKED
```

This behavior is veeeeery strange, since I expect that `save` is not like `save!`, so the transaction should not fail when if returns false.

**Comment by subvertallchris** [comment]
We can trace that back to https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/shared/validations.rb, which is from July 2014, but that was part of the ActiveRel alpha (!!!) branch, when I moved stuff out of ActiveNode and into Shared. If we follow parents, we can find its introduction in July 2013 as part of the rebuild of the gem. Behold: https://github.com/neo4jrb/neo4j/commit/010eb20876ed81386ac4ee63adee5847c7c1b8f3

I think we could change this default but let's give some thought to why it's there in the first place. Changing the default would have to wait for the 8.0 release, unfortunately, but we could start by making it configurable in 7.1.

**Comment by cheerfulstoic** [comment]
What about `7.0.0`?  We haven't officially released that yet.  Though I don't know how long it will take to do this.  I know we'd like to get `7.0.0` shortly.

Also, as a separate issue, I don't think you need the `uniqueness: true` in your validation because of the constraint because of the DB constraint and it will do an extra query.

**Comment by subvertallchris** [comment]
We've tried to avoid breaking API changes once we have an RC out in the
past, unless we want to count this as a bugfix, which I'm not sure I would.

**Comment by cheerfulstoic** [comment]
Ah, that's a good point as `rc` vs `beta`.  I put in the `with_associations` thing which is a breaking change, but that also fixes a number of issues people have been having and I was debating even about putting it in 6.1.x

**Comment by ProGM** [comment]
> Also, as a separate issue, I don't think you need the uniqueness: true in your validation because of the constraint because of the DB constraint and it will do an extra query.

@cheerfulstoic  Yes, but if I don't add `uniqueness: true`, when I `save` I'll got a `Neo4j::Server::CypherResponse::ConstraintViolationError`, and `errors` attribute will not be populated...


> Changing the default would have to wait for the 8.0 release, unfortunately, but we could start by making it configurable in 7.1.

@subvertallchris Why don't making it configurable from 7.0? I don't think that a configurable option is considered a breaking change.

**Comment by subvertallchris** [comment]
I think we should try to avoid adding anything to the RC that we wouldn't add to a bugfix release. There's nothing keeping us from releasing 7.1 almost immediately after the official 7.0, though. We've done it before!

While we're on the topic, I think 7.0 has proven to be stable. Maybe we should go ahead with that to keep things going?

**Comment by cheerfulstoic** [comment]
@ProGM good point about the `errors`

To follow semantic version, any sort of non-breaking change that we make should bump the minor version.  I'm happy to either release a 7.1 immediately or we could make a branch off master with the configuration.  That way you wouldn't need to worry about any additional changes that we make to master unexpectedly breaking things.

`7.0.0` released!
