### ISSUE TITLE
Was `find_or_initialize_by` method removed?

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1157]
It was added here:
https://github.com/neo4jrb/neo4j/pull/33

But now `Model.find_or_initialize_by` returns a `NoMethodError`. Is it intentional?

**Comment by subvertallchris** [comment]
This was in the old version of the gem. 3.0 was a complete rebuild, looks
like it was lost with that. We'll need to recreate it.

**Comment by ProGM** [comment]
Uhm, I see. I can make a PR with it, I think it's pretty simple to implement :+1:

**Comment by cheerfulstoic** [comment]
:dancers: 

Beers on me for @ProGM the next time we're in the same place ;)

**Comment by ProGM** [comment]
:beers:

Looking forward to your travel in Italy :laughing:
