### ISSUE TITLE
has_one/has_many require a model_class?

### ISSUE THREAD

**Issue by Joshfindit** [neo4jrb/neo4j#1171]
When working with Rails, it seems that a model_class is required, but this is not desired.

### Code example

    has_many :in, :atCoordinates, type: :GEOSPATIAL_RECORDED_AT

`@geospatial_node.atCoordinates` Results in: `Could not find class: ::AtCoordinate`

    has_many :in, :atCoordinates, type: :GEOSPATIAL_RECORDED_AT, model_class: :Artefact

`@geospatial_node.atCoordinates` returns results as expected

### Runtime information:

Neo4j database version: 2.3.2
neo4j (6.1.10)
neo4j-core (6.1.2)

**Comment by subvertallchris** [comment]
The gem always tries to find the model based on the association name but if it doesn't match, you have to provide the model class.

**Comment by Joshfindit** [comment]
Based on your comment, I was looking over https://github.com/neo4jrb/neo4j/wiki/Neo4j-v3-Declared-Relationships , and it did bring some clarity about how Neo4jrb is working here.

So, how do we specify that a node can connect to any other node through a specific relationship type?
This is trivial in Neo4j, and it feels like there's something missing.

**Comment by subvertallchris** [comment]
You set `model_class: false`. There some examples [here](https://github.com/neo4jrb/neo4j/wiki/Neo4j-v3-Declared-Relationships#association-names-polymorphic-matches-and-overriding-the-model).

**Comment by Joshfindit** [comment]
Aha; I thought I was missing something!
Cheers
