### ISSUE TITLE
Objects inconsistently respond to .empty, .nil, etc

### ISSUE THREAD

**Issue by Joshfindit** [neo4jrb/neo4j#1175]
This relates to trying to find a performant way to display related nodes in a Rails view (more discussion here: https://github.com/neo4jrb/neo4j/issues/1172 ).

While fumbling around at finding a solution by checking if there is a connected node, then displaying the correct information if there is (and showing 'none' when there is not), I've been using what seem to be the right choices:

* `node.relationship.try?`
* `node.relationship.results?`
* `node.relationship.empty?`
* `node.relationship.nil?`
* `node.relationship?`

Unfortunately, no single solution seems to work. `empty` is not always defined, `nil` will sometimes return false when where is no node, and so-on.

There are two parts to this question:

1. Is there a better way to display the right content when an node is connected to other nodes?
  - Both in a `has_one` and `has_many` situation
2. Is there a method that is consistent across all relationship and node types that *always* returns (in the same format) whether there is a connected node or not?

### Runtime information:

Neo4j database version: 2.3.2
`neo4j` gem version: 7.1.0
`neo4j-core` gem version: 6.1.2

**Comment by subvertallchris** [comment]
We ended up talking about this in Slack, so the issue went unanswered, but I just want to comment here in case anyone else comes upon it.

When your association is a `has_many`, it behaves like an enumerable of 0 or more nodes and you should interact with it like it's a list of things; when it's a `has_one`, it is nil or a single node and you interact with it accordingly. Therefore, you'd use `empty?` or something like it to check for the presence of associated nodes over a `has_many` and `nil?` for a `has_one`.

For the two parts of the question:

1. There isn't a better way than knowing what the association is and what you expect it to do. As we discussed in Slack, if you're programatically looping through ALL associations and displaying ALL content, you might be heading down a really bad path.

2. You can use the `association_proxy` instance method, which will always return an enumerable on which `each` can be called.

```ruby
student.association_proxy(:favorite_lesson).each do |lesson|
  # There will only ever be 0 or 1 lessons here
end
```

I don't really think this is something you should have to rely on too much, though.

Going to close this issue, anyone is free to get in touch if they have questions.

**Comment by Joshfindit** [comment]
Interestingly enough, in recent Rails projects, using `.empty?` on a `has_many` relationship is failing, but `.nil?` is working.
