### ISSUE TITLE
Rails 5.0.0.beta4 - to_prepare is deprecated

### ISSUE THREAD

**Issue by Joshfindit** [neo4jrb/neo4j#1189]
I'm sure this is minor, and may be addressed elsewhere, but it's over my head and I'm submitting just in case.

`DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead) (called from <class:Railtie> at /home/josh/.rvm/gems/ruby-2.2.4/bundler/gems/neo4j-f7f7f6f94642/lib/neo4j/railtie.rb:11)`

When running `rails s` with:

```
gem 'rails', '>= 5.0.0.beta4', '< 5.1'
gem 'neo4j', github: 'neo4jrb/neo4j', branch: 'rails5'
```

The app does serve pages as expected.

**Comment by cheerfulstoic** [comment]
Just made a commit to the `rails5` branch:

https://github.com/neo4jrb/neo4j/commit/c9d74c1add48fda35afbac486867ce1a88e6bb7d

Could you try a `bundle update neo4j` with that `Gemfile` line and see what you get?

**Comment by Joshfindit** [comment]
Yep, the warning is gone; bravo. :)
