### ISSUE TITLE
require 'base64'

### ISSUE THREAD

**Issue by roscom** [neo4jrb/neo4j#1193]
Additional information which could be helpful if relevent to your issue:

### Runtime information:

Neo4j database version:
`neo4j` gem version: 
`neo4j-core` gem version:

**Comment by cheerfulstoic** [comment]
Is there a place where it can't find `Base64`?  Can you provide a backtrace?

**Comment by roscom** [comment]
Sorry about that one.Typing in the wrong window. Please ignore.

**Comment by cheerfulstoic** [comment]
It's cool ;)
