### ISSUE TITLE
before_save, before_create callbacks are not working in neo4j v7.0.4

### ISSUE THREAD

**Issue by rahulmeena13** [neo4jrb/neo4j#1196]
Hey there, 
Thanks for this awesome Gem, I am moving my existing ActiveRecord(RDBMS) rails app to Neo4j. 
Rails: 4.2.6, ruby: 2.3.0, neo4j-core v6.1.3

I initially used the 6.1.x version of neo4j gem, had trouble with parenthesis mentioned in issue #1187, Neo4j v3 Syntax. So I updated to latest version 7.0.4, with @cheerfulstoic pull request changes. 

I ported my existing ActiveRecord model Session to ActiveNode:
```
class Session
  include Neo4j::ActiveNode

  scope :only_active, -> { where(is_active: true) }

  property :auth_token, type: String, index: :exact
  property :is_active, type: Boolean

  property :created_at, type: Integer
  property :updated_at, type: Integer

  validates_presence_of :auth_token
  validates_presence_of :device_id
  before_create :generate_auth_token
private
    def generate_auth_token
      unless self.auth_token
        self.auth_token = SecureRandom.hex(64)
        self.is_active = true
        self.expires_at = Time.zone.now + 1.month
      end
    end
end
```

The generate_auth_token was working fine in ActiveRecrod, and the auth_token was generated successfully. However I could not get it to work with ActiveNode. As soon as I call session.save on the object, it fails since the validation failed. I tried before_save just in case, but it wasn't working either. 
I finally got the code working with before_validation callback, which is working perfectly fine. But I would like to get to the bottom of this since before_save/create callbacks have been used extensively in my app. And it would cause quite a bit of pain to not have them :|

Any clues as to why this may be happening?

**Comment by subvertallchris** [comment]
I wouldn't expect that to work in ActiveRecord, since `before_create` always takes place after validation. Check out http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html, it shows the order in which callbacks are fired. Any callbacks associated with save or create actions will take place after validation has given its 👍.

If you don't want to use `before_validation`, you can use an `after_initialize` callback:

```ruby
after_initialize :generate_auth_token

def generate_auth_token
  return if self.auth_token
  self.auth_token = SecureRandom.hex(64)
  self.is_active = true
  self.expires_at = Time.zone.now + 1.month
end
```

**Comment by rahulmeena13** [comment]
Yeah I just checked, I happened to have a default value for the auth_token in active record version which was blank "" and I was checking uniqueness, so validation was never failing. Can't believe I overlooked that. Thanks for the after_initialize suggestion, makes much more sense of sense.
