### ISSUE TITLE
scopes are not inherited

### ISSUE THREAD

**Issue by veetow** [neo4jrb/neo4j#1205]
Given two `ActiveNode` classes, `Parent` and `Child`, if `Parent` includes a `scope`, that `scope` is not available in `Child`.

PR coming with failing spec to illustrate the issue.

### Runtime information:

Neo4j database version: 2.3.2
`neo4j` gem version: 6.1.5
`neo4j-core` gem version: 6.1.1

**Comment by veetow** [comment]
I've verified that this is also broken in the `7.1.x` and `master` branches.

**Comment by cheerfulstoic** [comment]
Great catch, thanks (and thanks for the failing spec)!

I'm headed to bed, but I'll put this on my list to look at tomorrow

**Comment by cheerfulstoic** [comment]
I've got a fix!  Give 6.1.11 a try and let me know if it works for you.  If it does I'll move the fix forward to the 7.0.x series.

Thanks again for reporting this!

**Comment by veetow** [comment]
Thanks @cheerfulstoic.  6.1.11 does work for me.

**Comment by cheerfulstoic** [comment]
Awesome!  Also released as 7.0.7
