### ISSUE TITLE
rake neo4j:install  error

### ISSUE THREAD

**Issue by FingersKey** [neo4jrb/neo4j#1212]
rake neo4j:install[enterprise-latest,test]

Errno::ENOENT: No such file or directory @ rb_sysopen - db/neo4j/test/conf/neo4j-server.properties

**Comment by ProGM** [comment]
I think you have an old version of `neo4j-rake_tasks`.
If you write `rake neo4j:install[enterprise-latest,test]`, it will try to install v3.0.1, that is supported from v0.5.5+

https://github.com/neo4jrb/neo4j-rake_tasks/blob/master/CHANGELOG.md

Try upgrading it running `bundle update neo4j-rake_tasks`.

**Comment by FingersKey** [comment]
Thank you, solved
