### ISSUE TITLE
Implement after_commit callback

### ISSUE THREAD

**Issue by CraigSnowden** [neo4jrb/neo4j#1218]
Given that queries are wrapped in a transaction by default, would it be possible to implement the _commit and _rollback callbacks?

**Comment by cheerfulstoic** [comment]
This is certainly something that I would like to see.  @ProGM actually just suggested this recently.  Would you like to comment Piero?

**Comment by ProGM** [comment]
I plan to work on this soon.

I took a look to ActiveRecord, and I noticed that Rails5 added new callbacks, to manage commit-based callbacks.

For example, if you wanted to capture commits only on creation, before you had to do something like:

```ruby
after_commit :something, on: :create
```

Now it's:

```ruby
after_create_commit :something
```

I think we should implement it in the same way.

What do you think?

**Comment by cheerfulstoic** [comment]
Sure, I'm definitely all for copying the state of the art of ActiveRecord.  They're such a big project that I think they've done a lot of the thinking for us on the topic of making an ORM (so long as it's not very different from Neo4j)
