### ISSUE TITLE
Class loading problems with subclasses & modules

### ISSUE THREAD

**Issue by bloomdido** [neo4jrb/neo4j#1219]
I have the following ActiveNode definitions:

```
class URL
  include Neo4j::ActiveNode

  property :value
end

class Event
  include Neo4j::ActiveNode
end

module DataSource
  class URL < ::URL
    self.mapped_label_name = "DataSource"

    has_one :out, :recipient, type: "DATA_SOURCE_FOR", model_class: false
  end
end

module DataSource
  class Event < DataSource::URL
  end
end
```

When I make the following query, the class I get back is an `::Event`, not a `DataSource::Event`.

```
data_source = DataSource::URL.find_by(value: "/some/value")
event = data_source.recipient    # method_missing error because data_source is an ::Event, not DataSource::Event
```

This is happening because `Neo4j::ActiveNode::Labels::model_for_labels([:URL, :DataSource, :Event]) `is returning `::Event`.

Two me, there are two actual bugs here:

1. `Neo4j::ActiveNode::Labels::model_for_labels` isn't returning the correct class
2. `DataSource::URL.find_by` is returning something other than a `DataSource::URL`

I am going to create a test for this (once I can figure out how the spec tests work) and probably try to fix issue 1 today with a PR. Issue 2 seems like a more systemic problem with type checking, and possibly is related to #1213.

**Comment by bloomdido** [comment]
FTR, in my case above, I have my config set to demodularize labels (as anyone would).

**Comment by cheerfulstoic** [comment]
Good catch, thank you for finding this and let us know if you would like any help figuring out the specs!

You might be surprised how often not demodularizing labels can be useful, but I could certainly see the argument for demodularizing being the default.  One thing that I ran into recently, though, was that we aren't demodularizing the `type` for `ActiveRel` and that is definitely a case where we should be demodularizing (at least by default)

**Comment by bloomdido** [comment]
Yeah, I've encountered that, as I namespace all my ActiveRels in a module called "Relationships" for organizational purposes.

**Comment by bloomdido** [comment]
Turns out this is a very simple bug caused by using the wrong Enumerable method. I have a fix and a tests written up, but it seems theres another rspec test that's failing due to my fix. It looks to be completely unrelated, but I'm gonna give myself another 30 minutes or so to track it down before I pass it on to the experts...
