### ISSUE TITLE
Cannot use ? params in scope where clause

### ISSUE THREAD

**Issue by yourpalal** [neo4jrb/neo4j#1224]
### Code example (inline, gist, or repo)

    class Person
        include Neo4j::ActiveNode
        property :name
        has_many :out, :friends, type: :friend, model_class: 'Person'
        scope :has_friends ->(count) { where("SIZE((#{identity}-[:friend]-()) = ?", count)  }
    end

    Person.all.has_friends(3)

### Runtime information:

raises the error: ```gems/neo4j-c2680108df1e/lib/neo4j/active_node/scope.rb:114:in `where': wrong number of arguments (given 2, expected 0..1) (ArgumentError)```

Looks like the problem is  at this line: 

https://github.com/neo4jrb/neo4j/blob/39456bf782f5a4fdb58f2108110e64837750c1ac/lib/neo4j/active_node/scope.rb#L109

**Comment by ProGM** [comment]
I think you can replace the `?` with a parameter, like this:

```ruby
scope :has_friends ->(count) { where("SIZE((#{identity}-[:friend]-()) = {identity_size}").param(identity_size: count) }
```

**Comment by yourpalal** [comment]
@ProGM I thought about that, but then if the scope is used twice in one query it will break, correct? I'm under the impression that ? params can be used multiple times in the same query (maybe I'm wrong about that!).

eg `Person.all.has_friends(2).friends.has_friends(5)`

Obviously that's a bit convoluted, but you get the drift.

As far as using a named parameter, it could be a helpful workaround for some cases, but I think that the methods in a scope context should behave the same as the methods on a query proxy.

**Comment by cheerfulstoic** [comment]
I was trying to reproduce this for a while and then realized that you're running off `master`.  That's actually a bad idea at the moment and I'm working on fixing `master` currently.  Can you reproduce on 7.0.11?

You should be able to use multiple question mark params in the query (definitely let us know if not), but it should translate those as Neo4j parameters with names like `question_mark_param_1`

**Comment by yourpalal** [comment]
@cheerfulstoic First of all, sorry that I took up your time like that! I actually am running from `master` but did not realize it. Sorry :(

I modified the example to not use identity (which exists on master but not in 7.0.11). and tried it again on 7.0.11. It seems the problem exists there too.

```
class Person
    include Neo4j::ActiveNode
    has_many :out, :friends, type: :friend, model_class: 'Person'
    scope :has_friends, ->(count) { where("SIZE((p)-[:friend]-()) = ?", count)  }
end

Person.all(:p).has_friends(3)
```

raises

```gems/neo4j-7.0.11/lib/neo4j/active_node/scope.rb:110:in `where': wrong number of arguments (given 2, expected 0..1) (ArgumentError)```


From the code that I linked, it looks like the problem could be solved by using parameter splatting?

The dynamic naming of question mark params is the feature I want to take advantage of, instead of using a regular old named parameter, which is subject to naming collisions.

**Comment by cheerfulstoic** [comment]
I think that this is a bug in `scope`.  In general I think we need to fix the way that we do scopes because that sometimes work a bit funny like this.  What if you try this?

```ruby
class Person
  include Neo4j::ActiveNode
  has_many :out, :friends, type: :friend, model_class: 'Person'
  def self.has_friends(count, var = :p)
    all(var).where("SIZE((#{var})-[:friend]-()) = ?", count)
  end
end
```

**Comment by yourpalal** [comment]
@cheerfulstoic Yes, that would work. I was hoping to use scopes because the composability makes it very easy to write readable, DRY queries.

It should work to splat the params given to `scope` into the lambda, right?

eg.

```
      Neo4j::ActiveNode::Query::QueryProxy::METHODS.each do |method|
        module_eval(%{
            def #{method}(*params)
              @target.all.scoping do
                (@query_proxy || @target).#{method}(*params)
              end
            end}, __FILE__, __LINE__)
      end
```

**Comment by ProGM** [comment]
@yourpalal I had a similar issues the first times I used Neo4j gem.

Even if it's not documented, `Neo4j::ActiveNode` class methods, as opposed to
ActiveRecord, are composable exactly like scopes in `ActiveRecord`.

So you can write:

```ruby
class Person
  include Neo4j::ActiveNode
  has_many :out, :friends, type: :friend, model_class: 'Person'
  def self.has_friends(count, var = :p)
    all(var).where("SIZE((#{var})-[:friend]-()) = ?", count)
  end
end
```

And then call:
```
Person.has_friends(2).friends.has_friends(5)
```

And it works!

**Comment by ProGM** [comment]
About that, @cheerfulstoic , an hot fix for scopes could be to replace the current implementation with a something like:

```ruby
def scope(name, lambda)
  define_singleton_method(name, &lambda)
end
```

Just an idea ;)

**Comment by cheerfulstoic** [comment]
Thanks @ProGM 

Definitely class methods work just as well as `scope` (perhaps better, as you've found).  If you use the `all` (which takes an argument for the node variable), you should be able to chain class methods together.

And yes, just having `scope` define class methods could certainly be a good fix.  Perhaps even a permanent one
