### ISSUE TITLE
Use 'id' as a normal property.

### ISSUE THREAD

**Issue by robfors** [neo4jrb/neo4j#1229]
Hello, is there a simple way to use 'id' as a property name just like any other property name?
I am working with data that already has unique ids.

Code that is having issues:
```ruby
class User
  include Neo4j::ActiveNode
  
  property :id, type: Integer
  property :idd, type: Integer
end

User.create(id: 5, idd: 7) # no errors reported, however the id property never makes it to the neo4j database, the idd property works without a problem
```

Is it possible to turn off the librarie's built in id functionality entirely?

Neo4j database version: 3.0.3
`neo4j` gem version: 7.0.12
`neo4j-core` gem version: 6.1.4

**Comment by cheerfulstoic** [comment]
Yup!  There is an `id_property` method which you can use to define the `id` for a model.  It's documented here:

https://github.com/neo4jrb/neo4j/wiki/Neo4j-v3-Unique-IDs

(sorry that hasn't been moved to the official neo4jrb.readthedocs.org docs yet)
