### ISSUE TITLE
Can't assign `enum` properties from `ActionController::Parameters` in Rails 5 

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1244]
Can't assign `enum` properties from `ActionController::Parameters` in Rails 5:

```ruby
irb(main):005:0> Desk.new(ActionController::Parameters.new({title: "some", type: 'timeline'}))
=> #<Desk uuid: nil, created_at: nil, title: "some", type: :standard, updated_at: nil>
```

(`type` is ignored, default value is used instead)

The issue seems to be related to rails 5:
In fact `ActionController::Parameters` is no longer a child of `Hash`.

### Runtime information:

Neo4j database version: 2.3.3
`neo4j` gem version: 7.1.0
`neo4j-core` gem version: 6.x

**Comment by cheerfulstoic** [comment]
That sucks ;(

I think I'm close to getting my branch ready (how many times have I said that now?)  The index / constraint functionality has been removed and replaced by warnings / errors, and now I need to get all of the tests working that expect the indexes / constraints to be created automatically

**Comment by cheerfulstoic** [comment]
(all that to say I can look at this afterward if you need help ;)
