### ISSUE TITLE
neo4jrb failing when doing `map` on an empty relationship

### ISSUE THREAD

**Issue by Joshfindit** [neo4jrb/neo4j#1246]
When using `:selected => @artefact.tags.map(&:id)` in ActiveRecord, if there are no `tags`, then an empty array is returned.
With Neo4j, an error stops the processing:  ```undefined method `map' for nil:NilClass```.

Additional information which could be helpful if relevant to your issue:

### Code example (inline, gist, or repo)

```
 <div class="field">
  <%= f.label :tags_id %><br>
  
  <%= f.collection_select(:tags, Tag.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {
    :prompt => "Please Select an Item",
    :selected => @artefact.tags.map(&:id)
  },
  html_options = {:multiple => true, :class=>"search"}) %>
</div>
```

### Runtime information:
Rails 5.0
`neo4j` gem version: 7.1.0
`neo4j-core` gem version: 6.1.4

**Comment by cheerfulstoic** [comment]
Interesting, is your `tags` association `has_one` or `has_many`?  If it is `has_many` then this seems broken.  If it's `has_one` then that makes sense.  You could do `@artefact.as(:a).tags.map(&:id)`.  That would first turn the `@artefact` variable into a query proxy and then you can call either type of association to build the chain.

Alternatively to have a somewhat more efficient query you can just return the `id` properties like this:

```ruby
# For `has_many`
@artefact.tags.pluck(:id)

# For `has_one`
@artefact.as(:a).tags.pluck(:id)
```

**Comment by Joshfindit** [comment]
The association is `has_many`, yes.

I've switched to using pluck, but leaving this open as this could catch users who are coming from ActiveRecord.

**Comment by cheerfulstoic** [comment]
Sounds good.  I'm going to close the issue because people should still be able to find it, but definitely reopen/comment if you're still having an issue or want to discuss it.  Thanks!
