### ISSUE TITLE
Arrays passed as question mark params only use the first value

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#1247]
Additional information which could be helpful if relevent to your issue:

### Code example (inline, gist, or repo)

```ruby
.where("something.something IN ?", ['foo', 'bar'])
```

### Runtime information:

Neo4j database version:
`neo4j` gem version: 7.0.14
`neo4j-core` gem version: 6.1.4

**Comment by ProGM** [comment]
Fixed in 7.2.1, 7.1., 7.0.16 and also on master. an 8.x release is upcoming.
