### ISSUE TITLE
`destroy` should return the object

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#1254]
This is consistent with what `ActiveRecord` does.  Currently `ActiveNode` models return `true` when `destroy` is called.

Should be easy, and 8.0 would be a good time for the API change

**Comment by subvertallchris** [comment]
I personally prefer our approach but do agree that we should maintain
parity with AR to prevent surprise. That's definitely one to display
prominently in the changelog!

**Comment by cheerfulstoic** [comment]
Definitely in the `CHANGELOG` as well as the migration guide

**Comment by cheerfulstoic** [comment]
Done on `8.0.x`

**Comment by ProGM** [comment]
Closing since it's released in 8.0.0.alpha.4
