### ISSUE TITLE
Enums should suggest adding an index on initialization

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1259]
In neo4j 8.0, enums should not try to define an index anymore. Instead, there should be a warning after defining an enum that suggest to setup an index using migrations.

Or maybe nothing at all, like AR does.
### Runtime information:

Neo4j database version: 3.0.3
`neo4j` gem version: 8.0.0
`neo4j-core` gem version: 7.0.0

**Comment by cheerfulstoic** [comment]
Weird...  I thought I had done this.  There's even a special method `ModelSchema.add_required_index` to handle this case, but I might not have implemented it completely...

**Comment by ProGM** [comment]
Indeed your code works, but... Isn't it though to migrate to neo4j 8?

My proposal is to have a "special" warning, that the user can simply ignore ;)

**Comment by cheerfulstoic** [comment]
Ah, so you're saying that they should be able to ignore it rather than it raising an exception?

**Comment by ProGM** [comment]
Yes. Indexing enums shouldn't be mandatory, since it's useful only if you're making search queries on it, right? Just a proposal, though

**Comment by cheerfulstoic** [comment]
Yeah, that's true.  I think that I assumed that people would almost always be making queries, but I guess that's not really true.

One concern that I'd have about a warning, though, is that somebody might want to not have an index in one place, but still want to be warned in other places.  Would there be a way to turn off warnings global / just for specific enums?

**Comment by ProGM** [comment]
Something like `require_index: false`?

**Comment by cheerfulstoic** [comment]
Yeah, that seems good to me.  I would probably put a note in the `WARNING` telling people about that option.

**Comment by thefliik** [comment]
@cheerfulstoic, I believe this issue has been resolved by [`enum _index: false`](http://neo4jrb.readthedocs.io/en/8.2.x/ActiveNode.html?highlight=enum#enums)

**Comment by thefliik** [comment]
oops, I take back my previous comment, apparently _index: false doesn't do what I thought it did. enums without indexes still raise an exception, they're just lazily evaluated.
