### ISSUE TITLE
Conflict with other railtie or initializers

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#1266]
When adding `require 'neo4j/railtie'` to my `application.rb`, Rolify's engine breaks and the following error is encountered:

```
undefined local variable or method `scopify' for Role (call 'Role.connection' to establish a connection):Class (NameError)
```

### Runtime information:

`neo4j` gem version: 3.x - 7.1.x, possibly 8.x

**Comment by subvertallchris** [comment]
Some searching revealed similar issues with other gems. The common solution is to change the order of inclusion in your `Gemfile`, but this presumes the gem will require the Railtie for the user. Since the Neo4j gem requires manual inclusion, the solution is to require the Railtie after `Bundler.require`.

```
# breaks
require 'neo4j/railtie'
Bundler.require(:default, Rails.env)

# works
Bundler.require(:default, Rails.env)
require 'neo4j/railtie'
```

**Comment by ppascualv** [comment]
I had the same issue, but this seems more a work arround than a real solution. 
Is there another solution?

**Comment by cheerfulstoic** [comment]
I see the fix, but I'm not 100% sure about the problem.  What's causing the conflict (at least in your case, @ppascualv )
