### ISSUE TITLE
session_url cannot be configured in config/application.rb anymore

### ISSUE THREAD

**Issue by klobuczek** [neo4jrb/neo4j#1267]
In 8.0 session_url configured in config/application.rb (or the other env files) is ignored.

Additional information which could be helpful if relevent to your issue:

### Runtime information:

Neo4j database version:
`neo4j` gem version: 8.0
`neo4j-core` gem version:

**Comment by cheerfulstoic** [comment]
Thanks for noting this!

**Comment by ProGM** [comment]
Released as 8.0.0.alpha.11
