### ISSUE TITLE
add update_columns method to bypass timestamp update

### ISSUE THREAD

**Issue by benjaminbradley** [neo4jrb/neo4j#1285]
ActiveRecord::Persistence implements an [update_column(s) method](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_column) to be able to update an attribute value directly in the database, bypassing validations,callbacks, and timestamp updates.

In my use case, this would be used to implement a last_access timestamp which is updated when the record is viewed, leaving the updated_at timestamp as-is.

**Comment by subvertallchris** [comment]
This is a great idea, I'm surprised the request hasn't popped up until now.

**Comment by cheerfulstoic** [comment]
Yes, this would be great!  Though perhaps the method should be `update_property` / `update_properties` and we could alias to `update_column` / `update_columns` for compatibility.

For now, you should be able to do something like:

```
user.query_as(:user).set(user: {property: value}).exec
```

That would also probably be how we would implement the method
