### ISSUE TITLE
Rails `initialize': wrong number of arguments (given 2, expected 0) (ArgumentError)

### ISSUE THREAD

**Issue by Vijeta141** [neo4jrb/neo4j#1307]
I am using a vagrant VM which uses ubuntu 16.04, rails 5.0.0.1 and gem 'neo4j', github: 'neo4jrb/neo4j', branch: 'rails-5-neo4jrb-7.0.x' .After successfully installing everything required on the vm to build a rails application with neo4j as the database, when i type in "rails console", the following error is displayed:

/home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in `initialize': wrong number of arguments (given 2, expected 0) (ArgumentError)

Can someone please help me understand why this is happening and how to solve it?

**Comment by ProGM** [comment]
It's a known bug of `net-http-persistent` 3.0 gem, try to lock it in your Gemfile in this way:

```
gem "net-http-persistent", "< 3.0"
```

P.S. Instead of using `rails-5-neo4jrb-7.0.x` branch, try upgrading to `neo4j` "~> 7.2", it has rails 5 support and many other improvements ;)

**Comment by Vijeta141** [comment]
Thank you so much!! It worked perfectly !!
