### ISSUE TITLE
Question - Inconsistent relationship query returns

### ISSUE THREAD

**Issue by jacquesporveau** [neo4jrb/neo4j#1312]
Regarding the screenshot below:

So you can see I call patch_meeting.rels and get an empty array

Then I call evaluation.from_node which returns the patch_meeting object. So the relationship does exist and it is from the patch meeting thus patch_meeting.rels should return that relationship. Also worth mentioning this call does not alter data in any way.

On the next line I call patch_meeting.rels and now it returns the expected outcome. So it was like when I called evaluation.from_node it remembered that there is a rel there. Really sketchy behaviour.

### Code example (inline, gist, or repo)

```
class Evaluation
  include Neo4j::ActiveRel
  include Neo4j::Timestamps

  enum eval_type: ['assignment', 'parked', 'resolved']

  from_class :PatchMeeting
  to_class :Shipment

  type 'EVALUATION_FOR'
end
```
<img width="1165" alt="screen shot 2016-10-11 at 1 18 43 pm" src="https://cloud.githubusercontent.com/assets/13607675/19287125/5380e2bc-8fb5-11e6-9bd5-3c07ac19e3da.png">

### Runtime information:

Neo4j database version: 2.3.5
`neo4j` gem version: 7.0
`neo4j-core` gem version: 6.1.4

**Comment by cheerfulstoic** [comment]
I see that you closed the issue, but let us know if there's anything that's still needed

**Comment by jacquesporveau** [comment]
This was an issue with rspec lazy loading variables in let statements.

I had `let(:evaluation) { Evaluation.create blehblehbleh}`
 With evaluation being a relationship between two objects it wasn't actually being created before I called the evaluation variable in my "it" blocks. Thanks anyways loving graph databases!

**Comment by cheerfulstoic** [comment]
Awesome!

In case you don't know, RSpec also lets you do `let!` instead of `let` which basically executes the let every time (kind of like a `before` block)
