### ISSUE TITLE
Database panic: java.nio.file.NoSuchFileException...write.lock

### ISSUE THREAD

**Issue by wjdhamilton** [neo4jrb/neo4j#1313]
[debug.txt](https://github.com/neo4jrb/neo4j/files/526787/debug.txt)

After trying to create a new record in neo4j, using the Rails neo4j gem, the database started to return a 500 error for all subsequent requests. The error in the log file (shown below) indicates that a file is missing from the database as detailed below. The full log is attached. 

This is the first time I've ever tried to use neo4j on a project, so I'm not really able to provide a lot of additional info, though I'm happy to supply anything anyone requests. 

`2016-10-13 09:18:52.522+0000 ERROR [o.n.k.i.DatabaseHealth] Database panic: Database has encountered some problem, please perform necessary action (tx recovery/restart) java.nio.file.NoSuchFileException: /Users/jameshamilton/sites/fresson_website/db/neo4j/development/data/databases/graph.db/schema/label/lucene/labelStore/1/write.lock
org.neo4j.kernel.impl.store.UnderlyingStorageException: java.nio.file.NoSuchFileException: /Users/jameshamilton/sites/fresson_website/db/neo4j/development/data/databases/graph.db/schema/label/lucene/labelStore/1/write.lock
    at org.neo4j.kernel.impl.transaction.command.LabelUpdateWork.apply(LabelUpdateWork.java:62)
    at org.neo4j.kernel.impl.transaction.command.LabelUpdateWork.apply(LabelUpdateWork.java:33)
    at org.neo4j.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:121)`

The db is now unusable, it will not start. 

I would like to recover the database, and more importantly stop this from happening in the future. Any help would be appreciated!
### Runtime information:

Mac OS Sierra 10.12
Neo4j database version: community-3.0.6
`neo4j` gem version: 7.2.3
`neo4j-core` gem version: 6.1.5

**Comment by cheerfulstoic** [comment]
Sorry for not responding sooner.  Were you able to figure out the issue?  Is this using jRuby embedded or server mode?

I'm not sure that I have a good answer since this seems to be something happening in Neo4j, but you might ask on Neo Technology's public Slack channel:

https://neo4j.com/blog/public-neo4j-users-slack-group/

Or alternatively on StackOverflow (I know there are at least a few Neo4j experts who watch for questions there)

**Comment by wjdhamilton** [comment]
Sorry! I somehow missed your response above. I never did get to the bottom of this, but deleting the database and starting again at least allowed me to progress and it hasn't happened since!
