### ISSUE TITLE
Properties and property options are ignored or not used in the query builder to search

### ISSUE THREAD

**Issue by tebayoso** [neo4jrb/neo4j#1327]
This could be easily tested:

```ruby
class User
  include Neo4j::ActiveNode
    
  property :name, type: String
  property :email, type: String, default: 'example@example.com'
  property :another_field, default: 'Something'
end
```

Then create two nodes:
```ruby
User.create(name: 'John', email: 'john@cena.com')
User.create(name: 'John')
```

We try to search for undeclared property **values**:
```ruby
User.where(title: 'Mr')
#<QueryProxy  CYPHER: "MATCH (result_user:`User`) WHERE (result_user.title = {result_user_title})">
```

We effectively call `Cyper` and get results, this means that the property declaration in model is not used at all in the `Neo4j::ActiveNode#where`

But neither is in the `Neo4j::ActiveNode#find`:

```ruby
User.find('title: Mr')
User 20ms MATCH (n:`User`) WHERE (n.uuid = {n_uuid}) RETURN n ORDER BY n.uuid LIMIT {limit_1} | {:n_uuid=>"title: Mr", :limit_1=>1}
```

It means is only used to set and get properties, but ignored by the finders.

Is not working either for default values in properties added after node creation:

```ruby
class User
  [...]
  property :another_field, default: 'Something'
end
```

```ruby
User.where(another_field: 'Something').count
CYPHER 82ms MATCH (result_user:`User`) WHERE (result_user.another_field = {result_user_another_field}) RETURN count(result_user) AS result_user | {:result_user_another_field=>"Something"}
=> 1
```

```ruby
User.where(another_field: nil).count
CYPHER 39ms MATCH (result_user:`User`) WHERE (result_user.title IS NULL) RETURN count(result_user) AS result_user
=> 1
```

You can search by array of values in the Cyper connector, but is not parsing properly the `nil` values:

```ruby
User.where(another_field: ['Something', nil]).count
CYPHER 12ms MATCH (result_user:`User`) WHERE (result_user.another_field IN {result_user_another_field}) RETURN count(result_user) AS result_user | {:result_user_another_field=>["Something", nil]}
=> 0
```

As you can see in the last query, `nil` is passed literally. So you can't do this.

Taking in account that Neo4j is schemaless, but thinking in this issue, maybe an implentation of a model schema for finders might be a good implementation. Also the array parsing issue should be fixed.

This was initially detected in this SO question:
http://stackoverflow.com/questions/40808845/r

**Comment by subvertallchris** [comment]
Just so I'm clear, are you saying that you would expect a property's default value to be used instead of `nil` when querying?

Also, this is not ever going to give you valid results:

```ruby
User.find('title: Mr')
User 20ms MATCH (n:`User`) WHERE (n.uuid = {n_uuid}) RETURN n ORDER BY n.uuid LIMIT {limit_1} | {:n_uuid=>"title: Mr", :limit_1=>1}
```

The `find` method is for ID values, not key/value pairs. You can see that it even queries against the UUID using the String you provided. Use `find_by` for pairs.

**Comment by tebayoso** [comment]
No the issue is that old nodes doesn't hold any information for new properties.

I understand that if you add a new property to the definition, not a single node will have it, as per schemaless definition itself. But if I add a property with a default value, all old nodes should respond to that default value search. Assuming I add `property :title, default: 'Mr', null: false` to the model. The search:

`User.where(title: 'Mr').count`

Should return all nodes that were created before the property was defined becaue I'm searching by the default, in the model they all have this value defined as `'Mr'`, and as it can't be null, it has to be the default.

I might be totally wrong around this and just making a wish to statement here, or maybe a scope is the solution for this issue. 

_You are right about the find, sorry about that._

**Comment by subvertallchris** [comment]
I understand now. In the upcoming version of the gem, we (meaning @ProGM) added an ActiveRecord-inspired `Migration` class that can be used to update data for things like this. http://neo4jrb.readthedocs.io/en/latest/Migrations.html provides detailed documentation. You can start using this now if you use v8.0.0.rc.4. I think that having the gem seek `nil` valued nodes would be an unexpected behavior for many people and potentially introduce some performance issues.

**Comment by tebayoso** [comment]
I think this migrations should be enough to handle the backwards nodes issue then. I appreciate your answer and time spent here. Closing.

**Comment by subvertallchris** [comment]
Glad to help!
