### ISSUE TITLE
Accesing relationship properties of neo4j 

### ISSUE THREAD

**Issue by Vijeta141** [neo4jrb/neo4j#1336]
I am building an application using ruby on rails and neo4j as database. I am finding it difficult to access the properties of a ActiveRel class object. 

If i query this: `p.tagged_creatives.first.rel` where p is an object of Project class and tagged_creatives is the relation from Project class to Creative class.

The relationship was created as :

    p.tagged_creatives << c 

where c is an object of Creative class

Additional information which could be helpful if relevent to your issue:

### Code example (inline, gist, or repo)
```
class HasProjectTag
  include Neo4j::ActiveRel
  from_class :Project
  to_class :any


  type 'TagStatus'

  # property :status, type: Integer
  enum status: [ :tentative, :confirm, :remove, :reject ]
end



 CYPHER 51ms MATCH (n), (n)-[r]-(p) WHERE (ID(n) = {ID_n}) RETURN r as result LIMIT 2 | {:ID_n=>78}
ArgumentError: wrong number of arguments (given 0, expected 2..3)
	from /home/vijeta/.rvm/gems/ruby-2.3.0/gems/neo4j-core-6.1.4/lib/neo4j-server/cypher_node.rb:176:in `match'
	from /home/vijeta/.rvm/gems/ruby-2.3.0/gems/neo4j-core-6.1.4/lib/neo4j-server/cypher_node.rb:211:in `ensure_single_relationship'
	from /home/vijeta/.rvm/gems/ruby-2.3.0/gems/neo4j-core-6.1.4/lib/neo4j-server/cypher_node.rb:156:in `rel'
	from (irb):9
	from /home/vijeta/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
	from /home/vijeta/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/vijeta/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/vijeta/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/vijeta/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

### Runtime information:

Neo4j database version:
`neo4j` gem version: 
`neo4j-core` gem version:

**Comment by cheerfulstoic** [comment]
I don't think I understand the question, but a few things that might help:

You can create an `ActiveRel` object by doing:

    HasProjectTag.create(project, other, status: :tentative)

Or you could do:

    project.tags.create(other, status: :tentative)

Also, I'd suggest that, as much as possible, you make your `ActiveRel` classes the same as the type.  That way you don't need to specify the type and it's less confusing to figure out how `ActiveRel` classes match to Neo4j relationships, like:

```ruby
class TagStatus
  include Neo4j::ActiveRel
  from_class :Project
  to_class :any

  enum status: [ :tentative, :confirm, :remove, :reject ]
end
```
