### ISSUE TITLE
Can not access ActiveRel relation directly

### ISSUE THREAD

**Issue by thestrangeknight** [neo4jrb/neo4j#1337]
If an active rel relation is made between two nodes, is there any way to get the relation between two nodes directly, without looping through all the 'rels' of one of the node and checking from_node/to_node property?

`node.relation_name.rel.find/where`
does not seem to exist.

**Comment by krishnarai30** [comment]
@thestrangeknight Very keen observation
I would like to rectify the problem.

**Comment by subvertallchris** [comment]
To determine whether a relationship exists between two nodes, you can do something like:

```ruby
student.lessons.where(id: math.id).exists?
```

In general, it is recommended to avoid using the association `rel` and `rels` methods because they immediately execute, returning one or many matching objects from the database. Because of this, chaining finders is not possible.

Since you mentioned ActiveRel, I'll also mention that the decision to not include finders for relationship classes was deliberate. At one point, it was possibly to do `MyRelClass.where(conditions)`, but this was deprecated for a number of reasons. It is always advisable to base queries around node classes.

**Comment by thestrangeknight** [comment]
Can you mention some reasons for this deprecation? Does looping through all the 'rels' of one node to access the relationship property between two known nodes, not give rise to code smells. Or should I change my design approach?

**Comment by cheerfulstoic** [comment]
The `ActiveRel` finders that @subvertallchris isn't about finding all relationships between two nodes, it's about finding all relationships of a certain relationship type in Neo4j, which is something which is discouraged by the design of Neo4j.  Relationships don't have any indexing and it's encouraged that you always start from one or more nodes in your queries.

But if you use `rels` to loop through relationships from a node to find the ones that are linked to another node, you've just loaded all of the relationships over the network and into Ruby's memory, which would be less efficient (if I'm understanding correctly) than making a query like what @subvertallchris is suggesting to have the database find and return just the nodes that you need.

**Comment by thestrangeknight** [comment]
> ...like what @subvertallchris is suggesting to have the database find and return just the nodes that you need.

The problem is not to return the nodes, but to return the relationship, I already have the nodes with me. The situation with me is

![gitques](https://cloud.githubusercontent.com/assets/17454742/21594199/be8a3168-d145-11e6-84e7-3e1ae5da4589.png)



**hasRel is an ActiveRel relation with a property 'id' which can contain uuid of node A or node B.** Currently to access the property of relation 'hasRel', emerging from node A and in between node R and K, I am doing something like this

```
R.hasRel.each_with_rel do |node, r|
     if r.id == A.id 
         return node
     end
end
```

```
R.hasRel.each_rel do |r|
    if r.to_node == K
       More Processing
    end
end
```

The problem is evident, In first case despite of having the relationship property "id" I have to loop through all the relationships of 'R' to get the one I want. 
And in the second case despite of having the "to_node" I have to loop through the relations of R to all the nodes to get the desired relationships.

Is there any better and efficient way to approach this problem?

**Comment by cheerfulstoic** [comment]
What about:

```ruby
R.hasRel.rel_where(id: A.id)
```

**Comment by cheerfulstoic** [comment]
:+1:
