### ISSUE TITLE
Handling recursive relationships

### ISSUE THREAD

**Issue by Joshfindit** [neo4jrb/neo4j#1346]
Just going through the basics with 8.0.5, and ran across something that's both way above my head, and an important question for later:

Is the `neo4j` gem considering recursive relationships?

I'm testing a Class who's nodes can connect to others of the same type, and have a couple test nodes that connect to themselves (I can certainly stop this from happening in production, but it's a good test for now)
Doing `Class.all[0]` seems to traverse all relationships (There's a lot returned, but I can't make sense of it), and then `Class.all[0].to_json` returns SystemStackError: stack level too deep (in this case, I have 24 nodes, and this error states `... 10976 levels...`)

### Runtime information:

Neo4j database version:
`neo4j` gem version: `8.0.5`
`neo4j-core` gem version: `7.0.3`

**Comment by cheerfulstoic** [comment]
If `Class` is an `ActiveNode` class, then I don't think the relationships should come into play when doing `Class.all`.  That should just be querying the nodes.  `Class.all[0]` will certain get all of the nodes from the DB into memory and then pick out the first.  You could use `Class.first` to get just the first node from the DB or something like `Class.where(foo: 1).order(something: :desc).first` or whatever to only get one node over the wire.

The `to_json` maybe be an issue, though, if that's trying to serialize recursively.  Do you have any custom JSON serialization?

**Comment by Joshfindit** [comment]
Here's the class definition:

```
class Artefact
  include Neo4j::ActiveNode
  property :name, type: String
  property :description, type: String
  has_many :both, :artefacts, type: :REFERS_TO, model_class: :Artefact
end
```

There's no custom `to_json` - I did play with it a little to massage the data, but quickly switched to creating a custom method to return JSON.

**Comment by Joshfindit** [comment]
Would it be helpful long-term to have `to_json` take a `max_depth` option?

**Comment by cheerfulstoic** [comment]
I wonder if this is related to this issue: https://github.com/neo4jrb/neo4j/issues/1347

If `Artefact.first` is returning a `Neo4j::Core::Node` object, then `to_json` is probably not doing the right thing

**Comment by Joshfindit** [comment]
Confirmed:
```
Artefact.first.class
=> Neo4j::Core::Node
```

Does seem to be related.
I also stopped looking at `to_json` when hitting the roadblock, rolling my own to get it going, so didn't come around full circle to notice that `Artefact.first.wrap.to_json`works.
Probably related, but trying to get the recursive relationships gets in to the same issues: 

- `arte.wrap.artefacts.to_json` = `Neo4j::ActiveNode::Labels::RecordNotFound: Couldn't find Artefact with 'uuid'=#<Neo4j::Core::Node:0x00000003d34868>`
- `arte.wrap.artefacts.result.to_json` = `SystemStackError: stack level too deep`
- etc

**Comment by Joshfindit** [comment]
Was related to https://github.com/neo4jrb/neo4j/issues/1347
Resolved now.
