### ISSUE TITLE
Accessing relationships without Rails

### ISSUE THREAD

**Issue by Joshfindit** [neo4jrb/neo4j#1347]
Looking for the 'right' (optimized for traversal) way to access relationships without Rails. (Plain Ruby + Sinatra in this case)

Filing as a 'documentation bug' as I assume there is a right way and I just haven't found it.

#### Class
```
class Artefact
  include Neo4j::ActiveNode

  property :name, type: String
  property :description, type: String

  has_many :both, :artefacts, type: :REFERS_TO, model_class: :Artefact
end
```

#### Assumption 1
```
 Artefact.first.artefacts
 CYPHER 
  MATCH (n:`Artefact`)
  RETURN n
  ORDER BY n.uuid
  LIMIT {limit_1} | {:limit_1=>1}
NoMethodError: undefined method `artefacts' for #<Neo4j::Core::Node:0x000000023e08f8>
	from (irb):34
	from /usr/local/bin/irb:11:in `<main>'
irb(main):035:0> 
```

#### Assumption 2
Since things have changed to [:property], and the syntax is now `object.properties[:property]`, looked for something like `object.relationships`

#### Assumption 3
```
Artefact.first.properties[:relationship] # knew this wouldn't work
```

#### Attempt 4 does 2 queries
```
Artefact.all[2].wrap.artefacts          
 Artefact 
  MATCH (n:`Artefact`)
  RETURN n 
 Artefact#artefacts 
  MATCH (artefact7)
  WHERE (ID(artefact7) = {ID_artefact7})
  MATCH (artefact7)-[rel1:`REFERS_TO`]-(result_artefacts:`Artefact`)
  RETURN result_artefacts | {:ID_artefact7=>7}
 Artefact 
  MATCH (n:`Artefact`)
  WHERE (n.uuid = {n_uuid})
  RETURN n
  ORDER BY n.uuid
  LIMIT {limit_1} | {:n_uuid=>4, :limit_1=>1}
Neo4j::ActiveNode::Labels::RecordNotFound: Couldn't find Artefact with 'uuid'=#<Neo4j::Core::Node:0x00000003888f30>
	from /usr/local/bundle/gems/neo4j-8.0.5/lib/neo4j/active_node/labels.rb:103:in `find'
	from /usr/local/bundle/gems/neo4j-8.0.5/lib/neo4j/active_node/has_n.rb:153:in `block in map_results_as_nodes'
	from /usr/local/bundle/gems/neo4j-8.0.5/lib/neo4j/active_node/has_n.rb:152:in `map'
	from /usr/local/bundle/gems/neo4j-8.0.5/lib/neo4j/active_node/has_n.rb:152:in `map_results_as_nodes'
	from /usr/local/bundle/gems/neo4j-8.0.5/lib/neo4j/active_node/has_n.rb:77:in `result_nodes'
	from /usr/local/bundle/gems/neo4j-8.0.5/lib/neo4j/active_node/has_n.rb:26:in `inspect'
	from /usr/local/bin/irb:11:in `<main>'
```

##### Tweaked
```
Artefact.all[2].wrap.artefacts.result[0]
 Artefact 
  MATCH (n:`Artefact`)
  RETURN n 
 Artefact#artefacts 
  MATCH (artefact7)
  WHERE (ID(artefact7) = {ID_artefact7})
  MATCH (artefact7)-[rel1:`REFERS_TO`]-(result_artefacts:`Artefact`)
  RETURN result_artefacts | {:ID_artefact7=>7}
=> #<Neo4j::Core::Node:0x00000001a0b378 @id=4, @labels=[:Artefact], @properties={:name=>"Mary", :description=>"Mary's description", :uuid=>"dd3bb970-8651-4aa9-9d3f-03a1bd733b27"}, @source_query_proxy=#<QueryProxy Artefact#artefacts [#<Neo4j::Core::Node:0x00000001a0b378 ...>]>, @source_proxy_result_cache=[#<Neo4j::Core::Node:0x00000001a0b378 ...>]>
```

##### Then
```
Artefact.all[5].wrap.artefacts.result.each do |a| puts a.properties[:name] end
 Artefact 
  MATCH (n:`Artefact`)
  RETURN n 
 Artefact#artefacts 
  MATCH (artefact21)
  WHERE (ID(artefact21) = {ID_artefact21})
  MATCH (artefact21)-[rel1:`REFERS_TO`]-(result_artefacts:`Artefact`)
  RETURN result_artefacts | {:ID_artefact21=>21}
Mary
Artefact 7
Artefact 3
```

### Runtime information:

Neo4j database version:
`neo4j` gem version: `8.0.5`
`neo4j-core` gem version: `7.0.3`

**Comment by cheerfulstoic** [comment]
That's strange.  You shouldn't need to have Rails to have nodes / rels wrapped.  Are you requiring the `neo4j` gem?  That should be brought in on these three lines:

https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j.rb#L18

The code in in question that enables the wrapping is in these files:

https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/node_wrapper.rb
https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_rel/rel_wrapper.rb

(The `wrapper_callback` is the primary point of integration with the `neo4j-core` gem)

**Comment by Joshfindit** [comment]
Yes, I'm requiring these:

```
require 'neo4j'
require 'neo4j/core/cypher_session/adaptors/http'
require 'neo4j/core/cypher_session/adaptors/bolt'
```

But it's still not responding to `Artefact.first.artefacts`

**Comment by cheerfulstoic** [comment]
Another thing to mention is that the `railtie` adds the `wrap_level: :proc` option when creating the adaptor here:

https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/session_manager.rb#L14

You might need to replicate that

**Comment by Joshfindit** [comment]
Aha!
Used the code in https://github.com/neo4jrb/neo4j/issues/1344

changed `options = {}`, and initial tests are promising. `Object.first.relatedobjects` returns `AssociationProxy` filled with the connected nodes.

No time to properly test, but looking forward to confirming later!

**Comment by cheerfulstoic** [comment]
Great!
