### ISSUE TITLE
rake neo4j:migrate fails in non Rails project (uninitialized constant Neo4j::Railtie)

### ISSUE THREAD

**Issue by phreakocious** [neo4jrb/neo4j#1353]
x$ rake neo4j:migrate --trace
** Invoke neo4j:migrate (first_time)
** Execute neo4j:migrate
** Invoke neo4j:migrate:all (first_time)
** Invoke neo4j:allow_migrations (first_time)
** Execute neo4j:allow_migrations
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant Neo4j::Railtie
/Users/x/.rvm/gems/ruby-2.3.3/gems/neo4j-8.0.5/lib/neo4j/tasks/migration.rake:9:in `block in <top (required)>'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/Users/x/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/Users/x/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/Users/x/.rvm/gems/ruby-2.3.3/gems/neo4j-8.0.5/lib/neo4j/tasks/migration.rake:41:in `block (2 levels) in <top (required)>'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/Users/x/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/Users/x/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/x/.rvm/gems/ruby-2.3.3/bin/rake:22:in `load'
/Users/x/.rvm/gems/ruby-2.3.3/bin/rake:22:in `<main>'
/Users/x/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/x/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => neo4j:migrate:all => environment

Neo4j database version:
`neo4j` gem version: 8.0.5
`neo4j-core` gem version: 7.0.3

**Comment by Joshfindit** [comment]
Related to https://github.com/neo4jrb/neo4j/issues/1330 ?

**Comment by phreakocious** [comment]
@Joshfindit - nailed it.  Only a minor issue with that PR, which I commented on there.

**Comment by cheerfulstoic** [comment]
Just released 8.0.6.  Give it a try!

**Comment by phreakocious** [comment]
LGTM.  Thanks!
