### ISSUE TITLE
console create error

### ISSUE THREAD

**Issue by tothestar** [neo4jrb/neo4j#1361]
when i run the code in console.
i got this error.. and what's the stable version? 

Additional information which could be helpful if relevant to your issue:

### Code example (inline, gist, or repo)
User.create(:name=>"test")
### Runtime information:
 HTTP REQUEST: 7ms GET http://localhost:7474/db/data/schema/constraint (0 bytes)
NoMethodError: undefined method `map' for "":String
Did you mean?  tap
	from /Users/super/.rvm/gems/ruby-2.3.0/gems/neo4j-core-7.0.5/lib/neo4j/core/cypher_session/adaptors/http.rb:62:in `constraints'
	from /Users/super/.rvm/gems/ruby-2.3.0/gems/neo4j-core-7.0.5/lib/neo4j/core/cypher_session.rb:36:in `block (2 levels) in <class:CypherSession>'

Neo4j database version:
`neo4j` gem version:  8.0.8
`neo4j-core` gem version: 7.0.5

**Comment by subvertallchris** [comment]
Can you share your User model?

**Comment by tothestar** [comment]
class User 
  include Neo4j::ActiveNode
  property :nickname, type: String
  property :user_id, type: Integer
  property :name, type: String
  property :position, type: String
  property :organization, type: String
  property :department, type: String
  property :tags, type: String
  property :email, type: String
  property :tel, type: String
  property :open_id, type: String
  property :sex, type: Integer
  property :city, type: String
  property :province, type: String
  property :country, type: String
  property :language, type: String
  property :avata_url, type: String
  property :enrolled_at, type: Integer
  property :union_id, type: String
  property :note, type: String
end

thanks!

**Comment by cheerfulstoic** [comment]
Have you logged into Neo4j and set the password (or if you setup Neo4j with the rake tasks it will, by default, have no password).  If you didn't set a password Neo4j doesn't allow requests via the HTTP endpoints (like from the gem) until you do.

The problem that you're having is that when the gem is trying to get the constraints from the database's schema, it's getting back an empty result.  That's on this line:

https://github.com/neo4jrb/neo4j-core/blob/master/lib/neo4j/core/cypher_session/adaptors/http.rb#L62

I would expect that if you aren't authorized.  It might be another problem too, but that's what I would try.

Also, if that's not the problem, you might try just starting with the model having the `name` property and see if it works to try to narrow things down

**Comment by tothestar** [comment]
I am not sure. i repeated again.
i set up the project with the instruction http://neo4jrb.readthedocs.io/en/stable/Setup.html
when i run User.create! in the rails console.
i got the info to run
rake neo4j:generate_schema_migration[constraint,User,uuid]
rake neo4j:migrate

then everything goes well. i'm sure i did this several days ago and got the error i posted before (except the first time i run it.).

I will keep my eyes on it. and i will inform u if i get any error again.
so odd...
anyway, thanks very much!   @cheerfulstoic

**Comment by cheerfulstoic** [comment]
Glad it's working now!
