### ISSUE TITLE
PendingMigrationError in test environment

### ISSUE THREAD

**Issue by wjdhamilton** [neo4jrb/neo4j#1366]
My app has three migrations, with the following versions:

20170317113511
20170317115110
20170317123256

Calling FactoryGirl.create_list in one of the specs causes a PendingMigrationsError to be called for the specs it is related to (it is the only place it is called). But this does not happen if I just call `FactoryGirl.create`. 

The migrations have definitely been run using `rake neo4j:migrate RAILS_ENV=test`. Immediately after this command completed, I ran rspec and everything behaved normally. However, further runs of rspec produce the following error:

```
Neo4j::PendingMigrationError:
       Migrations are pending:
       20170317113511
       20170317115110
       20170317123256
        To resolve this issue, run:

               bin/rails neo4j:migrate RAILS_ENV=test
```

Attempting to run `bin/rails neo4j:migrate RAILS_ENV=test` again produces the following error, which indicates that the migration has already taken effect:

`Neo4j::MigrationError: Duplicate constraint for PlanSegment#uuid`

And indeed calling `rake neo4j:migrate:status RAILS_ENV=test` yields the following information:

```
Status     Migration ID         Migration Name
--------------------------------------------------
down       20170317113511       PlanSegment
down       20170317115110       Event
down       20170317123256       RemovePositionFromPlanSegment
```

However, going into Rails console for the test environment and running the following command:

``` ruby
r = Neo4j::Migrations::Runner.new      
r.instance_variable_get("@up_versions")
```

returns the following:

```
#<SortedSet: {"20170317113511", "20170317115110", "20170317123256"}>
```

Which as you can see indicates that all the "down" migrations are up. 

I have tried stopping and starting the server, and deleting the test database and starting again. Not sure what else to try.

### Runtime information:

Neo4j database version:
`neo4j` gem version: 8.0.10
`neo4j-core` gem version: 7.0.8

**Comment by cheerfulstoic** [comment]
That's definitely strange.  I wonder if you have your tests set up to delete the database.  I ran into a problem a while ago where my tests would delete the whole database, but that also means that it was deleting the `SchemaMigration` nodes in the DB which are used to keep track of which migrations have been run.  For the moment I do the following:

```ruby
Neo4j::ActiveBase.current_session.query('MATCH (n) WHERE NOT n:`Neo4j::Migrations::SchemaMigration` DETACH DELETE n')
```

I think the best solution, though, is to implement something like what Rails / ActiveRecord have in a `schema.rb` file where every time you run migrations, a "schema" file is created which stores the state of the database.  For Neo4j for tests if you are starting with no nodes this means you'd only need to create the indexes and constraints.  This also has the advantage that you don't need to keep running migrations to set up your test database, which only gets slower and slower as you get more migrations.

Having a schema configuration file for tests is probably my highest priority for the next thing to implement, though I've been quite busy lately.  I'm happy to talk about how that might work if you're interested

**Comment by wjdhamilton** [comment]
I am interested, but have only a cursory understanding of with how this side of Rails works - so you might spend a while explaining this to me!

Further investigation of the bug get curiouser and curiouser:

I am using the `database_cleaner` gem, which has neo4j support, and I replaced it with the following snippet from the docs:

```ruby
  config.around do |example|
    Neo4j::Transaction.run do |tx|
      example.run
      tx.mark_failed
    end
  end
```

I also tried your code snippet above, in the following code: 

```ruby
  config.after(:each) do
    Neo4j::ActiveBase.current_session.query('MATCH (n) WHERE NOT n:`Neo4j::Migrations::SchemaMigration` DETACH DELETE n')
  end
```
and I still have the same problem.

Furthermore the issue appears to arise when `get` method is called in a `request` spec,  after `factory_girl.create_list` has run. If I go into `byebug` and call the `FactoryGirl.create_list` and `get` methods manually then the former runs and the latter does not - the code does not even reach the controller. 

I stepped through the process as far as I could, and got to:

`.rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:38`

but I couldn't trace the problem any further. 

So I then placed a breakpoint at `Neo4j::Migrations::CheckPending#call` and stepped as far as `Migrations::Runner#initialize`. The results at this point might be interesting. The `@schema_migrations` variable equals `[]` after it has been initialised. Which struck me as odd since there are clearly several migrations. 

`check_for_pending_migrations!` fails at this point as expected, which is obviously where the exception is being thrown.

**Comment by cheerfulstoic** [comment]
So, there are a couple of things to clarify:

 * Unfortunately, while Neo4j supports transactions and it will even let you nest transactions, but if you do, getting a failure of the inner transaction rolls back the entire outer transaction.  So transactions are not, unfortunately, a good way to roll back the state of the database after each test because if your test gets an exception (even an expected one that is expected by your test), the entire transaction for the test setup will fail.  That is why I instead use that `DETACH DELETE` command (incidentally, I prefer putting it in my `before` instead of my `after` because I don't like the idea of depending on other tests cleaning up)
 * The other problem that you may be having (which is not unique to Neo4j) is that if your test is running inside a transaction and you're doing a `request` spec, the browser won't be able to see the objects that were created by the tests (because they were inside a transaction are are only visible to the test itself until it's committed).  Changing out to use `DETACH DELETE` instead of transactions should help with that too.

**Comment by wjdhamilton** [comment]
Ah, yes! I forgot all about the second issue. Don't use non-api Rails as much as I used to. OK, so I've moved the `DETACH` command into the before block and removed `DatabaseCleaner` entirely. Then I ran rspec again and it still failed, complaining about attributes being defined in the model. However, this was fixed simply by migrating the test environment. 

Thank you so much for your help. You really made an effort. 

Do you think it would be worth adjusting the "pending migrations" error message such that if the program is running in the test environment that it mentions your point about request specs?

**Comment by cheerfulstoic** [comment]
There are potentially two issues (I think).  First, people shouldn't be running their tests in transactions (transactions in the tests are fine, just not transactions around the tests).  I could clarify that in the docs.

But I think that the pending migrations is a separate issue.  I've actually introduced some changes in the branch for the upcoming `8.1.x` series which makes migrations not checking inside of tests.  See this comment on another issue:

https://github.com/neo4jrb/neo4j/issues/1368#issuecomment-289940339

Of course your database still needs to be in a good state, but you'll generally get other errors (like that an index or a constraint isn't there) and thus you'll need to setup the db (again, from the comment that would be with the `neo4j:schema:load` rake task, but it could also be via migrations)
