### ISSUE TITLE
Heroku deployment throws DeprecatedSchemaDefinitionError

### ISSUE THREAD

**Issue by wjdhamilton** [neo4jrb/neo4j#1370]
Although I can use neo4jrb relatively easily on my local machine, I am finding deployment to Heroku  more difficult. 

Whenever I try to deploy to the Heroku environment, the app throws the DeprecatedSchemaDefinitionError, even after emptying the database and running `rake neo4j:migrate`. 

If I take the app's advice and run the suggested commands on heroku followed by migrating the database then I still get the same error. 

The models were all created using a version of neo4j > 8.0, and a migration exists for each of them. 

### Runtime information:

Neo4j database version:
`neo4j` gem version: 8.0.11
`neo4j-core` gem version: 7.0.8
Neo4j version: community 3.0.8

**Comment by cheerfulstoic** [comment]
Probably you have, but you might need to restart the server.

Have you looked at the database to see if the indexes / constraints are there?

**Comment by wjdhamilton** [comment]
The solution to this was to generate the migrations locally and then push them to Heroku. Running the rake task on the Heroku server didn't work because it didn't save the migration files, so they couldn't be run. It was odd because they were unnecessary on the local machine, so it was unclear that they would be necessary in the production environment but adding them solved the problem without changing the behaviour of the app locally.

**Comment by cheerfulstoic** [comment]
Ah, yeah, migrations should definitely be checked into the project to be run on all environments.  Glad it's working now!
