### ISSUE TITLE
How do I validate undeclared properties?

### ISSUE THREAD

**Issue by sebastialonso** [neo4jrb/neo4j#1372]
Hi. I'm using undeclared properties in one of my models. I'm trying to run a custom validation when I'm updating one or several undeclared properties, but there seems to be an issue in the way Neo4jrb get undeclared properties.

Additional information which could be helpful if relevant to your issue:

Let me explain
~~~
nodes_controller.rb
# ...
@node.update_attributes node_params
# ....
~~~
Here `node_params` permits the `candles` key corresponding to the candle undeclared attribute.

The validation is 
~~~
class Node 
  include Neo4j::ActiveNode
  include Neo4j::UndeclaredProperties
  
  validate :updated_custom_attributes_must_be_valid, on: :update
 
  def updated_custom_attributes_must_be_valid  
  # No matter the way I tried, I always get the pre-update value and NEVER the new value
  pp self[:candles]
  # Validate field in some way
  end
~~~

To me that raises a question. In regular Rails, I was to compare pre-update value with incoming value just doing something like self.candles == candles. self.candles would hold the pre-update value, and value the incoming one. But the way Neo4jrb treats undeclared **forbids** me to do that.

I can do self[:candles] to access the value I want to update, but how do I access the new one? There also little no documentation about that. Just that the module implements ActiveModel validation, but not the part I need it seems.

Any insight whatsoever, will be greatly appreciated!

### Runtime information:

Neo4j database version: 3.1.0
`neo4j` gem version:  8.0.6
`neo4j-core` gem version: 7.0.3

**Comment by cheerfulstoic** [comment]
Undeclared properties aren't part of the `ActiveModel` attributes that we define, they're just there from the underlying node object that we got from the dB.  So I don't think they'll work correctly in the normal lifecycle hooks (though I've never used `UndeclaredProperties`, so I couldn't say for sure).

You might try dynamically calling the `property` class method on the model class or perhaps using a serialized property

**Comment by sebastialonso** [comment]
Thanks @cheerfulstoic. You're right, they don't work correctly in the normal lifecycle hooks.
For anyone from the future reading this, I solved it by doing validation logic in the controller.
