### ISSUE TITLE
trying to set up connection and get an 'uninitialized constant`

### ISSUE THREAD

**Issue by angelacode** [neo4jrb/neo4j#1374]
Based on the documentation here: http://neo4jrb.readthedocs.io/en/8.0.x/Setup.html#using-the-neo4j-gem-activenode-and-activerel-without-rails

`require 'neo4j'`
`neo4j_adaptor = Neo4j::Core::CypherSession::Adaptors::HTTP.new(GRAPHENEDB_URL)`
`NameError: uninitialized constant Neo4j::Core::CypherSession::Adaptors`

Additional information which could be helpful if relevant to your issue:

### Runtime information:

Neo4j database version:
`neo4j` gem version: 
`bundle show neo4j
/usr/local/rvm/gems/ruby-2.2.1/gems/neo4j-8.0.13`
`neo4j-core` gem version: 
```
bundle show neo4j-core
/usr/local/rvm/gems/ruby-2.2.1/gems/neo4j-core-7.0.8
```

**Comment by cheerfulstoic** [comment]
Answered on [SO](http://stackoverflow.com/questions/43535082/neo4j-runtimeerror-no-session-defined/43543442?noredirect=1#comment74141933_43543442) I believe
