### ISSUE TITLE
How do I get the current Neo4j session in a Rails app?

### ISSUE THREAD

**Issue by matjemeisje** [neo4jrb/neo4j#1375]
I have a rake task to import some data. I would like to run this in a transaction (Neo4j::Transaction.run) but it complains about not finding a session.

Neo4j::Session.current always returns nil.

Neo4j::Session.open(:server_db) gives a Faraday error: "missing dependency for Faraday::Adapter::NetHttpPersistent: cannot load such file -- net/http/persistent". Installing the mentioned gem does not solve the error.

Neo4j::Session.open(:http) gives this error: "Neo4j::Session::InitializationError: Can't connect to database 'http', available".

### Runtime information:

Neo4j database version:
`neo4j` gem version: 8.0.15
`neo4j-core` gem version: 7.1.0

**Comment by cheerfulstoic** [comment]
Hey @matjemeisje !

Could you give a backtrace for the error?  I recently switched the `neo4j-core` gem (which the `neo4j` gem depends on) to use the `typhoeus` gem instead of `net-http-persistent`, so it's possible there might still be references to it...

Also, make sure to check out the [setup docs](http://neo4jrb.readthedocs.io/en/8.0.x/Setup.html) if you haven't already

**Comment by matjemeisje** [comment]
Hi Brian,

Thanks for your response. I solved it by using Neo4j::ActiveBase.current_session to get the current session, then the error went away.
I found it in the upgrade guide of the neo4j.rb docs. The other pages still seem to mention Neo4j::Session.current here and there, which caused the confusion.

Thanks anyway!

**Comment by cheerfulstoic** [comment]
Thanks for the update!

I see `Neo4j::Session.current` [here](http://neo4jrb.readthedocs.io/en/8.0.x/QueryClauseMethods.html) and I'll fix that now.  If you see it anywhere else please let me know or click on the "Edit in GitHub" link at the top to make a PR

For a deeper explanation: The `neo4j-core` gem was updated to allow an adaptor interface to connect to Neo4j via HTTP, Bolt, or embedded modes (the old code was getting a bit crufty in this respect).  At the same time, the concept of a current session was removed from `neo4j-core`, instead requiring users of that gem to keep track of their own session.  The `neo4j` gem, as a user of the `neo4j-core` gem, however, gained the concept of a current session in `Neo4j::ActiveBase.current_session`.  You can read a bit more about the change in the [upgrade guide](http://neo4jrb.readthedocs.io/en/8.0.x/UpgradeGuide.html)

Thanks again!
