### ISSUE TITLE
How do you add a property?

### ISSUE THREAD

**Issue by wjdhamilton** [neo4jrb/neo4j#1378]
There's a migration method for removing a property - `#remove_property`, but there doesn't appear to be one for adding a property. 

Shouldn't there be one so that `remove_property` can be rolled back easily?

**Comment by cheerfulstoic** [comment]
In Neo4j, properties don't exist until you set a value on them.  Also in Neo4j setting a property to `NULL` or doing a `REMOVE` on it are the same thing.  So it might make sense to have a `#set_property` method, perhaps which simply sets the value on a property for a label to a static value.  Does that make sense?

**Comment by wjdhamilton** [comment]
Yes, thanks for your swift response as always!
