### ISSUE TITLE
Range queries seem to hang neo4j server

### ISSUE THREAD

**Issue by wjdhamilton** [neo4jrb/neo4j#1379]
I'm not sure if this is to do with the gem or with neo4j itself. If it's the latter please just let me know. 

I have repeatedly found that the server hangs if an `ActiveRecord` query involving a range is made. 

Take the following model as an example:

```ruby
class NewsItem
  property :title, type: String
  property :story, type: String
  property :posted_on, type: Integer
end
```

If I try and use the following code: 

```ruby
NewsItem.where(posted_on: date_range)

    
    def date_range
      lower = DateTime.new(2010,1,1).to_i
      upper = (DateTime.now + 1).to_i
      lower..upper
    end

```

The server hangs and cannot be contacted. Using `rake:neo4j:restart` returns the following:

```
`Unable to run: db/neo4j/development/bin/neo4j restart
/Users/jameshamilton/.rvm/gems/ruby-2.4.0/gems/neo4j-rake_tasks-0.7.12/lib/neo4j/rake_tasks/server_manager.rb:249:in `system_or_fail'
/Users/jameshamilton/.rvm/gems/ruby-2.4.0/gems/neo4j-rake_tasks-0.7.12/lib/neo4j/rake_tasks/server_manager.rb:71:in `restart'
/Users/jameshamilton/.rvm/gems/ruby-2.4.0/gems/neo4j-rake_tasks-0.7.12/lib/neo4j/rake_tasks/neo4j_server.rake:140:in `block (2 levels) in <top (required)>'
/Users/jameshamilton/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/jameshamilton/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/jameshamilton/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

Now, this is fundamentally a problem at the neo4j end. It shouldn't just hang like this. However, I might point to a possible problem at the ruby end too.

This is the cypher output as printed in the puma log:

```cypher
 CYPHER
  MATCH (result_newsitem:`NewsItem`)
  WHERE (result_newsitem.posted_on IN RANGE({result_newsitem_posted_on_range_min}, {result_newsitem_posted_on_range_max}))
  RETURN count(result_newsitem) AS result_newsitem | {:result_newsitem_posted_on_range_min=>1262304000, :result_newsitem_posted_on_range_max=>1493895053}
```

Note that the parameters appear to be simply the output of calling `to_s` on a hash. I'm no cypher expert, and I don't know if this is even the message that the server receives but it looks wrong. Also, should it return 'count'?

If I copy and paste this into the neo4j browser then it too sends a request that never returns, even if I change the hash mentioned in the previous paragraph to explicitly use parameters like so:

```cypher
 CYPHER
  MATCH (result_newsitem:`NewsItem`)
  WHERE (result_newsitem.posted_on IN RANGE(1262304000, 1493895053))
  RETURN count(result_newsitem)
```

Which leads me to conclude that this is a problem with neo4j itself. I've created a bug report over there too, but I thought it was worth posting the issue here so you guys are aware of it too. 

### Runtime information:

Neo4j database version: 3.1.1
`neo4j` gem version: 8.0.16
`neo4j-core` gem version: 7.1.0

**Comment by cheerfulstoic** [comment]
Yeah, I'm thinking it's Neo4j and maybe the `RANGE` method doesn't take advantage of the index (assuming you have an index on `:NewsItem(posted_on)`).

You can prefix the query with `PROFILE ` or you might try this in the console just to see if it does better:

```
  MATCH (result_newsitem:`NewsItem`)
  WHERE result_newsitem.posted_on >= {result_newsitem_posted_on_range_min})
 AND (result_newsitem.posted_on <= {result_newsitem_posted_on_range_max})
  RETURN count(result_newsitem) AS result_newsitem | {:result_newsitem_posted_on_range_min=>1262304000, :result_newsitem_posted_on_range_max=>1493895053}
```

**Comment by cheerfulstoic** [comment]
Closing because I'm pretty sure this is a Neo4j thing (either something that they need to fix or maybe something that needs configured about Neo4j)

You might also check out the public Slack group for Neo4j to ask questions of Neo4j folks:

https://neo4j.com/blog/public-neo4j-users-slack-group/
