### ISSUE TITLE
Neo4j::Core::CypherSession::ConnectionFailedError (Connection failure:      Neo.ClientError.Security.Unauthorized: No authentication header supplied.)

### ISSUE THREAD

**Issue by azeemh** [neo4jrb/neo4j#1382]
using ruby 2.4 rails 5.1 -- following the new app tutorial, generating an app with the following commands works on my ubuntu 16.04 vm with all the latest patches/updates, however IT DOESN'T WORK ON macOS Sierra 10.12.4 which has the same version of ruby and rails.

```
rails new appname -m http://neo4jrb.io/neo4j/neo4j.rb -O
cd appname
rake neo4j:install[community-latest]
rake neo4j:start
rails g scaffold (insert any model scaffold here)
rails neo4j:migrate RAILS_ENV=development
```

any attempt by rails to connect gets the following:
Neo4j::Core::CypherSession::ConnectionFailedError (Connection failure: 
    Neo.ClientError.Security.Unauthorized: No authentication header supplied.).

I've tried every permutation -- my current FAILING application.rb on macOS looks like the following: 

```

require_relative 'boot'
require "rails"
require "active_model/railtie"
require "active_job/railtie"
require 'neo4j/railtie'
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
require "rails/test_unit/railtie"

Bundler.require(*Rails.groups)

module appname
  class Application < Rails::Application
    config.generators do |g|
      g.orm             :neo4j
    end

    config.neo4j.session.type = :http
    config.neo4j.session.url = 'http://localhost:7474'
    config.neo4j.session.options = {faraday_options: { ssl: { verify: true }}}
    
    Neo4j::ActiveBase.on_establish_session do
      adaptor = Neo4j::Core::CypherSession::Adaptors::HTTP.new('http://username_redacted:password_redacted@localhost:7474', wrap_level: :proc)
      
      Neo4j::Core::CypherSession.new(adaptor)
    end
    config.load_defaults 5.1
  end

```

and I can confirm that the (generic) code on ubuntu that works is as follows:

```
require_relative 'boot'
require "rails"
require "active_model/railtie"
require "active_job/railtie"
require 'neo4j/railtie'
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
require "rails/test_unit/railtie"

Bundler.require(*Rails.groups)

module appname
  class Application < Rails::Application
    
    config.generators do |g|
      g.orm             :neo4j
    end
    config.load_defaults 5.1
  end
end
```

this leads me to believe that neo4j security works by default for ubuntu however even when i clone the project to macOS it does not seem to work right.

### Runtime information:

Neo4j database version: 3.1.3
`neo4j` gem version: 8.0.17
`neo4j-core` gem version: 7.1.1

Ruby 2.4.0p0
Rails 5.1.0
macOS Sierra 10.2.4 = fail YET ubuntu 16.04 = run.

UPDATE:

after generating the app and rebooting my vm, it now also returns an authentication error -- most likely because the default neo4j user and pw have to be reset.

is there any clear way to configure a rails 5.1 app to interface with neo4j using authentication that actually works? none of the documentation explains this clearly and its disheartening to not be able to use the application that was just generated and working.

**Comment by cheerfulstoic** [comment]
If you used the `rake` tasks to set up the DB, it should disable authentication.  Otherwise you need to go to the Neo4j UI to set your username / password (Neo4j doesn't allow authentication via HTTP / Bolt until you've done this).  The docs could definitely be more clear here (documentation PRs always welcome!)

Also if you're using Rails you shouldn't need to do `Neo4j::ActiveBase.on_establish_session`.  I generally recommend just setting the `NEO4J_URL` environment variable in the format of `http://user:pass@host:port`, but you can also do:

```ruby
config.neo4j.session.type = :http
config.neo4j.session.url = 'http://user:pass@host:port'
```

If you're using Rails it should do the `on_establish_session` for you in the background.  Again, the docs could always be better ;)

Does that help?

**Comment by azeemh** [comment]
@cheerfulstoic THANK YOU!!!

I wouldn't mind helping with the docs either, the new updates made the whole upgrade a bit confusing plus there were very few up-to-date resources. For anyone else who was running into this issue, this application.rb configuration works on macOS Sierra and should work on Ubuntu etc. with ruby 2.4 and rails 5.1.0 (i'll test on my vm later)

it's best to install neo4j, create a new user for your application, and then run migrations after setting up your application.rb like so:

```
require_relative 'boot'

require "rails"
require "active_model/railtie"
require "active_job/railtie"
require 'neo4j/railtie'
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
require "rails/test_unit/railtie"

Bundler.require(*Rails.groups)

module YOUR_APPNAME
  class Application < Rails::Application
    
    config.generators do |g|
      g.orm             :neo4j
    end

    config.neo4j.session.type = :http
    config.neo4j.session.url = 'http://NEO4jUSERNAME:PASSWORD@127.0.0.1:7474'
    config.neo4j.session.options = {faraday_options: { ssl: { verify: true }}}
    
    config.load_defaults 5.1
  end
end
```

**Comment by shushugah** [comment]
I am having same issue. Should I be running something like `NEO4J_UR=http://neo4j:neo4j@host:port rails s` or `NEO4J_UR=http://user:pass@host:port rails s` ?

**Comment by cheerfulstoic** [comment]
Yeah, the environment variable is a good way to set the connection, though it's `NEO4J_URL` (in case that wasn't just a copy/paste error into this issue).
