### ISSUE TITLE
Superclass mismatch when Neo4jrb generates model migration w/ trailblazer-rails gem

### ISSUE THREAD

**Issue by thefliik** [neo4jrb/neo4j#1387]
On a new install of Rails 5.1.1 with Neo4jrb (installed using the `rails new myapp -m http://neo4jrb.io/neo4j/neo4j.rb -O` option described in the setup docs), running `rails g model User` creates a `user.rb` file in the `models` folder containing

    class User
      include Neo4j::ActiveNode
    end

and a migration file containing `class User < Neo4j::Migrations::Base` and results in a `superclass mismatch error` when I try and run `rake neo4j:migrate`.

If I edit the migration file to update its class name to `CreateUser`, the `superclass mismatch error` is eliminated but I get a new `ArgumentError: wrong number of arguments (given 2, expected 0..1)`.

I can't seem to find much information on migration files in the docs, so I'm not sure what the argument error is referring to.

### Runtime information:

Neo4j database version: 3.1.4
`neo4j` gem version: 8.0.17
`neo4j-core` gem version: 7.1.2
`neo4j-rake_tasks` gem version: 0.7.12

**Comment by cheerfulstoic** [comment]
If you change the class to `CreateUser` in the migration you may need to change the filename to match.  though I don't *think* that would be the error.  It would also be useful to have that error's backtrace if you're still having the issue.

Also, if you're still having the issue could you try Rails 5.0 or even 4.2 just in case?  I don't think that the 5.1 updates would have broken this, but this hasn't been an issue before, so you never know

Thanks

**Comment by thefliik** [comment]
I'll try to post some results from rails 5.0. In Rails 5.1.1, having run `rails g model Person`, running `rake neo4j:migrate` produces this backtrace:

```
** Invoke neo4j:migrate (first_time)
** Execute neo4j:migrate
** Invoke neo4j:migrate:all (first_time)
** Invoke neo4j:allow_migrations (first_time)
** Execute neo4j:allow_migrations
** Invoke environment (first_time)
** Execute environment
** Execute neo4j:migrate:all
== 20170526010213 Person: running... ===========================================
rake aborted!
TypeError: superclass mismatch for class Person
/home/ubuntu/volunteer-center-server/db/neo4j/migrate/20170526010213_person.rb:1:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/migration_file.rb:12:in `create'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:114:in `block in migrate'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:121:in `migration_message'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:113:in `migrate'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:26:in `block in all'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:24:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:24:in `all'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/tasks/migration.rake:53:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/tasks/migration.rake:46:in `block (2 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/bin/rake:22:in `load'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/bin/rake:22:in `<main>'
Tasks: TOP => neo4j:migrate:all
```

If I change `class Person < Neo4j::Migrations::Base` in `db/neo4j/development/migrate/xxxx_person.rb` to `class CreatePerson < Neo4j::Migrations::Base` then running `rake neo4j:migrate` produces this backtrace

```
** Invoke neo4j:migrate (first_time)
** Execute neo4j:migrate
** Invoke neo4j:migrate:all (first_time)
** Invoke neo4j:allow_migrations (first_time)
** Execute neo4j:allow_migrations
** Invoke environment (first_time)
** Execute environment
** Execute neo4j:migrate:all
== 20170526010213 Person: running... ===========================================
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 0..1)
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/active_node.rb:49:in `initialize'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/migration_file.rb:13:in `new'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/migration_file.rb:13:in `create'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:114:in `block in migrate'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:121:in `migration_message'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:113:in `migrate'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:26:in `block in all'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:24:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:24:in `all'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/tasks/migration.rake:53:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/tasks/migration.rake:46:in `block (2 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/bin/rake:22:in `load'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/bin/rake:22:in `<main>'
Tasks: TOP => neo4j:migrate:all
```

My `db/neo4j/development/migrate/xxxx_person.rb` file only contains the code automatically generated from `rails g model Person`. Specifically:

```
class Person < Neo4j::Migrations::Base
  def up
    add_constraint :Person, :uuid
  end

  def down
    drop_constraint :Person, :uuid
  end
end
```

For the first run and:

```
class CreatePerson < Neo4j::Migrations::Base
  def up
    add_constraint :Person, :uuid
  end

  def down
    drop_constraint :Person, :uuid
  end
end
```

For the second run.

**Comment by thefliik** [comment]
@cheerfulstoic testing in rails 5.0 worked, so I retried with a new rails 5.1.1 project and that worked. I thought I had originally tested with a clean install of 5.1.1 before creating this issue, but obviously I changed something as now everything seems to be working. I'm still not sure what caused the original issue.

Thanks for the quick response!

**Comment by thefliik** [comment]
@cheerfulstoic This issue popped up again and I was able to figure out what is causing it (kinda). If the `trailblazer-rails gem` is included in the gemfile (along with `neo4j`), running `rake neo4j:migrate` raises a `superclase missmatch error`. Commenting out the `trailblazer-rails gem` makes the migration work normally again. I've gone through my app and commented out all uses of `trailblazer` and the error is still raised, so I *think* merely including the gem raises the error.

When originally posting this issue, I had immediately added `trailblazer` to my new project (including `trailblazer-rails`), encountered the error, and then forgot I had added the `trailblazer-rails gem` (note, the `trailblazer gem` itself does not seem to cause any issues).

**Comment by thefliik** [comment]
@cheerfulstoic, you can see a discussion of this bug in an issue I made for `trailblazer-rails`. @apotonick, the creator of `trailblazer`, seems convinced the issue lies with the `neo4j` gem.

I must admit I don't totally follow his reasoning as I didn't think `include Neo4j::ActiveNode` counted as inheriting a superclass.

**Comment by apotonick** [comment]
That is not what I said, @thefliik. The problem is that neo4j defines `Product` twice, once in the migration as `class Product < Neo4j::Migrations::Base` and once as `class Product` with an include. These are two entirely different things and shouldn't have the same name.

It is probably not even the neo4j gem but your naming of the migration.

**Comment by thefliik** [comment]
@apotonick, I didn't mean to offend or misquote. As I mentioned, I'm not super experienced with ruby and a *greatly* appreciate your feedback thus far. I didn't realize that `class A < B` would conflict with `class A`. I thought it would only conflict with `class A < B` and `class A < C`.

`neo4j` automatically names the migration (I haven't modified any files except through standard rake tasks, here `rails g model Person`) and renaming the migration generates a different error (referenced in this issue above). It appears that `neo4j` expects the migration to have the same class name as the model being migrated, which seems to put these two gems at odds with one another.

As I mentioned over here, I can work around the issue by simply commenting out `trailblazer-rails` whenever I want to run a migration. A little annoying but not the end of the world.

**Comment by apotonick** [comment]
Haha, this mustn't be your workflow!!! :joy:  It's super inconvenient!

I am tending to make neo4j the villain here: The migration code should be designed to work in any environment, and not just when models are **not loaded**.

**Comment by thefliik** [comment]
Hmmm. I suppose I didn't think very far ahead. It'll be a larger problem during deployment...

**Comment by thefliik** [comment]
In case anyone else runs into this issue, I created a rake task to get around it by automatically commenting-out `gem "trailblazer-rails"`, running `rake neo4j:migrate`, and then un-commenting-out `gem "trailblazer-rails"`

```
desc "Migrate task to work around neo4j + trailblazer-rails bug"
task migrate: :environment do
    original = File.open('Gemfile', File::RDWR)
    original_copy = original.read
    # as file is read, ruby remembers its place in file so .read takes us to the end
    # need to move cursor back to beginning
    original.rewind
    modified = Tempfile.new('temp')
    # create modified file which is copy of original except gem "trailblazer-rails"
    # is commented out
    original.each do |line|
      if line =~ /gem \"trailblazer-rails\"/
        modified.write("##{line}")
      else
        modified.write(line)
      end
    end
    original.rewind
    modified.rewind
    # write over original file with modified temp file
    original.write(modified.read)
    modified.close
    original.close
    # Run migrations
    # Need to spawn new rake process so that environment is reloaded
    system("rake neo4j:migrate")
    # load original file
    File.open('Gemfile', 'w+').write(original_copy)
end
```

**Comment by apotonick** [comment]
This should absolutely **not** be considered as a solution! The real problem lies within neo4j's convention of requiring the migration class name to be *identical* to the actual model class. **THIS IS WRONG** and is supposed to break in any kind of environment, not just TRB.

Please find out how those two same-named classes could be avoided, instead. The temporary fix above is scary and doesn't help the two gems to work together correctly.

**Comment by apotonick** [comment]
For example, what if you'd namespace your migrations?

```ruby
module Migration
  class Person < ...
end
```

**Comment by thefliik** [comment]
So I've run into this bug again. This time with the `omniauth-identity` gem (which is the standard login/password strategy for the `omniauth` gem). If configuring `omniauth-identity` with a custom auth model, you must set up an initializer like so:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :identity, :fields => [:email], :model => MyCustomClass
end
```

WIth this initializer, running `rake neo4j:migrate` produces a `superclass mismatch error`. I assume because `OmniAuth` causes rails' models to load during initialization.

I'm a little surprised I've run into this issue twice in two days. Am I doing something wrong with neo4j migrations? Based on my own experience, I would think that this issue would be popping up with some regularity.

When I try to change the name of a migration, such as:

```
class CreatePerson < ...
```
or
```
module Migration
  class Person < ...
  end
end
```
I experience a `ArgumentError: wrong number of arguments (given 2, expected 0..1)`

I have an stripped down sample project documenting the problem which can be [viewed here](https://gitlab.com/john.carroll.p/issue-example-app). It's currently set up to demonstrate the issue with `omniauth-identity`, with the `trailblazer` gems being commented out.

**Comment by thefliik** [comment]
AH HA!!! It looks like I *was* doing something wrong. Adding `force: true` to a migration seems to fix the `ArgumentError: wrong number of arguments (given 2, expected 0..1)` and allow the migration to have a different name then the model. So the solution is to change this (the automatically generated migration):

```
class Person < Neo4j::Migrations::Base
  def up
    add_constraint :Person, :uuid
  end

  def down
    drop_constraint :Person, :uuid
  end
end
```
to this:
```
class ConstrainPerson < Neo4j::Migrations::Base
  def up
    add_constraint :Person, :uuid, force: true
  end

  def down
    drop_constraint :Person, :uuid
  end
end
```
It appears that the file name also needs to be updated from `xxxxx_person.rb` to `xxxxxx_constrain_person.rb`. Note I'm note yet sure what `force: true` is actually doing, other than fixing my problems, and I'm not sure if it needs to be added to the `def down` method as well.

I'll leave the issue open for now in case a future release can change the format of the automatically generated migrations (a.k.a. the migration created when `rails g model Person` is run). But I think this solution solves all of my issues.

Finally, despite all of these issues, **thanks so much for all of the awesome work on this gem!!!!!!**

**Comment by cheerfulstoic** [comment]
Doesn't `ActiveRecord` require that the migration class name be the same as the migration file name?  We simply copied the behavior of the well-worn gem.  Generally this isn't a problem because migrations should be generated (I often skip using generators for lots of things, but I never do for migrations).  And you should definitely make the migration not be the same name as the model.  I always name my migrations something like "add_person" instead of just "person".

That said, I'm sure this might happen again to somebody else.  I'd want to know how `ActiveRecord` handles it first

**Comment by apotonick** [comment]
It's exactly as you say @cheerfulstoic - naming the migration `Person` wasn't a good choice and renaming it "surprisingly" fixed it.

**Comment by thefliik** [comment]
@cheerfulstoic, the problem is that the *migration class name* is the same as the *model class name*. `active record` does not do this. When you generate a model in `active record`, the migration created to accompany the model is prefixed with `create`, and the migration is made plural.

As an example, in `active record ` running `rails g model Person` creates
```
app/models/person.rb
db/migrate/xxxxx_create_people.rb
```
`app/models/person.rb` contains
```
def Person < ActiveRecord::Base

end
```
`db/migrate/xxxxx_create_people.rb` contains
```
def CreatePeople < ActiveRecord::Migration

end
```
In `neo4j` running `rails g model Person` creates
```
app/models/person.rb
db/migrate/xxxxx_person.rb
```
`app/models/person.rb` contains
```
def Person
  include Neo4j::ActiveNode

end
```
`db/migrate/xxxxx_person.rb` contains
```
def Person < Neo4j::Migrations::Base

end
```
Neo4j's template creates a `superclass mismatch error`. If I manually change the class name in the migration (such as to `def ConstrainPerson`), I need to add `force: true` as an argument to make it work.

A good solution in `neo4j` would look like this:
running `rails g model Person` creates
```
app/models/person.rb
db/migrate/xxxxx_constrain_person.rb
```
`app/models/person.rb` contains
```
def Person
  include Neo4j::ActiveNode

end
```
`db/migrate/xxxxx_constrain_person.rb` contains
```
def ConstrainPerson < Neo4j::Migrations::Base

end
```
without needing `force: true` to make it work.

**Comment by thefliik** [comment]
@cheerfulstoic, I'll also note:
Running neo4j's generator to create a constraint migration "manually" also makes use of `force: true` to make it work. i.e.

Running `rake neo4j:generate_schema_migration[constraint,ConstrainPerson,uuid]` creates `db/migrate/xxxxx_force_create_constrain_person_uuid_constraint.rb` containing
```
class ForceCreateConstrainPersonUuidConstraint < Neo4j::Migrations::Base
  def up
    add_constraint :ConstrainPerson, :uuid, force: true
  end

  def down
    drop_constraint :ConstrainPerson, :uuid
  end
end
```

**Comment by cheerfulstoic** [comment]
Oh, duh!  I missed that you were using the `model` generator.  Definitely that should be creating a different class name.  I think that would be easy, let me have a quick look.

The `force: true` is added when doing the `generate_schema_migration` because it's creating a special migration to create the `id_property`'s constraint and the important thing there is that that the constraint exists (even if it was already created).  This was partially because users had to migrate from a system in which constraints and indexes were created automatically by defining them on the models (which turned out to be difficult to support.  In the normal case if you're adding a constraint for any given field, it's useful to know if the constraint is already there (though the `force` option is still available to you)

**Comment by cheerfulstoic** [comment]
Just released version `8.0.18`.  Give it a try!

**Comment by thefliik** [comment]
@cheerfulstoic, ***WOW that was fast!!!*** You're awesome!! It's totally working!!!

This will definitely simplify my workflow. Thank you so much!!!!! And on a Sunday no less!!!

As more of an FYI (because it's such a small issue), while testing the patch I noticed that running `rails g model Person` does:
```
      invoke  neo4j
      create    app/models/person.rb
>      create    db/neo4j/migrate/20170605063357_create_person.rb
      invoke    test_unit
      create      test/models/person_test.rb
      create      test/fixtures/people.yml
```
Then running `rails destroy model Person` does:
```
      invoke  neo4j
      remove    app/models/person.rb
>      remove    db/neo4j/migrate/20170605063502_create_person.rb
      invoke    test_unit
      remove      test/models/person_test.rb
      remove      test/fixtures/people.yml
```
Notably, the version numbers of the migration files (a.k.a the timestamps) in the two scripts mismatch (while they should be the same). This results in the migration file not being removed by the script.

**Comment by thefliik** [comment]
I'm going to reiterate that this gem is awesome and I **SUPER APPRECIATE** all the volunteer work you've put into it!!!!!

**Comment by cheerfulstoic** [comment]
Oh, wow, I didn't even realize that there was a `rails destroy model`! ;)

I'll have a look in a bit at that, and glad that you're enjoying the gem! ;)

**Comment by thefliik** [comment]
This is primarily a note to myself for when I have time to fix the handling of `rails destroy model`: 

ActiveRecord's migration handling is defined in https://github.com/rails/rails/blob/master/railties/lib/rails/generators/migration.rb

Importantly, ActiveRecord finds an existing migration by ignoring the file's timestamp and just looking at the migration name `migration_lookup_at(dirname).grep(/\d+_#{file_name}.rb$/).first`
