### ISSUE TITLE
each_with_rel should populate the relationship with its nodes rather than neo_id

### ISSUE THREAD

**Issue by klobuczek** [neo4jrb/neo4j#1392]
currently the relationship part of the `each_with_rel` has `neo_id` set for its end nodes, while it would be better if they were populated with the already known node. 

Additional information which could be helpful if relevant to your issue:

### Code example (inline, gist, or repo)
Assuming comment is an OUTGOING relationship
```movie.actors.each_with_rel.map { |node, rel| rel.to_node.name }```
should not cause 1 + n queries.

It may seem unreasonable to use the node via the relationship when the node is readily available, but there are situations especially in generic code where it would be of advantage to have the consistency without causing additional queries. 

### Runtime information:

Neo4j database version:
`neo4j` gem version:  8.1
`neo4j-core` gem version:

**Comment by cheerfulstoic** [comment]
Released as 8.1.2
