### ISSUE TITLE
Represent a chained relation as an "AssociationProxy"

### ISSUE THREAD

**Issue by alepee** [neo4jrb/neo4j#1399]
I wonder what would the best way to represent a "`has_many`" relation with a chained relation as below. I did not find anything like this in neo4jrb doc.

```
MATCH (:Purple)-[:NEXT_STAGE*]-(n:Red)
RETURN n
```

`n` instantiate as an `AssociationProxy` ordered from first to last.

---
I currently use a `QueryProxy`, but it feels wrong

```
purple.query_as(:i)
    .match('(i)-[chained_node_rel:NEXT_STAGE*]->(n:Red)')
    .proxy_as(Red, :n)
    .order_by('length(chained_node_rel)')
```
```
#<QueryProxy  [#<Red ...>, …]>
```

![Neo4j chained nodes](http://get.antoine.io/0K261p2r362P/Image%202017-07-28%20at%205.57.57%20PM.png)

**Comment by cheerfulstoic** [comment]
There is a `rel_length` option for associations documented [here](http://neo4jrb.readthedocs.io/en/8.1.x/Querying.html#variable-length-relationships)

```ruby
purple.next_stage(:n, :chained_node_rel, rel_length: :any).order('length(chained_node_rel)')
```

I've long wanted to have the ability to eagerly loaded some chain / tree / whatever structure via relative length relationship matches with one query, but it hasn't become a thing yet.  Though #1398 might be a piece of the puzzle

**Comment by alepee** [comment]
Thanks a lot, I will take a look into that.
