### ISSUE TITLE
Access neo4j db path from within app when using config/neo4j.yml

### ISSUE THREAD

**Issue by RyanSnodgrass** [neo4jrb/neo4j#1400]
When defining the database configs in the config/environments/[environment].rb with
```ruby
# config/environments/development.rb
config.neo4j.session.type = :http
config.neo4j.session.path = 'http://localhost:7474'
```
you could get the neo4j db path with `Rails.application.config.neo4j.session.path` and return `=> "http://localhost:7474"`.

However, when switching the configs out to the neo4j.yml config file, this command returns nil.
```ruby
# config/neo4j.yml
development:
  type: http
  url: http://localhost:7474
```
`Rails.application.config.neo4j.session.path`returns `=> nil`.  If I go up the chain with `Rails.configuration.neo4j` I get ` => {:session=>{}}`

I like defining the configs in the neo4j.yml file, I feel it separates concerns nicely. How do I get the path of neo4j from within the application?

neo4jrb gem 8.0.18
rails 5.0.0

**Comment by RyanSnodgrass** [comment]
I think I just found it:

`Neo4j::ActiveBase.current_session.adaptor.url`

**Comment by cheerfulstoic** [comment]
Yep, that'll do it! ;)
