### ISSUE TITLE
Failed Upgrade neo4jdb

### ISSUE THREAD

**Issue by ferryphang** [neo4jrb/neo4j#1405]
i try to copy my production db to local development machine...
and when try to run rake neo4j:start and i have make sure that neo4j.conf
```
# Enable this to be able to upgrade a store from an older version.
dbms.allow_format_migration=true
```
But i got this error

![neo4j_log_ _hitcheed](https://user-images.githubusercontent.com/4382692/29747406-c2a00c3e-8b24-11e7-9016-236bfb4f1348.png)

Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory
Component 'org.neo4j.kernel.NeoStoreDataSource@379892ee' was successfully initialized, but failed to start
Not possible to upgrade a store with version '' to current store version `v0.A.7` (Neo4j 3.1.2).

**Comment by cheerfulstoic** [comment]
Did you shut down the database when you made a backup?  In the community edition, it's not possible to backup while the server is running.

It that's not the problem, I'd suggest that this isn't a problem with any of the Neo4j.rb gems but rather Neo4j itself.  I'd suggest asking a question on [StackOverflow](https://stackoverflow.com/questions/ask?tags=neo4j) or or the [public Slack group](https://neo4j.com/blog/public-neo4j-users-slack-group/)
