### ISSUE TITLE
bug: has_many() assoc breaks in Neo4j community-3.2.3

### ISSUE THREAD

**Issue by thefliik** [neo4jrb/neo4j#1417]
Confirmed issue with a new, clean project. Given the following models:
```
class Person 
  include Neo4j::ActiveNode

  class Superhero < Person
  end

  class Supervillian < Person
  end
end
```
and
```
class Account 
  include Neo4j::ActiveNode

  has_many :in, :owner, type: :ACCOUNT, model_class: ["Person::Superhero", "Person::Supervillian"]
end
```

# Expected Behavior

```
hero = Person::Superhero.create
#=> #<Person::Superhero uuid: "7f923cbb-1f94-444c-a5fa-6beaeb58e6c0">

account = Account.create
#=> #<Account uuid: "f6f58ce1-5bd6-424a-bf6f-b57b5ab4b699">

account.owner = hero
#=> #<Person::Superhero uuid: "7f923cbb-1f94-444c-a5fa-6beaeb58e6c0">
```

# Actual Behavior

```
hero = Person::Superhero.create
#=> #<Person::Superhero uuid: "7f923cbb-1f94-444c-a5fa-6beaeb58e6c0">

account = Account.create
#=> #<Account uuid: "f6f58ce1-5bd6-424a-bf6f-b57b5ab4b699">

account.owner = hero
#=> Neo4j::Core::CypherSession::CypherError:   Cypher error:

    Neo.DatabaseError.Statement.ExecutionFailed: Expected
    RegularPlannerQuery(QueryGraph(Set(PatternRelationship(IdName(rel1),(IdName(account4),IdName(result_owner)),INCOMING,List(RelTypeName(ACCOUNT)),SimplePatternLength)),Set(IdName(account4), IdName(result_owner)),Set(),Selections(Set(Predicate(Set(IdName(result_owner)),Ors(Set(HasLabels(Variable(result_owner),List(LabelName(Person::Superhero), LabelName(Person))), HasLabels(Variable(result_owner),List(LabelName(Person::Supervillian), LabelName(Person)))))), Predicate(Set(IdName(account4)),In(FunctionInvocation(Namespace(List()),FunctionName(ID),false,Vector(Variable(account4))),ListLiteral(List(Parameter(ID_account4,Any))))))),Vector(),Set(),Set(),List(DeleteExpression(Variable(rel1),false))),RegularQueryProjection(Map(),QueryShuffle(List(),None,None)),None)


    Instead, got:
    RegularPlannerQuery(QueryGraph(Set(PatternRelationship(IdName(rel1),(IdName(account4),IdName(result_owner)),INCOMING,List(RelTypeName(ACCOUNT)),SimplePatternLength)),Set(IdName(result_owner), IdName(account4)),Set(),Selections(Set(Predicate(Set(IdName(result_owner)),Ors(Set(HasLabels(Variable(result_owner),List(LabelName(Person::Superhero), LabelName(Person))), HasLabels(Variable(result_owner),List(LabelName(Person::Supervillian), LabelName(Person)))))), Predicate(Set(IdName(result_owner)),HasLabels(Variable(result_owner),List(LabelName(Person::Superhero)))), Predicate(Set(IdName(account4)),In(FunctionInvocation(Namespace(List()),FunctionName(ID),false,Vector(Variable(account4))),ListLiteral(List(Parameter(ID_account4,Any))))), Predicate(Set(IdName(result_owner)),HasLabels(Variable(result_owner),List(LabelName(Person)))), Predicate(Set(IdName(result_owner)),HasLabels(Variable(result_owner),List(LabelName(Person::Supervillian)))))),Vector(),Set(),Set(),List(DeleteExpression(Variable(rel1),false))),RegularQueryProjection(Map(),QueryShuffle(List(),None,None)),None)
```

# Additional Info

If the `Account` model is changed to either of the following (same `Person` model):

```
class Account 
  include Neo4j::ActiveNode

  has_many :in, :owner, type: :ACCOUNT, model_class: "Person::Superhero"
end
```
or
```
class Account 
  include Neo4j::ActiveNode

  has_many :in, :owner, type: :ACCOUNT, model_class: false
end
```

Then `account.owner = hero` works normally.

### Runtime information:

Neo4j database version: 3.2.3
`neo4j` gem version: 8.2.2 & 8.1.0
`neo4j-core` gem version: 7.2.3

**Comment by cheerfulstoic** [comment]
I definitely want it to support 3.2.  I think the only reason why 3.2 isn't listed in the `README` is because I haven't gotten around to adding it.  There really should just be a line that says ">= 3.0.0".  I'll change that now

**Comment by cheerfulstoic** [comment]
I had a bit of time to look into this and it seems to have something to do with the multiple labels in the `model_class`.  It also doesn't seem to have anything to do with assignment.  If I do `account.owner` it also fails.

Though I should also point out that the association is a `has_many`.  You shouldn't use `=` for `has_many` associations with just one object.  Probably the association should be `owners` and you should do `owners = [hero]` or `owner << hero`

**Comment by cheerfulstoic** [comment]
When I call `to_cypher` I get the following:

```cypher
MATCH (account23907) WHERE (ID(account23907) = {ID_account23907}) MATCH (account23907)<-[rel1:`ACCOUNT`]-(result_owners) WHERE (`result_owners`:`Persona::Superhero`:`Persona` OR `result_owners`:`Persona::Supervillian`:`Persona`)
```

I think that this is a problem which is a combination of using an `Array` for `model_class` along with having models which are inherited because I don't know if this is valid syntax:

```cypher
`result_owners`:`Persona::Superhero`:`Persona`
```

But maybe that changed.  Looking deeper...

**Comment by cheerfulstoic** [comment]
Looks like this was a reversion of functionality in 3.2.5.  Reported issue https://github.com/neo4j/neo4j/issues/10100

Thanks for catching this!

**Comment by cheerfulstoic** [comment]
I just noticed that you said you were using 3.2.3, but I'm not getting this on 3.2.3 (only on 3.2.5).  Is that a typo or is something strange going on?

**Comment by thefliik** [comment]
That's probably a typo. I'll confirm later tonight, but I was under the (incorrect) impression that 3.2.3 was `community-latest`, and I _probably_ installed Neo4j using `community-latest`. It's convinient that you misread my mistake as the, apparenty, only value that could confirm this bug :rofl:

**Comment by cheerfulstoic** [comment]
Hrmm, if you were using `rake neo4j:install` then it was probably 3.2.3 because I updated the file which contains the versions a couple of hours after you submitted the issue.  I guess we'll see what you find and see what the Neo4j team says ;)

**Comment by thefliik** [comment]
I can confirm that I'm experiencing the problem specifically in 3.2.3 as well as in 3.2.0 (`account.owner = Person::Superhero.create` fails with an exception). I haven't tested other versions of 3.2.x, but I'm definitely not experiencing this issue in 3.1.5.

I notice that with the same `Person` class as above, and a default `Job` class, the following Account doesn't experience errors when `account.owners = Person::Superhero.create`

```
class Account 
  include Neo4j::ActiveNode

  has_many :in, :owner, type: :ACCOUNT, model_class: ["Person", "Job"]
end
```

**Comment by thefliik** [comment]
> Though I should also point out that the association is a has_many. You shouldn't use = for has_many associations with just one object. Probably the association should be owners and you should do owners = [hero] or owner << hero

You're right. I didn't put much thought into the association. Though I would expect `account.owners = hero` to either succeed or raise and exception if it needed to be wrapped `[hero]`

**Comment by thefliik** [comment]
In Neo4j `community-3.3.1`, this issue has been fixed. I'm not sure when the fix was first implemented.
