### ISSUE TITLE
YAML.safe_load in schema:load fails for Symbol keys

### ISSUE THREAD

**Issue by evanob** [neo4jrb/neo4j#1439]
Since switching from `YAML.load` to `YAML.safe_load` [here](https://github.com/neo4jrb/neo4j/commit/67583627fa1816647112907d599b0b9c675fac7d#diff-1a0805fbd5a411fb793783fc195ea4f6R98), it is not possible to run `schema:load`.

That's because the **schema.yml** file generated by by `schema:dump` uses symbol keys, which are forbidden by `safe_load` (see [YAML docs](http://ruby-doc.org/stdlib-2.1.0/libdoc/psych/rdoc/Psych.html#method-c-safe_load)).

This can be easily remedied adding `Symbol` to the whitelisted classes, like so:
```ruby
schema_data = YAML.safe_load(File.read(SCHEMA_YAML_PATH), [Symbol])
```

**Comment by cheerfulstoic** [comment]
Thanks!  Fixed and released as 8.3.3 and 9.0.4
