### ISSUE TITLE
Bump Neo4j gem version number in docs

### ISSUE THREAD

**Issue by simpsonjulian** [neo4jrb/neo4j#1443]
The docs (at http://neo4jrb.readthedocs.io/en/9.0.x/Setup.html) tell the first time user to use the 7.0.x version of neo4j:

```
# for rubygems
gem 'neo4j', '~> 7.0.0'
```

I got very confused until I changed the Gemfile in my project to read: `gem 'neo4j', '~> 9.0.0'`.

**Comment by cheerfulstoic** [comment]
Fixed, thanks Julian!
