### ISSUE TITLE
[DOCS] Duplicate/conflicting docs for cleaning test database

### ISSUE THREAD

**Issue by JustinAiken** [neo4jrb/neo4j#1447]
In the 8.x through 9.x docs (including latest), there's duplication between these two sections:
- [Miscellany -> Cleaning Your Database for Testing](http://neo4jrb.readthedocs.io/en/9.0.x/Miscellany.html#cleaning-your-database-for-testing)
- [Testing -> How to clear the database](http://neo4jrb.readthedocs.io/en/9.0.x/Testing.html#how-to-clear-the-database)

- Both have the cypher approach:
    ```ruby
    Neo4j::ActiveBase.current_session.query('MATCH (n) DETACH DELETE n')
    
    # For Neo4j < 2.3
    Neo4j::ActiveBase.current_session.query('MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n,r')
    ```
- Only the "testing" section has the "Delete data files" approach
- Only the "testing" section has the "RSpec Transaction Rollback" approach
- Only the "testing" section has the "Using Rack::Test" notes
- Only the "Miscellany" section has the "WHERE NOT n:`Neo4j::Migrations::SchemaMigration" clarification
- Only the "Miscellany" section has notes about database cleaner

It would probably make more sense to consolidate into a single **Testing -> How to clear the database** section, with all sections moved there:
- Cypher 
  - Using Ruby
   - If using `ActiveNode`/`ActiveRel`
    - Note about not clearing migrations
- Delete data files
- RSpec Transaction Rollback
- Using Rack::Test
- On using `database_cleaner`

Would submit a PR to do that myself, but don't have sphinx setup and running anymore for doc generation..

**Comment by cheerfulstoic** [comment]
Done!  Things are in a bit of a different order, but it should all be there.  Let me know if I missed anything!

Also FYI 9.1.0 is out now so I changed readthedocs to point to the `9.1.x` branch, so be aware when clicking your links above.

**Comment by JustinAiken** [comment]
Thanks! That reads more clear!
