### ISSUE TITLE
Warning: The Index Option is no longer supported (Defined on PROPERTY for MODEL)

### ISSUE THREAD

**Issue by ErikVanNorstrand** [neo4jrb/neo4j#1449]
I am getting the error: Warning: The Index Option is no longer supported (Defined on PROPERTY for MODEL)

When I try and save an object with an index on a given property.

Additional information which could be helpful if relevant to your issue:

### Code example (inline, gist, or repo)
test = Test.new
test.indexValue = "test"
test.save

Warning: The Index Option is no longer supported (Defined on indexValue for test)

### Runtime information:

Neo4j database version: 3.1.2
`neo4j` gem version: 9.0.7
`neo4j-core` gem version: 8.0.3

**Comment by thefliik** [comment]
Is the issue that you want the index option to be supported? If you're migrating from a previous version of the gem, you should check out the upgrade guide: http://neo4jrb.readthedocs.io/en/9.1.x/UpgradeGuide.html.

**Comment by ErikVanNorstrand** [comment]
I am on the 9.0.7 version of the gem, but I used the guide here: http://neo4jrb.readthedocs.io/en/9.1.x/Properties.html

which states

Node models have two more options:

index: :exact to declare an exact index in the database
constraint: :unique to declare a unique constraint

Is this no longer correct?

**Comment by thefliik** [comment]
Oh ya, that's pretty out of date and no longer correct. Skimming through the page, it looks like all of the information is correct except for the bit about the `index` and `constraint` options. Now both indexes and constraints are [made using migrations](http://neo4jrb.readthedocs.io/en/9.1.x/Migrations.html), much like in ActiveRecord.

**Comment by thefliik** [comment]
Hmm, it looks like the [ActiveNode section](http://neo4jrb.readthedocs.io/en/9.1.x/ActiveNode.html) of the docs also reference the `index` option in at least on example... but farther down the page it does specifically mention that [indexes and constraints should be made using migrations](http://neo4jrb.readthedocs.io/en/9.1.x/ActiveNode.html). Definitely confusing!

**Comment by ErikVanNorstrand** [comment]
So what is the proper solution for handling constraints?

**Comment by thefliik** [comment]
Now both [indexes and constraints are made using migrations](http://neo4jrb.readthedocs.io/en/9.1.x/Migrations.html).

Also, I submitted two PR's to fix the errors you found. If you run into anything else like that, I'm sure @cheerfulstoic would think it was awesome if you submitted a PR.

**Comment by thefliik** [comment]
If you're using rails, and you use a generator to create a model, a migration should also be created automatically for constraining the ID of the model to be unique.

**Comment by ErikVanNorstrand** [comment]
def up
  add_constraint :Test, :test_constraint, force: true
end

That is what I have, and I still get the error.

Is it because I have the constraint also in the Model?

property: test_constraint, type: String, index: :exact

**Comment by thefliik** [comment]
Probably

**Comment by ErikVanNorstrand** [comment]
Ok. I have to do some testing, I will update this ticket shortly!

**Comment by cheerfulstoic** [comment]
Yeah, you definitely need to remove the definitions from models, but also know you might need to restart your server

**Comment by cheerfulstoic** [comment]
@thefliik Just made a couple of changes to the docs which I've merged and are now updated on http://neo4jrb.readthedocs.io/

**Comment by ErikVanNorstrand** [comment]
Everything seems fixed! thank you

**Comment by cheerfulstoic** [comment]
🎉 Awesome!
