### ISSUE TITLE
Getting error Some schema elements were defined by the model (which is no longer supported), but they do not exist in the database. 

### ISSUE THREAD

**Issue by JakubA3informatics** [neo4jrb/neo4j#1452]
Hello,

I'm stuck with my application because of this error:

```
Some schema elements were defined by the model (which is no longer supported), but they do not exist in the database. Run the following to create them if you haven't already:

rake neo4j:generate_schema_migration[constraint,StudyVersion,uuid]


And then run rake neo4j:migrate
```

I tried to do so as asked in the terminal but after I have same error again and I cannot run the app.

Please provide me a solution for it.

Thank you

Additional information which could be helpful if relevant to your issue:

### Code example (inline, gist, or repo)
Repo where the problem occurs: https://gitlab.com/kubus41/AppDevDK.git 
Branch name: neo4j-dev 

### Runtime information:

Neo4j database version: 3.0.10
`neo4j` gem version: 9.0.5
`neo4j-core` gem version: 8.0.1

**Comment by cheerfulstoic** [comment]
Hey @JakubA3informatics !

Did you run `rake neo4j:migrate` and restart the server after running the migration?

I would also check the `:schema` command to make sure the constraint was created

I can't access the GitLab repo.  Here's my account if you want to give me access: https://gitlab.com/cheerfulstoic

**Comment by JakubA3informatics** [comment]
Hey Brian,

I did those as you suggested but still some issues.

I get you the access to the Repo so you can take a closer look.

Thank you ☺

**Comment by cheerfulstoic** [comment]
Hey @JakubA3informatics 

I set up the app against a Neo4j server and tried running `StudyVersion.first` in a rails console session.  That gave me the error:

```ruby
Neo4j::DeprecatedSchemaDefinitionError:           Some schema elements were defined by the model (which is no longer supported), but they do not exist in the database.  Run the following to create them if you haven't already:

rake neo4j:generate_schema_migration[constraint,StudyVersion,uuid]
rake neo4j:generate_schema_migration[index,StudyVersion,state]

And then run `rake neo4j:migrate`
```

I shut down my console, ran `rake neo4j:migrate`, and then when I run `StudyVersion.first` in the console it works fine (returning `nil` because I don't have anything in the DB).

Did you run `:schema` to see if the constraints were created in the DB?  Are you getting the error in the server or the console?  Did you restart the console as well?  I'm at a bit of a loss, unfortunately...

**Comment by JakubA3informatics** [comment]
Hey Brian,

I resolved my issue doing this steps:

rake neo4j:generate_schema_migration[constraint,Amendment,uuid]
then run
neo4j:migrate RAILS_ENV=test or for development

After this seems all working correctly and I restarted the console.

I also purged the Test DB with MATCH (n) DETACH DELETE to avoid issues.

Thank you for your help ☺

Jakub

**Comment by cheerfulstoic** [comment]
:tada: Thanks for the update!
