### ISSUE TITLE
Connection failure: Neo.ClientError.Security.Unauthorized: No authentication header supplied.

### ISSUE THREAD

**Issue by softwareeverything** [neo4jrb/neo4j#1470]
I use neo4j gem but I get an error when I try to access my page.

`Neo4j::Core::CypherSession::ConnectionFailedError`

`Connection failure: Neo.ClientError.Security.Unauthorized: No authentication header supplied.`

`fail CypherSession::ConnectionFailedError, "Connection failure: \n    #{message}"`

config/application.rb is;
```
require_relative 'boot'

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
# require "active_record/railtie"
require 'neo4j/railtie'
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Blog
  class Application < Rails::Application

    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.1

    config.generators do |g|
      g.orm             :neo4j
    end

    # Configure where to connect to the Neo4j DB
    # Note that embedded db is only available for JRuby
    config.neo4j.session.type = :http
    config.neo4j.session.url = 'http://neo4j:123@localhost:7474'
    #  or
    # config.neo4j.session.type = :bolt
    # config.neo4j.session.url = 'bolt://localhost:7687'
    #  or
    # config.neo4j.session.type = :embedded
    # config.neo4j.session.path = Rails.root.join('neo4j-db').to_s

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
  end
end
```

### Runtime information:

`Neo4j database` version: neo4j 3.3.1
`neo4j` gem version: 9.0.7
`neo4j-core` gem version: 8.1.0

**Comment by cheerfulstoic** [comment]
😦 I don't really see any problems with that configuration.  I can suggest some things to try/check, though:

There probably isn't, but your configuration could be overwritten in `config/environments/development.rb` or `config/environments/test.rb`

There is a `config/neo4j.yml` file which could affect things

You might try removing your configuration and simply setting a `NEO4J_URL` environment variable.

If all that fails, you should perhaps try creating a session as specified in the [`README` for the `neo4j-core` gem](https://github.com/neo4jrb/neo4j/issues/1470)

**Comment by softwareeverything** [comment]
Thanks @cheerfulstoic , I solved this problem. :)
For ubuntu: `pico /etc/neo4j/neo4j.conf`
After that do it: `dbms.security.auth_enabled=false`
It's all but In fact I'm searching more secure ways to do it.

**Comment by cheerfulstoic** [comment]
Interesting, that will certainly work to disable auth, though obviously I wouldn't do that in a production environment.

Also, one thing that I forgot about that might be relevant: When you first start up Neo4j (when auth is enabled) you need to reset the password through the UI before it will allow you to connect via the HTTP adapter.  The default username / password is `neo4j` / `neo4j` at the start.

Enjoy!
