### ISSUE TITLE
neo4j_config.session leading to stack too deep

### ISSUE THREAD

**Issue by RicardoTrindade** [neo4jrb/neo4j#1471]
Found this weird issue after upgrading to rails 5.1.
Whenever the `final_session_config ` method is called on `neo4j/railtie.rb` and it calls neo4j_config.session I get a stack level too deep error. The issue seems to be related with the ActiveSupport::OrderedOptions which allows to call `neo4j_config.session`.

I was able to get around it by changing the code to call `neo4j_config[:session]` instead.
 Would gladly submit a PR with the alteration if need be.

`neo4j` gem version: 8.3.4
`neo4j-core` gem version: 8.1.0

**Comment by thefliik** [comment]
Hmm. I'm using this gem with rails 5.1.4 and haven't run into this issue

**Comment by cheerfulstoic** [comment]
@mrstif May have had a similar issue to this that he reported on Gitter recently:

The conversation archives are on these two days:

https://gitter.im/neo4jrb/neo4j/archives/2018/01/09
https://gitter.im/neo4jrb/neo4j/archives/2018/01/10

Although looking at the backtrace from one of his errors, it looks like he's using 5.0

@RicardoTrindade Did you upgrade to 5.1 from 5.0, or from something before 5.0?

**Comment by RicardoTrindade** [comment]
@cheerfulstoic Upgraded from 5.0 to 5.1

**Comment by cheerfulstoic** [comment]
Hrmm, I guess that doesn't necessarily track then...

If `neo4j_config[:session]` works, I'd happily take a PR with the change.  I'd probably want to test it against an existing app I have to make sure everything still works.

As a larger concern, the gem's code that handles the configuration of Neo4j in Rails is a bit convoluted and has led to a few bugs, so it should probably be refactored.  You might also try just setting the `NEO4J_URL` environment variable.  That's worked pretty well for me (though, of course, that's just a workaround)

**Comment by cheerfulstoic** [comment]
Thanks, released as version 9.1.3!
