### ISSUE TITLE
Must require `forwardable`

### ISSUE THREAD

**Issue by smackesey** [neo4jrb/neo4j#1535]
If I open IRB and `require "neo4j"`, I get the following error:

    NameError (uninitialized constant Neo4j::Shared::Property::ClassMethods::Forwardable)

If I `require "forwardable"` (from the standard library) before requiring `neo4j`, this doesn't happen. Looks like the `neo4j` gem needs to require `forwardable`.

### Runtime information:

Neo4j database version: 3.5.2
`neo4j` gem version: 9.4.0
`neo4j-core` gem version: 9.0.0

**Comment by jschulenklopper** [comment]
Confirmed. I encountered the same problem.
