### ISSUE TITLE
Query with date conditions return nothing

### ISSUE THREAD

**Issue by asnad** [neo4jrb/neo4j#1542]
Date conditions are not working:

### Code example (inline, gist, or repo)
`Distance.all(:d).where("d.created_at <= {the_date}").params(the_date: DateTime.now)
`
it returns nothing while I have records for this condition.
### Runtime information:

Neo4j database version: 3.5.3
`neo4j` gem version:  9.4.0
`neo4j-core` gem version:  N/A

**Comment by opensourcechris** [comment]
You have to convert to timestamp: `DateTime.now.to_i`
