### ISSUE TITLE
Connect failure message

### ISSUE THREAD

**Issue by nomasprime** [neo4jrb/neo4j#1585]
Getting this error:

```
Neo4j::Core::CypherSession::ConnectionFailedError: Connection failure:
    status: 404
```

Connecting to what? Hard to debug without more info.

### Runtime information:

Neo4j database version: 3.5.14
`neo4j` gem version: 9.6.1
`neo4j-core` gem version: 9.0.0

**Comment by amitsuryavanshi** [comment]
Closing as the issue is resolved.
