### ISSUE TITLE
Support for active_model_serializers

### ISSUE THREAD

**Issue by jcf** [neo4jrb/neo4j#227]
Hi all,

I'm using Neo4j and need to serialise objects and associations for an HTTP API.

The way I do this with ActiveModel-compliant objects is to use active_model_serializers, which doesn't work out-of-the-box with Neo4j Rails.

To get the basic support I need I added the following to an initializer in my Rails app:

``` ruby
Neo4j::Rails::Model.send(:include, ActiveModel::SerializerSupport)
Neo4j::Rails::Relationships::NodesDSL.delegate(:active_model_serializer, to: :to_a)
```

This is something I'd normally add to the wiki of a project for others to find, but before doing so I wanted to get some feedback on where you think it would be appropriate, if at all.

**Comment by brancusi** [comment]
Hi,

I've tried to follow the steps listed but I think something has changed since this was outlined.

Is there a new solution for using the active_model_serializer gem?

Also, in general, is there a better approach to rendering json?

Thank you
