### ISSUE TITLE
Hot to setup and run an HA cluster with Rails

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#287]
Well, I followed the instruction and I'm now setting up a cluster with 3 machines:
- 1 rails server
- 2 neo4j-enterprise machines.

I'm running on a VMware VM, with 16GB RAM and 8core on a intel i7.

I star the Rail Server as a first machine in the cluster:

pdipietro@ubuntu:~$ cd myapp/
pdipietro@ubuntu:~/myapp$ rails s
Config HA cluster, ha.server_id: 1, db: /home/pdipietro/myapp/db/ha_neo_1
=> Booting WEBrick
=> Rails 3.2.15 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2013-11-22 11:38:49] INFO  WEBrick 1.3.1
[2013-11-22 11:38:49] INFO  ruby 1.9.3 (2013-10-22) [java]
[2013-11-22 11:38:49] INFO  WEBrick::HTTPServer#start: pid=2859 port=3000
starting Neo4j in HA mode, machine id: 1 at localhost:6003 db /home/pdipietro/myapp/db/ha_neo_1

Started GET "/assets/rails.png" for 127.0.0.1 at 2013-11-22 11:42:26 +0100
Served asset /rails.png - 200 OK (86ms)

CPU is 5%, the browser at port 3000 seems hunged, so I start the 2nd instance

pdipietro@ubuntu:~/neo4j-HA-02$ ./bin/neo4j start
WARNING: Max 1024 open files allowed, minimum of 40 000 recommended. See the Neo4j manual.
Using additional JVM arguments:  -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties -Djava.util.logging.config.file=conf/logging.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
Starting Neo4j Server...WARNING: not changing user
HA instance started in process [3559]. Will be operational once connected to peers. See /home/pdipietro/neo4j-HA-02/data/log/console.log for current status.
pdipietro@ubuntu:~/neo4j-HA-02$ 

-------------------------

Now, I retry on the port 3000 with localhost:3000/cats and then added a cat instance

On the rails s console I got:

Started POST "/cats" for 127.0.0.1 at 2013-11-22 11:47:18 +0100
Processing by CatsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"b7Z3URSA6290l/e/ZwbgDZWDMH3t+SDqFuaN8csoCOs=", "cat"=>{"name"=>"Susy"}, "commit"=>"Create Cat"}
Completed 500 Internal Server Error in 20015.0ms

NoMethodError (undefined method `finish' for nil:NilClass):
  app/controllers/cats_controller.rb:46:in `create'
  app/controllers/cats_controller.rb:45:in `create'

  Rendered /home/pdipietro/.rvm/gems/jruby-1.7.6/gems/actionpack-3.2.15/lib/action_dispatch/middleware/templates/rescues/_trace.erb (9.0ms)
  Rendered /home/pdipietro/.rvm/gems/jruby-1.7.6/gems/actionpack-3.2.15/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (7.0ms)
  Rendered /home/pdipietro/.rvm/gems/jruby-1.7.6/gems/actionpack-3.2.15/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (33.0ms)

Any idea about this error?

Paolo

**Comment by cheerfulstoic** [comment]
Just noticed this old old issue, what's the status here?

**Comment by pdipietro** [comment]
We can close it. I didn't remember about it.....
