### ISSUE TITLE
Support for linked lists: has_many

### ISSUE THREAD

**Issue by andreasronge** [neo4jrb/neo4j#416]
Example:

```ruby
class Post
   include Neo4j::ActiveNode
   property :name
   has_many :out, :comments, layout: :list # better name layout ?
end
```

Instead of just having one node with several relationship to comment nodes the comments are arranged in a linked list. This can be very useful, for example finding the first item in the list is very fast. One can also implement a sorted linked list. It is solution which make better use of the graph database and its relationships.

**Comment by subvertallchris** [comment]
I think we're putting this on hold indefinitely.
