### ISSUE TITLE
Option to use CREATE UNIQUE on relationships

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#473]
```
class Student
  has_many :out, :lessons, type: 'enrolled_in", unique: true
end
```
Should use CREATE UNIQUE when creating new relationships to ensure there exists only one rel of type `enrolled_in` between any given student and lesson.

**Comment by cheerfulstoic** [comment]
Had a desire for this in the wild: http://stackoverflow.com/questions/27816748/neo4j-rb-create-unique-relationship/27819046#27819046

**Comment by subvertallchris** [comment]
This should be really easy to do. I think I could probably throw it in sometime this week.

**Comment by cheerfulstoic** [comment]
Nice! ;)
