### ISSUE TITLE
Accessing several relationships in single trip

### ISSUE THREAD

**Issue by KieranLafferty** [neo4jrb/neo4j#477]
This is more of a generic neo4j question rather than one specific to this API

I am looking to save trips to the DB by accessing several nodes connected by rels in a single query. 

Example
(:User) -[:friend]-> (:User)
(:User) -[:photos]-> (:Photo)
(:User) -[:interest]-> (:Topic)

I want to be able grab all of my friends with their photos and list of their interests in a single cypher query. 

The ideal response would be an array of structs with the following format

[
 { user: USER_OBJECT,
   photos : [ PHOTO_1, PHOTO_2, ... , PHOTO_N],
   interests : [INT_1, INT_2, ... ,  INT_3]
},
...
]

I can easily get the list of User objects but getting the associated photos and interests requires additional calls for each property which means if I have N users I have to then do N calls for photos, and N calls for interests meaning I do 2N + 1 calls for every request which isnt ideal and takes a long time. 

Any suggestions?

Also, thanks again for all the help you have provided and for this amazing gem

**Comment by subvertallchris** [comment]
I think this is mostly implemented with eager loading. I'm going to close it since it's a constant goal and there's no real task to complete here.
