### ISSUE TITLE
LoadError: cannot load such file -- neo4j/tasks/neo4j_server

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#502]
If you started receiving this as of the recent update, go into `Rakefile` and remove the following line:

`require 'neo4j/tasks/neo4j_server'`

This file has been renamed and is automatically included by the `neo4j` gem, no need to do it manually. If you're not using Rails or need to include it manually for some reason, `load 'neo4j/tasks/neo4j_server.rake'` will do the trick.

**Comment by Redapted** [comment]
For people like myself who stumbled across this in the far-flung future, the name has changed again. Now you must:
```
load 'neo4j/rake_tasks/neo4j_server.rake'
```
> I am altering the deal. Pray I don't alter it any further.
> - "Darth Vader", Star Wars: Episode V - The Empire Strikes Back

**Comment by cheerfulstoic** [comment]
Sorry about that, but thanks for the update for future people (or for people a long time ago in a galaxy far far away).

FYI the reason for this was because we extracted the rake tasks into the `neo4j-rake_task` gem.  Also FYI, if you're using Rails it should automatically load this for you.

**Comment by isaacsanders** [comment]
The "Basic Setup" wiki page appears to be out of date after this change. I don't know how to correct, but I imagine one of you may, @cheerfulstoic.

Cheers,
Isaac

**Comment by cheerfulstoic** [comment]
Fixed, thanks for catching that!
