### ISSUE TITLE
Be able to create a node and association at the same time using a hash

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#510]
I remember starting to work on this, but I don't think it's finished.  Should be able to do something like:

`node.association.create_node(name: 'Foo')`

Right now `#create` on a QueryProxy has the method signature `(other_nodes, properties)`, which is probably good because doing a create on an association to me says you want to create a relationship.

**Comment by cheerfulstoic** [comment]
Proposal:

`QueryProxy.create` should be for creating nodes since QueryProxies represent a class-level view of a model.  It should take a first argument with attributes for the node, and a second, optional argument for attributes for the relationship.  If an Array is passed in, we give users the old behavior, but give a deprecation warning.

`QueryProxy.link` should replace the current `QueryProxy.create`

**Comment by subvertallchris** [comment]
Do you mean that `NodeClass.create` would go through QueryProxy?

**Comment by cheerfulstoic** [comment]
I don't know about the implementation, but that's an interesting thought.  We'd certainly want there to not be a second argument for relationship properties for `NodeClass.create`.  Maybe they'd share code in the background, but they would probably be different methods in the API

**Comment by subvertallchris** [comment]
Would you want to consider this done since we can do unpersisted nodes with associations? I also have that branch for ActiveRel that will do a rel and nodes in a single db query but haven't had time to finish it up.

**Comment by cheerfulstoic** [comment]
Yeah, I think so.  That would be something like `Person.create(films: film_list)`?

**Comment by subvertallchris** [comment]
Other way around, `person = Person.new; person.films << film_list; person.save`.

**Comment by subvertallchris** [comment]
Though it'd be interesting to see if that would work, too. I wouldn't be surprised, since it just does that behind the scenes.

**Comment by cheerfulstoic** [comment]
I think it would be much nicer if you could use the Hash syntax (maybe I'm just used to it from ActiveRecord).  Also it would be `=` or `+=` instead of `<<`, right?

**Comment by subvertallchris** [comment]
Hash syntax would work, it'd find the `films` association and send `film_list` to it, but I'm not sure if that uses `<<` or `=` under the hood. I think the unpersisted rules would take effect there but we should test to be sure.

**Comment by subvertallchris** [comment]
Both ActiveRel and plain ole' Associations can handle unpersisted nodes now, so I'm going to close this.
