### ISSUE TITLE
Finding a certain relationship between two nodes

### ISSUE THREAD

**Issue by arikan** [neo4jrb/neo4j#512]
In the wiki documentation https://github.com/neo4jrb/neo4j-core/wiki/Relationship finding a relationship between two nodes is exemplified like below. But this is for _any_ relationship, what about finding a certain relationship type between the nodes? 

``` rb
# outgoing between two nodes
n1.rels(dir: :outgoing, between: n2)
```

We keep an :id as relationship property, and when we want to find and delete a certain undeclared relationship between two nodes, this is what we do.

``` rb
node.rels(dir: :outgoing, type: props[:edge_name]).each do |rel|
   if rel[:id] == props[:id]
      rel.destroy
   end
end
```

There must be a better way no?

**Comment by shivamagg** [comment]
@subvertallchris 
`n1.association_name(:node, :rel).where(id: n2.id, rel: { id: props[:id] } ).pluck(:rel).first.destroy`

condition on rel does not seem to be working. this where query is converted to cypher as:

`WHERE (node.id = n2.id) AND (node.rel.id = props[:id] )`

can you suggest a workaround to send the query as 

`WHERE (node.id = n2.id) AND (rel.id = props[:id] )`

Thankyou.

**Comment by cheerfulstoic** [comment]
@shivamagg:

```ruby
n1.association_name(:node, :rel).where(id: n2.id).rel_where(id: props[:id]).pluck(:rel).first.destroy
```

I'm a bit worried, though, that the `where(id:` for the nodes isn't being turned into `uuid` (unless you defined an `id_property` to overwrite the default `uuid)
