### ISSUE TITLE
Neo4jrb Logging mechanism for Ruby

### ISSUE THREAD

**Issue by johnclegg** [neo4jrb/neo4j#525]
As a neo4jrb ruby user 
I would like to be able to see what REST API queries are being generated by neo4jrb
So that I can debug building of objects in the system

Can a native ruby logging mechanism be created for seeing the REST queries generated by neo4jrb.

I'm using Sinatra (Padrino) to build an API for my neo4j data model. I would like to see what REST queries are being generated by neo4jrb object queries.

I'm new to neo4jrb and I know the neo4j queries for the data. I'm trying to learn how to use the object function and it would be good to see the resulting queries to understand how to use the functionality to make the code more readable.

**Comment by subvertallchris** [comment]
Brian's recent work with logging should cover this.

**Comment by cheerfulstoic** [comment]
It's true!  For anybody reading you can set the `logger` configuration to define a custom logger (in Rails this gets set to `Rails.logger`).  You can also set `pretty_logged_cypher_queries = true` to have it output the cypher in a nice way (assuming it was generated by query/association chaining methods).  See the configuration documentation for more info on how to set configuration variables:

http://neo4jrb.readthedocs.org/en/5.2.x/Configuration.html

**Comment by cheerfulstoic** [comment]
Oh, and it sends logs at the `debug` level (which I think is what ActiveRecord does), so set log levels accordingly for your various environments
