### ISSUE TITLE
method to convert query result to graphjson

### ISSUE THREAD

**Issue by chrisgogreen** [neo4jrb/neo4j#534]
The result of:
n = Neo4j::Session.query("MATCH (n) WHERE ID(n) = {foobar} RETURN n", foobar: n.neo_id).to_graph_json would be a valid graphJSON object.

**Comment by subvertallchris** [comment]
Hey guys, can we close this or is there more to do?

**Comment by cheerfulstoic** [comment]
Closing.  I don't think that this is really the domain of either of the gems, but I'd welcome some standard solution out there
