### ISSUE TITLE
Unable to create relationship with non-persisted nodes

### ISSUE THREAD

**Issue by dpisarewski** [neo4jrb/neo4j#566]
I'm wondering why neo4j tries to persist a relationship when I just assign an another node.

```
[31] pry(main)> >> m = Memo.create
=> #<Memo client_uuid: nil, created_at: Mon, 10 Nov 2014 15:14:03 +0100, description_text: nil, id: "07cf3f15-56b9-4a5e-884c-352753b0fc9a", latitude: nil, longitude: nil, made_at: nil, title: nil, updated_at: Mon, 10 Nov 2014 15:14:03 +0100>
[32] pry(main)> 
[33] pry(main)> >> s = Statement.new
=> #<Statement created_at: nil, id: nil, updated_at: nil>
[34] pry(main)> 
[35] pry(main)> >> s.memo = m
Unable to create relationship with non-persisted nodes
/Users/dieter/.rvm/gems/ruby-2.1.2@8actions/bundler/gems/neo4j-2a25adfa38f1/lib/neo4j/active_node/has_n.rb:177:in `memo='
```

The 'new' method behaves differently but also doesn't assign the associated node.

```
[57] pry(main)> >> m = Memo.create
=> #<Memo client_uuid: nil, created_at: Mon, 10 Nov 2014 15:30:41 +0100, description_text: nil, id: "23fd064d-994c-4c5a-9a8a-2435bd88bb44", latitude: nil, longitude: nil, made_at: nil, title: nil, updated_at: Mon, 10 Nov 2014 15:30:41 +0100>
[58] pry(main)> 
[59] pry(main)> >> s = Statement.new(memo: m)
=> #<Statement created_at: nil, id: nil, updated_at: nil>
[60] pry(main)> 
[61] pry(main)> >> s.memo
=> nil
```

Is it possible to make autosaving associations optional?

**Comment by dpisarewski** [comment]
Related issue https://github.com/neo4jrb/neo4j/issues/647

**Comment by subvertallchris** [comment]
This behavior is there very deliberate but it's reasonable to want it to be a little different when running tests. Why don't we try to separate the `def #{name}=(other_node)` portion of the `has_one` definition into its own method, then you can make a `neo4j-factory_girl` gem that overloads it with your change?

**Comment by dpisarewski** [comment]
That would be better than a patched forked repository. But this solution requires monkey patching. What do you mean if on this place were a hook so developer can decide what should be done if the node isn't persisted. Another alternative were to make a configuration option which will trigger the behavior on this place.

**Comment by dpisarewski** [comment]
Here is a sample code for explanation what I meant:

https://github.com/dpisarewski/neo4j/compare/options_for_non_persisted_node?expand=1

**Comment by subvertallchris** [comment]
Love it!
