### ISSUE TITLE
`_rel_creation_query': undefined method `r' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#572]
This was emailed to me by someone having trouble creating a relationship using ActiveRel. The culprit was the same as https://github.com/neo4jrb/neo4j/issues/560 but creating a separate issue in case anyone else comes looking for help.

Make sure your `id_property` in ActiveNode is not set to `id`. Also make sure it's actually generating the IDs you think it is by calling whatever id_property value you have set on your node.

I'll close this once we raise an error in ActiveRel's `create` method.

**Comment by djvs** [comment]
If anyone googles their way here, you may see a similar error when you try to create a relationship on an unsaved class:

     Unable to create relationship. from_node: #<(xxx):0x00000005fba8b0>, to_node: #<(xxx):0x00000005724818>, error: undefined method `r' for nil:NilClass
/home/me/.rvm/gems/ruby-2.2.0/gems/neo4j-4.1.5/lib/neo4j/active_rel/persistence.rb:97:in `rescue in _rel_creation_query'

**Comment by subvertallchris** [comment]
We need to patch that error so it tells you which of those two nodes is not persisted. It did it at one point but forgot to commit. I'll reopen this for now.

**Comment by subvertallchris** [comment]
I'm going to close this but will open with an updated title to reflect what needs to happen.
