### ISSUE TITLE
extend the definition for polimorphic relationships

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#589]
Hi all,
I'd need to define a polimorphic relationship.
Your suggested solution is to use

     has_many :in, :people_playing_music, model_class: Band
     has_many :out, :managed_objects, type: 'manages', model_class: false

But this is a binary solution, while I'd like to have a more fuzzy one, like

     has_many :out, :managed_objects, type: 'manages', model_class: [:Band, :Singer, :Instrument]

Do you think this could be resolved anyway?

Paolo

**Comment by cheerfulstoic** [comment]
See commit 11939fc6bedd0d3181dde4fa12d29fc4e431c176

**Comment by cheerfulstoic** [comment]
GitHub is having some trouble showing the comparison.  It might be because I accidentially made the change on master first and then reverted it and based the branch on the original commit without the revision.  So probably GitHub thinks that the 589_fix branch is older than master with everything that master has.  Best to just look at the commit for now (see above)

**Comment by subvertallchris** [comment]
It's cause of the China DDOS, I think. I had trouble commenting to an
issue, too.

**Comment by cheerfulstoic** [comment]
Merged to master and ready for the next release

**Comment by pdipietro** [comment]
In my Gemfile I've `gem "neo4j", "~> 4.0"`

Trying to define the following polimorphic relationship

    has_one   :out, :belongs_to, model_class: [:Group, :Discussion]  
I got the error:

    SyntaxError (/home/pdipietro/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.5/lib/neo4j/active_node/has_n.rb:189: syntax error, unexpected [, expecting tCONSTANT
    ...Node::Query::QueryProxy.new(::[:Group, :Discussion],
    ...  

How can I specify the correct Gem?

**Comment by cheerfulstoic** [comment]
This is is master which means it isn't released to rubygems.  If you want you can try:

    gem 'neo4j', github: 'neo4jrb/neo4j'

Otherwise, it will be part of the 5.0 release which we're currently working on
