### ISSUE TITLE
Self referencing model with Relation

### ISSUE THREAD

**Issue by PedroSena** [neo4jrb/neo4j#625]
Hi,

I'm trying to create a self referencing model (Technology) with an entity as ActiveRel. Here is what I have so far:

``` ruby
class Technology
  include Neo4j::ActiveNode

  property :name, index: :exact
  validates :name, presence: true

  has_many :out, :technologies, type: 'references', rel_class: Association
end

class Association
  include Neo4j::ActiveRel

  type 'references'
  from_class Technology
  to_class Technology

  property :weight, type: Integer
end
```

They work when I save them like this:

```
t1 = Technology.new name: 'ruby'
t1.save
t2 = Technology.new name: 'java'
t2.save
rel = Association.new from_node: t1, to_node: t2
rel.save
```

However when I try to use `t1.technologies << t2` or `t1.technologies << Association.new` it fails with the following error:

NoMethodError: undefined method `_type' for Neo4j::ActiveNode::HasN::Association:Class
    from /home/pedro/.rvm/gems/ruby-2.1.4@markettrends.it/gems/neo4j-3.0.4/lib/neo4j/active_node/has_n/association.rb:73:in`relationship_class_type'
    from /home/pedro/.rvm/gems/ruby-2.1.4@markettrends.it/gems/neo4j-3.0.4/lib/neo4j/active_node/has_n/association.rb:57:in `relationship_type'
    from /home/pedro/.rvm/gems/ruby-2.1.4@markettrends.it/gems/neo4j-3.0.4/lib/neo4j/active_node/has_n/association.rb:26:in`arrow_cypher'
    from /home/pedro/.rvm/gems/ruby-2.1.4@markettrends.it/gems/neo4j-3.0.4/lib/neo4j/active_node/query/query_proxy.rb:253:in `_association_arrow'
    from /home/pedro/.rvm/gems/ruby-2.1.4@markettrends.it/gems/neo4j-3.0.4/lib/neo4j/active_node/query/query_proxy.rb:207:in`block in create'
    from /home/pedro/.rvm/gems/ruby-2.1.4@markettrends.it/gems/neo4j-3.0.4/lib/neo4j/active_node/query/query_proxy.rb:197:in `each'
    from /home/pedro/.rvm/gems/ruby-2.1.4@markettrends.it/gems/neo4j-3.0.4/lib/neo4j/active_node/query/query_proxy.rb:197:in`create'
    from /home/pedro/.rvm/gems/ruby-2.1.4@markettrends.it/gems/neo4j-3.0.4/lib/neo4j/active_node/query/query_proxy.rb:172:in `<<'

I'm not sure if it is my mistake or a real problem, a real example of self referencing with a relationship(with some attributes) in the middle would be awesome.

Thanks

**Comment by jaswinder97** [comment]
I would like to know how we can make both in and out has_many association for the same.
like we already have

 has_many :out, :technologies,  rel_class: Association

similarly ,can we make another association by replacing it with:

  has_many :both, :technologies, rel_class: Association

or for seperate references as:

  has_many :out, :technologies_1 , rel_class: Association
  has_many :in, :technologies_2 , rel_class: Association

This is needed as we have corresponding rails associations using foreign key references.

**Comment by cheerfulstoic** [comment]
Yeah, you can do a similar thing in `ActiveRecord`.  In `ActiveNode` you can make `technologies_1`, etc... but that's not very descriptive.  I'd suggest something like:

```ruby
has_many :out, :owned_technologies , rel_class: :Owns
has_many :in, :owning_technologies , rel_class: :Owns
has_many :both, :technologies, rel_class: :Owns
```

It all depends on what you're doing, though.  Here I'm assuming your relationship type is something like `OWNS` and that the `Owns` model describes those relationships, but you would probably change your association names depending on the relationship type in Neo4j.

Make sure that you're using the latest version of the gem.  It should require you to use a symbol or a string for the `rel_class` argument rather than the `ActiveRel` model constant

**Comment by cheerfulstoic** [comment]
@jaswinder97 (notification for the above, sorry for the delay in responding0
