### ISSUE TITLE
Support returning paths

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#636]
I don't think we support this, but it would be nice to be able to pluck/return a path and have it returned as an array of nodes and relationships

**Comment by Richard-Mathie** [comment]
How?

**Comment by cheerfulstoic** [comment]
Something like:

    query.match("path = (node1)-[*]-(node2)").pluck("nodes(path)")

**Comment by Richard-Mathie** [comment]
yeah that is what I was doing before. It seems I didn't understand what you meant about the nodes() function
