### ISSUE TITLE
Autoloading causes transactions to fail

### ISSUE THREAD

**Issue by dpisarewski** [neo4jrb/neo4j#640]
My model has properties with indexes. When I load any model class within a transaction it hangs up for 60 seconds until the transaction expires.

```
>> Neo4j::Transaction.run do
  User.first
end
 CYPHER 11ms MATCH (n:`User`) RETURN n ORDER BY n.uuid LIMIT 1
Neo4j::Server::Resource::ServerException: Expected response code 200 Error for request http://localhost:7474/db/data/transaction/5?headers%5BAccept%5D=application%2Fjson&headers%5BContent-Type%5D=application%2Fjson&headers%5BUser-Agent%5D=neo4j+gem%2F4.0.0.rc.1+%28https%3A%2F%2Fgithub.com%2Fneo4jrb%2Fneo4j%29, 404, 404
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j-server/resource.rb:38:in `handle_response_error'
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j-server/resource.rb:42:in `expect_response_code'
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j-server/cypher_transaction.rb:50:in `_delete_tx'
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j/transaction.rb:57:in `close'
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j/transaction.rb:91:in `ensure in run'
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j/transaction.rb:91:in `run'
	from (irb):1
```

The reason is that neo4j creates indexes on loading model class which doesn't work within a transaction. https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/shared/property.rb#L148

I must preload all models to avoid this issue. Is there any way to use transactions without preloading of models?

**Comment by jmdeldin** [comment]
I was just bitten by this and worked around by requiring the nodes I was working with -- glad I found this issue! I'm wondering if it'd be useful to have this error + workaround listed in an FAQ or on a docs page about Transactions just to save others from digging around in the future.

**Comment by cheerfulstoic** [comment]
Weird... I just got an E-Mail about your comment @jmdeldin ...  It happened with another issue.  Maybe GH is having some issues?

Yeah, I definitely think that you shouldn't need to reference the model before using it as this isn't necessary for ActiveRecord.

Created https://github.com/neo4jrb/neo4j/issues/972
