### ISSUE TITLE
Default relationship type for assocations

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#657]
So I've been thinking that we could do better in the realm of default relationship types for associations.  @subvertallchris and I have talked a lot in the past about sometimes having the desire to not specify a relationship type for an association, but still wanted those relationship types mean something when looking at the web console.  At the moment I believe we just use the association name.  We also don't really advertise much in the docs that you can leave out the relationship type. 

So, with that said, what about something like this?

```ruby
  class Post
    has_many :out, :comments  # has_comment
    has_many :in, :comments    # has_post
    has_one :in, :author             # has_author
    has_one :out, :author           # has_post
  end

**Comment by cheerfulstoic** [comment]
I'm still pondering this, but one thing that occurred to me: I think the reason I thought of this in the first place is because I keep seeing people come up with poor relationship names on SO.

**Comment by subvertallchris** [comment]
The gem now requires you to name your associations, so I'm closing this.
