### ISSUE TITLE
Fixnum Length Issue

### ISSUE THREAD

**Issue by jhmegorei** [neo4jrb/neo4j#663]
Hi everyone,

yesterday I tried to deploy a rails app with neo4j database on a raspberry pi (32 bit Raspbian).
When I tried to create a node with a timestamp in it, I encountered the following error:
```
ArgumentError: Invalid value type for DateType property: 1421248210
	from /home/live/apps/dinghub/shared/bundle/ruby/2.1.0/bundler/gems/neo4j-8b6a4efc3c27/lib/neo4j/shared/type_converters.rb:49:in `to_ruby'
```

Putting a debug statement in the code (```fail ArgumentError, "Invalid value type for DateType property: #{value.inspect} of class #{value.class}"```) I noticed that the timestamp was converted to a BigNum data type.

Doing some more research (http://patshaughnessy.net/2014/1/9/how-big-is-a-bignum) the issue was clear. On a 32 bit platform, a fixnum can have a maximum value of 2^30 (32 bit minus one bit for the fixnum flag and one bit for the sign), which is 1073741824. As the timestamp was larger than that, it was converted to BigNum as expected. This does not happen on a 64 bit platform, as the FixNum maximum value is much larger there.

The easiest fix would be a check for the value being of type Integer (the master type of FixNum and BigGun).

**Comment by subvertallchris** [comment]
That is a really cool discover. Do you think a custom type converter might help? You could set the property to use this in 32-bit environments to avoid this issue completely. I'm not sure how it would work, but we can figure that out. :-)

**Comment by jhmegorei** [comment]
I just forked the repo and will try just replacing Fixnum with Integer. Imho that should do the trick. If it does, I will go over it with @dpisarewski and create a pull request

**Comment by dpisarewski** [comment]
Great work. I guess there should be a rule in [ruby-style-guide](https://github.com/bbatsov/ruby-style-guide) saying it's better not to use platform-dependent types like `FixNum` and `BigNum` for type checking because the majority of ruby developers uses them and are not aware of this issue.
May be the origin of spreading `FixNum` usage comes from earlier ruby verstions where there was no `Integer` type.

**Comment by cheerfulstoic** [comment]
That's a good idea.  Plus then they could put it into rubocop so that it can be automatically checked (any maybe even automatically fixed)
