### ISSUE TITLE
Does Neo4j.rb fully support the WITH clause?

### ISSUE THREAD

**Issue by tritonresearch** [neo4jrb/neo4j#664]
I am trying to limit my query with a WITH clause, for example:

    MATCH 
        (c:Company)-[:has_attr]->(:SomeAttr)
    WITH c limit 10
    MATCH (c)-[r]->()
    RETURN c, count(r)

This limits the second MATCH clause to only look at 10 companies. However, if you try doing something like. . .

     Neo4j::Session.query
        .match('(c:Company)-[:has_attr]->(:SomeAttr)')
        .with(:c)
        .limit(10)
        .match('(c)-[r:has_attr]->()')
        .return('c.name', 'count(r)')

This gives the following, putting the limiting parameters at the end of the query.

    MATCH (c:Company)-[:has_attr]->(:SomeAttr) 
    WITH c MATCH (c)-[r:has_attr]->() RETURN c.name, count(r) LIMIT 10

Is there a way to associate limiting parameters with the WITH clause?

Thanks!

**Comment by subvertallchris** [comment]
QueryProxy sometimes messes with the order of methods when building the chain. To lock things in place, add `break` to your chain.

If you're using ActiveNode, you can also achieve this with something like `company.as(:c).attrs.query.with('c limit 10').proxy_as(Company, :c).attrs(:a2, :r).return('c.name', 'count(r)')`. `proxy_as` creates a QueryProxy object that builds upon a Core::Query, but it calls `break` behind the scenes to lock it down specifically to allow things like this.

**Comment by cheerfulstoic** [comment]
More and more I really think we ought to make any `limit` calls directly after `with` clauses to go onto those `with` statements.  I just put in an issue: https://github.com/neo4jrb/neo4j/issues/665

**Comment by tritonresearch** [comment]
Thanks, this is helpful. Making limit/offset calls sticky to with calls definitely seems reasonable.
