### ISSUE TITLE
Question about caching, performance and better DRY 

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#670]
I have several different classes, each one declares a relationship with a User#Owner.
For each class, the controller for the index action can be implemented in one of the following ways:

    def index
        @objects = Object.all.order(code: :asc)
    end
or

    def index
        @objects = Neo4j::Session.query("match (object:Object)<-[owns:owns]-(owner:User) return object,owner.uuid as owner_uuid")
    end

When I invoke the viewer, I must be able to allow only the owner to modify its own objects, while other users can only view.

Thus, I need to pass the owner_uuid and check it against the current_user.uuid

My question is: **which is the best solution (in terms of performance, standardization, pure MVC)?**

Can I forget these kind of problems letting the cache to solve it for me?

With the first one, I need to write

     @objects.each do |object|
         is_owner = Neo4j::Session.query("check the object to se if the user.uuid = current_user.uuid")
         render 'view', locals: { object: object , isOwer: is_owner } 
     end

while with the second one I have a better performing query, but I need to move around not an object, but a collection of an object and an owner, so needing to customize all the viewer and all the render call in the controllers.

Anyone has ever experienced this question and cansuggest the best approach to follow?

TIA

Paolo

**Comment by cheerfulstoic** [comment]
I suspect @subvertallchris has some experience, but I'll give it a shot.

Firstly, maybe you know this, but there's no need to use a cypher string.  Can you do something like this?

    @objects = Object.as(:object).owner.owner.return(:object, 'owner.uuid AS owner_uuid')

I believe that @subvertallchris 's new eager loading changes might be helpful with your issue.  If you made an `#is_owner?` method like this:

    def is_owner?(user)
      self.owner == user
    end

Then I think you could do `Object.all.includes(:owner)` and it would do a single cypher query to get all of the owners.  If you didn't do the `includes`, it would still work, but more slowly because it's many queries.

**Comment by subvertallchris** [comment]
Yeah, this is something I've done a few times... ;-)

Assuming you mean that read OR (read + write) needs to be determined in the same view based on who the user is. This will do it for now:

```ruby
results = Object.as(:object).query.proxy_as_optional(Object, :object).owners(:owner).pluck(:object, 'collect(owner)')
@objects, @owners = results.map { |row| row[0], row[1] }

<% @objects.each_with_index do |object, i| %>
  <% if @owners[i] == current_user %>
    It is the owner
  <% else %>
    It does not have write access
  <% end %>
<% end %>
```

By collecting the owners, you get one Owner for each Object and the indexes always match. When `includes` is merged in, it automates this for you, so `object.owner` will already have the result in its association cache and you won't need to mess with indexes or have a complicated Cypher query.

**Comment by subvertallchris** [comment]
Actually, `owners` there will also be an array, so you'd probably want:
```
@objects, @owners = results.map { |row| row[0], row[1].first }
```
I guess? Just going off the cuff here, you'll need to tweak but this is where I'd start.

Now, if you're only concerned about ensuring that an action is being attempted by a privileged user, that's a very easy query:

```
@objects = Object.as(:o).owners.match_to(current_user).pluck(:o)
```
That will only return the objects owned by that user. If you just want a specific object...

```
@objects = Object.as(:o).where(uuid: params[:id]).owners.match_to(current_user).pluck(:o)
```

You could also reverse those and start from the user, match_to the object's id, and then you can skip `pluck` entirely.

**Comment by pdipietro** [comment]
Thank you both!

My primary concern is about having the minimum DB effort/overload while running a query with lot of objects and related Users, so I think that the first answer from Chris could be the best one! Let me test it and verify.

By the way, another question: is there any way to let users write their own read-only queries on  the full database, except a couple of hidden objects? (i.e: everything except users and customers ....)

**Comment by cheerfulstoic** [comment]
If you're talking about Cypher queries, probably.  Though there's always room for danger.

If I was doing it I might take in the cypher query and fail if the query contains /(create|delete|update)/.  That might filter out some queries that are actually fine, but better safe than sorry.  Then, before returning the results, filter out the sort of objects that you don't want them to see.  I imagine there's room for danger there as there always is if let users do raw queries or `eval`s, but you get the idea.

**Comment by pdipietro** [comment]
Adding complexity: in the previous suggestion Chris suggested the following:


    results = Object.as(:object).query.proxy_as_optional(Object, :object).owners(:owner).pluck(:object, 'collect(owner)')
    @objects, @owners = results.map { |row| row[0], row[1] }


But, how can I find all the objects with a (A OR B) relationship with another?
Example: only Groups when a User (Owns or Participates)?
