### ISSUE TITLE
Question about Neo4j browser

### ISSUE THREAD

**Issue by ferryphang** [neo4jrb/neo4j#673]
Hi sorry for bothering you guys, how can i access neo4j http://localhost:7000/browser/, on my vps like for example http://ipaddress:7000/browser ? now my neo4j start on port 7474.
Thank you

**Comment by cheerfulstoic** [comment]
If you've installed neo4j from the neo4j gem, you can use `rake neo4j:config[development,7000]`.  If you installed it otherwise you can find the port configuration in the `neo4j-server.properties` file

**Comment by ferryphang** [comment]
Hi @cheerfulstoic thanks for the reply, i tried to ``` rake neo4j:config[development,7000] ``` and tried to access my vps ```http://ipaddress:70000/browser``` but got a response unable to connect. so i tried to change ```neo4j-server.properties``` 
and uncomment this section with my ip address
```org.neo4j.server.webserver.address=xxx.xxx.xxx.xxx```

**Comment by cheerfulstoic** [comment]
Sorry, I'm not sure I understand what your VPS is what exactly you're trying to do.  Maybe you should try over on Stackoverflow with the tag `neo4j` as this isn't really related to the gem (as far as I can tell).
