### ISSUE TITLE
Support `where("foo = {bar}", bar: val)`

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#675]
More copying from ActiveRecord.  Would be shorthand for `where('foo = {bar}').params(bar: val)` in our case

**Comment by subvertallchris** [comment]
I would loooove this, Brian.

**Comment by subvertallchris** [comment]
It'd probably need to be `where("n.foo = {bar}", bar: val)`. right?

**Comment by cheerfulstoic** [comment]
Yep, unless you had a `WITH` I suppose ;)

**Comment by cheerfulstoic** [comment]
On that note, this might make sense in Query as well as QueryProxy (probably if you implement in the former it will work in the later)
