### ISSUE TITLE
Again about DRY a query

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#678]
Adding complexity: in a previous suggestion #670  Chris wrote as following:

    results = Object.as(:object).query.proxy_as_optional(Object, :object).owners(:owner).pluck(:object, 'collect(owner)')
    @objects, @owners = results.map { |row| row[0], row[1] }
But, how can I find all the objects with a (A OR B) relationship with another?
Example: only Groups when a User (Owns or Participates)?

**Comment by subvertallchris** [comment]
I'd need to know your domain to answer that. Figure it out in Cypher first, then translate it to Ruby.

BTW, you're not using Object as a node model, are you? If so, you shouldn't, it's Ruby's base object class.

**Comment by pdipietro** [comment]
No, I'm not using object, is just to show that it is not a specific object.

In my mind, it doesn't depends on the domain, but is a general approach, easy to reproduce using cypher (it runs ...., but cannot imagine how to turn the OR (or AND or XOR ...) in neo4jrb):

    match (n)-[r:owns|likes]->(m)  return n,r,m;

of course, it could be    match (n:User)-[r:owns|likes]->(m)  return n,r,m;
or match (n)-[r:uses|shares|publish]->(m:domain_element)  return n,r,m;

**Comment by subvertallchris** [comment]
When you reach the point that something can't be expressed with QueryProxy in Neo4j.rb, just call `query` and work in Core::Query. You'll have access to the full Cypher DSL, where you can express anything that you'd normally do with Cypher.

**Comment by pdipietro** [comment]
I'm starting to understand, but when I use x = ClassName.as(....) am I working with Core::Query or not?

**Comment by subvertallchris** [comment]
These are not stupid questions. I'm in the middle of something right now but I've been meaning to write a blog post about this. I will write something up and link you a little later!

Short answer, though: QueryProxy has ActiveNode models and associations as its focus; Core::Query is a Cypher DSL. QueryProxy is an abstraction of the Cypher DSL, it gives shortcuts for common tasks. There are two approaches because QueryProxy has more "magic." It is "easier" but also gives you less control.

**Comment by subvertallchris** [comment]
OK, check this out! http://neo4jrb.io/blog/2015/02/08/query_or_query-proxy.html

**Comment by pdipietro** [comment]
I found this doc thru twitter, this morning .... just after my wake up ....
Good work. Thank you.
PDP
