### ISSUE TITLE
How to implement a query with a variable length relationships?

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#685]
Hi all,
I have

    match (user:User { uuid = "xyz" })-[likes:Likes*]->(anotherUser:User)-[owns:owns]->(dest:Post)
but I didn't find a way to translate in Ruby.

Also, can you provide some feedback on the #678?

Thank you

**Comment by subvertallchris** [comment]
You'd need to use Core::Query for that part of this one. Assuming there's a `posts` association defined in User, you could do it like this:

```
User.as(:user)
  .query.match("[likes:Likes*]->(anotherUser:User)")
  .proxy_as(User, :anotherUser).posts(:dest, :owns)
```

**Comment by pdipietro** [comment]
With the 4.0, should I still add the neo4j-will_paginate_redux or it is included?

**Comment by subvertallchris** [comment]
That contains behavior specific to the will_paginate gem. If you want to use that, yeah, you should include that.

**Comment by pdipietro** [comment]
Have you a feedback for the issue #678?

**Comment by pdipietro** [comment]
Well, I loaded the  `neo4j-will_paginate_redux gem`, then added  a `require 'neo4j-will_paginate_redux'`
but the following statement

     grp = Group.as(:groups).query.match(query_string).paginate(:page => actual_page, :per_page => items_per_page, return: :groups, order: "groups.created_at desc") 

returns the following error:

    Completed 500 Internal Server Error in 113ms
    NoMethodError (undefined method `paginate' for #<Neo4j::Core::Query:0x0000000729b268>):
any idea?

**Comment by subvertallchris** [comment]
It means what it says... As soon as you call `query`, you're working in Neo4j::Core::Query, which doesn't have a `paginate` method. That's added by QueryProxy. You'd need to use `proxy_as` before calling `paginate. You can open an issue on that gem if you need help with it.

**Comment by pdipietro** [comment]
ok
