### ISSUE TITLE
About querying polymorphic relationships

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#687]
I have the following query definition:

    class Owns
      include Neo4j::ActiveRel
      from_class  User
      to_class    :any
      type 'owns'
    end
and the following cypher query

    match (user:User {uuid : '123'})-[owns:owns]->(rel) return rel 

It returns 34 elements, belonging to 4 different classes (12 Groups, 7 Posts and so on) `correct`.

The following Ruby instructions, all returns 34, that is `wrong`.

    x1 = self.rels(dir: :outgoing, type: :owns, :_to_node => :Group).count
    x2 = self.rels(dir: :outgoing, type: :owns, :_to_class => :Group).count
    x3 = self.rels(dir: :outgoing, type: :owns, :_to_node => :Post).count
    x4 = self.rels(dir: :outgoing, type: :owns, :_to_class => :Post).count
    x4 = self.rels(dir: :outgoing, type: :owns, :_to_class => "Post").count

Which is the correct way to write the query?

By the way, this kind of query doesn't appera in the Rails Log, so is more difficult to understand what is happening

**Comment by cheerfulstoic** [comment]
What is `self` in your last example there?  The `User` class?

I wouldn't suggest using the `rels` method.  I would create associations.  For the `User` model that would be:

    class User
      include Neo4j::ActiveNode

      has_many :out, :owned_objects, type: :owns, model_class: false
    end

That way `user.owned_objects` should give you all of the different owned nodes

**Comment by pdipietro** [comment]
In the user model, I already have the following:

      has_many  :out, :owns, rel_class: Owns      
It is similar to your statement, but uses the  declared relationship

    class Owns
      include Neo4j::ActiveRel
      from_class  User
      to_class    :any
      type 'owns'
    end
My question is not about having all the different owned nodes, but to query only for all the owned_nodes of a particular type

In other words, while the following statements are equivalent (given `aUser instance with uuid=123`, both returns `34 nodes`)

     [cypher] match (user:User {uuid : '123'})-[owns:owns]->(rel) return rel 
     [ruby  ] aUser.rels(dir: :outgoing, type: :owns, :_to_node => :any)   
what is the equivalent for the following, where the cypher correctly returns `17 nodes`)

     [cypher] match (user:User {uuid : '123'})-[owns:owns]->(rel:Group) return rel 
     [ruby  ] aUser.rels(dir: :outgoing, type: :owns, :_to_node => ????????????? ) 
because the latter always returns 34 nodes with the following statements (please, note the last parameter of each statement)
 
    aUser.rels(dir: :outgoing, type: :owns, :_to_node => :Group)
    aUser.rels(dir: :outgoing, type: :owns, :_to_class => :Group)
    aUser.rels(dir: :outgoing, type: :owns, :_to_node => :Post)
    aUser.rels(dir: :outgoing, type: :owns, :_to_class => :Post)
    aUser.rels(dir: :outgoing, type: :owns, :_to_class => "Post")

**Comment by subvertallchris** [comment]
You'd either need to define a new association that uses `model_class` to force a label in the Cypher or use `query` to add info about the match.

```
user.as(:u).query.match("(other_node:Post)").query_as(User, :u).owns(:other_node)
```

That'll generate `MATCH (u:User), (other_node:Post) WHERE ID(u) = #{user.id}, WITH u, other_node MATCH (u)-[r1:owns]->(other_node)`.

**Comment by pdipietro** [comment]
it returns 
NoMethodError (undefined method `as' for #<User:0x00000007fbd630>)

as is a class method while aUser is an instance .....

**Comment by subvertallchris** [comment]
What version of neo4j.rb are you using? An `as` instance method was added in 4.1.0.

**Comment by pdipietro** [comment]
was 4.0.0 ;-)
Now I loaded the 4.1.2 and the error is changed ;-(

it is now

    NoMethodError (undefined method `query_as' for #<Neo4j::Core::Query:0x00000003d43ea8>):

**Comment by subvertallchris** [comment]
Typo in my sample, it should be `proxy_as`

**Comment by pdipietro** [comment]
Well Chris, the problem is not how to run a query for those results, because there are a lot of workarounds.

The real question is if there is a correct way to use 

    aUser.rels(dir: :outgoing, type: :owns, :_to_node => ????????????? )

Because it seems to be a third parameter but it seems not to run correctly ....

**Comment by subvertallchris** [comment]
I can't find any reference to a `rels` instance method that takes three arguments like that.  The only `rels` method I'm aware of is provided by Neo4j-core and like Brian, I try to avoid it.

**Comment by cheerfulstoic** [comment]
I would first try an association like Chris suggested, like this:

    has_many  :out, :owned_groups, rel_class: Owns, model_class: 'Group'

Then you can just say `aUser.owned_groups`

**Comment by pdipietro** [comment]
Ok, if you prefere to avoid that rels method, it's alright.
