### ISSUE TITLE
Eager Loading

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#689]
Ok, so eager loading!

I say we try to have:
 * something relatively simple but still much better than what we have
 * something that will fix the N+1 problem, but not try to make everything come from one query

We've talked about this a number of times, but I don't remember everything, so feel free to poke holes in my proposal.

So let's take an example:

    User.includes(:settings, :posts => {:comments => :author})

This could be implemented to make one query for every association:

    MATCH (u:User)
    MATCH (u:User)-[:HAS_SETTING]->(setting:Setting)
    MATCH (u:User)-[:CREATED]->(post:Post)
    MATCH (u:User)-[:CREATED]->(post:Post)<-[:COMMENTS_ON]-(comment:Comment)
    MATCH (u:User)-[:CREATED]->(post:Post)<-[:COMMENTS_ON]-(comment:Comment)<-[:WROTE]-(author:User)

If we want to get fancy we could do this:

    MATCH (u:User)
    MATCH (u:User), u-[:HAS_SETTING]->(setting:Setting), u-[:CREATED]->(post:Post)
        RETURN u, collect(setting), collect(post)
    MATCH (p:Post), p<-[:COMMENTS_ON]-(comment:Comment)
        WHERE ID(p) IN [id, list]
        RETURN p, collect(comment)
    MATCH (c:Comment), c<-[:WROTE]-(author:User)
        WHERE ID(c) IN [id, list]
        RETURN c, collect(author)

It shines when you're going wide with associations, and not so much when you're going deep.  It's more complicated, and I'm not convinced it's worth it, especially for a first pass.

So as far as filtered associations go, we could have users define the associations:

    User.includes(:posts => :hidden_comments)

    class Post
      has_many :in, :comments, type: :COMMENTS_ON

      has_many :in, :hidden_comments, type: :COMMENTS_ON, scope: -> { all.hidden }
    end

That way when they call `user.posts[0].hidden_comments` it's very clear what they're getting.  The downside is that you need to create a new association every time you want to make a query like this.  Also, I think that scope logic like this should belong on the other model, like this:

    class Comment
      scope :hidden, -> { where(hidden: true) }
    end

Perhaps we could have a bit of magic that, in this case, allows you to combine the `scope :hidden` from the `Comment` model and the `has_many :in, :comments` from the `Post` model to let you do eager loading of the `:hidden_comments` symbol.  If you have the post, though, you should be able to do `post.comments.hidden`, so I don't know.

**Comment by djvs** [comment]
Like mentioned in my 'assorted request for help' issue the other day, wouldn't this work better with OPTIONAL MATCH?

**Comment by subvertallchris** [comment]
Yeah, I think `OPTIONAL MATCH` is the way to go. I have a version of `includes` that lets you preload multiple associations one level deep (`User.includes(:settings, :posts)`) but completely falls apart as soon as you want to do `User.(:settings, :posts => {:comments => :author})`. I closed the PR a few weeks ago because it just didn't feel finished. You can see how it worked at https://github.com/neo4jrb/neo4j/blob/18f7f22985e8799d9aacf69445582b937cbfe5ea/spec/e2e/association_includes_spec.rb if you're interested.

I think we should start by figuring out what we want to accomplish. Do we need something that only uses one query for everything? Do we want to be able to filter the match used? Anything we want to avoid?

**Comment by cheerfulstoic** [comment]
I've made some progress on the `eager_loading` branch.   See the spec for a the two modes of how it currently works:

https://github.com/neo4jrb/neo4j/blob/eager_loading/spec/e2e/association_proxy_spec.rb#L43

Basically if you don't do anything it makes one query for every association that you use (no matter how deep you go).  If you want to load everything in one query, you can do that with `with_associations` which returns an array of the objects represented by the `QueryProxy` with associations eagerly loaded (this doesn't allow for chaining of eager loading at different points).  If you don't do all associations for the later format, the former format should kick in (though I should test that).

I feel like I'm probably missing something, so I'd love to hear feedback.  I've done a lot of refactoring so the method in which we eager load shouldn't be too hard to change

**Comment by djvs** [comment]
Sounds correct, you're doing this instead of `OPTIONAL MATCH`?  I did find some major performance problems with that recently.

**Comment by djvs** [comment]
Very cool

**Comment by cheerfulstoic** [comment]
If you just are browsing associations without specifying any eager loading it's doing `MATCH` because there's one query for every association so we don't need to use `OPTIONAL`.  If you eager load everything into one query it uses `OPTIONAL MATCH` because it needs for the one-query case.  So it's a bit of a trade off.

Also, one thing that I forgot to mention, I was thinking about having the eager loading method (currently `with_associations`, though I'm not necessarily attached to the name) take a hash argument where you could follow association chains like `with_associations(first_association, second_association: other_association)`.  In this case, I think the most efficient that we can be without having really crazy code is to have one query for every level (think a breadth-first search)

**Comment by djvs** [comment]
I mention the slow performance because I noticed a moderately sized set of
OPTIONAL MATCHES was actually hanging neo4j,  well over a minute,  for a
600 ms equivalent set  of individual queries (about 6 associations in that
case), which after some reading I concluded was due to the OPTIONAL
MATCH.   If you can get good performance from a hash chain like that,  it'd
be one of those 'killer app' features for me.  Not supported with some
ORMs,  personally I've been stuck writing individual methods for eager
loading here.

**Comment by subvertallchris** [comment]
This is very cool. The way you're doing it is much better than my early approach, I hope my stuff was at least useful for ideas.

@djvs I've only had issues with `OPTIONAL MATCH` when trying to use it in conjunction with `WHERE`. Never actually pinned down why. For what it's worth, I use OPTIONAL MATCH all the time without trouble these days.

**Comment by djvs** [comment]
Hm,  that would make sense,  wouldn't it.

**Comment by cheerfulstoic** [comment]
@subvertallchris It was for sure, thanks! ;)

**Comment by cheerfulstoic** [comment]
Could be a bit better, maybe, but merged into master for now
