### ISSUE TITLE
How to get a relationship?

### ISSUE THREAD

**Issue by djvs** [neo4jrb/neo4j#702]
Trying this in console:

    2.2.0 :070 > User.first.permissions.first
    NoMethodError: undefined method `mapped_label_name' for #<Class:0x000000042337b0>

With the following setup:

in class User:

    include Neo4j::ActiveNode
    has_many :both, :resources, rel_class: 'Permission', model_class: 'Resource'

in class Permission:

    include Neo4j::ActiveRel
    to_class :any 
    from_class :any 
    type 'permits'

in class Resource (the one being related to here):

    include Neo4j::ActiveNode
    has_many :both, :users, rel_class: 'Permission', model_class: 'User'
    has_many :both, :orgs, rel_class: 'Permission', model_class: 'Org' # is this a problem, by the way?

However, the Permission saves just fine:

    (ruby ver)> Permission.first
     => #<Permission accepted: false, blah blah blah...> 

I tried this "pluck", "each_with_rel" etc. stuff in the docs.  Confused if that's the best (or only) way.  

One other thing maybe you could help with...sort of related...

I'm migrating from MongoDB.  Previously there were embedded documents, and JSON methods that would encode them directly inside of something as EmbeddedDocuments (these were actually just very complex relationships).   Now I'm trying to figure out how to better accomplish this.  I used to call something like (just for example):

user.permissions.all[20].obj

for a polymorphic "obj".  How would I go about constructing data that way?   Do I have to do it manually via each_with_rel?    What would make my day right now, is if I could say (pseudocode):

    User.relationships(with class 'Permission').with_to_node

But I have no idea how to express this.

**Comment by cheerfulstoic** [comment]
What if you do `User.first.resources.first`?  The association method comes from the second argument to `has_one` / `has_many`

One thing to clarify is that you don't need to use `ActiveRel`.  Generally that's for if you have logic going on on relationships (like properties/validations/callbacks)

If I'm understanding right, if you want to have a polymorphic association, I think you'd want something like:

```ruby
class User
  include Neo4j::ActiveNode

  has_many :both, :resources, type: :permits
  # The `model_class` is assumed from `resources` association name
end

class Org
  include Neo4j::ActiveNode

  has_many :both, :resources, type: :permits
end

class Resource
  include Neo4j::ActiveNode

  has_many :both, :users, type: 'permits'
  has_many :both, :orgs, type: 'permits'
end
```

Some potential queries:

```ruby
  User.resources # Gives you all the resource nodes if you enumerate (call `to_a`, `each`, etc...)
  User.resources(:resource, :rel).pluck(:rel) # Gives you all the relationships
```

When you are returning relationships like that second query, it will give you CypherRelationship objects.  Again, if you want validations/callbacks, you can create an `ActiveRel` model

**Comment by djvs** [comment]
User.first.resources.first works fine.  And yes, we do have a number of properties on Permission, which is polymorphic in *both* directions (although that may change with refactoring).  Namely, we have a string based permission "type" (poorly named 'permission' itself).   This is something we want to *update* also.

The other non-permission example is basically a 'document' with dozens of embedded documents which we're reworking as ActiveRel relationships.  Each one has its own logic, but they are hierarchically arranged using ancestry-based arrays of IDs - we simply return an array of these components to be assembled on the client side - they also contain metadata about the objects they point to.  See the problem I'm having?

**Comment by djvs** [comment]
Data modelling questions aside - it seems like I can basically say:

u.rels(type:'permits)

and get an array of Permissions.  Is there any better way to narrow that further, besides with Ruby .select{|x|...}?

**Comment by cheerfulstoic** [comment]
I would avoid `#rels`, I think.

If you use model associations you can use `rel_where` to limit, like:

```ruby
  u.resources.rel_where(prop: val).rel_where("prop < val")
```

The other thing that I forgot to mention is that you can embed hashes as JSON objects with `serialize`:
https://github.com/neo4jrb/neo4j/wiki/Neo4j%3A%3AActiveNode#property-serialization

That may or may not be helpful in this case, but it's another tool in the chest.

I think I'm starting to see the problem, though examples would be helpful.  Also, @subvertallchris is the ActiveRel expert (though I really should dig in there more ;)

**Comment by subvertallchris** [comment]
The problem with this:
```
2.2.0 :070 > User.first.permissions.first
NoMethodError: undefined method `mapped_label_name' for #<Class:0x000000042337b0>
```
...is that it thinks that an ActiveRel class is an ActiveNode class. You don't have an example of what your `permissions` association looks like but I'm guessing it's something like this:

```
has_many :out, :permissions, rel_class: 'Permission'
```

Rel classes can't be targets of associations, they just make it easier to control behavior when creating and returning relationships. If you want to return the relationship between the user and resource, do `User.first.resources.each_rel` or `User.first.resources(:res, :rel).pluck(:rel)`.

Won't have a chance to really look through the rest of what you guys are talking about until later but one thing did jump out at me: while we do have the capability of serializing hashes to JSON to essentially embed content within nodes, I find this to be a bad practice in Neo. In these cases, wherever possible, you should try to create an additional node. It's obviously up to you since it does complicate application code -- it might be nice if we could automate some of this in the gem, so associations always return objects that should appear embedded in properties -- but for now, be careful with it.

**Comment by djvs** [comment]
No, we are moving away from embedding things, serializing sounds like a pointless nightmare for all but the simplest, least-requiring-indexes properties.

Anyway, maybe this will clarify.  Here's some Mongoid code I need to rewrite ("routes is now an ActiveRel):


    def num_admin_resources
      self.routes.where(:obj_type => "Resource", :attached_resource => false).count
    end

**Comment by subvertallchris** [comment]
Can you help me understand what your original Mongoid method was supposed to do and what the goal of the new method is?

**Comment by djvs** [comment]
def num_admin_resources
  self.routes.where(:obj_type => "Resource", :attached_resource => false).count
end

This would just query routes that pointed to 'resources', and had the property attached_resource set to false.  Looking to accomplish the same thing in Neo.

**Comment by subvertallchris** [comment]
OK, got it. Even though `Routes` is ActiveRel, focus your queries on nodes and associations defined in them. How bout this:

```
self.resources.rel_where(attached_resource: false).count 
```
Try to avoid anything that iterates an enumerable cause that'll return your results to Ruby first. Calling `count` on a QueryProxy chain performs the operation in the DB.

**Comment by djvs** [comment]
OK, that helps.  That's one model.

One other question if you don't mind.  Let's say there's a traversal User -> Courses -> License.  How can I say something like:

    user.courses.license

and get an array of courses, with a property 'license' set -- if license exists -- otherwise nil?

**Comment by subvertallchris** [comment]
There's a common pattern for this that we're working on integrating into
the gem. For now, it's like this:

```
result = user.courses(:c).license(:l).pluck(:c, 'collect(l)')
result.each { |course, license| }
```
`result` is an array, so is `license`, and each course is partnered with
its licenses, however many there many be. You use `collect` to prevent
cypher from spitting out the same course multiple times if it has more than
one license.

**Comment by djvs** [comment]
Nice!  How about this second bit (sorry, edited my comment) with collecting end nodes from routes?

**Comment by djvs** [comment]
Repasted here:

Have the same issue with the aforementioned ActiveRels (instead of ActiveNodes).  For example, need some way to write:

    Course.where(title:"My Cool Title").routes.to_nodes

I think the latter is basically this, in Cypher:

    MATCH (n { title: "My Cool Title" })-[r:routes]->(c)
    RETURN r,c;

No clue how to do either with the gem.

**Comment by djvs** [comment]
2.2.0 :037 > me.resources(:c).license(:l).pluck(:c, 'collect(l)').count
 => 0 
2.2.0 :038 > me.resources.count
 => 31

**Comment by subvertallchris** [comment]
Don't know about the second part, on my phone and can't check right now. My
bad about the query, it's only going to return resources that have
licenses. You need to do an OPTIONAL MATCH in cypher to return those with
and without. We implement that using the 'optional' method, though I find
'query.proxy_as_optional" easier to use. Can't link right now but you can
find it in the specs. Can help you more tomorrow if you still need a hand.

**Comment by djvs** [comment]
OK, thanks

**Comment by djvs** [comment]
Yeah, the main problem now looks like trying to scope an object's relationships' end points -- not only by the relationship's type, but by the properties of the relationship.  More inaccurate pseudocode...

     course.routes.rel_where(accepted: true).to_nodes

Could even settle with the non-polymorphic:

     course.routes.rel_where(accepted: true).resources

Sorry to bother -  just getting stuck, been over the gem docs 10 times now.

**Comment by djvs** [comment]
Sorry, scratch last comment, solved already.

https://github.com/neo4jrb/neo4j/issues/702#issuecomment-76858867 This one is the one I still need help with.  Sorry to bother.

**Comment by djvs** [comment]
Sorry, scratch last comment, solved already.

https://github.com/neo4jrb/neo4j/issues/702#issuecomment-76858363 This one is the one I still need help with.  Sorry to bother.   Ugh, pain in the butt how this sends emails and you can't fix a mistake.

**Comment by djvs** [comment]
(wipes sweat off brow).  OK, got this far:

    Course.query_as(:c).match("c-[r:routes]-n").pluck(:r,:n).map{|x|[x.first,x.last]}.first

**Comment by subvertallchris** [comment]
You get a CypherRelationship when it doesn't correctly map the rel to the class. I see you're calling `type` in the rel model, so make sure `eager_load` is enabled in all environments within Rails. You still shouldn't need to jump through hoops to get that. Can't really help troubleshoot more tonight but I'll be around tomorrow for most of the day. Pop into our Gitter room if you want, https://gitter.im/neo4jrb/neo4j, one or both of us will be around.

**Comment by cheerfulstoic** [comment]
I'm going to close this because I agree gitter in the better place.

In regards to serialization, I agree it can become a nightmare.  One case for embedded that I found really useful in Mongo as an example was for orders, storing the product object on the order so that you can see what the state of the product was at the time (What was the title of the product at the time, what was the price, etc...).

At a former job we used ActiveRecord serialization for having a separate table that could store less important variables that weren't stored on ever user.  Of course with document-type databases like Neo4j and Mongo, that's not really a concern
