### ISSUE TITLE
find_by not working

### ISSUE THREAD

**Issue by LeKristapino** [neo4jrb/neo4j#705]
Already posted this on SOF: http://stackoverflow.com/questions/28889103/find-by-in-rails-with-neo4j-not-working

Hope that is ok.

**Comment by subvertallchris** [comment]
We have [specs in place](https://github.com/neo4jrb/neo4j/blob/41486a864cd42811bf283e9060c66a3a1cc1d6fd/spec/e2e/active_model_spec.rb#L420) that check `find_by` and I use it all the time without trouble. @cheerfulstoic and I used very similar code in a project we did together a few months ago.

```
def self.find_or_create_from_auth_hash(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_from_omniauth(auth)    
  end
```

Could you add some debugging info to your code, maybe have it out put the results of different pieces of it to find where it's breaking down? Maybe split it into separate methods and build some tests for it?

**Comment by LeKristapino** [comment]
def self.find_for_facebook_oauth(auth)
	    user_connection = self.find_by(provider:auth.provider, uid:auth.uid )
	    return auth.provider+','+auth.uid

**Comment by subvertallchris** [comment]
Try calling to_i on the uid when using find_by. It looks like it's giving
you a string?

**Comment by LeKristapino** [comment]
When trying to call to_i i get a TypeError

    no implicit conversion of Bignum into String

**Comment by LeKristapino** [comment]
Yes, it seems that the problem is something in the auth.uid, because with just the provider it returns an object

**Comment by LeKristapino** [comment]
I did a 

    auth.uid.class
and it returned String

then tried it with .to_i and worked just fine. Don't know what happened the first time.

Thank you

**Comment by LeKristapino** [comment]
Relationship problem is also solved. Thank you (answer- before I had a different type: set and it found that node first all the time, so it couldn't see any relationship with the new type)

**Comment by cheerfulstoic** [comment]
Glad to hear it's fixed!
