### ISSUE TITLE
Relation type as target model class name: excessive behavior?

### ISSUE THREAD

**Issue by garmoshka-mo** [neo4jrb/neo4j#708]
https://github.com/neo4jrb/neo4j/wiki/Neo4j-v3-Declared-Relationships#second-argument-is-a-symbol-that-sets-the-method-and-defaults-relationship-type-and-expected-object-class

By this message i see, that there probably already was some hot discussions about such behavior:

> Looks for constant Band These are only DEFAULTS, though. All can be overridden.

After long learning of docs, if found how to turn it off (model_class: false)

Though it really seems excessive (maybe even harmful) logic.
To understand - is this logic useful - need to answer on question:
## Can we show example, when it is useful?
Usually we want to have objects with constant classes,
because usually bottle - is always bottle, either it is "one of objects on the table",
or "find me objects, which can keep water".
## Though, if such example exists in real programming challenges
(when we need dynamic class for object, depending on from which source it was retrieved)
is it often case?
Seems like it is really rare case - then better to make this behavior configurable,
for example have option inherit_model_class_from_type: true
which is turned off by default.

**Comment by garmoshka-mo** [comment]
Or at least would be good to add global config option to turn off this behavior.
For now how to hotfix it with:

    class Application < Rails::Application

    # Fix default behavior of Associations
    Neo4j::ActiveNode::HasN::Association.class_eval do
      def target_class_option(options)
        if options[:model_class]
          "::#{options[:model_class]}"
        end
      end
    end

**Comment by subvertallchris** [comment]
This behavior is inspired by ActiveRecord, where relationships names hint at the class that is targeted.

```
class Customer < ActiveRecord::Base
  has_many :orders
end
```

This would look for an `Order` table, which would return Order objects. To _not_ have this as the default behavior would deviate from expectations, as far as I'm concerned.

Almost as important is the fact that the `model_class` option allows more precise filtering of related data.

```
has_many :out, :commented_posts, type: 'COMMENTED_ON', model_class: 'Post'
# (u)-[r1:COMMENTED_ON]->(p:Post)
```
...is different from...
```
has_many :out, :commented_objects, type: 'COMMENTED_ON', model_class: false
# (u)-[r1:COMMENTED_ON]->(p)
```
The first would be "match all posts that the user commented on," the second would be "match all objects that the user commented on," but they both use the same relationship type. It's a way of filtering more precisely.

**Comment by garmoshka-mo** [comment]
Thanx for explanations
