### ISSUE TITLE
Hard to find config options for gem

### ISSUE THREAD

**Issue by garmoshka-mo** [neo4jrb/neo4j#711]
https://github.com/neo4jrb/neo4j/wiki/Neo4j-v3-Unique-IDs#id_property-primary-key

> This can be done through Neo4j::Config, Rails configuration, or models themselves. For example see config/application.rb or model

Links are broken, and how to perform configuration stays big mystery, even search on google don't give results
Until goto source codes (/lib/neo4j/config/neo4j/config.yml)
So would be good to give URL at least to config yml
https://github.com/neo4jrb/neo4j/blob/master/config/neo4j/config.yml

**Comment by cheerfulstoic** [comment]
We've got new documentation that should cover this:

http://neo4jrb.readthedocs.org/en/5.2.x/Configuration.html

Please re-open if this is insufficient
