### ISSUE TITLE
How to delete Node?

### ISSUE THREAD

**Issue by garmoshka-mo** [neo4jrb/neo4j#714]
Nothing works:

    a.delete_all
    a.delete
    a.destroy

> NoMethodError: undefined method `delete' for #<Node:0xb9db6e38>

Also wasn't able to find in documentation

**Comment by cheerfulstoic** [comment]
`destroy` should work.  What sort of node is it?  Is it an `ActiveNode` model object or a `CypherNode` object?

**Comment by garmoshka-mo** [comment]
ah, sorry `destroy` works.

I was confused by old docs:
https://github.com/neo4jrb/neo4j/wiki/Neo4j::Rails-Persistence#destroy-and-delete
> p1.friends.find(p2).delete  # deletes p2 and the friend relationship

And wasn't able to find in new docs how to delete records.

**Comment by cheerfulstoic** [comment]
Sorry about the docs.  I think one of the next things I'd like to do it start moving the docs to readthedocs.org.  There it's clear what version is what.  Also, you can have two levels of navigation.  The GitHub wiki is just a bit more limiting.

We might even remove all of the v2 docs.  @subvertallchris waddaya think (no rush, I know you're on holiday ;)?

**Comment by subvertallchris** [comment]
I'm down for that. Still not sold on readthedocs.org but I'll follow your lead. ;-)

If nothing else, I think we should remove them from the sidebar or keep them on an old branch of the wiki.
