### ISSUE TITLE
difference between find_by() and where().first with one node to search for?

### ISSUE THREAD

**Issue by LeKristapino** [neo4jrb/neo4j#715]
Have two types of nodes- users and social_networks. Each user can have multiple soc. network nodes, but not with the same provider(facebook, linkedin, etc.)

The problem was that when I was trying to access soc. network token through user node it gave me the wrong one. 

I had this line which didn't seem to work:
user.social_network_connections.find_by(provider: 'facebook').token
It always returned the token of the "oldest" social_network node. not the particular user related node.

When I changed it to:
user.social_network_connections.where(provider: 'facebook').first.token

It started to work the way I expected.

Can somebody please explain to me is this the way it should be? And how are they different.

**Comment by subvertallchris** [comment]
`find_by` is essentially `where(condition).limit(1)`, which tells the database to find only one result. `where(condition).first` will return all matched results, put them into an enumerable, and give you the first one from Ruby. The order that matched results are returned is determined by the database's query plan and can often be unpredictable, as you're seeing, and it never makes guarantee of order unless you tell it to order by a property. If you need the oldest, you should do `where(condition).order(your_timestamp_property).limit(1).first`.

**Comment by LeKristapino** [comment]
Basically I have a situation where User ->has_one-> social_network(provider: 'facebook'). So it should not really matter which query I use, right? Since they both should return that single node. But somehow the find_by returned the oldest node there is( which was not really related to the 'user' node that the query was called on). I just want to understand this to not make similar mistakes again (or have unexpected queries in production)

**Comment by subvertallchris** [comment]
Ah, well I see your problem now: `find_by` is a class method that isn't intended for chaining on associations. Even though it will not raise an error when called like this, it won't work correctly. You should continue using `where` and only use `find_by` as a class method.

**Comment by LeKristapino** [comment]
Ok, now it's clear. Thanks for the info.

**Comment by cheerfulstoic** [comment]
It seems like this should work.  Re-opening so that we can track this as a bug.  Thanks for the report!

**Comment by subvertallchris** [comment]
If we change that `self` to an `all`, it should take care of it.

**Comment by cheerfulstoic** [comment]
Yup, good call ;)  I actually had changed that locally but didn't commit it because I wanted to make a spec first

**Comment by subvertallchris** [comment]
Brian fixed this one.
