### ISSUE TITLE
Does errors.add work for Neo4j::ActiveNode?

### ISSUE THREAD

**Issue by arikan** [neo4jrb/neo4j#718]
While checking for an error within the model, I want to add a specific message to the error (below is a simple check if user is already registered with the submitted email). But `errors.add`  somehow does not add, it does not thro any error, the message is just not added. 

I'd appretiate if you can point to something that might be missing or wrong here? 
 
```rb
class Invitation
  include Neo4j::ActiveNode
  property :token, type: String
  property :recipient_email, type: String 
  index :token
  index :recipient_email

  private 

  def recipient_is_not_registered
    puts "is already registered"
    errors.add(:recipient_email, 'is already registered') if User.find_by(:email => recipient_email)
  end
end
```

**Comment by subvertallchris** [comment]
Try `self.errors.add`, I seem to have used that in some code with a Neo4j project in the past.

You'll get better performance if you check for the presence of the user with `User.where(email: recipient_email).limit(1).empty?`. It runs a `count` in Cypher instead of returning a node.

**Comment by arikan** [comment]
Thanks for the tip Chris, 

So I  actually see the errors added.

```rb
errors.add(:recipient_email, 'is already registered') if User.where(email: recipient_email).limit(1).empty?
puts self.errors.full_messages
> Recipient email is already registered
```
...somehow can't display them via the controller:

```
format.html { redirect_to root_path, :notice => @invitation.errors.full_messages }
```

**Comment by arikan** [comment]
Ok did this instead, now it is fine. 
```
format.html { redirect_to root_path, notice: @invitation.errors.full_messages.join(",") }
```
