### ISSUE TITLE
How to find the latest dev release

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#719]
From the manual:
   
   rake neo4j:install[community-2.2.0-M02]

I saw on the Neo4j site that the 2.2.0-RC1 has been released but it's not available with the above command.
At the same time I try 2.2.0-M04, which succeded. 

So, which is the most recent version to download? Or where can I find a version list?

**Comment by subvertallchris** [comment]
It's 2.2.0-RC01. Needs the 0. I usually just look at the file that's downloaded from neo4j.com, there's no list that I'm aware of.

**Comment by pdipietro** [comment]
Gracias
