### ISSUE TITLE
How to update an existing relation's rel_type?

### ISSUE THREAD

**Issue by arikan** [neo4jrb/neo4j#722]
We've got a ton of undeclared relations between two nodes, and we'd like to update the type of the relation. But updating the `rel_type` throws the error below. What would be the way to update the type of an existing undeclared relation? 

```rb
node.rels(dir: :outgoing, type: "FRIEND").each do |rel|
    rel.rel_type = "BEST_FRIEND"
end
```

```
NoMethodError: undefined method `rel_type=' for CypherRelationship 124840:Neo4j::Server::CypherRelationship
```

Here we can `rel.destroy` and reconnect it, but it is too much of a hasle, and the what if the relation contains other properties that we don't want to loose, like datetime and weight information. 

```rb
node.rels(dir: :outgoing, type: "FRIEND").each do |rel|
    node.create_rel("BEST_FRIEND", rel.end_node)
    rel.destroy
end
```

I'd appretiate if you have any suggestions here.

**Comment by subvertallchris** [comment]
Can't do it. Neo4j does not allow you to change a relationship type. [This post](http://stackoverflow.com/questions/22670369/neo4j-cypher-how-to-change-the-type-of-a-relationship) offers a simple Cypher query that might help.

**Comment by arikan** [comment]
Thanks for your prompt message Chris, trying the Cypher update...

**Comment by subvertallchris** [comment]
Sorry that I can't be more help. The properties will be the trickiest part. You could do it pretty easily in Ruby with the `props` method.

```
node.rels(dir: :outgoing, type: 'FRIEND').each do |rel|
  node.create_rel('BEST_FRIEND', rel.end_node, rel.props)
  rel.destroy
end
```

**Comment by arikan** [comment]
Thanks Chris, got it. The ruby version is easier, also might be more performant because of the existing context. Otherwise with Cypher, I have to go match the actual node with its id, then make the changes etc.

**Comment by garmoshka-mo** [comment]
I had the same issue, also need to change destination of nodes in the runtime,
so had to implement own method to do this:

````
  def change_base(type=nil, from=nil, to=nil)
    type_str = self.type
    from_str = '(from {ID: a.ID})'
    to_str = '(to {ID: b.ID})'
    something_changed = false
      
    if !type.nil? and type_str != type.upcase
      type_str = type.upcase 
      something_changed = true
    end
    unless from.nil?
      from_str = '(from {ID: '+from.id.to_s+'})'
      something_changed = true
    end
    unless to.nil?
      to_str = '(to {ID: '+to.id.to_s+'})'
      something_changed = true
    end
        
    if something_changed         
      Neo4j::Session.query
              .match('(a)-[r {ID: '+self.id.to_s+'}]->(b)
                ,'+from_str+','+to_str+'
                CREATE (from)-[r2:'+type_str+']->(to)
                SET r2 = r
                WITH r, r2
                DELETE r
                WITH r2')
              .pluck('r2').first
    else
      self
    end
  end
````
