### ISSUE TITLE
*_rels methods no longer defined

### ISSUE THREAD

**Issue by posgarou** [neo4jrb/neo4j#726]
Due to a similar issue to the one responded to [here](https://github.com/neo4jrb/neo4j/issues/724#issuecomment-84990610), I recently upgraded from neo4j 4.1.4 (with neo4j-core (~> 4.0.0)) to the commits recommended there.

Before this upgrade, I had found and used the (undocumented, I think) auto-generated *_rel methods (e.g., if a user has_many associated_groups, then `user.associated_groups` of course returns the groups but `user.associated_groups_rels` used to return the relationships).

Was this feature removed intentionally, or did some recent change inadvertently prevent the creation of these methods?

**Comment by subvertallchris** [comment]
@cheerfulstoic recently refactored all the code that controls that. Not sure if something replaced it but you can use `each_rel`, `each_with_rel`, or assign an identifier and call `pluck` to return all rels instead.

**Comment by posgarou** [comment]
Thanks!  I often find `each_rel` and `each_with_rel` inconvenient, but I
didn't think about that with `pluck`--that's a handy way of solving it.
Much appreciated.
