### ISSUE TITLE
NoMethodError: undefined method `mapped_label_name' 

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#727]
Using the Neo4j browser, I got the following query which returns a triple

    match (n:User { email : "pfedi@iol.it" })-[r]-(p) return n,r,p;

While the same query with the rel type return an empty set.

    match (n:User { email : "pfedi@iol.it" })-[r:UserProfile]-(p) return n,r,p;

I got a Class User with the following relationship:

    class User
      include Neo4j::ActiveNode
      has_one   :out, :has_profile, rel_class: HasUserProfile   # Profile

And the corresponding UserProfile class  

    class UserProfile
      include Neo4j::ActiveNode
      has_one  :in,  :belongs_to, rel_class: HasUserProfile   # User
      ....
The HasProfile ActiveRel has been declared as

    class HasUserProfile
      include Neo4j::ActiveRel
      from_class  User
      to_class    UserProfile
      type 'has_profile'
    end

In rails, I got the following error

    pry(main)> p = User.first
    => #<User activated: true, activated_at: nil,  created_at: Tue, 17 Mar 2015 08:55:32 +0000, email: "pfedi@iol.it", first_name: "Paolo" >

but p.has_user_profile returns
    
    NoMethodError: undefined method `mapped_label_name' for HasUserProfile(created_at: DateTime,     updated_at: DateTime):Class
    from /home/pdipietro/.rvm/gems/ruby-2.1.5/gems/neo4j-    4.1.5/lib/neo4j/active_node/query/query_proxy.rb:85:in `query_as'

**Comment by cheerfulstoic** [comment]
A couple of things to check:

Firstly, you are calling `has_user_profile` on the user object (I think, you assigned the first `User` to the variable `p` in the previous example), but neither class has that association (there's just `has_profile` and `belongs_to`).

Also, you might need to specify the `model_class` on associations, even though the `rel_class` is specified.  I know @subvertallchris and I talked about that a while ago, but I don't know if that got addressed.

**Comment by subvertallchris** [comment]
Like Brian said, this won't work:

```
match (n:User { email : "pfedi@iol.it" })-[r:UserProfile]-(p) return n,r,p;
```

The rel type is defined as `has_profile`.

We never addressed the `model_class` thing. It's been on the to-do list but I always push it off in favor of working on something else. Maybe we can work it into the new release.

**Comment by pdipietro** [comment]
Ok, I make some order: 

    Class User
      has_one   :out, :has_user_profile, rel_class: HasUserProfile   # Profile

    class HasUserProfile
      include Neo4j::ActiveRel
      include CreatedAtUpdatedAt
      from_class  User
      to_class    UserProfile
      type 'has_user_profile'
    end   

    class UserProfile 
      has_one  :in,  :belongs_to, rel_class: HasUserProfile   # User

now, the following query runs nicely

    match (n:User { email : "pfedi@iol.it" })-[r:has_user_profile]-(p) return n,r,p;
But this one doesn't:
    
    [4] pry(main)> p = User.first
    [5] pry(main)> p.has_user_profile
    NoMethodError: undefined method `mapped_label_name' for HasUserProfile(created_at: DateTime, updated_at: DateTime):Class
    from /home/pdipietro/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.5/lib/neo4j/active_node/query/query_proxy.rb:85:in `query_as'

This is a subset of p.methods:
    :has_user_profile=,
    :has_user_profile_query_proxy,
    :has_user_profile_rel,
    :has_user_profile,

The question is: 
How do I access in Ruby the related node of a User if p.has_user_profile doesn't work?

**Comment by subvertallchris** [comment]
Set `model_class` here: `has_one   :out, :has_user_profile, rel_class: HasUserProfile   # Profile`. It needs to point to the node on the other end.

**Comment by pdipietro** [comment]
Sorry Chris, but I don't understand: this is an Active_rel, and the model on the other end is described into the relationship class as the to_class UserProfile.

Class HasUserProfile
  include Neo4j::ActiveRel
  include CreatedAtUpdatedAt
  from_class  User
  to_class    UserProfile
  type 'has_user_profile'
end   

Or not?

**Comment by subvertallchris** [comment]
This 

```
has_one :out, :has_user_profile, rel_class: HasUserProfile, model_class: 'Profile'
```

The association doesn't look at the ActiveRel model's `to_class` to figure out what kind of node it's supposed to return.

**Comment by subvertallchris** [comment]
Going to close this because I don't think there's anything to be done, but please reopen if I'm missing anything.
