### ISSUE TITLE
Ability to omit labels in Cypher generated by QueryProxy 

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#741]
Labels are only really needed in Cypher queries if you need to filter a match or force Cypher to use an index. Otherwise, you take a performance hit because the database has to examine every node to ensure it matches the given label. As evidenced by [Mark Needham's blog post](http://www.markhneedham.com/blog/2014/09/30/neo4j-genericvague-relationship-names/), you should use relationship types without labels to match when possible.

When you build a match using QueryProxy, it always uses labels.

```
Student.all.lessons.to_cypher
=> "MATCH (n:`Student`), n-[rel1:`ENROLLED_IN`]->(result_lessons:`Lesson`)"
```

If we always know that our `ENROLLED_IN` relationships go from `Student` to `Lesson`, we introduce a performance hit by including that second label. If you're chaining a few relationship types and need to filter a large number of nodes, this results in even bigger performance hits.

A workaround for this is to use `model_class: false` in the association, but that breaks QueryProxy's method chaining. The simplest solution might be another option, `match_with_label: false`, which would control the behavior when building the Cypher string.

**Comment by cheerfulstoic** [comment]
Also, do we know if this is still a performance issue in Neo4j 2.2?

**Comment by subvertallchris** [comment]
As far as I can tell. The profiler indicates it still tries to filter all nodes based on given labels.

**Comment by cheerfulstoic** [comment]
So to clarify, this would be an option that you would specify on associations or in the chain?  I can imagine following the same relationship type but them pointing to multiple labels, so I think it would need to be an optimization that the user makes on a case-by-case basis

**Comment by subvertallchris** [comment]
I think so, yes. I figure that you usually make that decision when you're writing each query anyway, so it makes sense to handle it as part of the chain. That's really the thing that I think needs the most thought. What should it look like? `user.friends(node: node, rel: rel, labels: false)`? Guess there aren't really a lot of options.

**Comment by subvertallchris** [comment]
This was in 5.0.0.
