### ISSUE TITLE
Make sure that you can easily do `count` calls on QueryProxy objects

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#747]
Don't remember the status of this, but just thought about it

**Comment by subvertallchris** [comment]
https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/query/query_proxy_methods.rb#L20 should cover that.

**Comment by cheerfulstoic** [comment]
Ah, interesting...  I actually feel like it would be better if we could do this instead:

```ruby

  query_proxy.count # Does a `count(*)`

  query_proxy.count('column') # Does a `count(identity.column)`

  query_proxy.count('DISTINCT column') # Does a `count(DISTINCT identity.column)`
```

Though I'm realizing we'd need to do a bit of parsing to check on the `DISTINCT`, but I don't think it would be too bad.  Maybe this is just a matter of the arguments being switched...

**Comment by subvertallchris** [comment]
I wouldn't mind switching the argument order, especially if it saves a string parse. When I added this, I was way more interested in having access to `DISTINCT` than specifying the target, but I feel like that's totally subjective. We usually do target first, then modifiers, so maybe going the other way would be better.

**Comment by cheerfulstoic** [comment]
Made a change on `query_proxy_count`.  I added a `count_distinct` method which gives a count of the `target` `DISTINCT`ed.  I also changed the `count` method to just pass the argument down (but use the identity if nothing is specified).  What do you think?
