### ISSUE TITLE
Compatibility problem with neo4j's relationships property as array

### ISSUE THREAD

**Issue by arikan** [neo4jrb/neo4j#748]
Neo4j allows storing arrays of same type in relationships properties. 
http://neo4j.com/docs/stable/rest-api-property-values.html

However in neo4jrb, although we can set and get a rel's property as array...
```rb
node.rels(dir: :outgoing).each do |rel|
   rel[:some_ids] = ["id1", "id2"]
   puts rel[:some_ids]
end

id1
id2

```
... updating the property array overwrites the value:

```rb
rel[:some_ids] << "id3"
puts rel[:some_ids]

id3
```

As a temporary solution, we copy the existing property to a new array, update and to set it: 
```rb
some_ids = rel[:some_ids].to_a
some_ids << "id3"
rel[:some_ids] = some_ids
puts rel[:some_ids]

id1
id2
id3
```

It would be more compatible to be able to update the property array directly.

**Comment by subvertallchris** [comment]
This is a known issue that other libraries also deal with, ActiveRecord
included, if I remember correctly. Fixing it isn't on the roadmap unless
someone is feeling really ambitious.

**Comment by arikan** [comment]
I see, just a note, the same issue exists on serialized properties (when we want to store a hash in the property), we need to do string-to-json and json-to-string back.

**Comment by subvertallchris** [comment]
Found a little workaround for this that's a bit better than creating a new array every time. From [ActiveRecord::Dirty's docs](http://apidock.com/rails/ActiveRecord/Dirty):

```
  person.name_will_change!
  person.name << 'by'
  person.name_change    
```

Gonna close this issue since there's nothing for us to do here.
