### ISSUE TITLE
 Cannot perform schema updates in a transaction that has performed data updates. (Neo4j::Server::CypherResponse::ResponseError)

### ISSUE THREAD

**Issue by StaymanHou** [neo4jrb/neo4j#749]
Get the following error when testing with cucumber:
```
Cannot perform schema updates in a transaction that has performed data updates. (Neo4j::Server::CypherResponse::ResponseError)
      ./app/models/video_category.rb:2:in `include'
      ./app/models/video_category.rb:2:in `<class:VideoCategory>'
      ./app/models/video_category.rb:1:in `<top (required)>'
      ./app/controllers/admin/video_categories_controller.rb:7:in `index'
      ./features/step_definitions/web_steps.rb:2:in `/^I click "(.*?)"$/'
      features/video_category_manage.feature:17:in `When I click "Video categories"'
```

The VideoCategory model:
`app/models/video_category.rb`
```ruby
class VideoCategory
  include Neo4j::ActiveNode

  property :name, type: String
  property :hide, type: Boolean, default: false
end
```
This feature step is simply click the link for video_category#index. Although I get this error during the cucumber test, it can render the page in the development environment without any error.

Environment:
Ubuntu 14.04
RVM 1.26.10
Ruby 2.2.0p0
Rails 4.2.0
neo4j 4.1.5
neo4j-core 4.0.5
cucumber 1.3.19
Java 1.7.0_75 OpenJDK

**Comment by subvertallchris** [comment]
Enable `eager_load` in your test environment and it should take care of that. Alternatively, call the `VideoCategory` constant somewhere before your first test starts.

**Comment by StaymanHou** [comment]
Thanks. The error has gone by setting the `eager_load` to `true` in my test environment. I think it would be great to mention it somewhere in the documentations.

**Comment by subvertallchris** [comment]
It's mentioned in a few places, though I can't remember where at the moment. I'll add it to the setup section.
