### ISSUE TITLE
Disallow creation of relationships with `both` associations?

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#750]
I think this is just going to lead to confusion.  I remember discussing it in the past, but I don't remember the line of thought.  @subvertallchris what do you think?

This came up on this SO question:

http://stackoverflow.com/questions/29518353/using-has-many-both-in-neo4j-rb/29518687#29518687

**Comment by cheerfulstoic** [comment]
Should probably also give a message explaining this

**Comment by bswinnerton** [comment]
I'll be the first one to say that I was the one to be confused (and opened the StackOverflow question) :smile:, I like this functionality:

```ruby
class GeneralAssemblyAccount
  include Neo4j::ActiveNode

  has_many :both, :connections,
    model_class: 'User',
    type: 'connection',
    unique: true

  has_many :in, :followers,
    model_class: 'User',
    type: 'connection',
    unique: true
end
```

```ruby
user_one = User.create
user_two = User.create
user_one.followers = [user_two]
```

Gives us:

![screen shot 2015-04-22 at 11 09 22 am](https://cloud.githubusercontent.com/assets/934497/7277803/07468b04-e8e0-11e4-9ee2-3fe390b19954.png)

And then,

```ruby
user_two.followers = [user_one]
```

Creates two, inefficient, edges:

![screen shot 2015-04-22 at 11 10 13 am](https://cloud.githubusercontent.com/assets/934497/7277823/22f4de3c-e8e0-11e4-81d1-d1a370b83f89.png)

Whereas if you do the assignment via the `both` setter:

```ruby
user_one = User.create
user_two = User.create
user_one.connections = [user_two]
user_two.connections = [user_one]
```

Only leaves one edge:

![screen shot 2015-04-22 at 11 11 49 am](https://cloud.githubusercontent.com/assets/934497/7277882/5df8bea4-e8e0-11e4-86f9-62ef69630301.png)

This is especially helpful when iterating over a set of users and trying to connect them all to one another.

**Comment by subvertallchris** [comment]
Using `=` with the `both` setter is going to delete all existing relationships before it's created. The `=` operator always starts with a Cypher `MATCH/DELETE`, it is effectively a "replace" operator whereas `<<` is a simple "create." Since `both` matches without direction, its initial delete task clears out everything regardless of direction, so you're always left with only one relationship.

**Comment by bswinnerton** [comment]
Perhaps it's just my scenario, but that's exactly the desired result @subvertallchris.

**Comment by subvertallchris** [comment]
I completely missed the "I like this functionality" line! Haha!

**Comment by bswinnerton** [comment]
:smile:. This functionality is _fantastic_ for when you're trying to connect an array of users to one another, all while maintaining the minimum set of edges.

I'd love for it to stick around!

**Comment by subvertallchris** [comment]
That's really interesting and very cool. I never thought of using `=` with `both` as a way of forcing that behavior!

**Comment by bswinnerton** [comment]
For posterity's sake. Using a `both` as a setter was the end result of [this](http://stackoverflow.com/questions/29781450/proper-way-to-set-up-friends-bidirectional-relationship-in-neo4j-rb/29786607) StackOverflow question.

**Comment by subvertallchris** [comment]
Awesome! We should make sure that always occurs within a transaction. I don't think it does.

**Comment by cheerfulstoic** [comment]
That's a really good point, I never thought about how the match would match either and thus keep just the one relationship.  I feel like that should be documented well

**Comment by subvertallchris** [comment]
I think we can close this since we're going to let `both` stick around. Please let me know if anything was missed.
