### ISSUE TITLE
translation missing: en.neo4j.errors.models.any_model.attributes.any_attribute.taken

### ISSUE THREAD

**Issue by ernestoe** [neo4jrb/neo4j#759]
I'm using simple_form in my project and every time that the uniqueness constraint is violated in an attribute, I get a "translation missing" error similar to the one in the issue title. Just replace the `any_model` model and the `any_attribute` attribute with the proper ones.

Being familiar with i18n, I don't think the proper way to handle is with specific messages for every model - field combination that requires to be unique, but actually making sure a default message exists for all cases.

I'm not sure if this is specific to the simple_form usage or if it can be replicated elsewhere.

Researching on this I came to a similar issue that was raised in the neo4j-devise gem which had the following comment:

> I think that the issue might be that in the Rails-specific ActiveRecord-like part of neo4j, it's trying to mimic the way ActiveRecord handles internationalisation and localisation, but is not conforming to the complete spec maybe?

> The way ActiveRecord localisation works is it looks for translation keys starting with the most detailed ("en.neo4j.errors.models.user.attributes.email.taken") and then works backwards if keys are blank until it would reach the top level ("en.errors.messages.taken").

> So the quick fix would be: Add the full translation key ("en.neo4j.errors.models.user.attributes.email.taken") to @johannesE's project (because adding the full key to devise-neo4j would only work if the model is always going to be named, 'User').

> The 'proper' fix would be: Alter the neo4j gem so it handles translations in that fallback way like ActiveRecord does.

Is this something that can be properly addressed in the neo4j gem?

**Comment by cheerfulstoic** [comment]
Sorry for missing this issue!

I'm not sure about the localization stuff, but I believe that simple_form has a number of places that are very tied to `ActiveRecord`.  See here:

https://github.com/plataformatec/simple_form/issues/268

https://github.com/plataformatec/simple_form/pull/281

@subvertallchris and I have had good luck using client-side tools like Angular/Ember/React/Backbone/Rivets/etc... because a lot of the things that we build with Neo4j are more complicated because it's working at a higher level than simple CRUD, but obviously that takes more work and I don't know what your usecase is.

Maybe formtastic would work somewhat better?

http://stackoverflow.com/questions/4215239/formtastic-alternative-that-works-well-with-mongoid

**Comment by ernestoe** [comment]
Thanks Brian.

Actually I was able to solver the issue by using

````yaml
en:
  errors:
    messages:
      taken: "would create a duplicate %{attribute}"
````
as a default fallback message in my <code>en.yml</code> file . After reading the other thread comments decided to post it here in case the recommended fix makes sense, i.e.

> The 'proper' fix would be: Alter the neo4j gem so it handles translations in that fallback way like 
> ActiveRecord does.

however I'm aware that both devise & simple_form are plataformatec's gems and thus very tied to active record. Please close the issue if the fix doesn't make sense for neo4jrb .

In any case I'll be doing some tests with formtastic in order to review if it's better suited for ActiveNode. Can you please point to some **emberjs** examples ?

**Comment by cheerfulstoic** [comment]
My only real example of using emberjs is this:

https://github.com/neo4jrb/neo4j-meta_model

It's a bit odd because it's a Rails engine in a gem and it's all about modeling models using models (hence 'meta_model' ;)

**Comment by cheerfulstoic** [comment]
I don't think we have any i18n stuff in this gem.  Maybe we should, but I'm going to close for now

**Comment by jonblack** [comment]
I get the same error message when I add the following constraint to a model:

```
validates :email, uniqueness: true
```

I'm migrating from mongo which also uses [ActiveRecord validation](http://guides.rubyonrails.org/active_record_validations.html#uniqueness) and by default returns "is already taken". The translations used by mongid are [here](https://github.com/mongodb/mongoid/blob/master/lib/config/locales/en.yml).

I think it would be nice for neo4jrb to include English translations as well. I suppose you could (maybe) copy the file from mongoid.

**Comment by jonblack** [comment]
To work around this error for Sinatra you need to install the `i18n` gem and load your own translations from `config/locales`:

```
I18n.load_path << Dir[File.join(File.dirname(__FILE__), 'config', 'locales', '*.yml')]
```

My translation file looks like this:

```
en:
  errors:
    messages:
      taken: "is already taken"
```

I'd personally like to see some English translations. I'm porting code from mongoid to neo4j, and the mongoid gem includes some by default.
