### ISSUE TITLE
`replace_with` method should happen within a transaction

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#766]
Since it's an n+1 (or more) query, it can potentially leave the database in an inconsistent state if if the initial delete is successful but the create fails.

https://github.com/neo4jrb/neo4j/blob/5c960c12ed4f1633bdbbf9c6b2987ffe7e80a619/lib/neo4j/active_node/query/query_proxy_methods.rb#L116

**Comment by cheerfulstoic** [comment]
:+1:
