### ISSUE TITLE
Problem with a class property named :type

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#772]
Hi all,
There is a strange error I cannot understand: 
I had a class with some attributes. Then I removed 2 of these boolean attributes and replaced by a text one named 'type'.
On the db side (console, etc) everything runs fine, but, when I go to display the attribute content in the view, it has always the same value, which differs from the one in the db.
If I change the value in a UI, it changes on the DB, but shows incorrect in the UI when I reopened.

I didn't made any 'migration', just removed by hand all the old attributes.

What did I have missed?

**Comment by subvertallchris** [comment]
Can you post some code and console output examples?

**Comment by pdipietro** [comment]
Chris, I was just cancelling the issue. It was my fault: An hidden = instead of ==.
Sorry to have disturbed you for nothing, ant thank you for your usual availability !
Paolo
