### ISSUE TITLE
How to implement return distinct?

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#776]
Hi all,

I have the following query_string:
`(user:User)-[p:participates|owns|admins]->(g:Group { uuid : 'b68fbf69-aabb-4755-890d-ba97ee6c3e02' }) `

I use it in the following way:
`@users = Neo4j::Session.query.match(query_string).proxy_as(User, :user).paginate(:page => first_page, :per_page => secondary_items_per_page, return: "distinct user", order: "user.last_name asc, user.first_name  asc")`

but the return clause doesn't eliminate duplicates.

I tried other ways to use the distinct keyword, but with no success.

Can you help.

Thank you.

**Comment by subvertallchris** [comment]
Try throwing a `WITH DISTINCT` in there to clean it up before it gets to the end. Also, make sure you get the results you're looking for in the Neo4j web browser before moving it into Ruby.

**Comment by pdipietro** [comment]
I tried a lot of variations with `with distinct` but with no result.
Here is the code and the result, and I saw 2 starnge things:
1) there is no distinct clause in the query
2) there are 2 queries .... in the wrong order

    puts "Query: #{query_string}"
    @users = Neo4j::Session.query.match(query_string).proxy_as(User, :user).paginate(:page => first_page, :per_page => secondary_items_per_page, return: "user with distinct",order: "user.last_name asc, user.first_name  asc")
    puts "Count: #{@users.count}"

and this is the console output

    Query: (user:User)-[p:participates|owns|admins]->(g:Group { uuid : 'b68fbf69-aabb-4755-890d-ba97ee6c3e02' }) 
     CYPHER 5ms MATCH (user:User)-[p:participates|owns|admins]->(g:Group { uuid : 'b68fbf69-aabb-4755-890d-ba97ee6c3e02' }) , (user:`User`) WITH user as user RETURN COUNT(user)
     CYPHER 7ms MATCH (user:User)-[p:participates|owns|admins]->(g:Group { uuid : 'b68fbf69-aabb-4755-890d-ba97ee6c3e02' }) , (user:`User`) RETURN user ORDER BY user.last_name asc, user.first_name  asc SKIP {skip_0} LIMIT {limit_25} | {"skip_0"=>0, "limit_25"=>25}
    Count: 2

**Comment by pdipietro** [comment]
![cattura](https://cloud.githubusercontent.com/assets/3890316/7443657/8af00fcc-f15d-11e4-91a7-39ac1b25aae0.JPG)

**Comment by pdipietro** [comment]
![cattura](https://cloud.githubusercontent.com/assets/3890316/7443725/e59c5008-f161-11e4-86c8-88527ef03d94.JPG)

**Comment by subvertallchris** [comment]
Are you using https://github.com/neo4jrb/neo4j-will_paginate_redux? The `return` option is specified there, it's ignored entirely in Paginated module here.

**Comment by pdipietro** [comment]
Please, I moved this to the https://github.com/neo4jrb/neo4j-will_paginate_redux issue, but it seems nobody is looking at those issues .....

**Comment by subvertallchris** [comment]
I'll check it out today.
