### ISSUE TITLE
The default attribute does not seem to work anymore

### ISSUE THREAD

**Issue by drouchy** [neo4jrb/neo4j#783]
Hi,

My application is configure to use the gem from github.

I've got a class defined as below

```ruby
class MyClass
  include Neo4j::ActiveNode
  property :api_version,                  default: ‘2.1’
end
```

Before, when I was using the gem with the git sha1 1002bed268952e5c811e685fc4f351fb414a433b, it was working as expected

```ruby
irb(main):001:0> MyClass.new.api_version
=> "2.1"
irb(main):002:0> 
```

and since I upgraded the gem version to use the sha1 5fab265f490ca4d570b186ab7f72341f8420899a, I've got

```ruby
irb(main):001:0> MyClass.new.api_version
=> nil
irb(main):002:0> 
```

As you can see the default value is not set

Cheers,

David

**Comment by subvertallchris** [comment]
This broke a week or two ago and the patch just went in yesterday, but it doesn't set the default properties until you call `save`. The behavior was controlled by https://github.com/cgriego/active_attr and we weren't testing it at all locally, so I wasn't entirely sure how it behaved or if it would matter. I can probably patch that for you if the change is causing a problem.

**Comment by cheerfulstoic** [comment]
I believe that @drouchy is on a branch, so maybe master hasn't been merged into that branch since this change went in?

**Comment by drouchy** [comment]
@cheerfulstoic no, we are now using the master branch

@subvertallchris the new behaviour breaks our code at the moment. When we receive a new request, we build a new object, as some attributes are optional, we merge with the default values and only then check if the object is valid?

Cheers,

David

**Comment by subvertallchris** [comment]
Ok. I'll check it out this morning, I have an idea of how it can be fixed.

**Comment by subvertallchris** [comment]
@drouchy Would you mind checkout out the branch and PR I just pushed? I changed where the default properties are mixed in, so they'll be set during `initialize` instead of during `save`. Behavior matches what the dependency was doing when it was in control.

**Comment by subvertallchris** [comment]
Merged just now, let me know if something isn't right.

**Comment by drouchy** [comment]
@subvertallchris the behaviour has been restored.

Thanks you very much for the quick fix.

David
