### ISSUE TITLE
how to correctly define MyErrorClass on Transaction rescue

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#784]
Hi all,
I need a kick to correctly use transactions.

My question is how to declare/describe `MyErrorClass` to include only transaction or neo4j errors, avoiding to rescue all the other standard errors from rails and other components.

In other words, please, provide us a short sample of a correct MyErrorClass ;-)

I didn't find anything on the wiki nor on the internet. 

By the way, the following links from the transaction page on the wiki appear to be broken:

    API
    Neo4j::Transaction class YARD
    Neo4j::Transaction instance YARD
    Neo4j::Transaction Core Wiki

**Comment by cheerfulstoic** [comment]
I'm not sure that I'm clear on what you're looking for.  We don't raise any transaction errors specifically.  If you're running in server mode, a `Neo4j::Session::CypherError` error is raised from queries where something was wrong on the server.  If any exception happens inside of a transaction and bubbles up out of the transaction block (if you're using a block) then the transaction will rollbar

**Comment by pdipietro** [comment]
Can yoy tell me if, by your experience, the following function is correct? 
My concern is about the generic `rescue => e` which doesn't specialize the exception catching

      def create
        @group = Group.new(group_params)

        respond_to do |format|
          begin
            tx = Neo4j::Transaction.new
              @group.save
              rel = Owns.create(from_node: current_user, to_node: @group)
              rel = BelongsTo.create(from_node: @group, to_node: current_social_network)
            rescue => e
              tx.failure
              format.js   { render :new, object: @group }
              format.html { render :new }
              format.json { render json: @group.errors, status: :unprocessable_entity }
            ensure
              tx.close
              format.js   { render partial: "enqueue", object: @group, notice: 'Group was successfully created.' }
              format.html { redirect_to(request.env["HTTP_REFERER"]) }
              format.json { render :show, status: :created, location: @group }
          end
       end
    end

**Comment by subvertallchris** [comment]
Unless you're trying to catch a specific error raised by the gem, you can rescue from whatever exception classes that you'd look for if Neo4j wasn't involved. I usually try to check for the errors that I think are possible or likely before entering the transaction ("Does everything validate?" "Are these objects in the expected states, have the expected/required properties, etc,...?") so I can notify the user of an error state without a `rescue`.

**Comment by pdipietro** [comment]
I agree with your point of view: in my example, after the creation of a @group node, i need to create two relationships with the new node itself and if, for any reason, the creation of one or both the relationships should fail, I need to rollback tha entire transaction.

But,  while with the @group.save any check returns me back an error message on the user interface (a property is missed, a required value is not present, or is invalid and so on), How can I return an error as 'Owns create relationship failed' or 'BelongsTo create relationship failed'???


By the way, can you give an extra look at #776, because It fails for me ;-)

**Comment by cheerfulstoic** [comment]
I would say definitely try to rescue from specific exceptions rather than a general `rescue`.  Testing use cases can help with this somewhat.  Also generally in my experience from ActiveRecord creating methods on your model which deal with transactional cases is good because transactions are, IMO, a model-concern.

Also, your case here seems like a good case for using `after_save` callbacks.  @subvertallchris do you know if our callbacks are run inside of transactions?  If not, they should be, I think.  Then you wouldn't need to worry about transactions at all.  You would just need to check if the `save` succeeded.

**Comment by subvertallchris** [comment]
Yep, all callbacks occur within transactions.
