### ISSUE TITLE
How to create multiple named time trees?

### ISSUE THREAD

**Issue by chrisgogreen** [neo4jrb/neo4j#788]
How would I achieve multiple named times trees. If I wanted one time tree to manage work schedules, another time tree to manage deliveries, another time tree to track user actions and events, is there a way to implement this with Neo4jrb? Or maybe it's best to set these tree's up once manually and not manage them through the neo4jrb api?

**Comment by subvertallchris** [comment]
You could do it with Neo4j.rb but I wouldn't. Check out GraphAware's
Timetree plugin, then maybe create a class in your app that makes it easy
to interact with its REST API. https://github.com/graphaware/neo4j-timetree

**Comment by subvertallchris** [comment]
Hey @chrisgogreen, I'm gonna close this but let me know if there's anything else we can do here.
