### ISSUE TITLE
Hunt down behavior that should be moved to property classes

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#791]
Anything that registers indexes or constraints comes to mind.

**Comment by cheerfulstoic** [comment]
@subvertallchris Hey, I'm not quite sure what this is all about, but codetriage pointed me to it ;)  I know you were going to work on index/constraint stuff soon, though

**Comment by subvertallchris** [comment]
It's part of what I'm working on, I'll fill you in through chat tomorrow.

**Comment by cheerfulstoic** [comment]
double :metal:

**Comment by subvertallchris** [comment]
But don't get me wrong, you're more than welcome to dive in. :-D

I have a short to-do list related to indexing, some light refactoring,
and fixing an inheritance bug. _This_ issue is just a reminder to find
property management logic and move it if needed/possible.

**Comment by subvertallchris** [comment]
Eeeeh I'm going to close this out. It's always a work-in-progress but we're looking much better.
