### ISSUE TITLE
DRY Refactoring RE: class label/type names

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#792]
There's some duplication that should be moved to the Shared module but I'm too wiped out to make it really nice tonight.

**Comment by cheerfulstoic** [comment]
Triaging this one.  Did this eventually get taken care of?

**Comment by subvertallchris** [comment]
I've started it, just need some time to finish it up.

**Comment by cheerfulstoic** [comment]
Fair enough!  I've been using codetriage.com to point me at a random issue from `neo4j` and `neo4j-core` every day so that we can keep our plates spinning on their poles ;)

**Comment by subvertallchris** [comment]
This is done.
