### ISSUE TITLE
Relations has_many :out not return result

### ISSUE THREAD

**Issue by JeremyPinhel** [neo4jrb/neo4j#813]
Hi,

I have some problem when I try to get companies link to my node user. I use the gem with Rails 4.2

``` ruby
class Graph::User
  include Neo4j::ActiveNode

  property :ext_id, type: Integer, constraint: :unique, index: :exact

  property :email, type: String, index: :exact

  has_many :out, :companies, type:'work_with', model_class: 'Graph::Company'
end

class Graph::Company
  include Neo4j::ActiveNode

  property :ext_id, type: Integer, constraint: :unique, index: :exact

  property :name, type: String, index: :exact

  has_one :in, :creator, type: 'founder', model_class: 'Graph::User'
end
```
When I try to get companies of user:
 `user.companies`

The result return:
`#<Neo4j::ActiveNode::Query::QueryProxy:0x007fcc73854b60 @model=Graph::Company(country: String, ext_id: Integer, name: String), @association=#<Neo4j::ActiveNode::HasN::Association:0x007fcc7c9521a8 @type=:has_many, @name=:companies, @direction=:out, @target_class_name_from_name="Company", @target_class_option="::Graph::Company", @callbacks={:before=>nil, :after=>nil}, @origin=nil, @relationship_class="Graph::WorkWith", @relationship_type=nil, @dependent=nil, @unique=nil, @target_class_name="::Graph::Company", @target_class_name_or_nil="::Graph::Company">, @context="Graph::User#companies", @options={:session=>Neo4j::Server::CypherSession url: 'http://graphdb:7474/db/data/' version: '2.2.1', :start_object=>#<Graph::User email: "", ext_id: 1>, :node=>nil, :rel=>nil, :optional=>nil, :caller=>#<Graph::User email: "", ext_id: 1>}, @node_var=nil, @rel_var=:rel0, @session=Neo4j::Server::CypherSession url: '' version: '2.2.1', @caller=#<Graph::User email: "", ext_id: 1>, @chain_level=nil, @chain=[], @starting_query=nil, @optional=nil, @params={}>`

I don't understand what I did wrong.

**Comment by cheerfulstoic** [comment]
That's a `QueryProxy` object which is what you're supposed to get.  You can call `#to_a` on it like this:

    user.companies.to_a

Or iterate over it (with `each`, `map`, `select`, etc...) to work with the results.

You might also try the new release candidate (`5.0.0.rc.2`) which returns `AssociationProxy` objects and which gives a somewhat clearer output on the console.

**Comment by JeremyPinhel** [comment]
ok thank you !

**Comment by subvertallchris** [comment]
In the new RC, you can also set config options to deal with that namespacing.

```
Neo4j::Config[:association_model_namespace] = 'Graph'
```

That'll add `Graph` to all models in associations so you can remove the `model_class` call when association name matches model name.

```
Neo4j::Config[:association_model_namespace] = 'Graph'
# will look for Graph::Company
has_many :out, :companies, type: 'work_with'
```

**Comment by subvertallchris** [comment]
You also don't need both the index and constraint. A constraint is a type of index. :-)
