### ISSUE TITLE
single element array property returns as string

### ISSUE THREAD

**Issue by artsince** [neo4jrb/neo4j#814]
I am trying to create a relationship with a property of Array type. It looks like when the array has one element, the rel property returns as a String. Please check the sample console output.

```
2.1.2 :010 > first.rels(between: second).count
 => 0 
2.1.2 :011 > my_arr = ["arr"]
 => ["arr"] 
2.1.2 :012 > rel = first.create_rel("FOLLOWS", second, :my_prop => my_arr)
 => CypherRelationship 18315 
2.1.2 :013 > rel[:my_prop]
 => "arr" 
2.1.2 :014 > my_arr_2 = ["val1", "val2"]
 => ["val1", "val2"] 
2.1.2 :015 > rel2 = first.create_rel("FOLLOWS_2", second, :my_prop => my_arr_2)
 => CypherRelationship 18316 
2.1.2 :016 > rel2[:my_prop]
 => ["val1", "val2"] 
2.1.2 :017 > first.rels(between: second).count
 => 2
```

I am using the latest neo4j gem
  * neo4j (5.0.0.rc.2 72320a3)
  * neo4j-core (5.0.0.rc.2 6403516)
  * neo4jrb-paperclip (0.0.3 e70f1f9)

Can you reproduce this? is this the expected behavior?

**Comment by artsince** [comment]
I actually can't reproduce this when I start a project from scratch, using the instructions on the wiki
>  rails new myapp -m http://neo4jrb.io/neo4j/neo4j.rb -O

```
2.1.2 :026 > user
 => #<User email: "ahmet@test.com", name: "ahmet"> 
2.1.2 :027 > user.rels.count
 => 0 
2.1.2 :028 > rel = user.create_rel('FRIENDS_WITH', burak, :prop => arr)
 => CypherRelationship 0 
2.1.2 :029 > rel[:prop]
 => ["some_value"] 
2.1.2 :030 > rel[:prop].is_a?(Array)
 => true 
2.1.2 :031 > arr
 => ["some_value"] 
2.1.2 :032 > arr.is_a?(Array)
 => true 
```
Notice that neo4j version is different:
 * neo4j (4.1.5)
 * neo4j-core (4.0.7)

**Comment by artsince** [comment]
updating the Gemfile to the latest version of neo4j, I am able to reproduce the error with a new project, as well.

```
2.1.2 :002 > User.all.count
 => 0 
2.1.2 :003 > first = User.new(:name => "ahmet", :email => 'ahmet@test.com')
 => #<User email: "ahmet@test.com", name: "ahmet"> 
2.1.2 :004 > first.save
 => true 
2.1.2 :005 > second = User.new(:name => "burak", :email => 'mehmet@test.com')
 => #<User email: "mehmet@test.com", name: "burak"> 
2.1.2 :006 > second.save
 => true 
2.1.2 :007 > my_arr = ["my_val"]
 => ["my_val"] 
2.1.2 :008 > rel = first.create_rel("FOLLOWS", second, :my_prop => my_arr)
 => CypherRelationship 0 
2.1.2 :009 > rel[:my_prop]
 => "my_val" 
```

  * neo4j (5.0.0.rc.2 72320a3)
  * neo4j-core (5.0.0.rc.2 6403516)

**Comment by cheerfulstoic** [comment]
Very interesting find, I'll take a look!

**Comment by cheerfulstoic** [comment]
Looks like it was a pretty simple fix.  Could you try adding this in your `Gemfile`?

    gem `neo4j-core`, github: 'neo4jrb/neo4j-core', branch: '814_fix'

That branch is running the specs on Travis now.  If they pass I'll merge and cut a `rc.3`

**Comment by artsince** [comment]
it seems to work with 814_fix

```
2.1.2 :005 > first.rels(between: second).count
 => 0 
2.1.2 :006 > my_arr = ["val"]
 => ["val"] 
2.1.2 :007 > rel = first.create_rel("FOLLOWS", second, :my_prop => my_arr)
 => CypherRelationship 18317 
2.1.2 :008 > rel[:my_prop]
 => ["val"]
```

  * neo4j (5.0.0 61955c6)
  * neo4j-core (5.0.0.rc.2 dd1da46)
  * neo4jrb-paperclip (0.0.3 e70f1f9)

I will update the bundle after the PR merge. Thanks a lot.

**Comment by subvertallchris** [comment]
What was it? On my phone with lousy connection so I can't check code but
I'm really curious!

**Comment by subvertallchris** [comment]
Good catch!

**Comment by cheerfulstoic** [comment]
I changed `set` to `set_props`.  I feel like this probably shouldn't be a problem with `set` though, so now I'm feeling guilty that I didn't do a thorough job.  I'll see if I can do that in a bit.  Also JRuby failed on Travis CI because I implemented this fix for CypherNode but not EmbeddedNode (fortunately I put the failing test in the shared spec! ;)

**Comment by cheerfulstoic** [comment]
Just updated `neo4j-core` to `5.0.0.rc.3`, so you should be able to remove that line from your `Gemfile` now.  I'm going to keep this open until I figure out the `set` / `set_props` issue, but it should work for you now

**Comment by artsince** [comment]
@cheerfulstoic thanks a lot.

**Comment by dam13n** [comment]
Thanks for getting this update in!

**Comment by cheerfulstoic** [comment]
No problem ;)
