### ISSUE TITLE
Weird relationship behaviour with 5.0.0.rc2

### ISSUE THREAD

**Issue by drouchy** [neo4jrb/neo4j#818]
Hi,

We are trying to use the latest RC of the gem with an old project, and we have some regressions.

we have a class defined like so

```ruby
class OneClass
  include Neo4j::ActiveNode
  # some properties

  has_many :out, :contains, type: :contains
end
```

the first load the nodes always fail, and the next one succeed

```shell
be irb
starting neo4j
building session for embedded_db db
Start embedded Neo4j db at db/development
irb(main):001:0> OneClass.first
ArgumentError: The 'type' option must be specified( even if it is `nil`) or `origin`/`rel_class` must be specified (Class#contains)
	from /opt/rubies/jruby-1.7.19/lib/ruby/gems/shared/gems/neo4j-5.0.0.rc.2/lib/neo4j/active_node/has_n.rb:335:in `validate_association_options!'
	from /opt/rubies/jruby-1.7.19/lib/ruby/gems/shared/gems/neo4j-5.0.0.rc.2/lib/neo4j/active_node/has_n.rb:295:in `has_many'
	....
irb(main):002:0> OneClass.first
=> <OneClass {....}>
```

and now we can't access the contains relationship

```shell
irb(main):003:0> c = OneClass.first
=> <OneClass {...}>
irb(main):004:0> c.contains
NoMethodError: undefined method `contains' for <OneClass {}>:OneClass
	from org/jruby/RubyBasicObject.java:1494:in `method_missing'
	from /opt/rubies/jruby-1.7.19/lib/ruby/gems/shared/gems/activemodel-4.2.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
	from (irb):4:in `evaluate'
	from org/jruby/RubyKernel.java:1107:in `eval'
	from org/jruby/RubyKernel.java:1507:in `loop'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from ./script/console:23:in `start_session'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from ./script/console:22:in `start_session'
	from ./script/console:28:in `(root)'
irb(main):005:0> c.contains = []
NoMethodError: undefined method `contains=' for <OneClass {}>:OneClass
	from org/jruby/RubyBasicObject.java:1494:in `method_missing'
	from /opt/rubies/jruby-1.7.19/lib/ruby/gems/shared/gems/activemodel-4.2.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
	from (irb):5:in `evaluate'
	from org/jruby/RubyKernel.java:1107:in `eval'
	from org/jruby/RubyKernel.java:1507:in `loop'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from ./script/console:23:in `start_session'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from ./script/console:22:in `start_session'
	from ./script/console:28:in `(root)'
irb(main):006:0> 
```

**Comment by subvertallchris** [comment]
Do you have `eager_load` enabled in your app's config? If not, try enabling it.

**Comment by drouchy** [comment]
Hi,

not sure how to do that. The only eager loading documentation I was able to found is

http://neo4jrb.readthedocs.org/en/latest/ActiveNode.html#eager-loading

but it seems on per request bases.

Cheers,

David

**Comment by subvertallchris** [comment]
Different kind of eager load. In your application.rb or any environment's rb file, you can do `config.eager_load = true` to make it load all of your classes during initialize. See http://edgeguides.rubyonrails.org/configuring.html for more info.

**Comment by drouchy** [comment]
Does not make any difference on that issue.

David

**Comment by cheerfulstoic** [comment]
I can understand how if you get that error in the console it would give that error the first time but not the second.  The first time The model class is getting auto-loaded meaning the Ruby code for the class is being evaluated.  When the association is being defined it hits an error.  The class is still partially loaded, though so you can query with it, but there wouldn't be association methods.

Now why you're getting that error is more puzzling.  Some thoughts;

* Do you have any other associations which don't have type, origin, or rel_type specified?
* Maybe this is an issue when the `type` is the same as the association name?  If you change the name of the association does it still work?

**Comment by drouchy** [comment]
hi,

removing the auto loading and adding a couple of type: in the relationship definition fix that particular issue, but now the database doest not want to start for an unknown reason:

Start embedded Neo4j db at db/development
Java::JavaLang::RuntimeException: Error starting org.neo4j.kernel.EmbeddedGraphDatabase, /Users/drouchy/src/xxxx/db/development
	from org.neo4j.kernel.InternalAbstractGraphDatabase.run(org/neo4j/kernel/InternalAbstractGraphDatabase.java:334)
	from org.neo4j.kernel.EmbeddedGraphDatabase.<init>(org/neo4j/kernel/EmbeddedGraphDatabase.java:59)
	from org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(org/neo4j/graphdb/factory/GraphDatabaseFactory.java:108)
	from org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(org/neo4j/graphdb/factory/GraphDatabaseFactory.java:95)
	from org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(org/neo4j/graphdb/factory/GraphDatabaseBuilder.java:176)
	from java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:483)
	from RUBY.start(/opt/rubies/jruby-1.7.19/lib/ruby/gems/shared/gems/neo4j-core-5.0.0.rc.3/lib/neo4j-embedded/embedded_session.rb:46)

Cheers,

David

**Comment by subvertallchris** [comment]
Check the Neo4j logs, anything there?

**Comment by drouchy** [comment]
there is nothing in the logs.

I've deleted my database and now it's starting, but I've got an error on a class

```
class Country
has_many :out, :contains, type: :contains
end
```

```shell
Country.create.contains
NameError: uninitialized constant Contain
	from org/jruby/RubyModule.java:2726:in `const_missing'
```

David

**Comment by subvertallchris** [comment]
This is what `eager_load` fixes.

**Comment by subvertallchris** [comment]
If you want to sign into gitter.im/neo4jrb/neo4j, I can help you figure it out.

**Comment by cheerfulstoic** [comment]
I'm not sure `eager_load` fixes that...  I think maybe you need a `model_class` on the association

**Comment by drouchy** [comment]
Hi,

the problem in that situation is the other side of the relationship can be an other Area or an other class named Locality.

**Comment by cheerfulstoic** [comment]
Solution from Gitter: Use an array (like `model_class: [:Area, :Locality]`) which is new in 5.0.0
