### ISSUE TITLE
Boolean data type doesn't work in concern

### ISSUE THREAD

**Issue by mithucste30** [neo4jrb/neo4j#821]
When declaring a common concern to use in multiple model i made a concern and then I declared common property like this 

included do
    property :expires,             type: Boolean
end

but it throws the error 

uninitialized constant ModuleName::Boolean (NameError)

**Comment by subvertallchris** [comment]
Within a module, set type as `ActiveAttr::Typecasting::Boolean` or `include ActiveAttr::Typecasting` at some point before declaring the property.

**Comment by cheerfulstoic** [comment]
Do you include the concern after you include `Neo4j::ActiveNode`?

**Comment by mithucste30** [comment]
yes i included the concern after the Neo4j::ActiveNode, but anyway, thanks to @subvertallchris, you solution worked perfectly! (y)

**Comment by mithucste30** [comment]
it would be also very helpful if someone added this glitch in the documentation.

**Comment by cheerfulstoic** [comment]
@subvertallchris I'm curious to know why this is needed...  Shouldn't the `included` block be run in the context of the model class?

**Comment by Joshfindit** [comment]
Quick tip for anyone that runs across this next time:

As of [7.0.0.rc.1](https://github.com/neo4jrb/neo4j/blob/master/CHANGELOG.md#700rc1---03-08-2016), you don't need `include ActiveAttr::Typecasting` or `type: ActiveAttr::Typecasting::Boolean`.

Use `type: Neo4j::Shared::Boolean` instead.
