### ISSUE TITLE
Rake tasks enable_/disable_auth do not work

### ISSUE THREAD

**Issue by olance** [neo4jrb/neo4j#822]
After installing a community-edition of Neo4j 2.2.2 using the adhoc rake task, I found I could not enable/disable server authentication using `rake neo4j:enable_auth` and `rake neo4j:disable_auth`.

The property that controls this feature has probably been changed, as I've managed to fix the issue locally by changing `lib/neo4j/tasks/config_server.rb` :

`set_property(source_text, 'dbms.security.authorization_enabled', status_string)`

replaced by:

`set_property(source_text, 'dbms.security.auth_enabled', status_string)`

However I have no idea when this change did happen....

**Comment by subvertallchris** [comment]
Make sure you're using the newest version of this gem and neo4j-core. There was an update to the gem that fixed it a month or two ago.

**Comment by olance** [comment]
Ah, well I'm using the latest non-rc versions of both gem, so that's probably in the 5.x branch?

**Comment by cheerfulstoic** [comment]
Yup, that's right, I think that would be in the rc.  You can include that in your Gemfile like:

    gem `neo4j`, '~> 5.0.0.rc.2`
    gem `neo4j-core`, '~> 5.0.0.rc.4`

I think we're close to releasing it as a non-RC version.  I'd like to get some docs in order first.

**Comment by olance** [comment]
All right, thank you! :)
