### ISSUE TITLE
Spatial Index property on ActiveNode

### ISSUE THREAD

**Issue by KieranLafferty** [neo4jrb/neo4j#830]
Using the awesome spatial plugin for neo4j (https://github.com/neo4j-contrib/spatial) and created a spatial index layer called "geom" which is requried by the plugin. I wanted to be able to make it so that whenever a new ActiveNode subclass (i.e. a Place) is created that it registers it with this custom index.

Any tips on how to achieve this?

**Comment by cheerfulstoic** [comment]
You could make a class which all models must inherit from, though that has potential the downside of all models having an additional label.

I would suggest defining a module which defines an `inherited` callback method like this:

https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/labels.rb#L12

Then if you do something like `Neo4j::ActiveNode.include(YourModule)` in your gem then whenever somebody uses your gem it will extend `Neo4j::ActiveNode`

**Comment by subvertallchris** [comment]
https://github.com/neo4jrb/neo4jrb_spatial closes

**Comment by subvertallchris** [comment]
I should rephrase my last comment. https://github.com/neo4jrb/neo4jrb_spatial doesn't close this because it doesn't seem possible to automatically manage spatial indexes -- they don't work within transactions. This gem does aid with other spatial management and querying tasks, though.
