### ISSUE TITLE
Add enum property "type"

### ISSUE THREAD

**Issue by olance** [neo4jrb/neo4j#833]
I have just extracted [this gist](https://gist.github.com/olance/9603f73c9e352c2ed4f3) out of my project to be able to declare "enums" on my nodes.

This code basically allows this:

```ruby
class Order
    include Neo4j::ActiveNode

    enum :status, values: [:pending_payment, :processed, :cancelled, :shipped]
end

o = Order.first
o.status # => :processed
o.status = :shipped # 'shipped' works as well
o.status = :wut # => raises ArgumentError
o.status_values # => [:pending_payment, :processed, :cancelled, :shipped]
```
I wonder if that would be of any interest for the Neo4j.rb project?

It might not be the best implementation and tests are not complete yet; I've done this quite quickly.
But I'm ready to spend some time on it with some pointers on how to integrate this in a better way!

**Comment by cheerfulstoic** [comment]
What about this?

```ruby
class Order
  property :status
  validates :status, inclusion: { in: [:pending_payment, :processed, :cancelled, :shipped] }
end
```

**Comment by olance** [comment]
ahah :)
Simple enough!!

Damn, I had totally forgotten about validations... shame on me! :astonished:

**Comment by cheerfulstoic** [comment]
No problem ;)

**Comment by cheerfulstoic** [comment]
FYI @olance we're talking about implementing enum here:

https://github.com/neo4jrb/neo4j/issues/1082

I know your issue is solved, but thought you might like to know ;)

**Comment by olance** [comment]
Nice :)
