### ISSUE TITLE
[Discussion] Creating nodes and rels at the same time/without persisting nodes first

### ISSUE THREAD

**Issue by olance** [neo4jrb/neo4j#840]
So we've started this discussion on Gitter with @cheerfulstoic & @subvertallchris and many ideas came out...

The initial question was: could we make it possible to create relationships between two possibly transient nodes?

@subvertallchris suggested a way to do this:

> There would need to be a little magic. When setting the association, if either node is non-persisted, it’d need to store info about the association in one of the node’s association cache. save could look at the cache and find pending actions.

We could have a look at what's done in ActiveRecord and see if we can copy some behaviors from there.

We also talked about coming up with some kind of DSL to be able to create nodes and relationships much like Cypher natively allows us to do. Something like this could be nice?

```ruby
node.query_as(:node) do
  match '(node)-[rels*]->(n)'
  where 'ALL (rel in rels WHERE rel.valid = 1)'
end.return(:n)
```

I'm not fully convinced it would be more useful than what's already there, especially since we couldn't use `#return` without writing `self.return`, which kinda defeats the DSL-like construct.

However we could already start by adding methods to QueryProxy?
Here's an idea, using association's `type` value to create chaining methods to declare relationships on nodes:

```ruby
class Student
  include Neo4j::ActiveNode
  property :name
  has_many :out, :lessons, type: :enrolled_in, model_class: 'Lesson'
  has_many :both, :friends, type: :has_friend, model_class: self
end

class Lesson
  include Neo4j::ActiveNode
  property :title
  has_many :out, :tags, type: :has_tag, model_class: 'Tag'
end

class Tag
  include Neo4j::ActiveNode
  property :title
end

# Create and save nodes & relationships on the fly:
lesson = Lesson.new(title: "Learning Neo4j")
cheerfulstoic = Student.where(name: "cheerfulstoic").first
olance = Student.new(name: 'olance').enrolled_in(lesson).has_friend(cheerfulstoic).save

# or...
Lesson.where(title: 'Learning Neo4j').students.where(name: 'cheerfulstoic').has_friend(Student.new(name: 'olance'))
```

We could probably do more than that, but I guess that should then go at the neo4j-core level...

I really can see the benefit of being able to create rels and nodes on the fly like above. We'd have to make some rules about the method names inferred from `type` when it is not explicitly given (using "has_" + `target_class_name`?).

What do you think? ^^

**Comment by beno** [comment]
I stumbled on this trying to implement some authorization code, where I'd like to check for certain properties before allowing some method. But I have found this doesn't work:

```ruby
author = Author.create(name:'Author')
book = Book.new(title:'Title', author:author)
book.author # => nil -- this seems a bug me?
```

So I have no way of checking beforehand whether this author can create this book. So I guess my requirements are quite a bit simpler than discussed above?

**Comment by subvertallchris** [comment]
I've been thinking about this a lot and might have a simple idea to get autosave of associations and association creation with non-persisted nodes working. Not sure if I'll have time to work on it today but it shouldn't take long.

**Comment by olance** [comment]
Oh well that's great news!

**Comment by cheerfulstoic** [comment]
Sorry for being out of the loop.  Life is just starting to stabilize again ;)  I look forward to Chris' PR!

**Comment by subvertallchris** [comment]
I'm going to see if I can have something to show for this tomorrow. So far, I've managed to shove nodes into the association cache when something isn't persisted. Next, I need it to be aware that there are pending associations and, when `save` occurs, it should cascade through the pending associations and create them or fail the entire transaction.

**Comment by olance** [comment]
:+1:

**Comment by subvertallchris** [comment]
Moving in this direction with https://github.com/neo4jrb/neo4j/pull/871.

**Comment by olance** [comment]
It's looking good!
I guess we should discuss the details on the PR?

**Comment by subvertallchris** [comment]
Since this PR opened last summer, two major changes have been made to the code:

Where basic node associations are concerned, we have support for creating relationships between unpersisted rels through the DSL:

```
node1 = Node.new
node2 = Node.new
node1.friends << node2

# This will save node1, then node2, then create the rel
node1.save
```

That is three queries but arguably a better experience for the user.

When using ActiveRel models, unpersisted nodes and the rel will be created in a single Cypher query.

```
MyRelClass.create(Node.new, Node.new)
```

All validations and callbacks will be fired first, too.

The query is built using https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/shared/query_factory.rb, which can be used by anyone to build their own match-or-create Cypher query.

With this in mind, I'm going to close this issue since I think it's covered nicely.

**Comment by olance** [comment]
Hey Chris, I'm very sorry there were a lot of changes on my side that completely diverted me from Neo4j (and many other things) :(

This solution looks good though, I'm glad it made it to the code base and that I could help a bit while working with the gem last year!
