### ISSUE TITLE
saving relations through associated _id?

### ISSUE THREAD

**Issue by beno** [neo4jrb/neo4j#845]
Sorry if this has been asked/answered before, but is it possible to save an associated record bij having its <association>_id (uuid) in the attributes, same as ActiveModel? I suppose this is a very SQL-y thing to ask, but a lot of exposed API and web forms rely on this behaviour. 

    Book.create(author_id: '1f2b30efwf23e3')

**Comment by subvertallchris** [comment]
I think that it's done by giving it a key matching the association name containing an array of ids.

```
Book.create(authors: [1f2b30efwf23e3'])
```

**Comment by beno** [comment]
Thanks, that (mostly) works. But in playing around with this I ran into a strange bug. Consider the following testcase and the error below.  I update the author by object here, but the same error occurs when updating by author.id. Is there something I'm doing wrong (I am 1 day into neo4j)?

```ruby
require "test_helpers"

class Reader
  include Neo4j::ActiveNode
  has_one :out, :book, origin: :reader
  property :name
end

class Book
  include Neo4j::ActiveNode
  has_one :in, :author, type: :written_by
  has_one :in, :reader, type: :reading
  property :title
end

class Author
  include Neo4j::ActiveNode
  has_many :out, :books, type: :wrote
  property :name
end

class AssociationsTest < Minitest::Test
    
  def setup
    @book = Book.create(title: "Book")
    @author = Author.create(name: "Author")
    @author_2 = Author.create(name: "Author 2")
    @reader = Reader.create name: "Reader"
    @reader.book = @book
  end
  
  def teardown
    # Reader.destroy_all
    # Book.destroy_all
    # Author.destroy_all
  end
  
  def test_passes
    @reader.book.update_attributes author: @author_2
    assert_equal @author_2, @reader.book.author
  end
    
  # passes only when teardown is enabled
  def test_fails
    reader = Reader.find_by name: "Reader"
    reader.book.update_attributes author: @author_2
    assert_equal @author_2, reader.book.author
  end

  
  
end
```    

When I run this test I get this error:

```
Error:
AssociationsTest#test_fails:
TypeError: no implicit conversion of Symbol into Integer
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:104:in `[]'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:104:in `looks_like_an_object?'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:78:in `map_row_value'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:81:in `block in map_row_value'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:81:in `map!'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:81:in `map_row_value'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:71:in `block (2 levels) in row_pair_in_struct'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:70:in `each_pair'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:70:in `block in row_pair_in_struct'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:69:in `tap'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:69:in `row_pair_in_struct'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:62:in `block (2 levels) in to_node_enumeration'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:41:in `block in each'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:183:in `block in each_data_row'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:183:in `each'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:183:in `each_data_row'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:40:in `each'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-server/cypher_response.rb:60:in `block in to_node_enumeration'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-core/query.rb:201:in `each'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-core/query.rb:201:in `each'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-core/query.rb:201:in `each'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-core/query.rb:239:in `map'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j-core/query.rb:239:in `pluck'
  /vendor/bundle/gems/neo4j-5.0.0/lib/neo4j/active_node/query/query_proxy_enumerable.rb:52:in `pluck'
  /vendor/bundle/gems/neo4j-5.0.0/lib/neo4j/active_node/has_n.rb:175:in `previous_association_proxy_results_by_previous_id'
  /vendor/bundle/gems/neo4j-5.0.0/lib/neo4j/active_node/has_n.rb:150:in `block in association_proxy'
  /vendor/bundle/gems/neo4j-5.0.0/lib/neo4j/active_node/has_n.rb:136:in `block in association_proxy_cache_fetch'
  /vendor/bundle/gems/neo4j-5.0.0/lib/neo4j/active_node/has_n.rb:135:in `fetch'
  /vendor/bundle/gems/neo4j-5.0.0/lib/neo4j/active_node/has_n.rb:135:in `association_proxy_cache_fetch'
  /vendor/bundle/gems/neo4j-5.0.0/lib/neo4j/active_node/has_n.rb:148:in `association_proxy'
  /vendor/bundle/gems/neo4j-5.0.0/lib/neo4j/active_node/has_n.rb:353:in `block (2 levels) in define_has_one_setter'
  /vendor/bundle/gems/neo4j-core-5.0.0/lib/neo4j/transaction.rb:82:in `run'
  /vendor/bundle/gems/neo4j-5.0.0/lib/neo4j/active_node/has_n.rb:353:in `block in define_has_one_setter'
  /vendor/bundle/gems/active_attr-0.8.5/lib/active_attr/mass_assignment.rb:41:in `block in assign_attributes'
  /vendor/bundle/gems/active_attr-0.8.5/lib/active_attr/mass_assignment.rb:39:in `each'
  /vendor/bundle/gems/active_attr-0.8.5/lib/active_attr/mass_assignment.rb:39:in `assign_attributes'
  /vendor/bundle/gems/active_attr-0.8.5/lib/active_attr/mass_assignment.rb:56:in `attributes='
  /vendor/bundle/gems/neo4j-5.0.0/lib/neo4j/shared/persistence.rb:122:in `update'
  /test/associations_test.rb:46:in `test_fails'

```

**Comment by subvertallchris** [comment]
That is interesting! Definitely a bug. I have a hunch about what's going on but give me a moment to get this setup on my end to confirm.

**Comment by subvertallchris** [comment]
Returning arrays appears to be broken within transactions. I think I have a fix, just need a few more minutes to test it.

**Comment by subvertallchris** [comment]
https://github.com/neo4jrb/neo4j-core/pull/213 will fix this. Once tests pass, I'll release it as neo4j-core 5.0.1, then I'll do a new release of this gem with the same version number.

**Comment by subvertallchris** [comment]
Released 5.0.1, let us know if you have any trouble.

**Comment by beno** [comment]
Fantastic, what a response. Works for me now.

But back on topic, I now need to be converting lots of **abc_id** and **abc_ids** attributes to **abc** / **abcs**. Is there maybe a hook or callback in neo4j that allows me to do that globally or do I have to implement something myself at the controller level?

**Comment by subvertallchris** [comment]
There's nothing at the moment that will do that for you. https://github.com/neo4jrb/neo4j/blob/72320a3b817e526947ed7f8684062fb3d2c83477/lib/neo4j/active_node/property.rb#L15 is as far as it goes right now. If this is something that ActiveRecord provides, it'd be nice to implement it in the gem.

**Comment by beno** [comment]
> If this is something that ActiveRecord provides, it'd be nice to implement it in the gem.

I would go as far as calling it one of the defining characteristics of AR. I am talking about the association reflection (translating _id and _ids to relations) of course, not so much about the sequence of callbacks it provides.

To me providing an explicit way of relating via id vs relating via object is more elegant too, compared to neo4jrb's current combined solution.

**Comment by beno** [comment]
Allright, this doesn't seem to get much traction so I will close the issue. But I reiterate: calling this gem 'ActiveRecord compliant' and not support this feature is a bit of a stretch. But we can work around it, so it's not a huge deal.

**Comment by subvertallchris** [comment]
I wouldn't say that it doesn't have traction, it's just not something that can happen in 72 hours. ActiveModel compliance and ActiveRecord compliant are a bit different -- we claim the former, not the latter, though we're always interested in closing the gap between their public API and ours.

As an open source project with only a few regular contributors, it's sometimes tough to balance our day jobs, our personal projects/priorities within the gem, and requests from issues. If something is of high priority to you but it doesn't seem like it is to us, I think the best thing to do is work on a pull request to add the feature, or stop by the [Gitter](https://gitter.im/neo4jrb/neo4j) chat room during the day to poke us for action.

**Comment by beno** [comment]
Sorry, I didn't mean to come across as unappreciative or overly critical, I greatly admire and value the work you are doing. But I have seen this issue brought up by several people on this list over a longer period of time without much success, so that's why I closed the issue.

BTW, on the home page it says "It tries to follow API conventions established by ActiveRecord", so I guess that's where the expectation comes from? Thanks again, and I will see about that PR.

**Comment by subvertallchris** [comment]
It's ok, and I totally understand that it's frustrating to feel like something should work and it just doesn't. You're right, this has been requested for a long time. We'd love for it to be in there but there's been a lot of ground to cover over the past year+.

Association reflection is something that I started working on a long time ago. I was pursuing support for one of the nicer form helper gems and found that there was just too much work to be done in one sitting. My lack of familiarity with ActiveRecord and its internals definitely didn't help. The researched yielded a few small features for the gem but I couldn't go all the way. I think we're in a much better place now to implement more of the features that AR relies on to provide this stuff, but it'd definitely help if you and/or other AR-users who need the features were either at the wheel or helping us along.

**Comment by beno** [comment]
Gotcha.  FYI: I am looking into using neo4j&ruby in a high profile production setting so I have a vested interest to make neo4jrb as good as it can be. For now I am working around the _id limitation by converting the incoming params hash, but it sure would be nice if it worked out of the box.

So since this *is* my actual day job, I will definitely look into this and try to move it forward. Any pointers on where to possibly make the necessary changes would be greatly appreciated.

**Comment by subvertallchris** [comment]
Awesome! That's great to hear. I'm also using it in a similar setting and get to spend time during the day fixing things and adding stuff that seems reasonable, but we're a Sinatra environment with a JSON API so things like this tend to be off my radar.

When you have time, pop into the Gitter room and I can point you in the right direction. Brian and I are usually there all day during the workday. In the meantime, you could possibly hack this into https://github.com/neo4jrb/neo4j/blob/72320a3b817e526947ed7f8684062fb3d2c83477/lib/neo4j/active_node/property.rb#L15. You might also want to investigate creating the `#{association}_id` methods when the association is defined, https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/has_n.rb, but the whole "handling-of-non-persisted-nodes" things might make things tricky.
