### ISSUE TITLE
Gem should test against Neo4j 2.2.2, not 2.2.1

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#847]

**Comment by cheerfulstoic** [comment]
Should test against `comunity-latest`

Also we should probably test the latest versions of 2.1.x and 2.2.x (and maybe 2.3.x / 3.0.x?).  We might do that via the mechanism described here:

https://github.com/neo4jrb/neo4j-rake_tasks/issues/1

**Comment by subvertallchris** [comment]
I think we were using this at one point, weren't we? I feel like I had to
roll it back but I can't remember why beyond "broken."

**Comment by cheerfulstoic** [comment]
Yup, I don't recall why either.  Just trying to give context in case somebody else picks it up ;)
