### ISSUE TITLE
Read the Docs

### ISSUE THREAD

**Issue by mattdharmon** [neo4jrb/neo4j#849]
When I visit the http://neo4jrb.readthedocs.org/en/latest/ site, it show an empty page with empty content.

**Comment by cheerfulstoic** [comment]
This is something that I've been struggling with with RTD for a while.  I hunk it stems from the fact that we have a really old git tag with the name "latest".  If you change "latest" to "stable" it should give you the docs.  Let's keep this issue though until we find a permanent solution

**Comment by cheerfulstoic** [comment]
It's fixed now, but it's gone back to broken in the past.  I'll check it again in a week or so

**Comment by mattdharmon** [comment]
Sounds good.
BTW, I think there should be a cookbook with more explicit examples on how to use this gem. The current documentation got me started with a project, but it took a lot of trial and error to get it working. Such as finding out that find_or_create method not throwing errors when it didn't do anything.

I might open a separate issue, but do you know if this 5.0 version will have factory girl support?

**Comment by cheerfulstoic** [comment]
Good point, I've added #851.  Also note that I'm planning on releasing a series of short screencasts which will try to thoroughly overview each aspect of each functionality.

As far as `factory_girl`, that's something I would definitely like to see.  I don't think it would work right now, but @subvertallchris might have a better idea

**Comment by mattdharmon** [comment]
Right now I am using: gem 'neo4j', github: 'dpisarewski/neo4j', branch: 'factory_girl', which is version 4.0.0.rc.1

**Comment by cheerfulstoic** [comment]
Oh, nice, so it seems like that's just a month or two old.  @dpisarewski what's the status of that branch?  Are you still using it?  If so, it would be nice to get it into master

**Comment by jessmartin** [comment]
@mattdharmon @cheerfulstoic It looks like that link loads properly and this can be closed.

**Comment by cheerfulstoic** [comment]
Ah, yes.  I think I created a `latest` tag, though that's stuck as a particular commit and thus will get older and older.  http://neo4jrb.readthedocs.org/ is the best URL in general and right now that forwards to http://neo4jrb.readthedocs.org/en/5.2.x/  We'll change the default version to whatever the newest version branch is each time we update the gem(s)
