### ISSUE TITLE
`#persisted?` should not call the database

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#857]
I'm working on a Neo4j adapter for `rails_admin` and one thing that I just ran across is that it does a lot of calls to `#persisted?`.  In neo4j this causes a lot of calls to the database.  I think that the difference comes down to the `#destroyed?` method.  In ActiveRecord this is just a check on the instance variable to see if it's been set as destroyed.  In `neo4j` it also checks `(!new_record? && !exist?)` and it's the `#exist?` that makes the call to the DB.  I'm find with two methods, but we should sort this out.  Curious for all opinions, but particularly @subvertallchris

**Comment by subvertallchris** [comment]
I always use the presence of "_persisted_obj" to do a quick check and
reserve "persisted?" for those times that I want to be SURE a node still
exists in the database, which is... basically never. I'm totally fine with
changing it, since nobody really seems to expect its current behavior.

**Comment by cheerfulstoic** [comment]
Good to know, thanks ;)  Since it's an API change I would think it would need to at least be version 5.1, but maybe it should have to wait until 6.0 technically?

**Comment by subvertallchris** [comment]
Let's just put it in 5.1. It's not a breaking change and I can't see anyone
complaining about it.

**Comment by cheerfulstoic** [comment]
I could definitely see it as a breaking change since people might be depending on the behavior.  One thing that I thought of is to have a temporary configuration option to change the behavior in earlier versions and then change that later.  We could also have a time bomb-style check so that when it processes the configuration option it fails if (for example) the version is >= '6.0.0' so that we know to refactor it back

**Comment by subvertallchris** [comment]
Believe it or not...

```
# from a project at work
..........*....................................................................................F.......................

Failure/Error: expect(rando_user.destroyed?).to be_truthy
       expected: truthy value
            got: false
```

So I guess it _might_ be a breaking change after all! ;-)

**Comment by cheerfulstoic** [comment]
I put this in as described, by the way.  It's possible to use the `_active_record_destroyed_behavior` configuration variable to get the ActiveRecord behavior today.  That should raise an error, though and fail the tests when we up the version of the gem to `6.0` so that we know to remove the check.
