### ISSUE TITLE
Returning Pair results in Core-Query

### ISSUE THREAD

**Issue by YanZhenLin** [neo4jrb/neo4j#866]
Hi Chris, I'm having trouble returning pair results using the core-query return function. The cypher query that I am trying to replicate in core-query is something of this form:

```cyphecr
  MATCH (users:`User`), (user2:`User`), users-[:lives_in]->(country:Country)<-[:lives_in]-(user2:User), (user2)-[:has_been_to]-(visitedList:Country), (user2:`User`)
  WHERE ( visitedList.name IN ['United States', 'Canada'])
  RETURN user2, count(user2) AS strength
  ORDER BY strength DESC
```

using some template strings, I have worked out my core query to be the following:

```ruby
match_exp = 'users-[:lives_in]->(country:Country)<-[:lives_in]-(user2:User), (user2)-[:has_been_to]-(visitedList:Country)'

where_exp = 'visitedList.name IN ['United States', 'Canada']'

return_exp = 'user2, count(*) AS strength'

@matches = User.query_as(:users).match(user2: User).match("#{match_exp}").where("#{where_exp}").return("#{return_exp}").proxy_as(User, :user2).order(strength: :desc)
```

which I turn back into a proxy query for later use on ActiveNode. The problem is that when I run the script, it generates the following query:

```cypher
  MATCH (users:`User`), (user2:`User`), users-[:lives_in]->(country:Country)<-[:lives_in]-(user2:User), (user2)-[:has_been_to]-(visitedList:Country), (user2:`User`)
  WHERE (visitedList.name IN ['United States','Canada']')
  RETURN count(user2) AS user2
```

which returns a non pair-wise result of all users living in United States or Canada. I know I am misusing the return function in such a way that it converts `RETURN user2, count(*) AS strength`  to `RETURN count(user2) AS user2`. What is the proper way to return a paired result in this case?

**Comment by cheerfulstoic** [comment]
So there are a number of things I would suggest, but I think it's easier to talk with code and see what questions you have ;)  One common thing that I would point out though to help with thinking about things is naming your variables as singular and not plural since each result is a single path of nodes.

How I would express it via the simplest possible Cypher:

```cypher
 MATCH (user:`User`)-[:lives_in]->(country:Country)<-[:lives_in]-(user2:User)-[:has_been_to]-(visited_country:Country)
  WHERE visited_country.name IN ['United States', 'Canada']
  RETURN user2, count(user2) AS strength
  ORDER BY strength DESC
```

```ruby
User.query_as(:user).match("(user:`User`)-[:lives_in]->(country:Country)<-[:lives_in]-(user2:User)-[:has_been_to]-(visited_country:Country)").where(visited_country: {name: ['United States', 'Canada']}).order(strength: :desc).return(:user2, strength: 'count(user2)')
```

If you've got a `User` model then you shouldn't need the `proxy_as`.  It will simply wrap the nodes in the model class for you.  Also, you can use `pluck` instead of `return` if you want a 2D arary.

Also, if you're using `ActiveNode` already you could probably make things a lot simple by having associations.  Something like:

```ruby
class Country
  include Neo4j::ActiveNode
  has_many :in, :residents, model_class: :User, origin: :resident_country
end

class User
  include Neo4j::ActiveNode
  has_one :out, :resident_country, type: :lives_in
  has_many :out, :visited_countries, type: :has_been_to
end

User.resident_county.residents(:user2).visited_countries.where(name: ['United States', 'Canada']).order(strength: :desc).return(:user2, strength: 'count(user2)')
```

**Comment by YanZhenLin** [comment]
Thanks a ton Brian. I choose not use pluck because I believe it returns an
enumerable, rather than a query object. I want to chain the results further
down the road with the proxyquery paginate method.

**Comment by cheerfulstoic** [comment]
Gotcha ;)  Just a clarification on the terminology, `pluck` returns an `Array` which happens to be `Enumerable`, and `return` returns a `QueryProxy` which also happens to be enumerable (and a lazy-loading object, meaning it doesn't query until the enumeration happens).

Did the above solve the issue?

**Comment by YanZhenLin** [comment]
Hi Brain, the returning method works with the count as strength, which
orders the highest correlating users, but I'm having troubling accessing
the enumerable after the return, trying to figure the best way to deal with
the problem, most likely some kind of map method from neo4j-core.

**Comment by YanZhenLin** [comment]
@matches = User.query_as(:users).match(user2:
User).match("#{match_exp}").where("#{where_exp}").order(strength:
:desc).return(:user2, strength: 'count(user2)') returns a enumerable of
couples at the moment, I am trying to map the enumerable of pairs into just
an enumerable of only users.

**Comment by YanZhenLin** [comment]
I think I will need to use the with() method for this to work, going to try
this now.

**Comment by cheerfulstoic** [comment]
If you use `return` you'll get a `QueryProxy` object.  This won't do anything until you call `to_a` or call any of the `Enumerable` module methods on it.  At which point each element in the enumeration will be a result object which will respond to calls to `user2` and `strength`.

I'm not sure what you mean by wanting "an enumerable of only users".  What context do you want to run this code in?

**Comment by YanZhenLin** [comment]
I realize it would probably be harder to solve this problem returning an
enumerable of pairs using
@matches = User.query_as(:users).match(user2: User).match("#{match_exp}").
where("#{where_exp}").order(strength: :desc).return(:user2, strength:
'count(user2)')

the context that would make the most sense would be to use a with clause to
pass user2, and the count of all the hits. Something in the form of the
following cypher:

MATCH (users:`User`), (user2:`User`),
users-[:lives_in]->(country:Country)<-[:lives_in]-(user2:User),
(user2)-[:has_been_to]-(visitedList:Country) WHERE (users.email <> '
testuser1@mailinator.com' AND country.name = 'United States' AND
visitedList.name IN ['Canada','Mexico','United States']) with user2,
count(user2) as strength order by strength desc return user2

such that when we perform the return from this query, the enumerable will
be only user2 objects and not including the strength parameter.

**Comment by cheerfulstoic** [comment]
Oh, I see what you mean.  Yeah, that's tricky because you couldn't just add an `order('count(user2)')` because it needs to be in either a `WITH` or a `RETURN`.  So yeah, I think you'd need to do what you're saying.


```ruby
User.as(:user).resident_county.residents(:user2).visited_countries.where('user.email <> ?', email).where(name: ['United States', 'Canada']).with(:user2, strength: 'count(user2)').order(strength: :desc).proxy_as(User, :user2).return(:user2)
```

The end should be the same if you're not using associations.  Also you might need to switch the `with` and the `order`, but I think that's fixed with 5.0

**Comment by YanZhenLin** [comment]
after setting up neo4j ~> '5.0.0' and using this query chain:

@matches = User.query_as(:users).match(user2:
User).match("#{match_exp}").where("#{where_exp}").with(:user2, strength:
'count(user2)').order(strength: :desc).return(:user2).proxy_as(User, :user2)

it generates the following cypher
MATCH (users:`User`), (user2:`User`),
users-[:lives_in]->(country:Country)<-[:lives_in]-(user2:User),
(user2)-[:has_been_to]-(visitedList:Country) WHERE (users.email <> '
testuser8@mailinator.com' AND country.name = 'United States' AND
visitedList.name IN ['United States','Canada']) WITH user2, count(user2) AS
strength ORDER BY strength.desc MATCH (user2:`User`) RETURN user2

which has the correct clause ordering, however, this causes issues at
"strength.desc", which is generated by the clause order(strength: :desc)
with the database issue:

"Type mismatch: expected Map, Node or Relationship but was Integer."

If the cypher is order by is changed to 'order by strength desc' instead of
'order by strength.desc':

MATCH (users:`User`), (user2:`User`),
users-[:lives_in]->(country:Country)<-[:lives_in]-(user2:User),
(user2)-[:has_been_to]-(visitedList:Country) WHERE (users.email <> '
testuser8@mailinator.com' AND country.name = 'United States' AND
visitedList.name IN ['United States','Canada']) WITH user2, count(user2) AS
strength ORDER BY strength desc MATCH (user2:`User`) RETURN user2

the query will run without the error.

**Comment by cheerfulstoic** [comment]
Interesting, so that can by solved by changing the `order(strength: :desc)` to `order('strength DESC')`.  I'm a bit surprised that it doesn't work though

**Comment by YanZhenLin** [comment]
It works!!! Thank you Brian for your patience and counseling.

**Comment by cheerfulstoic** [comment]
Yay, glad to hear it ;)
