### ISSUE TITLE
Allow for associations in `where` for `QueryProxy` chains

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#870]
Like `.where(teacher: teacher)`

**Comment by andrewhavens** [comment]
:+1:

**Comment by cheerfulstoic** [comment]
Hrmmm, actually, it seems like this is already there and I just forgot that I put it there ;)  I tried this:

```
2.2.0 :003 > Person.all.where(species: species).to_a
 CYPHER 59ms
  MATCH
    (n:`Person`),
    n-->(n1)
  WHERE (ID(n1) = {ID_n1})
  RETURN n | {:ID_n1=>446}
```

I actually just made a change to master to make sure the association has a relationship name (a change which actually uses less code now, funnily):

```
2.2.0 :003 > Person.all.where(species: species).to_a
 CYPHER 59ms
  MATCH
    (n:`Person`),
    n-[:`species`]->(n1)
  WHERE (ID(n1) = {ID_n1})
  RETURN n | {:ID_n1=>446}
```

Does that work for you @andrewhavens either an official stable release or off master should work, though before my change on master it might match more nodes that you want because of the lack of a relationship type.

**Comment by andrewhavens** [comment]
This example assumes Person has_one species, is that correct? Sorry, its a little confusing because it sounds plural. Does this also work if you simply call `Person.where(species: species)`?

**Comment by cheerfulstoic** [comment]
Yup, that seems to work too:

```
2.2.0 :023 > Person.all.where(films: film).to_a.size
 CYPHER 8ms
  MATCH
    (n:`Person`),
    n-[:`films`]->(n1)
  WHERE (ID(n1) = {ID_n1})
  RETURN n | {:ID_n1=>440}
 => 18
2.2.0 :024 > film.characters.size
 Film#characters 75ms
  MATCH
    film440,
    film440<-[rel1:`films`]-(result_characters:`Person`)
  WHERE (ID(film440) = {ID_film440})
  RETURN count(result_characters) AS result_characters | {:ID_film440=>440}
 => 18
```

Fortunately `has_one` and `has_many` are implemented very similarly under the covers so it seems to have just worked ;)

**Comment by cheerfulstoic** [comment]
Going to close unless anybody finds something not working

**Comment by andrewhavens** [comment]
Thanks!
