### ISSUE TITLE
Single quote error in Cypher 

### ISSUE THREAD

**Issue by arikan** [neo4jrb/neo4j#873]
We are having error in cypher property match for single quote.

```
cypher = "MATCH (h:Hub {_id: '#{self.id}'})-[:NODES]->(n:Node {name: '#{name}'}) RETURN n"
result = Neo4j::Session.query(cypher)
```
throws error: 
```
(n:Node {name: 'Festival d'Automne'})`
Neo4j::Server::CypherResponse::ResponseError (Invalid input 'u': expected 'n/N
```
But whe we escape the single quote it works fine:

```
name = name.gsub("'", %q(\\\'))
cypher = "MATCH (h:Hub {_id: '#{self.id}'})-[:NODES]->(n:Node {name: '#{name}'}) RETURN n"
```

Cypher doc says the String Literals can be escaped. Should the neo4jrb escape these by default?

http://neo4j.com/docs/stable/cypher-expressions.html

**Comment by subvertallchris** [comment]
It's possible that the escape process isn't evaluating strings given to the
'query' method. Try using 'query.match()', see if it's any different. I
know that if you use parameters, which you absolutely should, quotes will
be escaped, so that could be a workaround for the time being.

**Comment by subvertallchris** [comment]
But yes, it does sound like a bug and I will take a look sometime today.

**Comment by cheerfulstoic** [comment]
I'm not sure how this is a bug.  We can't take arbitrary query strings and escape the string literals that we find.  You should definitely use parameters.  They are faster, more secure if this data is coming from users, and easier because there is no escaping to worry about.

Also if you use the Query method chaining API parameters will be used for you.  Like this:

```ruby
cypher = "MATCH (h:Hub {_id: '#{self.id}'})-[:NODES]->(n:Node {name: '#{name}'}) RETURN n"
result = Neo4j::Session.query.match("(h:Hub)-[:NODES]->(n:Node)").where(h: {_id: self.id}, n: {name: name}).return(:n).exec
```

Or:

```ruby
result = Neo4j::Session.query.match(h: {Hub: {_id: self.id}}, n: {Node: {name: name}}).match("h-[:NODES]->n").return(:n).exec
```


You can also replace the `return(:n).exec` with `pluck(:n)`

**Comment by cheerfulstoic** [comment]
Thoughts?  I say we close, but I could be misunderstanding the issue

**Comment by cheerfulstoic** [comment]
Closing for now.  Please let me know if I'm misunderstanding, though
