### ISSUE TITLE
is there a way to turn enumerables into QueryProxy object?

### ISSUE THREAD

**Issue by YanZhenLin** [neo4jrb/neo4j#876]
currently my issue is trying to perform a UNION query on two core::query objects, which at the moment I am using the union_cypher method to chain the two core objects together into a cypher string. At the moment I don't know of any way to performing a UNION query other than utilizing the Neo4j::Session::query( ) method, which returns an enumerator object. However, the issues lie in that I would like to further chained the results returned from the Neo4j::Session::query( ) with QueryProxy methods.

here is the code section for the above issue:

```ruby
second_query = User.query_as(:users)
                                  .match(user2: User)
                                  .match("#{join_match_exp}")
                                  .where("#{join_where_exp}")
                                  .with(:user2, strength: 'count(user2)')
                                  .order('strength DESC')
                                  .return(:user2)

join_query =  User.query_as(:users)
                             .match(user2: User)
                             .match("#{nonjoin_match_exp}")
                             .where("#{nonjoin_where_exp}")
                             .with(:user2, strength: 'count(user2)')
                             .order('strength DESC')
                             .return(:user2)
                             .union_cypher(second_query)

#returns an enumerator
@matches = Neo4j::Session.query(join_query) 
```

is there a better or more logical way of performing union queries on ProxyQuery or Core::query? If not, how can I convert the @matches enumerator object back to a ProxyQuery or a Core Query Object?

**Comment by cheerfulstoic** [comment]
Well it should already be a `Neo4j::Query` object after the `union_cypher` call.  So actually instead of doing `Neo4j::Session.query(join_query)` you should be able to just do `join_query.exec`

Are you trying to turn it back into a `QueryProxy` because you want to query on it further, or do you just want the results?  If you just want the results, I think you could do `pluck(:user2)` after the `union_cypher`.  Otherwise you could maybe use the `@matches` result that you get and do `@matches.map(&:user2)`.

**Comment by YanZhenLin** [comment]
No Brian, I don't think we will get a Neo4j::Query Object after the
union_cypher call, I've checked the documentation many times here:
http://neo4jrb.io/neo4j-core/doc/Neo4j/Core/Query.html#union_cypher-instance_method,
on that documentation it says its returns a String object.
Also I ran the union_cypher in my program and the class type on
join_query.class returns a string class rather than a Neo4j::Query Object

**Comment by cheerfulstoic** [comment]
Sorry for dropping this!

You're right, `union_cypher` does return a string.  I don't think it makes sense to turn a `UNION` query back into a QueryProxy.  I think you would need to either do a raw Cypher query or do two queries and combine the results in memory (maybe you could add a `WHERE NOT(ID() IN {id_list_from_first_query})` to the second query to make things somewhat more efficient...

**Comment by YanZhenLin** [comment]
Ok Brian, will give your advices a go.

**Comment by YanZhenLin** [comment]
Just curious, to do the raw cypher query, you mean do it via the
Neo4j::Session:query() method?

**Comment by cheerfulstoic** [comment]
Yeah, I think that's what I meant.  I suppose that's what you're already doing...  I was probably just saying something about how you can't re-proxy it

**Comment by YanZhenLin** [comment]
Gotcha
