### ISSUE TITLE
has_one relationship : NoMethodError: undefined method `cache_result'

### ISSUE THREAD

**Issue by codeinus** [neo4jrb/neo4j#877]
so I tested eager loading for has_one relationship using same models in https://github.com/neo4jrb/neo4j/blob/master/docs/ActiveNode.rst

```
Post.comments.with_associations(:author).each do |comment|
Rails.logger.info comment.content
Rails.logger.info comment.author.name
end
```

the result was 
console : 
```
NoMethodError: undefined method `cache_result' for #Person:0x007fa44da4fa30
```

RSpec log : 
```
Post#comments#comments 6ms MATCH (node2:Post), node2<-[rel1:post]-(previous:Comment) OPTIONAL MATCH previous-[:author]->author RETURN previous, [collect(author)] 
Comment#author#author 17ms MATCH comment3157, comment3157-[rel1:author]->(result_author:Person) WHERE (ID(comment3157) = {ID_comment3157}) RETURN result_author | {:ID_comment3157=>3157}
```

**Comment by cheerfulstoic** [comment]
Interesting, I'll have a look at that.  What version of `neo4j` / `neo4j-core` do you have in your `Gemfile.lock` (assuming you're using bundler)?

Also if you want a rendered version of the docs you can find them here:

http://neo4jrb.readthedocs.org/en/latest/

I'll update the README with that link.  We just starting using it recently

**Comment by codeinus** [comment]
in my Gemfile.lock
```
 neo4j (5.0.1)
      active_attr (~> 0.8)
      activemodel (~> 4)
      activesupport (~> 4)
      neo4j-core (~> 5.0.1)
      orm_adapter (~> 0.5.0)
    neo4j-core (5.0.5)
      activesupport
      faraday (~> 0.9.0)
      faraday_middleware (~> 0.9.1)
      faraday_middleware-multi_json
      httparty
      httpclient
      json
      multi_json
      net-http-persistent
      os
      zip
```

**Comment by cheerfulstoic** [comment]
Got it, thanks!  I'm looking at it now (if I don't respond I'll have run out of time this evening, but I'll look more soon).  FYI `neo4j` is up to 5.0.5 and `neo4j-core` is up to 5.0.6 so you might want to try updating those gems.  I don't know if it will help, but it's worth a shot

**Comment by cheerfulstoic** [comment]
Actually, it looks like it might be fixed in the latest version of the `neo4j` gem.  Could you try the latest versions from above and see if that works?

Thanks again

**Comment by codeinus** [comment]
I did neo4j version up. now it is resolved!
Thank you!

**Comment by cheerfulstoic** [comment]
Great, glad to hear it!  Thanks!
