### ISSUE TITLE
`where(id: value)` in QueryProxy should use `id_property` definition

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#883]
That is to say this:

```ruby
Asset.where(id: 'foo')
```

Should execute this Cypher:

```cypher
MATCH (result_asset:`Asset`)
WHERE (result_asset.uuid = {result_asset_id})
```

(unless `id_property` specifies another property name and then that name should be used)

**Comment by cheerfulstoic** [comment]
Probably `#find_by` as well...

**Comment by subvertallchris** [comment]
+1

I think it'd be easy to hook this into the method that references type
converters when calling 'where'.

**Comment by cheerfulstoic** [comment]
See https://github.com/neo4jrb/neo4j/pull/884 (closing this and making that the issue)
