### ISSUE TITLE
Callbacks not called if calling find_or_create method to create a new model instance

### ISSUE THREAD

**Issue by alexw668** [neo4jrb/neo4j#885]
I am using neo4j version 5.0.5. I noticed that if I call find_or_create method to create a new instance of a model, the callbacks defined in the model don't get called.

For example, assuming I have the following model defined:

```ruby
class BugReport
  include Neo4j::ActiveNode
  property :name, type: String
  property :priority, type: Integer

  before_save :on_before_save
  after_save :on_after_save

  def on_before_save
    puts "on_before_save called"
    priority = 0
  end

  def on_after_save
    puts "on_after_save called."
    priority = 1
  end
end
```

If I call BugReport.find_or_create name: "Callbacks not called", I don't see the callbacks get called. If I call BugReport.create name: "Callbacks get called", I can see the callbacks get called.

**Comment by cheerfulstoic** [comment]
Ah, good catch, thanks!  We should definitely fix this

**Comment by subvertallchris** [comment]
`find_or_create` uses a Cypher merge and doesn't trigger callbacks or validations at the moment. You'll want to use `find_or_create_by` to perform do it in a two-step process through Ruby. Not saying it's ok but... just saying.

**Comment by cheerfulstoic** [comment]
Ah, right, I forgot about that difference.  It might be good to match ActiveRecord (if we aren't already) to avoid confusion again

**Comment by alexw668** [comment]
For now, I can live with find_or_create_by. :)
