### ISSUE TITLE
creating multiple nodes 

### ISSUE THREAD

**Issue by swiftly112** [neo4jrb/neo4j#886]
Hi 
![screen shot 2015-07-27 at 5 19 57 pm](https://cloud.githubusercontent.com/assets/5517191/8918069/c4a92898-3483-11e5-8af2-7f625d855394.png)

I was getting the error Neo4j::ActiveNode::HasN::NonPersistedNodeError
so i used the Neo4j:Config[autosave_on_assignment] = true in application.rb

it fixed the issue, but now i am getting duplicate comments. any help will appreciated.

**Comment by subvertallchris** [comment]
Can you share the relevant section of your controller?

**Comment by swiftly112** [comment]
![screen shot 2015-07-27 at 5 38 26 pm](https://cloud.githubusercontent.com/assets/5517191/8918516/63796c1a-3486-11e5-8be5-fd072520bd19.png)

**Comment by swiftly112** [comment]
is this the relevant part of the controller you needed?

**Comment by cheerfulstoic** [comment]
Sorry for not getting back earlier.  Were you able to figure out the issue?
