### ISSUE TITLE
Basic usage of RoR gems not returning or returned with TimeoutError: too many connection resets

### ISSUE THREAD

**Issue by levidamian** [neo4jrb/neo4j#900]
Here is what i am using (rails console):

```
$ gem list neo
*** LOCAL GEMS ***
neo4j (5.0.9)
neo4j-core (5.0.6)

irb(main):001:0> l = Language.find_by(iso_639_2_code: 'eng')
 CYPHER 150ms MATCH (n:`Language`) WHERE (n.iso_639_2_code = {n_iso_639_2_code}) RETURN n LIMIT {limit_1} | {:n_iso_639_2_code=>"eng", :limit_1=>1}
=> Language uuid: nil, english_name_of_language: "English", french_name_of_language: "anglais", german_name_of_language: "Englisch", iso_639_1_code: "en", iso_639_2_code: "eng", spoken_in: "English, a West Germanic language is the first language for about 309–400 million people. See: Countries by Languages - English Speaking Countries."

irb(main):003:0> n = l.descriptions.count
 Language#descriptions 6695ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN count(result_descriptions) AS result_descriptions | {:ID_language137=>137}
=> 2107041
```

Trying to get the first description in English:
```
irb(main):008:0>  d = l.descriptions.first
```

After a very long run the result is:
```
 Language#descriptions 1200265ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN result_descriptions | {:ID_language137=>137}
Faraday::TimeoutError: too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 0 requests on 70276164611260, last used 1438711280.7209878 seconds ago
```

During the long processing no other connection is allowed to the database and if one is still open, any processing there takes for ever until the first session is terminated.
Most of the time a server reboot is required to resume normal usage of the database.

Another failure time to time is:
```
d = l.descriptions.first
Language#descriptions 951802ms MATCH language137, language137-[rel1:DESCRIBED_IN]->(result_descriptions:Description) WHERE (ID(language137) = {ID_language137}) RETURN result_descriptions | {:ID_language137=>137}
Neo4j::Session::CypherError: Java heap space
from /Users/levi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/neo4j-core-5.0.6/lib/neo4j-server/cypher_response.rb:211:in `raise_cypher_error'
```

**Comment by cheerfulstoic** [comment]
Thanks and sorry for the confusion.

So your querying that's timing out is:

```cypher
MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN result_descriptions
```

Does that query (with the `ID_language137` param replaced with `137`) also timeout in the Neo4j console?  If it's hitting 120s and dying then it's not (I don't think) the gem, but the server actually taking that long to respond which is why it's worth verifying.

The query isn't a particularly complicated query, so I'm led to believe that you've got a lot of `DESCRIBED_IN` relationships.  I know that Neo4j sometimes has issues with lots of relationships around one node so that's one possibility.

Also have you made any changes to your server's memory configuration to allow for more memory (I don't know if that will help or not, but it's just good to know)?

**Comment by levidamian** [comment]
This query runs between 6 and 15 seconds, depending on the caches, but never dies.

neo4j-sh (?)$ match (l:Language{iso_639_2_code:'eng'})-[:DESCRIBED_IN]-(d:Description) return l.iso_639_2_code, count(d);
+-----------------------------+
| l.iso_639_2_code | count(d) |
+-----------------------------+
| "eng"            | 2107041  |
+-----------------------------+
1 row
6773 ms

**Comment by levidamian** [comment]
How I can get the first description out of those 2107041 using cypher instead of the rails "first" method?
Did not changed recently any params of the server except increasing those two, the values shown below:
wrapper.java.initmemory=8240
wrapper.java.maxmemory=8240

**Comment by cheerfulstoic** [comment]
Ah, well that's not the same query.  You're using a label, not using a relationship variable, and doing a count in the `RETURN`.  So while it's useful to have that datapoint, it might not perform the same.  What about this exact query?

```
MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = 137) RETURN result_descriptions
```

**Comment by cheerfulstoic** [comment]
Actually, it's interesting because the `first` should be adding a `LIMIT 1`.  Not sure why it's doing that, I'll check now...

**Comment by levidamian** [comment]
Running the one you suggested:
MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = 137) RETURN result_descriptions;
In the web browser failed.
In the shell lists a very long result. Before listing is started,processing time took like 6-7 seconds or so.

**Comment by levidamian** [comment]
These queries below works but does not explain why the method first in the initial query is not working.

irb(main):023:0* l = Language.find_by(iso_639_2_code:'eng')
 CYPHER 350ms MATCH (n:`Language`) WHERE (n.iso_639_2_code = {n_iso_639_2_code}) RETURN n LIMIT {limit_1} | {:n_iso_639_2_code=>"eng", :limit_1=>1}
=> Language uuid: nil, english_name_of_language: "English", french_name_of_language: "anglais", german_name_of_language: "Englisch", iso_639_1_code: "en", iso_639_2_code: "eng", spoken_in: "English, a West Germanic language is the first language for about 309–400 million people. See: Countries by Languages - English Speaking Countries."

irb(main):024:0> d = l.descriptions.limit(1)
=> QueryProxy Language#descriptions CYPHER: "MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) LIMIT {limit_1}"

irb(main):025:0> d.first
 Language#descriptions 350ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN result_descriptions LIMIT {limit_1} | {:ID_language137=>137, :limit_1=>1}
=> Description uuid: nil, description_text: "Each Fodor's Travel Guide is researched and written by resident writers and experts."

**Comment by levidamian** [comment]
For the queries below only find_by triggers the addition of limit(1).

irb(main):030:0* a = Author.find_by(author_name: 'Camus, Albert')
 CYPHER 790ms MATCH (n:`Author`) WHERE (n.author_name = {n_author_name}) RETURN n LIMIT {limit_1} | {:n_author_name=>"Camus, Albert", :limit_1=>1}
=> Author uuid: nil, author_name: "Camus, Albert"

irb(main):031:0> w = a.wokas.first
 Author#wokas 1561ms MATCH author20415116, author20415116-[rel1:`AUTHORED_BY`]->(result_wokas:`Woka`) WHERE (ID(author20415116) = {ID_author20415116}) RETURN result_wokas | {:ID_author20415116=>20415116}
=> Woka uuid: nil, woka_title: "Postoronnij"

irb(main):032:0> w = Woka.first
 CYPHER 222098ms MATCH (n:`Woka`) RETURN n ORDER BY n.uuid LIMIT {limit_1} | {:limit_1=>1}
=> Woka uuid: nil, woka_title: "Articles on People from the District of Unna, Including: Eugen Drewermann, Hans-Martin Linde, Albert Von Maybach, Lars M Ller, Marvin Pourie, Theodor Homann, Richard Grathoff, Paul Verhoeven (Germany), Marco Jakobs, Roland PR LL"

irb(main):033:0> a = w.authors.first
 Woka#authors 833ms MATCH woka711, woka711<-[rel1:`AUTHORED_BY`]-(result_authors:`Author`) WHERE (ID(woka711) = {ID_woka711}) RETURN result_authors | {:ID_woka711=>711}
=> Author uuid: nil, author_name: "Hephaestus Books"

**Comment by cheerfulstoic** [comment]
Sorry for the delay, but I think I've got a solution.  Could you try out version 5.0.11?

**Comment by levidamian** [comment]
Installed 5.0.11, uninstalled all previous versions.
It worked. Please take a look at these (execution times also much faster than before):

irb(main):001:0> l = Language.find_by(iso_639_2_code:'eng')
 CYPHER 130ms MATCH (n:`Language`) WHERE (n.iso_639_2_code = {n_iso_639_2_code}) RETURN n LIMIT {limit_1} | {:n_iso_639_2_code=>"eng", :limit_1=>1}
=> Language uuid: nil, english_name_of_language: "English", french_name_of_language: "anglais", german_name_of_language: "Englisch", iso_639_1_code: "en", iso_639_2_code: "eng", spoken_in: "English, a West Germanic language is the first language for about 309–400 million people. See: Countries by Languages - English Speaking Countries."

irb(main):010:0>  d = l.descriptions.count
 Language#descriptions 14730ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN count(result_descriptions) AS result_descriptions | {:ID_language137=>137}
=> 2107041

irb(main):013:0> d = l.descriptions.first
 Language#descriptions 26240ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN result_descriptions ORDER BY result_descriptions.uuid LIMIT {limit_1} | {:ID_language137=>137, :limit_1=>1}
=> Description uuid: nil, description_text: "Each Fodor's Travel Guide is researched and written by resident writers and experts."

irb(main):014:0>

**Comment by levidamian** [comment]
I also run couple more to see if more complex things works also well. Complete success. Please take a look at these:

irb(main):001:0> l = Language.find_by(iso_639_2_code: 'eng')
 CYPHER 126ms MATCH (n:`Language`) WHERE (n.iso_639_2_code = {n_iso_639_2_code}) RETURN n LIMIT {limit_1} | {:n_iso_639_2_code=>"eng", :limit_1=>1}
=> Language uuid: nil, english_name_of_language: "English", french_name_of_language: "anglais", german_name_of_language: "Englisch", iso_639_1_code: "en", iso_639_2_code: "eng", spoken_in: "English, a West Germanic language is the first language for about 309–400 million people. See: Countries by Languages - English Speaking Countries."

irb(main):002:0> d = l.descriptions.first
 Language#descriptions 18713ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN result_descriptions ORDER BY result_descriptions.uuid LIMIT {limit_1} | {:ID_language137=>137, :limit_1=>1}
=> Description uuid: nil, description_text: "Each Fodor's Travel Guide is researched and written by resident writers and experts."

irb(main):003:0> n = l.descriptions.count
 Language#descriptions 16191ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN count(result_descriptions) AS result_descriptions | {:ID_language137=>137}
=> 2107041

irb(main):004:0> w = d.woka
 Description#woka 16993ms MATCH description26472193, description26472193<-[rel1:`DESCRIBED_BY`]-(result_woka:`Woka`) WHERE (ID(description26472193) = {ID_description26472193}) RETURN result_woka ORDER BY result_woka.uuid LIMIT {limit_1} | {:ID_description26472193=>26472193, :limit_1=>1}
=> Woka uuid: nil, woka_title: "Fodor's Caribbean 2010"

irb(main):005:0> a = w.authors.first
 Woka#authors 861ms MATCH woka10524805, woka10524805<-[rel1:`AUTHORED_BY`]-(result_authors:`Author`) WHERE (ID(woka10524805) = {ID_woka10524805}) RETURN result_authors ORDER BY result_authors.uuid LIMIT {limit_1} | {:ID_woka10524805=>10524805, :limit_1=>1}
=> Author uuid: nil, author_name: "Fodor Travel Publications"

irb(main):006:0> ll = w.language
 Woka#language 840ms MATCH woka10524805, woka10524805<-[rel1:`PUBLISHED_IN`]-(result_language:`Language`) WHERE (ID(woka10524805) = {ID_woka10524805}) RETURN result_language ORDER BY result_language.uuid LIMIT {limit_1} | {:ID_woka10524805=>10524805, :limit_1=>1}
=> Language uuid: nil, english_name_of_language: "English", french_name_of_language: "anglais", german_name_of_language: "Englisch", iso_639_1_code: "en", iso_639_2_code: "eng", spoken_in: "English, a West Germanic language is the first language for about 309–400 million people. See: Countries by Languages - English Speaking Countries."

irb(main):007:0> dd = ll.descriptions.first
 Language#descriptions 8085ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN result_descriptions ORDER BY result_descriptions.uuid LIMIT {limit_1} | {:ID_language137=>137, :limit_1=>1}
=> Description uuid: nil, description_text: "Each Fodor's Travel Guide is researched and written by resident writers and experts."

**Comment by cheerfulstoic** [comment]
Awesome, thanks!  I'm noticing with the third query in the first set that it's still taking 26 seconds.  I'm guessing that's because it's doing an `ORDER BY` on the uuid.  Neo4j isn't always great at doing `ORDER BY` on lots of nodes unless you give it more memory (I'm not an expert on how to do that).  If you just want one object without regard for order you could do something like

```ruby
l.descriptions.limit(1)[0]
```

**Comment by levidamian** [comment]
Many thanks for help and advise. I will consider it for future developments.

**Comment by cheerfulstoic** [comment]
Awesome, thanks for verifying the change.  Closing for now, but feel free to reopen or to create a new issue if something else comes up
