### ISSUE TITLE
Array input for ActiveRel.`(from|to)_class`

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#911]
For validating to make sure the right nodes are set when you want to have a number of different kinds but not necessarily `:any` class

**Comment by cheerfulstoic** [comment]
Also, associations use `model_class: false` and ActiveRel uses the `:any` Symbol, so maybe we should standardize that...

**Comment by subvertallchris** [comment]
It takes `false`, too, to mirror the association option.

**Comment by subvertallchris** [comment]
In latest release!
