### ISSUE TITLE
Reserved class keyword or bug??

### ISSUE THREAD

**Issue by alexw668** [neo4jrb/neo4j#913]
Hi,

I have an ActiveNode model class named App in my code base: 

class App
  include Neo4j::ActiveNode

  property :name, type: String, index: :exact, constraint: :unique
  ...
end

There are a few places where I need to check if an object is of the App type. e.g., my_app.is_a?(App). From time to time, this would fail, in my test, and in my Rails console session:

> my_app = App.first
=> #<App uuid: "010111b9-b8a8-4b12-86c7-2202dcf7197e", name: "Tester">

> my_app.is_a?(App)
=> false

> "#{my_app.name} is a #{my_app.class}? #{my_app.is_a?(App)}"
=> Tester is a App? false

This does not always happen. When it happens, it happens to any Rails env (test, or development), and restarting database server won't even help. I don't have this kind of problem with other models not named App, which make me think if App is a reserved class name in the neo4j gem or in any of its dependent gems.

Did you ever have such problem?

This is really weird.

Thanks for looking into this.

Alex

**Comment by subvertallchris** [comment]
Try using the latest release, I believe it is 5.0.15 but rubygems can
confirm. It may fix this.

**Comment by alexw668** [comment]
Yes, the newer version works fine. What I am curious about was that why the problem I saw did not happen all the time? Should I be concerned about using "App" as my model name?

**Comment by subvertallchris** [comment]
Great! No, this was not an issue with naming. I actually wrote about the
issue in my blog when I fixed it, I found it so interesting.
http://blog.subvertallmedia.com/2015/07/03/model-caching-in-rails-or-when-a-student-is-not-a-student/
gives an overview. The TLDR is that Rails reloader creates new instances of
classes but the gem was holding onto old instances and using them as the
basis for comparison against nodes. Your instances of App were being
checked against a different version of the model!

**Comment by alexw668** [comment]
That's an interesting blog post. I had the same feeling when I saw the behavior. However, I first noticed the problem on suddenly failing tests, and then I did the is_a?(App) test right from a fresh Rails console in dev env with the strange behavior. I also restarted the Neo4j database. Since either helped, I thought it had nothing to do with the Rails reloading.

**Comment by subvertallchris** [comment]
Glad it's working! Let us know if you have any trouble.
