### ISSUE TITLE
Installing Neo4jrb in a Linux server, not under $HOME

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#923]
Hi all,

I'd need to install Neo4j to run as a service in a Ubuntu Server machine.

All the instructions seems to install the product in a /users/$HOME directory.

Is there any instruction for this? 

The instructions in the Neo4j manual explains how to load Neo4j and configure it on a server, but does't explain how to configure Neo4jrb ....

Any suggestion will be highly appreciated

**Comment by cheerfulstoic** [comment]
If you're using Neo4j.rb in server mode, then the instructions are the same.  The Neo4j server is set up separately and then you just make sure to configure the port that you want and then use that port in your Neo4j.rb project.  It should be as simple as unzipping the file to the directory that you want, optionally configuring the `conf/neo4j-server.properties` file (as well as any other configuring that you want to do), and running `./bin/neo4j start`.  Of course you'll probably want to do all the standard linux stuff to make sure that it starts up automatically when the server starts.  You might check out this project:

https://github.com/mperham/inspeqtor

It's a monitoring service, but it encourages the use of init.d, etc...

Lastly as an FYI I recently extracted the `rake` tasks that came with `neo4j-core` into the `neo4j-rake_tasks` gem.  This has some assumptions built into it, but eventually it would be nice if it could be run outside of a `neo4j`/`neo4j-core` project just to manage a Neo4j server.

**Comment by pdipietro** [comment]
following your experience, which are the right directories where to install the application and the database?
It is a good idea to have them in two separate directories instead of <application_dir>/db?

**Comment by cheerfulstoic** [comment]
That's a good question ;)  I don't have a whole lot of experience with managing Linux servers and putting things in places where another system administrator or developer would expect to find them.

As far as should they be in separate DBs, that's a good question.  I would probably have them in separate databases.  But if you used sqlite for you database, you might very well put that under the `db` folder of the Rails application.  But separating them probably will make it easier when you get to the point where you would like to scale your database/application to a separate servers and maybe even across many servers.

Just remember, though, if you do use the rake tasks to install the database with your Ruby application that by default the authentication is disabled (I don't recall if it's just for test/development modes or if it disables it for production to).  So make sure that works if you're deploying a production environment.
