### ISSUE TITLE
`update_all` for models / scopes

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#926]

**Comment by ProGM** [comment]
@cheerfulstoic I'm trying to implement a temporary replacement. What could be a good implementation for this?

I thought about something like:
```ruby
def update_all(params = {})
  query_as(:c).set(c: params).exec
end
```

or maybe:

```ruby
def update_all(updates, bindings = {})
  if updates.is_a? Hash
    query_as(:n).set(n: values).exec
  elsif updates.is_a? String
    query_as(:n).set(values).params(bindings).exec
  else
    raise ArgumentError, 'Invalid parameters.'
  end
end
```

**Comment by cheerfulstoic** [comment]
I think you're on a good path.  If you come up with a good final solution I'm happy to throw it in the gem (or you can make a PR and get credit ;)  I have a few thoughts:

 * First, I would call `bindings` `parameters` or `params` to be consistent.
 * I would probably use a `case` statement for the second implementation
 * These should all start with the `all` method so that you could run `Model.where('something').update_all()` and it should only update the objects that you have scoped to.

Maybe something like:

```ruby
def update_all(updates, params = {})
  query = all.query_as(:n)

  case updates
  when Hash
    query.set(n: values).exec
  when String
    query.set(values).params(params).exec
  else
    raise ArgumentError, 'Invalid parameters.'
  end
end
```

There's also the argument to be made that Cypher makes this sort of thing really easy with `SET`, so that maybe users should just choose whichever of these paths that they want manually.  In the end, though, it's good to have compatibility with ActiveRecord so that plugins can work more easily between the two.

Let me know if you have any other questions!
