### ISSUE TITLE
Error on relationships serialization

### ISSUE THREAD

**Issue by raphi** [neo4jrb/neo4j#938]
Hi guys, there is an issue when trying to serialize a relationship:
```
render json: @user, include: :likes
```
Where likes is defined in the User model as:
```
has_many :out, :likes, type: :LIKES, model_class: User, unique: true
```
I obtain this error:
```
undefined method `serializable_hash' for #<Neo4j::ActiveNode::HasN::AssociationProxy:0x007ff600c869c0>
```
Thanks

**Comment by cheerfulstoic** [comment]
Fix made and pushed to `5.1.x` branch.  Will release a 5.1.4 when this build passes:

https://travis-ci.org/neo4jrb/neo4j/builds/77017130

**Comment by cheerfulstoic** [comment]
5.1.4 released!  Give that a try and let us know how it works.

Thanks for catching this!

**Comment by raphi** [comment]
Yes I confirm it works great. Thank you :+1:

**Comment by cheerfulstoic** [comment]
Yay!  Thanks for letting me know!
