### ISSUE TITLE
NoMethodError (undefined method `body=' for CypherNode 2093 (69983648512020):Neo4j::Server::CypherNode):

### ISSUE THREAD

**Issue by djvs** [neo4jrb/neo4j#943]
After:

     q = @res.questionbyid(params[:id])

   [...]

     def questionbyid(id)
         self.query_as(:a).match('a-[r:aquestions]-n').where(n: {uuid: id}).pluck(:n).first
     end

**Comment by djvs** [comment]
Also a possibly related error (???) - 

      TypeError (no implicit conversion of Symbol into Integer):
        app/models/resource.rb:968:in `block in as_json'
        app/models/resource.rb:968:in `map'
        app/models/resource.rb:968:in `as_json'

Possibly another class mismatch?

**Comment by subvertallchris** [comment]
You're getting a CypherNode because it's having trouble finding the mode
that's responsible for that combination of labels. Weird. If you call
`:wrapper` on the CypherNode, what does it return?

**Comment by djvs** [comment]
Might have been an error in my code (commas left over from a hash...) testing...

**Comment by djvs** [comment]
Hmm yes...so I guess if you define a model's attribute to be the model itself... or possibly some hash... it will cause that...

**Comment by subvertallchris** [comment]
Can you elaborate and give an example?

**Comment by djvs** [comment]
Well, I closed the file now, but it looked something like this:

    q.explanation = params[:explanation],
    q.version = 0,
    q.answers = answers
    q.save

This would mess something up, then the next time the whole Rails action was called (I think), it would give the CypherNode error.  Removing the commas makes the problem vanish.

**Comment by djvs** [comment]
A very unusual  error so maybe not of interest.

**Comment by djvs** [comment]
I take that back.  It's still doing it.

**Comment by djvs** [comment]
`puts q.wrapper.inspect` gives:

CypherNode 2170 (69979787324900)

**Comment by djvs** [comment]
Yes, the two bugs I reported are related.  This:

    obj[:questions] = self.questions.map{|x|puts x.inspect + " XXX"; x.as_json("teacher")}


Will give this:

    CypherNode 2093 (70028474526840) XXX
    Completed 500 Internal Server Error in 19ms

    TypeError (no implicit conversion of Symbol into Integer):

**Comment by subvertallchris** [comment]
I just released 5.1.5 to fix this.

**Comment by subvertallchris** [comment]
You can reopen this issue and/or ping me on Gitter if you're still having trouble.
