### ISSUE TITLE
Should relationships be wrapped if their type matches an ActiveRel model type?

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#944]
I'm working on an app which represents the Neo4j built-in movie database.  There is a `people` relationship and it would be nice if, when returning relationships, it automatically wrapped the `CypherRelationship` objects.  I can't really specify a `rel_type` because there are multiple types

**Comment by subvertallchris** [comment]
Closing this one. Pointed out to Brian that this problem is resolved by making sure the ActiveRel class is loaded within the app before returning the relationships.

**Comment by cheerfulstoic** [comment]
So I might argue that this is still something to fix.  In Rails' development mode models aren't loaded until they're referenced, but our wrapping process should try to reference that class, I think.  You shouldn't need to put a random reference in your code to the model to load it.  The same thing is actually happening to me in the asset_portal with an ActiveNode class actually
