### ISSUE TITLE
Calling `rel_where` on a previously materialized AssociationProxy has no effect

### ISSUE THREAD

**Issue by jmdeldin** [neo4jrb/neo4j#952]
Splitting this issue up from the [other issue](https://github.com/neo4jrb/neo4j/issues/951) I reported in Gitter, calling `rel_where` on an `AssociationProxy` that's previously been `to_a`'d has no effect. It seems like the `AssociationProxy` should not respond to `rel_where` in this case if it isn't going to do anything.

My workaround is just `reload`ing the model, but here's [a gist](https://gist.github.com/jmdeldin/2d67e63e84021426d669), and the relevant snippet:

```ruby
a1.books.to_a # returns an array

# this next line returns the results from the line above instead of querying
rs = a1.books.rel_where(enjoyed_writing: false).to_a
```

**Comment by subvertallchris** [comment]
It's actually that _any_ modifications to a returned query are ignored.

```
2.2.2 :035 > s.lessons.to_a
 Student#lessons 27ms MATCH student7943 WHERE (ID(student7943) = {ID_student7943}) MATCH student7943-[rel1:`ENROLLED_IN`]->(result_lessons:`Lesson`) RETURN result_lessons | {:ID_student7943=>7943}
 => [#<Lesson uuid: "e962672b-cd86-4c6b-893f-4ef0d7ea99d3", date: nil, level: nil, subject: "Math">, #<Lesson uuid: "5152dfa7-5c02-4347-b935-8f585f5d1e1d", date: nil, level: nil, subject: "Science">] 
2.2.2 :036 > s.lessons.where(subject: 'Math').to_a
 => [#<Lesson uuid: "e962672b-cd86-4c6b-893f-4ef0d7ea99d3", date: nil, level: nil, subject: "Math">, #<Lesson uuid: "5152dfa7-5c02-4347-b935-8f585f5d1e1d", date: nil, level: nil, subject: "Science">] 
2.2.2 :037 > s.lessons.rel_where(grade: 60).to_a
 => [#<Lesson uuid: "e962672b-cd86-4c6b-893f-4ef0d7ea99d3", date: nil, level: nil, subject: "Math">, #<Lesson uuid: "5152dfa7-5c02-4347-b935-8f585f5d1e1d", date: nil, level: nil, subject: "Science">] 
```

**Comment by cheerfulstoic** [comment]
I think that I've fixed this in 5.2.6.  Give it a shot!

**Comment by subvertallchris** [comment]
I think we're good here so going to close. Please get in touch if you have more trouble.

**Comment by jmdeldin** [comment]
Just got a chance to upgrade and test, and queries work as expected now. Thanks for fixing!
