### ISSUE TITLE
Cloudinary and Carrierwave integration

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#953]
Hi all,

After a lot of attempts using cloudinary with neo4j, using the cloudinary_neo4j gem, it seemed to me that the best way to integrate was to directly use the cloudinary gem.

But that gem didn't support Neo4j.

So I made a couple of minor changes and now it is up & running for me.

It is interesting, because it allows the full use of the latest cloudinary services to upload and modify the images while uploading.

If you are interested and like to review, give a look at https://github.com/pdipietro/cloudinary_gem and let me know.

Paolo

**Comment by cheerfulstoic** [comment]
That's awesome, thanks!  It seems pretty simple!

I'm not sure how cloudinary does their versioning, but if the follow http://semver.org/ they would probably want to do this as a 1.2.x.

**Comment by cheerfulstoic** [comment]
Closing this, but @subvertallchris is welcome to comment as well (he's on vacation right now)

**Comment by pdipietro** [comment]
As in the Readme, it will be in the 1,1,1 !
