### ISSUE TITLE
CypherNode instead of entity class instance after `reload!` in rails c

### ISSUE THREAD

**Issue by janpieper** [neo4jrb/neo4j#955]
If you open the rails console, query for an entity, reload the rails console and query for the same entity without any changes to the code, you get a `CypherNode` instead of an instance of the entity's class, in this case `GroupEntity`.

```
jan@svadlupnir$ rails c
Loading development environment (Rails 4.2.0)

2.1.5 :001 > Neo4j::Session.query.match("(g:`GroupEntity`)").limit(1).pluck(:g).first
 CYPHER 10ms MATCH (g:`GroupEntity`) RETURN g LIMIT {limit_1} | {:limit_1=>1}
 => #<GroupEntity uuid: "40b677f1-b4b2-4bc4-96e1-06f02ff55515", [...]> 

2.1.5 :002 > reload!
Reloading...
 => true

2.1.5 :003 > Neo4j::Session.query.match("(g:`GroupEntity`)").limit(1).pluck(:g).first
 CYPHER 4ms MATCH (g:`GroupEntity`) RETURN g LIMIT {limit_1} | {:limit_1=>1}
 => CypherNode 2 (68201940)
```

You can see the problem, if you want to access a property:

```
jan@svadlupnir$ rails c
Loading development environment (Rails 4.2.0)

2.1.5 :001 > Neo4j::Session.query.match("(g:`GroupEntity`)").limit(1).pluck(:g).first.name
 CYPHER 10ms MATCH (g:`GroupEntity`) RETURN g LIMIT {limit_1} | {:limit_1=>1}
 => "Example" 

2.1.5 :002 > reload!
Reloading...
 => true

2.1.5 :003 > Neo4j::Session.query.match("(g:`GroupEntity`)").limit(1).pluck(:g).first.name
 CYPHER 4ms MATCH (g:`GroupEntity`) RETURN g LIMIT {limit_1} | {:limit_1=>1}
NoMethodError: undefined method `name' for CypherNode 2 (53866960):Neo4j::Server::CypherNode
        from (irb):3
        from /home/jan/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
        from /home/jan/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
        from /home/jan/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/jan/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/jan/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'
```

**Comment by subvertallchris** [comment]
Try it with v5.2.3, which I just released. 5.1.5 tries to fix this but it looks like it got missed in the earlier 5.2.x releases.

**Comment by janpieper** [comment]
Ah, we read about a fix and that it was planned to be available in 5.1.5. We currently use 5.2.0 and thought we've hit another bug. Will update and come back to give you a feedback! Thanks!

**Comment by subvertallchris** [comment]
Nope, our goof, sorry! I think this will clear it up for you -- it fixes this issue by making your app hang onto a list of models to  re-initialize after `reload!` completes -- but please let me know how things go.

**Comment by janpieper** [comment]
Upgraded from 5.2.0 to 5.2.3. Works fine now! Thanks!

**Comment by brisingr123** [comment]
Getting the following error. The same method runs fine when I open up a fresh console. 

![image](https://cloud.githubusercontent.com/assets/7721955/15027248/74eee624-1260-11e6-8f9f-c8662d87c6ea.png)

![image](https://cloud.githubusercontent.com/assets/7721955/15027262/8ec39f36-1260-11e6-9445-7a6713538284.png)

**Comment by cheerfulstoic** [comment]
Thanks for the report!

I think that this may be related to the other issue that you commented on.  Normally when nodes are loaded from the DB they are wrapped according to what labels are on the node and the model classes that you have.  For example if you have a `Slot` model which includes `Neo4j::ActiveNode` then any nodes that have the `Slot` label should be wrapped as objects of the `Slot` class.  If the gem can't find any models to wrap the node with you end up with a raw `CypherNode` object.

You can also have, for example, a `Slot` model that includes `Neo4j::ActiveNode` and then a `Foo` class which inherits from `Slot`.  Then whenever you do `Foo.create` the resulting nodes will have both the `Slot` and `Foo` labels and any time a label has both `Slot` and `Foo` they will be wrapped as objects of the `Foo` class.

Feel free to drop by https://gitter.im/neo4jrb/neo4j and we can work out your issue in real-time
