### ISSUE TITLE
Raise an error if a property gets set to both `index: :exact` and `constraint: :unique`

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#967]
Probably should also do this for the separate methods for setting indexes and constraints

**Comment by cheerfulstoic** [comment]
We could also probably ignore the `index` if there's a constraint, but it's good to educate when we can ;)

**Comment by subvertallchris** [comment]
I've been meaning to move the property indexing responsibility to the property management class, since it should already have the knowledge of what has been set. This should be easy enough to do.

**Comment by subvertallchris** [comment]
Will be fixed in https://github.com/neo4jrb/neo4j/pull/977.

**Comment by cheerfulstoic** [comment]
:metal: :dancers:
