### ISSUE TITLE
Excessive cypher query generation with Neo4j 5.2.6 in Ruby on Rails 4.2.4

### ISSUE THREAD

**Issue by brian-ewell** [neo4jrb/neo4j#975]
**Disclaimer:** This very well could be user error.  I've been using this library for less than 6 hours.

Use of neo4jrb/neo4j within rails appears to produce excessive cypher queries to neo4j.  This can be easily reproduced by creating a scaffold, populating it with data and viewing the index:

**app/models/card_sets.rb**

    class CardSet
        include Neo4j::ActiveNode
        property :name, type: String, index: :exact
    end

**app/controllers/card_sets_controller.rb**

    ....
    # GET /card_sets.json
    def index
        @card_sets = CardSet.all
    end
    ...

**app/views/card_sets/index.html.haml**

    %h1 Listing Card Sets

    %table
      %thead
        %tr
          %th Name
          %th
      %tbody
        - @card_sets.each do |card_set|
          %tr
            %td= card_set.name
            %td
              = link_to 'Show', card_set
              = link_to 'Edit', edit_card_set_path( card_set )
              = link_to 'Destroy', card_set, method: :delete, data: { confirm: 'Are you sure?' }
    %br
    = link_to 'New Card set', new_card_set_path

Running a query against this page takes progressively longer periods of time, checking the development.log file showed the following (formatting cleaned up):

    Started GET "/card_sets" for ::1 at 2015-09-24 23:28:49 +0000
    Processing by CardSetsController#index as HTML
    CYPHER 32ms MATCH (n:`CardSet`) RETURN n
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>8}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>8}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>8}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>8}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>8}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>9}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>9}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>9}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>9}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>9}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>10}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>10}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>10}
    CYPHER 4ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>10}

This goes on for quite a while, with total render time being around 2 seconds for 47 rows.

In contrast, performing the same general function in the directly within the controller yields a significantly saner result.  Apologies for the crudeness of this test.

**app/controllers/card_sets_controller.rb**

    ....
    # GET /card_sets.json
    def index
        @card_sets = CardSet.all
        tmp = []
        @card_sets.each do |card_set|
            tmp << [card_set.name,card_set.inspect,card_set.inspect,card_set,inspect]
        end
        raise tmp.inspect
    end
    ...

**log/development.log**

    Started GET "/card_sets" for ::1 at 2015-09-25 00:14:58 +0000
    Processing by CardSetsController#index as HTML
    CYPHER 17ms MATCH (n:`CardSet`) RETURN n
    Completed 500 Internal Server Error in 28ms

So why the difference?

**Comment by cheerfulstoic** [comment]
I haven't looked closely at your issue yet, but could you try putting this into your `config/application.rb` first?

```ruby
    config.neo4j._active_record_destroyed_behavior = true
```

That's actually something that will be fixed in 6.0.0 which we're planning on releasing soon.

**Comment by brian-ewell** [comment]
Overall query time dropped (average of 900ms now), but it's still performing all of the queries.

**Comment by brian-ewell** [comment]
Scratch that, I had re-enabled some additional test queries.

Current output of log/development.log:

    Started GET "/card_sets" for 73.231.178.33 at 2015-09-25 00:58:56 +0000
    Processing by CardSetsController#index as HTML
    CYPHER 25ms MATCH (n:`CardSet`) RETURN n
    Rendered card_sets/index.html.haml within layouts/application (48.3ms)
    CYPHER 5ms MATCH (n:`User`) WHERE (n.uuid = {n_uuid}) RETURN n LIMIT {limit_1} | {:n_uuid=>"82c12b49-fcbb-434f-8715-f8355db2534e", :limit_1=>1}
    Rendered application/_navigation.html.haml (0.6ms)
    Completed 200 OK in 139ms (Views: 137.8ms)

It looks like that did it just fine.  Are there any problems with using that configuration switch in the long term?

**Comment by cheerfulstoic** [comment]
Nope, no problems at all!  Though it won't be necessary in >= 6.0.0

Thanks for the feedback!

**Comment by cheerfulstoic** [comment]
6.0.0.alpha.3 is out so give it a try!
