### ISSUE TITLE
Optionally wait for database to become available instead of dying immediately on connection failure

### ISSUE THREAD

**Issue by jbhannah** [neo4jrb/neo4j#981]
I came up with a [workaround](https://github.com/thetallgrassnet/pokesite/blob/feea729d48397f49d5577ede5bede8d1cb103ea5/lib/wait_for_neo4j.rb) that allows me to use Rails+Neo4j with Docker Compose. Docker Comopse tries to start everything up in the right order, but usually tries to start the web server before the Neo4j server is ready for connections, and because the Rails application immediately tries to connect to the Neo4j server on initialization, it errors out and dies.

Instead of having to remember to pre-start the Neo4j server, I created a method which tries once a second for 30 seconds (by default) to open a simple connection to the Neo4j server, before allowing initialization to continue. The upside is that `docker-compose up` works smoothly now, and the web server typically has to wait less than ten seconds for Neo4j to be ready for connections. The downside is that running `rake` tasks that would not normally even get to the point of trying to connect to Neo4j (e.g., in my case, setting up and starting Neo4j with the provided `rake` task in Travis CI) have to wait 30 seconds for no reason whatsoever.

Would it be desirable to add an option to wait for a (optionally specified) length of time for the Neo4j server to become available, before erroring out as unable to connect? Or, is there another approach I could take that wouldn't make everything that goes through my application's `config/application.rb` wait for 30 seconds, whether or not Neo4j would even try to connect to the database server? (I've thought about emulating how the connection itself happens in `Neo4j::Railtie`, and programmatically adding an initializer that runs between `load_config_initializers` and `neo4j.start`, but haven't tried implementing it yet.)

**Comment by jbhannah** [comment]
This was implemented in thetallgrassnet/pokesite@96965e6745123cbde02713e8cb845d2ff84c6592, which shows where the necessary changes to `config/application.rb` and `spec/rails_helper.rb` were made.

**Comment by cheerfulstoic** [comment]
I'm unfortunately not yet very familiar with Docker nor Docker Compose.  It seems like there should be a way to configure it so that it waits for Neo4j to be done starting up.  What command are you using to start Neo4j?

My instinct is that it should be the infrastructure's responsibility to make sure that Neo4j is up and running first rather than the gem, but I'm really not sure.  @subvertallchris or anybody else have any thoughts?

**Comment by jbhannah** [comment]
Good point @cheerfulstoic, a better general solution might be for Docker Compose wait until the exposed ports of a container are being listened on before starting any dependent containers. This is already being discussed at great length over there (see docker/compose#374), but since my expertise is in Ruby and not Go, I thought I'd try here first. ;)

I've had this problem and tested this solution with the [semi-official Neo4j Docker container](https://github.com/neo4j/docker-neo4j) and with my own fork of it (same code on a slimmer base image), both of which ultimately start the server with `neo4j console`. I'll try my second idea of adding an initializer instead of doing a hard wait in `config/application.rb` and see if that gives any better results than my current implementation.

**Comment by jbhannah** [comment]
I've implemented a more elegant solution in thetallgrassnet/pokesite@03c8ba3757e223788053d5acfdad5ba6aa9734fb (took a few tries, that's what I get for trying to code while waiting for a sick toddler to fall asleep). In addition to being more testable, it now also uses an initializer instead of a hard wait on application boot. Might still be worth considering this ticket if someone can come up with other situations where this might occur.

**Comment by cheerfulstoic** [comment]
Ok, so I've been playing with Docker Compose and I've decided that I was wrong ;)

I just released version `6.1.6` which has a `wait_for_connection` config which you can set in `config/application.rb` or `config/environments/*.rb` like:

```ruby
    config.neo4j.wait_for_connection = true
```

That should keep trying to connect for up to 60 seconds if set with some dots outputted to STDOUT.

**Comment by jbhannah** [comment]
:+1: Thank you!

**Comment by cheerfulstoic** [comment]
Thank **you**! ;)

**Comment by disastrous-charly** [comment]
Hello ! 

I'm running the same issue with a rails 5 application, and the rails5 branch of neo4jrb.

When launching docker-compose up :

`web_1   | => Booting Puma
web_1   | => Rails 5.0.0.beta3 application starting in development on http://localhost:3000
web_1   | => Run `rails server -h` for more startup options
web_1   | => Ctrl-C to shutdown server
web_1   | Exiting
web_1   | /usr/local/bundle/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:641:in `rescue in connection_for': connection refused: 172.17.0.3:7474 (Faraday::ConnectionFailed)`

After that, the neo4j start successfully (but too late)

Any clue ?

**Comment by cheerfulstoic** [comment]
@subvertallchris You just merged `master` into the `rails5` branch, right?

@disastrous-charly Did you set the configuration as:

```ruby
config.neo4j.wait_for_connection = true
```

**Comment by disastrous-charly** [comment]
@cheerfulstoic Yes I did.

**Comment by subvertallchris** [comment]
@cheerfulstoic yeah, just updated it yesterday

**Comment by disastrous-charly** [comment]
@subvertallchris @cheerfulstoic Sorry to disturb,

I tried to bundle update again but the gem didn't change. Do you know where my issue can come from ?

**Comment by cheerfulstoic** [comment]
I think maybe @subvertallchris didn't push the merge.  I've just merged and pushed, so give it a try

@subvertallchris I see that the `gemspec` is changed to `~> 5.0.0.beta1`, but shouldn't that be something like `>= 4`?

**Comment by subvertallchris** [comment]
Oh man, egg on my face. I pushed to my fork, not the main repo. Sorry! I
can push tomorrow morning when I'm back on my computer.

**Comment by cheerfulstoic** [comment]
;)  No problem, I pushed so I think it should be working now

**Comment by disastrous-charly** [comment]
I now use the gem version 6.1.2 and it's working ! 

Thanks to both of you !

**Comment by cheerfulstoic** [comment]
Awesome, though I think that Rails 5 won't work yet, right?

**Comment by disastrous-charly** [comment]
Hey @cheerfulstoic , Rails 5 beta is already working great !

**Comment by cheerfulstoic** [comment]
That's great to hear!  Just to verify, is that on a branch or on one of our gem releases from rubygems?

**Comment by disastrous-charly** [comment]
Hey ! Sorry for the long time without answering ! 
My project with your gem is 2 month old, you can see it here, it was a quick test : 
[https://github.com/disastrous-charly/breizhcamp-pokerails]

I was using your github branch !
