### ISSUE TITLE
Eager loading returns wrong result sets

### ISSUE THREAD

**Issue by 4cc8783b** [neo4jrb/neo4j#996]
Hey folks!

I'm working on a personal project making heavy use of different kinds of nodes and relationships between them. Therefore I've a few situations where I want to eagerly load relating nodes to speed up the application and reduce database round trips.

I could observe that the result sets of some queries are not the expected ones. Especially when using scopes (filtering) on collections or eagerly load relationships that may be null.

#### Nullable-Refs-Example
```
class User
  property :name, constraint: :unique
  has_one :out, :role, model_class: Role, type: :ROLE       # never null, every user has a role
  has_many :out, :trips, model_class: Trip, type: :PLANS    # may be null if the user does not plan any trips
  has_many :out, :cars, model_class: Car, type: :OWNS    # may be null if the user has no cars
```  
Executing this code:
```
User.all.each do |u| 
  puts "Name: #{u.name} (#{u.role.name})"
  puts "Trips (#{u.trips.count}): #{(u.trips.map! do |t| t.id; end).inspect}"
  puts "Cars (#{u.cars.count}): #{(u.cars.map! do |c| c.id; end).inspect}"; end
```
returns the correct result
```
Name: User A (admin)
Trips (3): ["45278b1d-7ebc-4c06-99ac-23e9252b2716", "4f44fe1a-c50e-4c38-b498-e048ba89bb07", "576b5dcd-e729-461e-85b4-5f31d2415d50"]
Cars (1): ["8d6b106d-b818-4179-bdf4-4ab8cb17a490"]

Name: User B (guest)
Trips (0): []
Cars (0): []

Name: User C (traveller)
Trips (0): []
Cars (1): ["9f6a63b1-84e4-4c13-bd44-87aedd35ff52"]

Name: User D (traveller)
Trips (1): ["1e40401a-51c4-4be1-91e4-ac9625dc96ba"]
Cars (2): ["de126f90-efbe-43dc-b74d-dc58b0cabafb", "346f4f93-21c8-4941-9d54-b5528f00caa5"]
```

Changing the query to `User.all.with_associations(:role, :trips, :cars).each` helps me avoid many database queries (as intended) but returns the result

`undefined method ```name' for nil:NilClass`

Wait. What?
Removing the call to "u.role.name" and replacing it with "u.role" does the trick (for now). Now I get a (strange) result set without the error from above:
```
Name: User A (#<Role:0x007f2879e4e7a8>)
Trips (3): ["45278b1d-7ebc-4c06-99ac-23e9252b2716", "4f44fe1a-c50e-4c38-b498-e048ba89bb07", "576b5dcd-e729-461e-85b4-5f31d2415d50"]
Cars (3): ["8d6b106d-b818-4179-bdf4-4ab8cb17a490", "8d6b106d-b818-4179-bdf4-4ab8cb17a490", "8d6b106d-b818-4179-bdf4-4ab8cb17a490"]

Name: User B ()
Trips (0): []
Cars (0): []

Name: User C ()
Trips (0): []
Cars (0): []

Name: User D (traveller)
Trips (2): ["1e40401a-51c4-4be1-91e4-ac9625dc96ba", "1e40401a-51c4-4be1-91e4-ac9625dc96ba"]
Cars (2): ["de126f90-efbe-43dc-b74d-dc58b0cabafb", "346f4f93-21c8-4941-9d54-b5528f00caa5"]
```
We can see two different things in here:
1) the number of cars magically raised to 3 for User A (OK, all the same, but who cares, we have 3 instead of 1 car!) and the number of trips for User D climbed from 1 to 2.
2) One of the cars must be stolen from User C since there is no car left ;-)
3) The "role" of each user is not loaded properly as well. Only User A and D have a role instance bound

Oh, I missed something... the duplicates are also present for the roles - in the plain result set coming from the database there are 3 roles (with name "admin") for User A and 2 (with name "traveller") for User D.

Why did that happen? The query which was build with help of `QueryProxyEagerLoading.query_from_association_spec` is

```
MATCH (n:`User`) OPTIONAL MATCH n-[:`ROLE`]->role, n-[:`PLANS`]->trips, n-[:`OWNS`]->cars WHERE (role:Role) AND (trips:Trip) AND (cars:Car) RETURN n, [collect(role),collect(trips),collect(cars)]
```
This query matches all users (allright, we have all users in the result set) and optionally matches users that have a role (all of them have) AND have trips planned AND are car owners. Only User A and D fulfill all of these assumptions. Therefore all other users (B and C) are matching against the "MATCH" clause only and not against the triple-condition "MATCH OPTIONAL".

Additionally the optional clause matches 3 times for User A (each trip once, the car is used in every of these matches), therefore we get the "duplication" of the cars. For User D it is the same: the optional match matches twice: one time for each trip / car combination.

After doing some modifications to the `query_from_association_spec` method (adding a break()):

```
query.optional_match("#{identity}#{association.arrow_cypher}#{association_name}")
              .where(association.target_where_clause).break()
```
...the result (adding the .name to the role field again ;) ) set looks like
```
Name: User A (admin)
Trips (3): ["45278b1d-7ebc-4c06-99ac-23e9252b2716", "4f44fe1a-c50e-4c38-b498-e048ba89bb07", "576b5dcd-e729-461e-85b4-5f31d2415d50"]
Cars (3): ["8d6b106d-b818-4179-bdf4-4ab8cb17a490", "8d6b106d-b818-4179-bdf4-4ab8cb17a490", "8d6b106d-b818-4179-bdf4-4ab8cb17a490"]

Name: User B (guest)
Trips (0): []
Cars (0): []

Name:  User C (traveller)
Trips (0): []
Cars (1): ["9f6a63b1-84e4-4c13-bd44-87aedd35ff52"]

Name: User D (traveller)
Trips (2): ["1e40401a-51c4-4be1-91e4-ac9625dc96ba", "1e40401a-51c4-4be1-91e4-ac9625dc96ba"]
Cars (2): ["de126f90-efbe-43dc-b74d-dc58b0cabafb", "346f4f93-21c8-4941-9d54-b5528f00caa5"]
```

We are getting close. But we still got duplicates.
Changing another method (`with_associations_return_clause`) to the following:

```
'[' + with_associations_spec.map { |n| "collect(DISTINCT #{n})" }.join(',') + ']'
```

Will finally fix our result set:
```
Name: User A (admin)
Trips (3): ["45278b1d-7ebc-4c06-99ac-23e9252b2716", "4f44fe1a-c50e-4c38-b498-e048ba89bb07", "576b5dcd-e729-461e-85b4-5f31d2415d50"]
Cars (1): ["8d6b106d-b818-4179-bdf4-4ab8cb17a490"]

Name: User B (guest)
Trips (0): []
Cars (0): []

Name: User C (traveller)
Trips (0): []
Cars (1): ["9f6a63b1-84e4-4c13-bd44-87aedd35ff52"]

Name: User D (traveller)
Trips (2): ["1e40401a-51c4-4be1-91e4-ac9625dc96ba"]
Cars (2): ["de126f90-efbe-43dc-b74d-dc58b0cabafb", "346f4f93-21c8-4941-9d54-b5528f00caa5"]
```

The problem: if a user had multiple relationships to exactly the same trip it would break those down to a single one. But in most of the times it would simply repair the result. In the current state this case would not be feasible as well because of the duplication in the result sets one could not distinguish between "real" duplicates and "fake" ones that were added by the query.

#### Adding a `where` clause

I'll use the same user class as above. 
When executing this code:
```
User.where(name: "User A").each do |u| 
  puts "Name: #{u.name} (#{u.role.name})"
  puts "Trips (#{u.trips.count}): #{(u.trips.map! do |t| t.id; end).inspect}"
  puts "Cars (#{u.cars.count}): #{(u.cars.map! do |c| c.id; end).inspect}"; end
```
I get the correct result
```
Name: User A (admin)
Trips (3): ["45278b1d-7ebc-4c06-99ac-23e9252b2716", "4f44fe1a-c50e-4c38-b498-e048ba89bb07", "576b5dcd-e729-461e-85b4-5f31d2415d50"]
Cars (1): ["8d6b106d-b818-4179-bdf4-4ab8cb17a490"]
```

Adding a `with_associations` now magically kills the filter.

`User.where(name: "User A").with_associations(:role, :trips, :cars)` returns the following:
```
Name: User A (#<Role:0x007f2879e4e7a8>)
Trips (3): ["45278b1d-7ebc-4c06-99ac-23e9252b2716", "4f44fe1a-c50e-4c38-b498-e048ba89bb07", "576b5dcd-e729-461e-85b4-5f31d2415d50"]
Cars (3): ["8d6b106d-b818-4179-bdf4-4ab8cb17a490", "8d6b106d-b818-4179-bdf4-4ab8cb17a490", "8d6b106d-b818-4179-bdf4-4ab8cb17a490"]

Name: User B ()
Trips (0): []
Cars (0): []

Name: User C ()
Trips (0): []
Cars (0): []

Name: User D ()
Trips (2): []
Cars (2): []
```

because the generated query:

```cypher
MATCH (result_user:`User`) OPTIONAL MATCH result_user-[:`ROLE`]->role, result_user-[:`PLANS`]->trips, result_user-[:`OWNS`]->cars WHERE (result_user.name = {result_user_name}) AND (role:Role) AND (trips:Trip) AND (cars:Car) RETURN result_user, [collect(role),collect(trips),collect(cars)] | {:result_user_name=>"User A"}
```

applies the "where" statement to the `OPTIONAL MATCH` clause. Every `where` must be put to the corresponding `MATCH`. The [documentation on OPTIONAL MATCH](http://neo4j.com/docs/stable/query-optional-match.html) emphasizes this:

> Either the whole pattern is matched, or nothing is matched. Remember that WHERE is part of the pattern 
> description, and the predicates will be considered while looking for matches, not after. This matters 
> especially in the case of multiple (OPTIONAL) MATCH clauses, where it is crucial to put WHERE 
> together with the MATCH it belongs to.

We can more or less easily get this by adding some more statements to the query:
`User.as(:u).where(name: "User A").query.break().proxy_as(User, :u).with_associations(:role, :trips, :cars).each` which results in a query like `MATCH (u:`User`) WHERE (u.name = {u_name}) MATCH (u:`User`) OPTIONAL MATCH u-[:`ROLE`]->role, u-[:`PLANS`]->trips, u-[:`OWNS`]->cars WHERE (role:Role) AND (trips:Trip) AND (cars:Car) RETURN u, [collect(role),collect(trips),collect(cars)] | {:u_name=>"User A"}`

There is a duplicate "MATCH (u:`User`)" but that seems not to hurt. It is introduced by the "proxy_as", I think.

It would be nice to fix those issues directly in the QueryProxyEagerLoading class :)

Thank you for your awesome work!

**Comment by cheerfulstoic** [comment]
This is so great and thorough, thank you!

I don't have time to look at this at the moment, but we should definitely fix this!

**Comment by subvertallchris** [comment]
+1 to what Brian said. This is the most thorough issue I've ever seen. Thank you so much for taking the time to write this up!

**Comment by 4cc8783b** [comment]
Hi again,

no problem. That's like I would have issue descriptions at work ^^
Still missing are the used versions but I think all versions are affected.

I think (did not test yet) that one could just cut the query `User.as(:u).where(name: "User A").query.break().proxy_as(User, :u).with_associations(:role, :trips, :cars).each`  by changing `query_from_association_spec` to the following:

```query.break().optional_match("#{identity}#{association.arrow_cypher}#{association_name}")
              .where(association.target_where_clause)```

**Comment by cheerfulstoic** [comment]
Hey @4cc8783b !

Sorry for not getting back to this, but I think we have a solution now!  Could you try one of these two in your `Gemfile`?

    gem 'neo4j', github: 'neo4jrb/neo4j', branch: 'with_associations_fix' # If you are using 6.1.X

    gem 'neo4j', github: 'neo4jrb/neo4j', branch: 'with_associations_fix_70' # If you are using 7.0.0.rc.X

Thanks

**Comment by cheerfulstoic** [comment]
I think that `7.0.0` fixes this. Let me know if not!
