### ISSUE TITLE
`after_initialize` callback not working

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#997]
Hi all,

I'm usually using uuid's for a year without troubles, but now I discover a strange behavior.
I'm running 
neo4j (6.0.0.alpha.4, 5.0.15)
neo4j-core (6.0.0.alpha.2, 5.0.10)

Now I need to assign a value to uuid property just after a Group.new call. But nothing happens. It is returned empty.

My controller code is:
```
  # GET /groups/new
  def new
     @group = Group.new
    puts ("uuid after Group.new: #{@group.uuid}")
  end
```
The group.rb code fragment  is
```
class Group 
  include Neo4j::ActiveNode
  include Uuid

  after_initialize :init_uuid

  def init_uuid 
    puts "init_uuid called!"
    @uuid = create_uuid if @uuid.nil?
    puts "init_uuid is #{@uuid}"
  end
end
```
And finally the module uuid code is
```
module Uuid
  extend ActiveSupport::Concern

  included do 
		id_property :uuid, on: :create_uuid
	end

	def create_uuid
		SecureRandom::uuid
	end

end 
```

The result is 

```
uuid after Group.new: 
```

**Comment by subvertallchris** [comment]
Is this module new or did it break with the new updates?

**Comment by pdipietro** [comment]
The module is old, but I just added the initialize now, whiule I already have in another classes ...

**Comment by subvertallchris** [comment]
I'll have to test it out before I can tell you much. I do know that your `create_uuid` method will get called twice even if this is working correctly. Setting `@uuid` won't translate to setting the `uuid` property on the node.

**Comment by pdipietro** [comment]
Yes, I know. I just added now the after-initialize on the class, as a test because the standard definition of the `module Uuid` seems not to correctly set the property. I use the same approach of including the Uuid module in all the class.

I just checked some other classes and they all seems not to run: at this point it could be related with the new updates ....

Please, tell me if you want I reload the previous version and recheck.

**Comment by subvertallchris** [comment]
If you wouldn't mind, that would be helpful. I don't think that the `after_initialize` callbacks are firing, they might not have ever worked. I seem to remember an issue about this at one point, I'll see if I can find it. The fix seems to be pretty simple, I can work it into the PR I'm preparing now since it makes other changes in this module.

**Comment by pdipietro** [comment]
I made the test, reloading the neo4j 5.0.15 and neo4j-core 5.0.12

It generate an UUID when I do a `subject.save`, but not with an `subject.new`.
It includes `module Uuid` as in the previous example.

Look at this piece of code.

```
    @subject = Subject.new(subject_params)
    puts "--------- /subject uuid: #{@subject.uuid}"

    respond_to do |format|
      begin
        tx = Neo4j::Transaction.new
          @subject.save
```

and at the corresponding console output:
```
I, [2015-10-22T00:27:20.769203 #11696]  INFO -- : Processing by SubjectsController#create as JS
I, [2015-10-22T00:27:20.769553 #11696]  INFO -- :   Parameters: {"utf8"=>"✓", "subject"=>{"nickname"=>"aaa", "first_name"=>"bbbbbbb", "last_name"=>"nnnnnnn", "email"=>"pdipietro@diviana.net", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"", "remote"=>:true}
--------- /subject uuid: 
I, [2015-10-22T00:27:21.009933 #11696]  INFO -- :  CYPHER 7ms MATCH (result:`Subject`) WHERE (result.nickname =~ {result_nickname}) RETURN COUNT(result) AS count | {:result_nickname=>"(?i)^aaa$"}
I, [2015-10-22T00:27:21.017727 #11696]  INFO -- :  CYPHER 6ms MATCH (result:`Subject`) WHERE (result.email =~ {result_email}) RETURN COUNT(result) AS count | {:result_email=>"(?i)^pdipietro@diviana\\.net$"}
I, [2015-10-22T00:27:21.234617 #11696]  INFO -- :  CYPHER 7ms CREATE (n:`Subject` {props}) RETURN ID(n) | {:props=>{:uuid=>"1a631c17-82ee-4ab6-a6e5-72c17949ca50", :created_at=>1445466441, :updated_at=>1445466441, :activation_digest=>"$2a$10$x0zkgOvooa1EXg9WvLABhu.vhZ18iPqDUXVEh26Kt3SXz20hHqEVi", :admin=>false, :nickname=>"aaa", :first_name=>"Bbbbbbb", :last_name=>"Nnnnnnn"}}
```

In the 3rd line the subject.uuid is empty (after the @subject.new in the code)
in the last line the subject.uuid is filled, (after the @subject.save )

This means that after_initialize is never called for a new.

**Comment by cheerfulstoic** [comment]
I might be misunderstanding something, but the `Uuid` module seems to be doing exactly what `ActiveNode` does by default without specifying any `id_property`.  By default we set `uuid` as the `id_property` and use `SecureRandom.uuid` as the value...

**Comment by pdipietro** [comment]
Ok, let me start again in an easier way

As you say that your product automatically do the same as my `module Uuid`, I just removed my module, and effectively it runs fine. ;-)

But the question remains: the  `after_initialize` is not fired and the uuid is not assigned a value until the `create` action.

**Comment by subvertallchris** [comment]
I'm going to change the title of this issue because the problem here seems to be that `after_initialize` is not firing at all. The `id_property` is working as expected.

**Comment by pdipietro** [comment]
Sorry to bother you, but the problem is severe enough.
Any idea about time-to-release this patch?

**Comment by subvertallchris** [comment]
I have the code finished and hoped to merge it yesterday but issues with
the 2.3.0 release derailed my plans. It will probably be up tomorrow or
Monday but there probably won't be an official release for a few days.
You'll be able to lock your Gemfile at the commit that merges it in.

**Comment by subvertallchris** [comment]
@pdipietro Can you try locking your Gemfile at ref d6783e81ebedb542f188d721a6a4355d8e0071d8?

```
gem 'neo4j', github: 'neo4jrb/neo4j', ref: 'd6783e81ebedb542f188d721a6a4355d8e0071d8'
```

It's in the 5.2.x release branch. It'll be part of the next patch release.

**Comment by pdipietro** [comment]
@subvertallchris I've seen it just now: it runs ;-)
Thank you

**Comment by pdipietro** [comment]
@cheerfulstoic Now the after_initialize runs fine.

You told me 4 days ago
` but the Uuid module seems to be doing exactly what ActiveNode does by default without specifying any id_property. By default we set uuid as the id_property and use SecureRandom.uuid as the value...`

So I ask you exactly `when` you set the value ....

**Comment by cheerfulstoic** [comment]
Good question.  I'm not sure exactly!  It seems to be `before_create` because it's not there until that first `save`.  But with a quick look through the code it doesn't seem to be immediately obvious.

**Comment by subvertallchris** [comment]
I can answer this. UUID and timestamps are set by `props_for_create`, which is called in `#create_model` in ActiveNode, https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/persistence.rb#L49. It is defined at https://github.com/neo4jrb/neo4j/blob/c678e7a9c6d7039386bff6f8b6963695b3db137a/lib/neo4j/shared/persistence.rb#L26.

`props_for_create` returns the properties hash to be used when creating the object, as the name suggests. It's split out like this because the "magic" that has to happen when a graph object is created needs to be reused at different places in the code; in particular, when using `merge` or if someone wants to build a node in Ruby but then manually create a Cypher query to create and perform other actions.

**Comment by subvertallchris** [comment]
Oh, and as for `uuid` specifically, it's set in `inject_defaults!`, https://github.com/neo4jrb/neo4j/blob/c678e7a9c6d7039386bff6f8b6963695b3db137a/lib/neo4j/shared/persistence.rb#L207. The name is a throwback to the earliest version of the id property. The proc that sets the auto uuid is still held in a `default_properties` hash and this method is named like this to keep it consistent. I was going to refactor that out completely but ended up finding a kind of cool use for it, so I left it alone for the time being.

**Comment by subvertallchris** [comment]
Whoops, sorry for all the spam, guys. :-) Deleted that last comment, misspoke a little. The `uuid` specifically is set by `inject_primary_key!`, https://github.com/neo4jrb/neo4j/blob/637186853a3bc717eaf1b050f237470ae603af2e/lib/neo4j/active_node/persistence.rb#L71. There's a comment in the code that explains things but I want to wait on the refactoring it mentions.

**Comment by pdipietro** [comment]
I'm not sure if this is a good behavior.

By my point of view, there should be no contraindication if the uuid is assigned just after having created the object instance.

At most, we wasted an uuid!

But if I need to have the uuid of the object before creating the node into the db, this is the only way!!!

In my use  case, I need to upload an object on the cloud (cloudinary or similar) with the uuid of the 'parent'.
If the transaction will abort, I'll delete the object from the cloud.

**Comment by cheerfulstoic** [comment]
I'm not sure I understand your use-case.  ActiveRecord doesn't get it's primary keys until after creation because the server creates the IDs.  Our case is different certainly because we have the flexibility since we're generating the UUID ourselves, but it must be possible to link objects together within a transaction.

**Comment by subvertallchris** [comment]
You can do this:

```
class MyModel
  include Neo4j::ActiveNode
  id_property :uuid, on: :get_or_set_uuid
  after_initialize :set_uuid!
  attr_accessor :_uuid

  private

  def set_uuid!
    @_uuid = SecureRandom.uuid
  end

  def get_or_set_uuid 
    @_uuid || SecureRandom.uuid
  end
end

```

After init, `set_uuid!` will set your `@_uuid` variable. It's set as an accessor, so `node._uuid` will return this. When the node is saved, `get_or_set_uuid` will return that value or, if for some reason you unset it, it will create a new one.

**Comment by pdipietro** [comment]
Yes, yhat is exactly the way I was doing tat in the past.
My suggestion is that you can do that and the object from the beginning for any user and any class ;-)

**Comment by cheerfulstoic** [comment]
To clarify: I'm not trying to say you're wrong, I just think that we need a good reason to deviate from the `ActiveRecord`. Why do you need it to be `after_initialize` rather than `before_create`?

**Comment by pdipietro** [comment]
Question: uuid is an active record extension or a Neo4j one?

In the first case, I agree with you.
But in the second, if you add the feature of automatically create an uuid, well, why do not initialize it and add a little more magic?

If I'm correct, on neo4j, you're not substituting the neo4j::id with the uuid, uuid is another property, and the neo4j::id still remain the main index for neo4j. 

And an overall index that could be used/accessed in an independent way with respect of the node type ;-)

**Comment by cheerfulstoic** [comment]
uuid is a notion from ActiveNode / Neo4j.rb.  ActiveRecord models primary keys which are handled by the RDMS in question.

It's not really more magic to create the UUID at initialization time, it's just different than what ActiveRecord does.  Many people come to the neo4j.rb project having used ActiveRecord in the past, so if we're going to be different we should have a good reason.  As I said, I'm not against it, I just think we need a good reason, like a specific use-case

The Neo4j internal ID (which you can access with the `neo_id` method, I believe) is one of the ways to access nodes, but it's use for long term references to nodes is discouraged because the integers used can be recycled later.

**Comment by pdipietro** [comment]
Ok, that's right.  It's not really a problem for me.

People coming from other RDBMS have the primary key generated at the 'start to fill' time:  if you start to add a new row, it is immediately filled with the primary key. The user can fill other fields and save, but can also cancel the operation and then lose the key: that's for Oracle, MS-SQL, My SQL and MS-Access (this one just as a simple object to test an auto generated form with fille key field), and also for Exist DB (an XML DB). Not sure about the old IBM DB 

By my point of view having that property ready to use before saving on the DB is an important use case, but I can resolve by myself.

**Comment by cheerfulstoic** [comment]
I see an object mapper like neo4j.rb or ActiveRecord as different than the database directly.  I'm happy to consider a situation where making the uuid at initialize time fixes a problem or makes things faster, but until we have a compelling usecase I think we should close the issue.

Thanks as always for the discussion!

**Comment by subvertallchris** [comment]
Another thing to consider regarding the gem's handling of UUIDs is that our process is somewhat of a workaround for the database's inability to create it for us. There have been many requests to Neo Technology for a `UUID` function or constraint in Cypher and I have a hunch that this will happen sooner or later. When that does, I imagine we will want to remove our gem-managed solution in favor of that. The expectation that the primary key -- `neo_id` or `uuid` -- will not be present until after the node has been persisted is satisfied by both our current implementation and this possible database-powered solution.
